act_code: '142801'
requisite: Решение акима Акбулакского сельского округа Сайрамского района Туркестанской области от 13 мая 2020 года № 11. Зарегистрировано Департаментом юстиции Туркестанской области 14 мая 2020 года № 5615
title:
  rus: О присвоении наименовании улицам
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-05-13
approved_by:
- '166008002002'
version_date:
  kaz: 2020-05-13
  rus: 2020-05-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/142801/kaz/13.05.2020
  rus: https://zan.gov.kz/client/#!/doc/142801/rus/13.05.2020
