act_code: '153609'
requisite: Решение акима Коксаекского сельского округа Толебийского района Туркестанской области от 18 марта 2021 года № 13. Зарегистрировано Департаментом юстиции Туркестанской области 18 марта 2021 года № 6111
title:
  rus: Об установлении ограничительных мероприятий по бруцеллезу на улице Досалы би в населенном пункте Коксаек Коксаекского сельского округа
  kaz: Көксәйек ауылдық округі Көксәйек елді мекені Досалы би көшесінде бруцеллез бойынша шектеу шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-03-18
approved_by:
- '166011009002'
version_date:
  kaz: 2021-03-18
  rus: 2021-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/153609/kaz/18.03.2021
  rus: https://zan.gov.kz/client/#!/doc/153609/rus/18.03.2021
