act_code: '140724'
requisite: Решение Созакского районного маслихата Туркестанской области от 18 марта 2020 года № 322. Зарегистрировано Департаментом юстиции Туркестанской области 30 марта 2020 года № 5531. Утратило силу решением Созакского районного маслихата Туркестанской области от 2 сентября 2020 года № 350 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи по Созакскому району
  kaz: Созақ ауданы бойынша тұрғын үй көмегiн көрсетудiң мөлшерi мен тәртiбiн айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-03-18
approved_by:
- '166010000002'
version_date:
  kaz: 2020-03-18
  rus: 2020-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/140724/kaz/18.03.2020
  rus: https://zan.gov.kz/client/#!/doc/140724/rus/18.03.2020
