act_code: '109135'
requisite: Решение Созакского районного маслихата Южно-Казахстанской области от 23 декабря 2016 года № 54. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 10 января 2017 года № 3954. Утратило силу решением Созакского районного маслихата Южно-Казахстанской области от 29 марта 2018 года № 155
title:
  rus: О повышении базовых ставок земельного налога
  kaz: Жер салығының базалық мөлшерлемелерін жоғарлату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-23
approved_by:
- '166010000002'
version_date:
  kaz: 2016-12-23
  rus: 2016-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/109135/kaz/23.12.2016
  rus: https://zan.gov.kz/client/#!/doc/109135/rus/23.12.2016
