act_code: '49646'
requisite: Оңтүстік Қазақстан облысы Төлеби аудандық мәслихатының 2009 жылғы 25 желтоқсандағы N 22/150-IV шешімі. Оңтүстік Қазақстан облысы Төлеби ауданының Әділет басқармасында 2009 жылғы 30 желтоқсанда N 14-13-62 тіркелді
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '166011000002'
version_date:
  kaz: 2010-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/49646/kaz/03.11.2010
caused_by:
  code: '55310'
  requisite: Оңтүстік Қазақстан облысы Төлеби аудандық мәслихатының 2010 жылғы 3 қарашадағы N 33/215-IV шешімі. Оңтүстік Қазақстан облысы Әділет департаментінде 2010 жылғы 11 қарашада N 14-13-79 тіркелді
  title:
    rus: Төлеби аудандық мәслихатының 2009 жылғы 25 желтоқсандағы N 22/150-IV "2010-2012 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
    kaz: Төлеби аудандық мәслихатының 2009 жылғы 25 желтоқсандағы N 22/150-IV "2010-2012 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/55310/rus
