act_code: '49646'
requisite: Оңтүстік Қазақстан облысы Төлеби аудандық мәслихатының 2009 жылғы 25 желтоқсандағы N 22/150-IV шешімі. Оңтүстік Қазақстан облысы Төлеби ауданының Әділет басқармасында 2009 жылғы 30 желтоқсанда N 14-13-62 тіркелді
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '166011000002'
version_date:
  kaz: 2011-05-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/49646/kaz/13.05.2011
