act_code: '126112'
requisite: Решение Туркестанского городского маслихата Туркестанской области от 19 ноября 2018 года № 40/204-VI. Зарегистрировано Департаментом юстиции Туркестанской области 23 ноября 2018 года № 4800. Утратило силу решением Туркестанского городского маслихата Туркестанской области от 23 июля 2024 года № 21/90-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения
  kaz: Пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемесін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-19
approved_by:
- '166015000002'
version_date:
  kaz: 2018-11-19
  rus: 2018-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/126112/kaz/19.11.2018
  rus: https://zan.gov.kz/client/#!/doc/126112/rus/19.11.2018
