act_code: '97303'
requisite: Решение Шардаринского районного маслихата Южно-Казахстанской области от 22 декабря 2015 года № 50-291-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 24 декабря 2015 года № 3483. Утратило силу решением Шардаринского районного маслихата Южно-Казахстанской области от 15 апреля 2016 года № 3-26-VI
title:
  rus: О повышении ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения
  kaz: Пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының мөлшерлемесін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-22
approved_by:
- '166013000002'
version_date:
  kaz: 2015-12-22
  rus: 2015-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/97303/kaz/22.12.2015
  rus: https://zan.gov.kz/client/#!/doc/97303/rus/22.12.2015
