act_code: '52075'
requisite: Оңтүстік Қазақстан облысы Төлеби аудандық мәслихатының 2010 жылғы 19 наурыздағы N 26/172-IV шешімі. Оңтүстік Қазақстан облысы Төлеби ауданының Әділет басқармасында 2010 жылғы 27 сәуірде N 14-13-70 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Төлеби ауданы мәлихатының 2012 жылғы 29 наурыздағы № 3/20-V шешімімен
title:
  rus: Тұрғын үй көмегін көрсетудің мөлшері мен тәртібін бекіту туралы
  kaz: Тұрғын үй көмегін көрсетудің мөлшері мен тәртібін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-19
approved_by:
- '166011000002'
version_date:
  kaz: 2010-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/52075/kaz/19.03.2010
