act_code: '467'
requisite: Решение акима Южно-Казахстанской области от 23 января 1998 года № 50. Зарегистрировано Управлением юстиции Южно-Казахстанской области 13 апреля 1998 года № 24. Утратило силу решением акима Южно-Казахстанской области от 28 ноября 2001 года № 225
title:
  rus: Об увеличении льготных норм потребления коммунальных услуг
  kaz: Жеңiлдiкпен коммуналдық қызмет көрсету нормаларын кеңейту жөнiнде
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-01-23
approved_by:
- '166000000003'
version_date:
  kaz: 1998-01-23
  rus: 1998-01-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/467/kaz/23.01.1998
  rus: https://zan.gov.kz/client/#!/doc/467/rus/23.01.1998
