act_code: '176828'
requisite: Решение Келесского районного маслихата Туркестанской области от 28 декабря 2022 года № 22-187-VII
title:
  rus: О бюджетах села и сельских округов на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған ауыл және ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-28
approved_by:
- '166018000002'
version_date:
  kaz: 2023-12-21
  rus: 2023-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/176828/kaz/21.12.2023
  rus: https://zan.gov.kz/client/#!/doc/176828/rus/21.12.2023
caused_by:
  code: '190516'
  requisite: Решение Келесского районного маслихата Туркестанской области от 21 декабря 2023 года № 8-84-VIII
  title:
    rus: О внесении изменений в решение Келесского районного маслихата от 28 декабря 2023 года № 22-187-VII «О бюджетах села и сельских округов на 2023-2025 годы»
    kaz: Келес аудандық мәслихатының 2022 жылғы 28 желтоқсандағы № 22-187-VII «2023-2025 жылдарға арналған ауыл және ауылдық округтердің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/190516/rus
