act_code: '69747'
requisite: Решение Шардаринского районного маслихата Южно-Казахстанской области от 21 декабря 2012 года № 11-72-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 8 января 2013 года № 2199
title:
  rus: О районном бюджете на 2013-2015 годы
  kaz: 2013-2015 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-21
approved_by:
- '166013000002'
version_date:
  kaz: 2013-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/69747/kaz/24.05.2013
caused_by:
  code: '72862'
  requisite: Решение Шардаринского районного маслихата Южно-Казахстанской области от 24 мая 2013 года № 14-98-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 3 июня 2013 года № 2297
  title:
    rus: О внесении изменений в решение Шардаринского районного маслихата от 21 декабря 2012 года № 11-72-V "О районном бюджете на 2013-2015 годы"
    kaz: Шардара аудандық мәслихатының 2012 жылғы 21 желтоқсандағы № 11-72-V "2013-2015 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/72862/rus
