act_code: '120811'
requisite: Решение акима Колкентского сельского округа Сайрамского района Южно-Казахстанской области от 27 марта 2018 года № 194. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 10 апреля 2018 года № 4511
title:
  rus: О переименовании улиц населенных пунктов Колкентского сельского округа Сайрамского района
  kaz: Сайрам ауданы Көлкент ауылдық округіне қарасты елді мекендердің көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-27
approved_by:
- '166008014002'
version_date:
  kaz: 2018-03-27
  rus: 2018-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/120811/kaz/27.03.2018
  rus: https://zan.gov.kz/client/#!/doc/120811/rus/27.03.2018
