act_code: '41206'
requisite: Оңтүстiк Қазақстан облысы Отырар аудандық мәслихатының 2008 жылғы 14 шілдедегі № 11/69-IV шешiмi. Оңтүстік Қазақстан облысы Отырар ауданының Әділет басқармасында 2008 жылғы 13 тамызда № 14-9-66 болып тiркелдi
title:
  rus: Жергілікті маңызы бар, жалпыға ортақ пайдаланылатын автомобиль жолдарының бөлінген белдеулерінде орналастырылатын және елді мекендерде жарнама объектілері бойынша төлемақы ставкаларын белгілеу туралы
  kaz: Жергілікті маңызы бар, жалпыға ортақ пайдаланылатын автомобиль жолдарының бөлінген белдеулерінде орналастырылатын және елді мекендерде жарнама объектілері бойынша төлемақы ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-07-14
approved_by:
- '166007000002'
version_date:
  kaz: 2008-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/41206/kaz/14.07.2008
