act_code: '72121'
requisite: Решение Кентауского городского маслихата Южно-Казахстанской области от 29 марта 2013 года № 86. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 22 апреля 2013 года № 2271. Утратило силу решением Кентауского городского маслихата Туркестанской области от 28 сентября 2018 года № 210
title:
  rus: Об оказании социальной помощи специалистам государственных учреждений сельских населенных пунктов
  kaz: Ауылдық елді мекендердегі мемлекеттік ұйымдарының мамандарына әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-03-29
approved_by:
- '166014000002'
version_date:
  kaz: 2013-03-29
  rus: 2013-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/72121/kaz/29.03.2013
  rus: https://zan.gov.kz/client/#!/doc/72121/rus/29.03.2013
