act_code: '42029'
requisite: Решение Шымкентского городского маслихата Южно-Казахстанской области от 24 марта 2006 года N 27/239-3с. Зарегистрировано Управлением юстиции города Шымкента Южно-Казахстанской области 10 апреля 2006 года N 14-1-27. Утратило силу решением Шымкентского городского маслихата Южно-Казахстанской области от 31 марта 2010 года N 33/306-4c
title:
  rus: О правилах застройки территории города Шымкента
  kaz: Шымкент қаласының аумағында құрылыс жүргізу Қағидасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-03-24
approved_by:
- '166002000002'
version_date:
  kaz: 2008-12-23
  rus: 2008-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/42029/kaz/23.12.2008
  rus: https://zan.gov.kz/client/#!/doc/42029/rus/23.12.2008
caused_by:
  code: '43879'
  requisite: Решение Шымкентского городского маслихата Южно-Казахстанской области от 23 декабря 2008 года N 16/163-4с. Зарегистрировано Управлением юстиции города Шымкента Южно-Казахстанской области 27 января 2009 года N 14-1-87. Утратило силу решением Шымкентского городского маслихата Южно-Казахстанской области от 31 марта 2010 года N 33/306-4c
  title:
    rus: О внесении изменений и дополнений в решение маслихата города Шымкента от 24 марта 2006 года N 27/239-3с "О правилах застройки территории города Шымкента"
    kaz: Шымкент қалалық мәслихатының 2006 жылғы 24 наурыздағы N 27/239-3с "Шымкент қаласының аумағындағы құрылыс жүргізу Қағидасы туралы" шешіміне өзгертулер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/43879/rus
