act_code: '121517'
requisite: Решение Туркестанского городского маслихата Южно-Казахстанской области от 5 апреля 2018 года № 29/161-VI. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 20 апреля 2018 года № 4559. Утратило силу решением Туркестанского городского маслихата Туркестанской области от 14 августа 2019 года № 51/253-VI
title:
  rus: Об утверждении Регламента собрания местного сообщества сельских округов города Туркестан
  kaz: Түркістан қаласының ауылдық округтерінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-04-05
approved_by:
- '166015000002'
version_date:
  kaz: 2018-04-05
  rus: 2018-04-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/121517/kaz/05.04.2018
  rus: https://zan.gov.kz/client/#!/doc/121517/rus/05.04.2018
