act_code: '70869'
requisite: Решение Шардаринского районного маслихата Южно-Казахстанской области от 30 января 2013 года № 12-84-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 13 февраля 2013 года № 2228
title:
  rus: О предоставлении в 2013 году подъемного пособия и социальной поддержки для приобретения или строительства жилья специалистам здравоохранения, образования, социального обеспечения, культуры, спорта и ветеринарии, прибывшим для работы и проживания в сельские населенные пункты Шардаринского района
  kaz: Шардара ауданының ауылдық елді мекендеріне жұмыс iстеу және тұру үшiн келген денсаулық сақтау, бiлiм беру, әлеуметтiк қамсыздандыру, мәдениет, спорт және ветеринария мамандарына 2013 жылы көтерме жәрдемақы және тұрғын үй сатып алу немесе салу үшін әлеуметтiк қолдауды ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-01-30
approved_by:
- '166013000002'
version_date:
  kaz: 2014-01-01
  rus: 2014-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/70869/kaz/01.01.2014
  rus: https://zan.gov.kz/client/#!/doc/70869/rus/01.01.2014
