act_code: '56591'
requisite: Оңтүстік Қазақстан облысы Мақтаарал ауданы әкімдігі Ынтымақ ауылдық округі әкімінің 2010 жылғы 6 желтоқсандағы № 90 шешімі. Оңтүстік Қазақстан облысы Мақтаарал ауданының Әділет басқармасында 2011 жылғы 5 қаңтарда № 14-7-132 тіркелді
title:
  rus: Көше атауларын өзгерту туралы
  kaz: Көше атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-06
approved_by:
- '166005009001'
version_date:
  kaz: 2010-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/56591/kaz/06.12.2010
