act_code: '96637'
requisite: Решение акима сельского округа Майлыкент Тюлькубасского района Южно-Казахстанской области от 22 декабря 2015 года № 232. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 23 декабря 2015 года № 3479
title:
  rus: О наименовании переулка улицы Б.Момышулы в селе Т.Рыскулова
  kaz: Т.Рысқұлов ауылы Б.Момышұлы көшесінің қиылысына атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-22
approved_by:
- '166012008001'
version_date:
  kaz: 2015-12-22
  rus: 2015-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/96637/kaz/22.12.2015
  rus: https://zan.gov.kz/client/#!/doc/96637/rus/22.12.2015
