act_code: '154839'
requisite: Решение акима сельского округа Шолаккорган Созакского района Туркестанской области от 15 апреля 2021 года № 125. Зарегистрировано Департаментом юстиции Туркестанской области 16 апреля 2021 года № 6165
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-15
approved_by:
- '166010001002'
version_date:
  kaz: 2021-04-15
  rus: 2021-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/154839/kaz/15.04.2021
  rus: https://zan.gov.kz/client/#!/doc/154839/rus/15.04.2021
