act_code: '193426'
requisite: Решение Ордабасинского районного маслихата Туркестанской области от 19 февраля 2024 года № 12/2
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов, тарифов на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по Ордабасинскому району
  kaz: Ордабасы ауданы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын, қатты тұрмыстық қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге  арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-19
approved_by:
- '166006000002'
version_date:
  kaz: 2024-02-19
  rus: 2024-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/193426/kaz/19.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193426/rus/19.02.2024
