act_code: '213244'
requisite: Решение акима города Туркестан Туркестанской области от 8 августа 2025 года № 6
title:
  rus: Об установлении ограничительных Мероприятии
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-08-08
approved_by:
- '166015000003'
version_date:
  kaz: 2025-08-08
  rus: 2025-08-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/213244/kaz/08.08.2025
  rus: https://zan.gov.kz/client/#!/doc/213244/rus/08.08.2025
