act_code: '175841'
requisite: Решение Кентауского городского маслихата Туркестанской области от 20 декабря 2022 года № 202
title:
  rus: О городском бюджете на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-20
approved_by:
- '166014000002'
version_date:
  kaz: 2023-11-13
  rus: 2023-11-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/175841/kaz/13.11.2023
  rus: https://zan.gov.kz/client/#!/doc/175841/rus/13.11.2023
caused_by:
  code: '188259'
  requisite: Решение Кентауского городского маслихата Туркестанской области от 13 ноября 2023 года № 57
  title:
    rus: О внесении изменений в решение Кентауского городского маслихата от 20 декабря 2022 года № 202 «О городском бюджете на 2023-2025 годы»
    kaz: Кентау қалалық мәслихатының 2022 жылғы 20 желтоқсандағы № 202 «2023-2025 жылдарға арналған қалалық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/188259/rus
