act_code: '191163'
requisite: Решение акима Созакского района Туркестанской области от 25 декабря 2023 года № 51. Зарегистрировано в Департаменте юстиции Туркестанской области 26 декабря 2023 года № 6436-13
title:
  rus: Об образовании избирательных участков на территории Созакского района
  kaz: Созақ ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-25
approved_by:
- '166010000003'
version_date:
  kaz: 2024-12-27
  rus: 2024-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/191163/kaz/27.12.2024
  rus: https://zan.gov.kz/client/#!/doc/191163/rus/27.12.2024
caused_by:
  code: '205000'
  requisite: Решение акима Созакского района Туркестанской области от 27 декабря 2024 года № 63. Зарегистрировано в Департаменте юстиции Туркестанской области 27 декабря 2024 года № 6643-13
  title:
    rus: О внесении изменений в решение акима Созакского района от 25 декабря 2023 года № 51 «Об образовании избирательных участков на территории Созакского района»
    kaz: Созақ ауданы әкімінің 2023 жылғы 25 желтоқсандағы «Созақ ауданының аумағында сайлау учаскелерін құру туралы» № 51 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/205000/rus
