act_code: '44737'
requisite: Оңтүстік Қазақстан облысы Төлеби аудандық мәслихатының 2009 жылғы 12 ақпандағы N 12/93-IV шешімі. Оңтүстік Қазақстан облысы Төлеби ауданының Әділет басқармасында 2009 жылғы 12 наурызда N 14-13-52 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Төлеби аудандық мәслихатының 2012 жылғы 28 қыркүйектегі № 9/47-V Шешімімен
title:
  rus: Елді мекендер мен Ленгір қаласының жерлеріне салынатын базалық салық ставкаларының мөлшерін белгілеу туралы
  kaz: Елді мекендер мен Ленгір қаласының жерлеріне салынатын базалық салық ставкаларының мөлшерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-12
approved_by:
- '166011000002'
version_date:
  kaz: 2009-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/44737/kaz/12.02.2009
