act_code: '176060'
requisite: Решение Шардаринского районного маслихата Туркестанской области от 23 декабря 2022 года № 24-149-VII
title:
  rus: О районном бюджете на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-23
approved_by:
- '166013000002'
version_date:
  kaz: 2023-12-12
  rus: 2023-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/176060/kaz/12.12.2023
  rus: https://zan.gov.kz/client/#!/doc/176060/rus/12.12.2023
caused_by:
  code: '190003'
  requisite: Решение Шардаринского районного маслихата Туркестанской области от 12 декабря 2023 года № 13-61-VIII
  title:
    rus: О внесении изменений в решение районного маслихата от 23 декабря 2022 года № 24-149-VІІ «О районном бюджете на 2023-2025 годы»
    kaz: Шардара аудандық мәслихатының 2022 жылғы 23 желтоқсандағы № 24-149-VІІ «2023-2025 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/190003/rus
