act_code: '92860'
requisite: Решение Мактааральского районного маслихата Южно-Казахстанской области от 21 июля 2015 года № 46-291-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 10 августа 2015 года № 3310. Утратило силу решением Мактааральского районного маслихата Южно-Казахстанской области от 5 февраля 2016 года № 54-354-V
title:
  rus: Об утверждении Методики ежегодной оценки деятельности административных государственных служащих аппарата Мактааральского районного маслихата корпуса «Б»
  kaz: «Б» корпусындағы Мақтаарал аудандық мәслихат аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін жыл сайынғы бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-07-21
approved_by:
- '166005000002'
version_date:
  kaz: 2015-10-01
  rus: 2015-10-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/92860/kaz/01.10.2015
  rus: https://zan.gov.kz/client/#!/doc/92860/rus/01.10.2015
caused_by:
  code: '94939'
  requisite: Решение Мактааральского районного маслихата Южно-Казахстанской области от 1 октября 2015 года № 47-308-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 30 октября 2015 года № 3395. Утратило силу решением Мактааральского районного маслихата Южно-Казахстанской области от 5 февраля 2016 года № 54-354-V
  title:
    rus: О внесении изменения в решение Мактааральского районного маслихата от 21 июля 2015 года № 46-291-V «Об утверждении Методики ежегодной оценки деятельности административных государственных служащих аппарата Мактааральского районного маслихата корпуса «Б»»
    kaz: ««Б» корпусындағы Мақтаарал аудандық мәслихат аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін жыл сайынғы бағалаудың әдістемесін бекіту туралы» Мақтаарал аудандық мәслихатының 2015 жылғы 21 шілдедегі № 46-291-V шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/94939/rus
