act_code: '92860'
requisite: Решение Мактааральского районного маслихата Южно-Казахстанской области от 21 июля 2015 года № 46-291-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 10 августа 2015 года № 3310. Утратило силу решением Мактааральского районного маслихата Южно-Казахстанской области от 5 февраля 2016 года № 54-354-V
title:
  rus: Об утверждении Методики ежегодной оценки деятельности административных государственных служащих аппарата Мактааральского районного маслихата корпуса «Б»
  kaz: «Б» корпусындағы Мақтаарал аудандық мәслихат аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін жыл сайынғы бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-07-21
approved_by:
- '166005000002'
version_date:
  kaz: 2015-07-21
  rus: 2015-07-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/92860/kaz/21.07.2015
  rus: https://zan.gov.kz/client/#!/doc/92860/rus/21.07.2015
