act_code: '44315'
requisite: Оңтүстік Қазақстан облысы Арыс қалалық мәслихатының 2009 жылғы 23 қаңтардағы N 16/102-IV шешімі. Оңтүстік Қазақстан облысы Арыс қаласының Әділет басқармасында 2009 жылғы 20 ақпанда N 14-2-68 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Арыс қалалық мәслихатының 2015 жылғы 20 наурыздағы № 38/227-V шешімімен
title:
  rus: Тіркелген салық ставкалары туралы
  kaz: Тіркелген салық ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-23
approved_by:
- '166016000002'
version_date:
  kaz: 2011-10-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/44315/kaz/21.10.2011
caused_by:
  code: '61637'
  requisite: Решение Арысского городского маслихата Южно-Казахстанской области от 21 октября 2011 года № 48/307-IV. Зарегистрировано Управлением юстиции города Арыс Южно-Казахстанской области 24 ноября 2011 года № 14-2-118. Утратило силу решением Арысского городского маслихата Южно-Казахстанской области от 20 марта 2015 года № 38/227-V
  title:
    rus: О внесении изменений в решение Арысского городского маслихата от 23 января 2009 года № 16/102-IV "О ставках фиксированного налога"
    kaz: Арыс қалалық мәслихатының 2009 жылғы 23 қаңтардағы № 16/102-IV "Тіркелген салық ставкалары туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/61637/rus
