act_code: '48217'
requisite: Оңтүстік Қазақстан облысы Мақтаарал ауданы әкімдігі Қазыбек би ауылдық округі әкімінің 2009 жылғы 14 қыркүйектегі N 55 шешімі. Оңтүстік Қазақстан облысы Мақтаарал ауданы Әділет басқармасында 2009 жылғы 18 қазанда N 14-7-102 тіркелді
title:
  rus: Ауыл көшелеріне атау беру туралы
  kaz: Ауыл көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-09-14
approved_by:
- '166005003001'
version_date:
  kaz: 2009-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/48217/kaz/14.09.2009
