act_code: '39563'
requisite: Оңтүстік Қазақстан облысы Отырар аудандық мәслихатының 2008 жылғы 7 сәуірдегі N 7/48-IV шешімі. Оңтүстік Қазақстан облысы Отырар ауданының Әділет басқармасында 2008 жылғы 13 мамырда N 14-9-62 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Отырар аудандық мәслихатының 2012 жылғы 5 қарашадағы № 7/49-V Шешімімен
title:
  rus: Аудандағы елді мекендерде аймақтардың шекаралары мен жерге ақы төлеудің базалық ставкасына қолданылатын түзету коэффициенттерін белгілеу туралы
  kaz: Аудандағы елді мекендерде аймақтардың шекаралары мен жерге ақы төлеудің базалық ставкасына қолданылатын түзету коэффициенттерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-04-07
approved_by:
- '166007000002'
version_date:
  kaz: 2008-04-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/39563/kaz/07.04.2008
