act_code: '104785'
requisite: Решение Кентауского городского маслихата Южно-Казахстанской области от 28 июня 2016 года № 20. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 19 июля 2016 года № 3793. Утратило силу решением Кентауского городского маслихата Южно-Казахстанской области от 29 марта 2018 года № 146
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения на территории города Кентау
  kaz: Кентау қаласының аумағында пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерге жер салығының базалық мөлшерлемесін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-06-28
approved_by:
- '166014000002'
version_date:
  kaz: 2016-06-28
  rus: 2016-06-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/104785/kaz/28.06.2016
  rus: https://zan.gov.kz/client/#!/doc/104785/rus/28.06.2016
