act_code: '162237'
requisite: Решение Байдибекского районного маслихата Туркестанской области от 24 декабря 2021 года № 12/75. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 декабря 2021 года № 26051
title:
  rus: О районном бюджете на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '166003000002'
version_date:
  kaz: 2022-09-21
  rus: 2022-09-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/162237/kaz/21.09.2022
  rus: https://zan.gov.kz/client/#!/doc/162237/rus/21.09.2022
caused_by:
  code: '172010'
  requisite: Решение Байдибекского районного маслихата Туркестанской области от 21 сентября 2022 года № 21/136
  title:
    rus: О внесении изменений в решение маслихата района Байдибек от 24 декабря 2021 года № 12/75 «О районном бюджете на 2022-2024 годы»
    kaz: Бәйдібек аудандық мәслихатының 2021 жылғы 24 желтоқсандағы № 12/75 «2022-2024 жылдарға арналған аудан бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172010/rus
