act_code: '54694'
requisite: Оңтүстік Қазақстан облысы Ордабасы ауданы әкімдігі Жеңіс ауылдық округі әкімінің 2010 жылғы 24 тамыздағы N 11 Шешімі. Оңтүстік Қазақстан облысы Ордабасы ауданы Әділет басқармасында 2010 жылғы 24 қыркүйекте N 14-8-91 тіркелді
title:
  rus: Көше атын беру туралы
  kaz: Көше атын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-24
approved_by:
- '166006006001'
version_date:
  kaz: 2010-08-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/54694/kaz/24.08.2010
