act_code: '89024'
requisite: Решение Туркестанского городского маслихата Южно-Казахстанской области от 27 марта 2015 года № 40/229-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 20 апреля 2015 года № 3147. Утратило силу решением Туркестанского городского маслихата Южно-Казахстанской области от 19 марта 2018 года № 28/153-VI
title:
  rus: О единых ставках фиксированного налога
  kaz: Бірыңғай тіркелген салықтың мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-03-27
approved_by:
- '166015000002'
version_date:
  kaz: 2015-03-27
  rus: 2015-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/89024/kaz/27.03.2015
  rus: https://zan.gov.kz/client/#!/doc/89024/rus/27.03.2015
