act_code: '56749'
requisite: Оңтүстік Қазақстан облысы Шардара аудандық мәслихатының 2010 жылғы 22 желтоқсандағы N 39-287-IV шешімі. Оңтүстік Қазақстан облысы Шардара ауданының Әділет басқармасында 2011 жылғы 14 қаңтарда N 14-15-109 тіркелді
title:
  rus: 2011-2013 жылдарға арналған аудандық бюджет туралы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-22
approved_by:
- '166013000002'
version_date:
  kaz: 2011-11-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/56749/kaz/11.11.2011
caused_by:
  code: '61415'
  requisite: Решение маслихата Шардаринского района Южно-Казахстанской области от 11 ноября 2011 года N 49-370-IV. Зарегистрировано Управлением юстиции Шардаринского района Южно-Казахстанской области 17 ноября 2011 года N 14-15-125
  title:
    rus: О внесении изменений в решение Шардаринского районного маслихата от 22 декабря 2010 года № 39-287-IV "О районном бюджете на 2011-2013 годы"
    kaz: Шардара аудандық мәслихатының 2010 жылғы 22 желтоқсандағы № 39-287-IV "2011-2013 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер негізу туралы
  link: https://zan.gov.kz/client/#!/doc/61415/rus
