act_code: '137977'
requisite: Решение Келесского районного маслихата Туркестанской области от 25 декабря 2019 года № 21-156-VI. Зарегистрировано Департаментом юстиции Туркестанской области 8 января 2020 года № 5354
title:
  rus: О бюджетах села и сельских округов на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған ауыл және ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '166018000002'
version_date:
  kaz: 2020-12-28
  rus: 2020-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/137977/kaz/28.12.2020
  rus: https://zan.gov.kz/client/#!/doc/137977/rus/28.12.2020
caused_by:
  code: '150953'
  requisite: Решение Келесского районного маслихата Туркестанской области от 28 декабря 2020 года № 35-263-VI. Зарегистрировано Департаментом юстиции Туркестанской области 30 декабря 2020 года № 5985
  title:
    rus: О внесении изменений в решение Келесского районного маслихата от 25 декабря 2019 года № 21-156-VI «О бюджетах села и сельских округов на 2020-2022 годы»
    kaz: Келес аудандық мәслихатының 2019 жылғы 25 желтоқсандағы № 21-156-VI «2020-2022 жылдарға арналған ауыл және ауылдық округтердің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/150953/rus
