act_code: '193649'
requisite: Решение Жетысайского районного маслихата Туркестанской области от 22 февраля 2024 года № 13-77-VIII. Зарегистрировано в Департаменте юстиции Туркестанской области 23 февраля 2024 года № 6466-13
title:
  rus: Об оказании в 2024 году дополнительной социальной помощи ветеранам войны в Афганистане к 35-летию вывода ограниченного контингента Советских войск из Демократической Республики Афганистан
  kaz: 2024 жылы Ауғанстан Демократиялық Республикасынан Кеңес әскерлері шектеулі контингентінің шығарылғанына 35-жылдығына орай Ауғанстан соғысының ардагерлеріне қосымша әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-22
approved_by:
- '166017000002'
version_date:
  kaz: 2024-02-22
  rus: 2024-02-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/193649/kaz/22.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193649/rus/22.02.2024
