act_code: '60165'
requisite: Оңтүстік Қазақстан облысы Сарыағаш аудандық мәслихат сессиясының 2011 жылғы 12 тамыздағы N 48-364-IV шешімі. Оңтүстік Қазақстан облысы Сарыағаш ауданының Әділет басқармасында 2011 жылғы 23 тамызда N 14-11-172 тіркелді
title:
  rus: Сарыағаш ауданының ауылдық елді мекендерде жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына 2011 жылға әлеуметтік қолдау шараларын ұсыну туралы
  kaz: Сарыағаш ауданының ауылдық елді мекендерде жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына 2011 жылға әлеуметтік қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-08-12
approved_by:
- '166009000002'
version_date:
  kaz: 2012-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/60165/kaz/01.01.2012
