act_code: '128948'
requisite: Решение Жетысайского районного маслихата Туркестанской области от 27 декабря 2018 года № 10-50-VI. Зарегистрировано Департаментом юстиции Туркестанской области 31 января 2019 года № 4897. Утратило силу решением Жетысайского районного маслихата Туркестанской области от 7 февраля 2020 года № 27-151-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О предоставлении социальной помощи на оплату коммунальных услуг и приобретение топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Жетысайского района
  kaz: Жетісай ауданының ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебінен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алуға әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-27
approved_by:
- '166017000002'
version_date:
  kaz: 2018-12-27
  rus: 2018-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/128948/kaz/27.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128948/rus/27.12.2018
