act_code: '122098'
requisite: Решение акима Аккумского сельского округа Отрарского района Южно-Казахстанской области от 24 мая 2018 года № 8. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 1 июня 2018 года № 4620. Утратило силу решением акима Аккумского сельского округа Отырарского района Южно-Казахстанской области от 13 июля 2018 года № 10
title:
  rus: Об установлении ограничительных мероприятий на территории улицы Б.Абдурахманова в селе Аккум сельского округа Аккум
  kaz: Аққұм ауылдық округіне қарасты Аққұм ауылы Б.Әбдрахманов көшесінің аумағына шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-24
approved_by:
- '166007001002'
version_date:
  kaz: 2018-05-24
  rus: 2018-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/122098/kaz/24.05.2018
  rus: https://zan.gov.kz/client/#!/doc/122098/rus/24.05.2018
