act_code: '126173'
requisite: Решение акима Созакского района Туркестанской области от 22 ноября 2018 года № 28. Зарегистрировано Департаментом юстиции Туркестанской области 23 ноября 2018 года № 4807. Утратило силу решением акима Созакского района Туркестанской области от 16 июля 2021 года № 19 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков на территории Созакского района
  kaz: Созақ ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-22
approved_by:
- '166010000003'
version_date:
  kaz: 2019-12-27
  rus: 2019-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/126173/kaz/27.12.2019
  rus: https://zan.gov.kz/client/#!/doc/126173/rus/27.12.2019
caused_by:
  code: '137717'
  requisite: Решение акима Созакского района Туркестанской области от 27 декабря 2019 года № 20. Зарегистрировано Департаментом юстиции Туркестанской области 30 декабря 2019 года № 5337. Утратило силу решением акима Созакского района Туркестанской области от 16 июля 2021 года № 19 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнений в решение акима Созакского района от 22 ноября 2018 года № 28 «Об образовании избирательных участков на территории Созакского района»
    kaz: Созақ ауданы әкімінің 2018 жылғы 22 қарашадағы № 28 «Созақ ауданының аумағында сайлау учаскелерін құру туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/137717/rus
