act_code: '126173'
requisite: Решение акима Созакского района Туркестанской области от 22 ноября 2018 года № 28. Зарегистрировано Департаментом юстиции Туркестанской области 23 ноября 2018 года № 4807. Утратило силу решением акима Созакского района Туркестанской области от 16 июля 2021 года № 19 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков на территории Созакского района
  kaz: Созақ ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-22
approved_by:
- '166010000003'
version_date:
  kaz: 2018-11-22
  rus: 2018-11-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/126173/kaz/22.11.2018
  rus: https://zan.gov.kz/client/#!/doc/126173/rus/22.11.2018
