act_code: '146788'
requisite: Решение акима Балыктинского сельского округа акимата Тюлькубасского района Туркестанской области от 25 сентября 2020 года № 49. Зарегистрировано Департаментом юстиции Туркестанской области 25 сентября 2020 года № 5817
title:
  rus: О переименовании улиц в селе Балыкты Балыктинском сельском округе
  kaz: Балықты ауылдық округіндегі Балықты ауылындағы көшелеріне қайта атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-25
approved_by:
- '166012003002'
version_date:
  kaz: 2020-09-25
  rus: 2020-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/146788/kaz/25.09.2020
  rus: https://zan.gov.kz/client/#!/doc/146788/rus/25.09.2020
