act_code: '142693'
requisite: Решение Сарыагашского районного маслихата Туркестанской области от 16 апреля 2020 года № 50-445-VI. Зарегистрировано Департаментом юстиции Туркестанской области 6 мая 2020 года № 5607
title:
  rus: Об утверждении Правил и размеров оказания социальной поддержки специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населённых пунктах Сарыагашского района, по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств
  kaz: Сарыағаш ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария салаларындағы мемлекеттік ұйымдардың мамандарына коммуналдық қызметтерді төлеу және отын сатып алу үшін бюджет қаражаты есебінен әлеуметтік қолдау көрсету қағидалары мен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-04-16
approved_by:
- '166009000002'
version_date:
  kaz: 2025-10-03
  rus: 2025-10-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/142693/kaz/03.10.2025
  rus: https://zan.gov.kz/client/#!/doc/142693/rus/03.10.2025
caused_by:
  code: '215795'
  requisite: Решение Сарыагашского районного маслихата Туркестанской области от 3 октября 2025 года № 34-261-VIII. Зарегистрировано в Министерстве юстиции Республики Казахстан 17 октября 2025 года № 37159
  title:
    rus: О внесении изменений к решению Сарыагашского районного маслихата от 16 апреля 2020 года № 50-445-VI «Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Сарыагашского района»
    kaz: Сарыағаш аудандық мәслихатының 2020 жылғы 16 сәуірдегі № 50-445-VI «Сарыағаш ауданының ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебінен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсетудің тәртібі мен мөлшерін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/215795/rus
