act_code: '145093'
requisite: Решение Сарыагашского районного маслихата Туркестанской области от 25 июня 2020 года № 53-472-VI. Зарегистрировано Департаментом юстиции Туркестанской области 23 июля 2020 года № 5731
title:
  rus: О порядке организации и проведения мирных собраний в Сарыагашском районе
  kaz: Сарыағаш ауданында бейбіт жиналыстарды ұйымдастыру және өткізу тәртібі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-25
approved_by:
- '166009000002'
version_date:
  kaz: 2020-10-14
  rus: 2020-10-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/145093/kaz/14.10.2020
  rus: https://zan.gov.kz/client/#!/doc/145093/rus/14.10.2020
caused_by:
  code: '148059'
  requisite: Решение Сарыагашского районного маслихата Туркестанской области от 14 октября 2020 года № 56-508-VI. Зарегистрировано Департаментом юстиции Туркестанской области 28 октября 2020 года № 5865
  title:
    rus: О внесении изменений в решение Сарыагашского районного маслихата от 25 июня 2020 года № 53-472-VI «О порядке организации и проведения мирных собраний в Сарыагашского района»
    kaz: Сарыағаш аудандық мәслихатының 2020 жылғы 25 маусымдағы № 53-472-VI «Сарыағаш ауданында бейбіт жиналыстарды ұйымдастыру және өткізу тәртібі туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148059/rus
