act_code: '145093'
requisite: Решение Сарыагашского районного маслихата Туркестанской области от 25 июня 2020 года № 53-472-VI. Зарегистрировано Департаментом юстиции Туркестанской области 23 июля 2020 года № 5731
title:
  rus: О порядке организации и проведения мирных собраний в Сарыагашском районе
  kaz: Сарыағаш ауданында бейбіт жиналыстарды ұйымдастыру және өткізу тәртібі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-25
approved_by:
- '166009000002'
version_date:
  kaz: 2024-06-27
  rus: 2024-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/145093/kaz/27.06.2024
  rus: https://zan.gov.kz/client/#!/doc/145093/rus/27.06.2024
caused_by:
  code: '198445'
  requisite: Решение Сарыагашского районного маслихата Туркестанской области от 27 июня 2024 года № 19-149-VIII. Зарегистрировано в Департаменте юстиции Туркестанской области 3 июля 2024 года № 6550-13
  title:
    rus: О внесении изменения в решение Сарыагашского районного маслихата от 25 июня 2020 года № 53-472-VI «О порядке организации и проведения мирных собраний в Сарыагашском районе»
    kaz: Сарыағаш аудандық мәслихатының 2020 жылғы 25 маусымдағы № 53-472-VI «Cарыағаш ауданында бейбіт жиналыстарды ұйымдастыру және өткізу тәртібі туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198445/rus
