act_code: '48149'
requisite: Оңтүстік Қазақстан облысы Мақтаарал ауданы әкімдігі Достық ауылдық округі әкімінің 2009 жылғы 14 қыркүйектегі N 12 шешімі. Оңтүстік Қазақстан облысы Мақтаарал ауданы Әділет басқармасында 2009 жылғы 9 қазанда N 14-7-91 тіркелді
title:
  rus: Ауыл көшелерін атау және қайта атау туралы
  kaz: Ауыл көшелерін атау және қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-09-14
approved_by:
- '166005005001'
version_date:
  kaz: 2009-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/48149/kaz/14.09.2009
