act_code: '59592'
requisite: Оңтүстік Қазақстан облысы Ордабасы ауданы Қараспан ауылдық округі әкімінің 2011 жылғы 5 шілдедегі № 39 шешімі. Оңтүстік Қазақстан облысы Ордабасы ауданының Әділет басқармасында 2011 жылғы 14 шілдеде № 14-8-106 тіркелді
title:
  rus: Көше атын беру туралы
  kaz: Көше атын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-07-05
approved_by:
- '166006004001'
version_date:
  kaz: 2011-07-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/59592/kaz/05.07.2011
