act_code: '41514'
requisite: Оңтүстік Қазақстан облысы Сайрам аудандық мәслихат сесиясының 2008 жылғы 7 тамыздағы N 9/111-IV шешімі. Оңтүстік Қазақстан облысы Сайрам ауданының Әділет басқармасында 2008 жылғы 15 қыркүйекте N 14-10-100 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Сайрам аудандық мәслихат сессиясының 2010 жылғы 30 маусымдағы N 33-299/IV шешімімен
title:
  rus: Жергілікті бюджеттен қаржыландыратын мемлекеттік мекемелердің мамандарына отын сатып алуға әлеуметтік көмек беру туралы
  kaz: Жергілікті бюджеттен қаржыландыратын мемлекеттік мекемелердің мамандарына отын сатып алуға әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-08-07
approved_by:
- '166008000002'
version_date:
  kaz: 2008-08-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/41514/kaz/07.08.2008
