act_code: '190898'
requisite: Решение Шардаринского районного маслихата Туркестанской области от 22 декабря 2023 года № 15-67-VIII
title:
  rus: О районном бюджете на 2024-2026 годы
  kaz: 2024-2026 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-22
approved_by:
- '166013000002'
version_date:
  kaz: 2024-04-24
  rus: 2024-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/190898/kaz/24.04.2024
  rus: https://zan.gov.kz/client/#!/doc/190898/rus/24.04.2024
caused_by:
  code: '196125'
  requisite: Решение Шардаринского районного маслихата Туркестанской области от 24 апреля 2024 года № 22-108-VIII
  title:
    rus: О внесении изменений в решение районного маслихата от 22 декабря 2023 года № 15-67-VІІІ «О районном бюджете на 2024-2026 годы»
    kaz: Шардара аудандық мәслихатының 2023 жылғы 22 желтоқсандағы № 15-67-VІІІ «2024-2026 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/196125/rus
