act_code: '69654'
requisite: Решение маслихата Созакского района Южно-Казахстанской области от 21 декабря 2012 года № 61. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 29 декабря 2012 года № 2196
title:
  rus: О районном бюджете на 2013-2015 годы
  kaz: 2013-2015 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-21
approved_by:
- '166010000002'
version_date:
  kaz: 2013-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/69654/kaz/18.12.2013
caused_by:
  code: '75979'
  requisite: Решение Созакского районного маслихата Южно-Казахстанской области от 18 декабря 2013 года № 130. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 19 декабря 2013 года № 2447
  title:
    rus: О внесении изменений в решение Созакского районного маслихата от 21 декабря 2012 года № 61 "О районном бюджете на 2013-2015 годы"
    kaz: Созақ аудандық мәслихатының 2012 жылғы 21 желтоқсандағы № 61 "2013-2015 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/75979/rus
