act_code: '53923'
requisite: Оңтүстік Қазақстан облысы Отырар ауданы әкімдігі Қоғам ауылдық округі әкімінің 2010 жылғы 1 шілдедегі N 44 шешімі. Оңтүстік Қазақстан облысы Отырар ауданының Әділет басқармасында 2010 жылғы 10 тамызда N 14-9-118 тіркелді
title:
  rus: Көшеге ат қою туралы
  kaz: Көшеге ат қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-01
approved_by:
- '166007006001'
version_date:
  kaz: 2010-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/53923/kaz/01.07.2010
