act_code: '49834'
requisite: Оңтүстік Қазақстан облысы Созақ аудандық мәслихатының 2009 жылғы 25 желтоқсандағы N 152 шешімі. Оңтүстік Қазақстан облысы Созақ ауданының Әділет басқармасында 2010 жылғы 11 қаңтарда N 14-12-82 тіркелді
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '166010000002'
version_date:
  kaz: 2010-05-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/49834/kaz/28.05.2010
caused_by:
  code: '53018'
  requisite: Оңтүстік Қазақстан облысы Созақ аудандық мәслихатының 2010 жылғы 28 мамырдағы N 186 шешімі. Оңтүстік Қазақстан облысы Созақ ауданының Әділет басқармасында 2010 жылғы 8 маусымда N 14-12-96 тіркелді
  title:
    rus: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Созақ аудандық мәслихатының 2009 жылғы 25 желтоқсандағы N 152 шешіміне өзгерістер енгізу туралы'
    kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Созақ аудандық мәслихатының 2009 жылғы 25 желтоқсандағы N 152 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/53018/rus
