act_code: '137702'
requisite: Решение Жетысайского районного маслихата Туркестанской области от 24 декабря 2019 года № 25-142-VI. Зарегистрировано Департаментом юстиции Туркестанской области 27 декабря 2019 года № 5331
title:
  rus: О районном бюджете на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-24
approved_by:
- '166017000002'
version_date:
  kaz: 2020-09-03
  rus: 2020-09-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/137702/kaz/03.09.2020
  rus: https://zan.gov.kz/client/#!/doc/137702/rus/03.09.2020
caused_by:
  code: '146348'
  requisite: Решение Жетысайского районного маслихата Туркестанской области от 3 сентября 2020 года № 34-183-VI. Зарегистрировано Департаментом юстиции Туркестанской области 15 сентября 2020 года № 5801
  title:
    rus: О внесении изменений в решение Жетысайского районного маслихата от 24 декабря 2019 года № 25-142-VI «О районном бюджете на 2020-2022 годы»
    kaz: Жетісай аудандық мәслихатының 2019 жылғы 24 желтоқсандағы № 25-142-VI «2020-2022 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146348/rus
