act_code: '76379'
requisite: Решение Туркестанского городского маслихата Южно-Казахстанской области от 20 декабря 2013 года № 22/122-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 31 декабря 2013 года № 2477
title:
  rus: О городском бюджете на 2014-2016 годы
  kaz: 2014-2016 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-20
approved_by:
- '166015000002'
version_date:
  kaz: 2014-04-23
  rus: 2014-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/76379/kaz/23.04.2014
  rus: https://zan.gov.kz/client/#!/doc/76379/rus/23.04.2014
caused_by:
  code: '79241'
  requisite: Решение Туркестанского городского маслихата Южно-Казахстанской области от 23 апреля 2014 года № 27/158-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 29 апреля 2014 года № 2644
  title:
    rus: О внесении изменений в решение Туркестанского городского маслихата от 20 декабря 2013 года № 22/122-V "О городском бюджете на 2014-2016 годы"
    kaz: Түркістан қалалық мәслихатының 2013 жылғы 20 желтоқсандағы № 22/122-V "2014-2016 жылдарға арналған қалалық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/79241/rus
