act_code: '56245'
requisite: Оңтүстік Қазақстан облысы Отырар аудандық мәслихатының 2010 жылғы 24 желтоқсандағы N 36/229-IV шешімі. Оңтүстік Қазақстан облысы Отырар ауданының Әділет басқармасында 2010 жылғы 28 желтоқсанда N 14-9-139 тіркелді
title:
  rus: 2011-2013 жылдарға арналған аудан бюджеті туралы
  kaz: 2011-2013 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '166007000002'
version_date:
  kaz: 2012-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/56245/kaz/01.01.2012
