act_code: '147653'
requisite: Решение Тюлькубасского районного маслихата Туркестанской области от 29 сентября 2020 года № 60/3-06. Зарегистрировано Департаментом юстиции Туркестанской области 21 октября 2020 года № 5852. Утратило силу решением Тюлькубасского районного маслихата Туркестанской области от 27 сентября 2022 года № 23/5-07 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О повышении базовых ставок земельного налога на не используемые земли сельскохозяйственного назначения
  kaz: Пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерге жер салығының базалық мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-29
approved_by:
- '166012000002'
version_date:
  kaz: 2020-09-29
  rus: 2020-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/147653/kaz/29.09.2020
  rus: https://zan.gov.kz/client/#!/doc/147653/rus/29.09.2020
