act_code: '76033'
requisite: Решение областного маслихата Южно-Казахстанской области от 10 декабря 2013 года № 21/172-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 18 декабря 2013 года № 2441
title:
  rus: Об областном бюджете на 2014-2016 годы
  kaz: 2014-2016 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-10
approved_by:
- '166000000002'
version_date:
  kaz: 2014-04-15
  rus: 2014-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/76033/kaz/15.04.2014
  rus: https://zan.gov.kz/client/#!/doc/76033/rus/15.04.2014
caused_by:
  code: '78853'
  requisite: Решение областного маслихата Южно-Казахстанской области от 15 апреля 2014 года № 26/209-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 17 апреля 2014 года № 2608
  title:
    rus: О внесении изменений и дополнений в решение Южно-Казахстанского областного маслихата от 10 декабря 2013 года № 21/172-V "Об областном бюджете на 2014-2016 годы"
    kaz: Оңтүстік Қазақстан облыстық мәслихатының 2013 жылғы 10 желтоқсандағы № 21/172-V "2014-2016 жылдарға арналған облыстық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/78853/rus
