act_code: '45851'
requisite: Решение областного маслихата Южно-Казахстанской области от 23 апреля 2009 года № 17/215-IV. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 13 мая 2009 года № 2010. Утратило силу решением Туркестанского областного маслихата от 28 августа 2018 года № 29/315-VI
title:
  rus: Об утверждении Правил присвоения звания "Почетный гражданин Южно-Казахстанской области (города, района Южно-Казахстанской области)"
  kaz: '"Оңтүстік Қазақстан облысының (Оңтүстік Қазақстан облысының қаласының, ауданының) Құрметті азаматы" атағын беру қағидасын бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-23
approved_by:
- '166000000002'
version_date:
  kaz: 2013-06-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/45851/kaz/26.06.2013
caused_by:
  code: '73658'
  requisite: Решение областного маслихата Южно-Казахстанской области от 26 июня 2013 года № 14/123-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 26 июля 2013 года № 2344. Утратило силу решением Туркестанского областного маслихата от 28 августа 2018 года № 29/315-VI
  title:
    rus: О внесении изменений в решение Южно-Казахстанского областного маслихата от 23 апреля 2009 года № 17/215-IV "Об утверждении Правил присвоения звания "Почетный гражданин Южно-Казахстанской области (города, района Южно-Казахстанской области)"
    kaz: Оңтүстік Қазақстан облыстық мәслихатының 2009 жылғы 23 сәуірдегі № 17/215-IV "Оңтүстік Қазақстан облысының (Оңтүстік Қазақстан облысының қаласының, ауданының) Құрметті азаматы" атағын беру ережесін бекіту туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/73658/rus
