act_code: '45851'
requisite: Решение областного маслихата Южно-Казахстанской области от 23 апреля 2009 года № 17/215-IV. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 13 мая 2009 года № 2010. Утратило силу решением Туркестанского областного маслихата от 28 августа 2018 года № 29/315-VI
title:
  rus: Об утверждении Правил присвоения звания "Почетный гражданин Южно-Казахстанской области (города, района Южно-Казахстанской области)"
  kaz: '"Оңтүстік Қазақстан облысының (Оңтүстік Қазақстан облысының қаласының, ауданының) Құрметті азаматы" атағын беру қағидасын бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-23
approved_by:
- '166000000002'
version_date:
  kaz: 2009-04-23
  rus: 2009-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/45851/kaz/23.04.2009
  rus: https://zan.gov.kz/client/#!/doc/45851/rus/23.04.2009
