act_code: '127461'
requisite: Решение Мактааральского районного маслихата Туркестанской области от 23 ноября 2018 года № 41-275-VI. Зарегистрировано Департаментом юстиции Туркестанской области 21 декабря 2018 года № 4844. Утратило силу решением Мактааральского районного маслихата Туркестанской области от 30 апреля 2020 года № 64-400-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О предоставлении социальной помощи на оплату коммунальных услуг и приобретение топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Мактааральского района
  kaz: Мақтаарал ауданының ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебінен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алуға әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-23
approved_by:
- '166005000002'
version_date:
  kaz: 2018-11-23
  rus: 2018-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/127461/kaz/23.11.2018
  rus: https://zan.gov.kz/client/#!/doc/127461/rus/23.11.2018
