act_code: '77713'
requisite: Решение Шардаринского районного маслихата Южно-Казахстанской области от 24 февраля 2014 года № 25-155-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 28 февраля 2014 года № 2552
title:
  rus: О предоставлении в 2014 году подъемного пособия и социальной поддержки для приобретения или строительства жилья специалистам здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, прибывшим для работы и проживания в сельские населенные пункты Шардаринского района
  kaz: Шардара ауданының ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен мамандарына 2014 жылы көтерме жәрдемақы және тұрғын үй сатып алу немесе салу үшін әлеуметтік қолдауды ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-24
approved_by:
- '166013000002'
version_date:
  kaz: 2015-01-01
  rus: 2015-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/77713/kaz/01.01.2015
  rus: https://zan.gov.kz/client/#!/doc/77713/rus/01.01.2015
