act_code: '99169'
requisite: Решение Ордабасинского районного маслихата Южно-Казахстанской области от 20 января 2016 года № 51/4
title:
  rus: О признании утратившим силу решение Ордабасинского районного маслихата от 24 ноября 2015 года 47/1 «О повышении ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения»
  kaz: «Пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының мөлшерлемесін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы» Ордабасы аудандық мәслихатының 2015 жылғы 24 қарашадағы № 47/1 шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-01-20
approved_by:
- '166006000002'
version_date:
  kaz: 2016-01-20
  rus: 2016-01-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/99169/kaz/20.01.2016
  rus: https://zan.gov.kz/client/#!/doc/99169/rus/20.01.2016
