act_code: '125951'
requisite: Решение акима Ордабасынского района Туркестанской области от 8 ноября 2018 года № 31. Зарегистрировано Департаментом юстиции Туркестанской области 12 ноября 2018 года № 4775. Утратило силу решением акима Ордабасынского района Туркестанской области от 22 июля 2024 года № 23 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков на территории Ордабасынского района
  kaz: Ордабасы ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-08
approved_by:
- '166006000003'
version_date:
  kaz: 2018-11-08
  rus: 2018-11-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/125951/kaz/08.11.2018
  rus: https://zan.gov.kz/client/#!/doc/125951/rus/08.11.2018
