act_code: '125951'
requisite: Решение акима Ордабасынского района Туркестанской области от 8 ноября 2018 года № 31. Зарегистрировано Департаментом юстиции Туркестанской области 12 ноября 2018 года № 4775. Утратило силу решением акима Ордабасынского района Туркестанской области от 22 июля 2024 года № 23 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков на территории Ордабасынского района
  kaz: Ордабасы ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-08
approved_by:
- '166006000003'
version_date:
  kaz: 2022-09-21
  rus: 2022-09-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/125951/kaz/21.09.2022
  rus: https://zan.gov.kz/client/#!/doc/125951/rus/21.09.2022
caused_by:
  code: '172009'
  requisite: Решение акима Ордабасынского района Туркестанской области от 21 сентября 2022 года № 29. Зарегистрировано в Министерстве юстиции Республики Казахстан 23 сентября 2022 года № 29781. Утратило силу решением акима Ордабасынского района Туркестанской области от 22 июля 2024 года № 23 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение акима Ордабасынского района от 8 ноября 2018 года № 31 «Об образовании избирательных участков на территории Ордабасынского района»
    kaz: Ордабасы ауданы әкімінің 2018 жылғы 8 қарашадағы № 31 «Ордабасы ауданының аумағында сайлау учаскелерін құру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172009/rus
