act_code: '129263'
requisite: Решение акима Тастумсыкского сельского округа акимата Тюлькубасского района Туркестанской области от 19 февраля 2019 года № 5. Зарегистрировано Департаментом юстиции Туркестанской области 22 февраля 2019 года № 4913
title:
  rus: О присвоении наименований безымянным улицам населенных пунктов в сельском округе Тастумсык
  kaz: Тастұмсық ауылдық округіндегі елді мекендердегі атаусыз көшелерге атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-02-19
approved_by:
- '166012006002'
version_date:
  kaz: 2019-12-18
  rus: 2019-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/129263/kaz/18.12.2019
  rus: https://zan.gov.kz/client/#!/doc/129263/rus/18.12.2019
caused_by:
  code: '137507'
  requisite: Решение акима Тастумсыкского сельского округа акимата Тюлькубасского района Туркестанской области от 18 декабря 2019 года № 35. Зарегистрировано Департаментом юстиции Туркестанской области 25 декабря 2019 года № 5318
  title:
    rus: О внесении изменений в решение акима сельского округа Тастумсык от 19 февраля 2019 года № 5 «О присвоении наименований безымянным улицам населенных пунктов в сельском округе Тастумсык»
    kaz: Тастұмсық ауылдық округі әкімінің 2019 жылғы 19 ақпандағы № 5 «Тастұмсық ауылдық округіндегі елді мекендердегі атаусыз көшелерге атаулар беру туралы» шешіміне өзгерістер енгізу туралы»
  link: https://zan.gov.kz/client/#!/doc/137507/rus
