act_code: '56248'
requisite: Оңтүстік Қазақстан облысы Сарыағаш аудандық мәслихатының 2010 жылғы 21 желтоқсандағы N 43-290-IV шешімі. Оңтүстік Қазақстан облысы Сарыағаш ауданының Әділет басқармасында 2010 жылғы 28 желтоқсанда N 14-11-163 тіркелді
title:
  rus: 2011-2013 жылдарға арналған аудандық бюджет туралы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-21
approved_by:
- '166009000002'
version_date:
  kaz: 2011-11-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/56248/kaz/11.11.2011
caused_by:
  code: '61300'
  requisite: Решение маслихата Сарыагашского района Южно-Казахстанской области от 11 ноября 2011 года N 52-391-IV. Зарегистрировано Управлением юстиции Сарыагашского района Южно-Казахстанской области 15 ноября 2011 года N 14-11-175
  title:
    rus: О внесении изменений в решение Сарыагашского районного маслихата от 21 декабря 2010 года № 43-290-IV "О районном бюджете на 2011-2013 годы"
    kaz: Сарыағаш аудандық мәслихатының 2010 жылғы 21 желтоқсандағы № 43-290-IV "2011-2013 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/61300/rus
