act_code: '56248'
requisite: Оңтүстік Қазақстан облысы Сарыағаш аудандық мәслихатының 2010 жылғы 21 желтоқсандағы N 43-290-IV шешімі. Оңтүстік Қазақстан облысы Сарыағаш ауданының Әділет басқармасында 2010 жылғы 28 желтоқсанда N 14-11-163 тіркелді
title:
  rus: 2011-2013 жылдарға арналған аудандық бюджет туралы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-21
approved_by:
- '166009000002'
version_date:
  kaz: 2011-05-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/56248/kaz/31.05.2011
caused_by:
  code: '59149'
  requisite: Оңтүстік Қазақстан облысы Сарыағаш аудандық мәслихатының 2011 жылғы 31 мамырдағы N 46-340-IV шешімі. Оңтүстік Қазақстан облысы Сарыағаш ауданының Әділет басқармасында 2011 жылғы 8 маусымда N 14-11-170 тіркелді
  title:
    rus: Сарыағаш аудандық мәслихатының 2010 жылғы 21 желтоқсандағы № 43-290-IV "2011-2013 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
    kaz: Сарыағаш аудандық мәслихатының 2010 жылғы 21 желтоқсандағы № 43-290-IV "2011-2013 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/59149/rus
