act_code: '194974'
requisite: Решение Отрарского районного маслихата Туркестанской области от 29 марта 2024 года № 13/71-VII. Зарегистрировано в Департаменте юстиции Туркестанской области 29 марта 2024 года № 6505-13. Утратило силу решением Отрарского районного маслихата Туркестанской области от 19 февраля 2026 года № 33/190-VIII (вводится в действие с 01.01.2026 и подлежит официальному опубликованию)
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога в Отырарском районе
  kaz: Отырар ауданында бөлшек салықтың арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-29
approved_by:
- '166007000002'
version_date:
  kaz: 2024-03-29
  rus: 2024-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/194974/kaz/29.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194974/rus/29.03.2024
