act_code: '226129'
requisite: Решение Туркестанского городского маслихата Туркестанской области от 20 мая 2026 года № 43/193-III. Зарегистрировано в Министерстве юстиции Республики Казахстан 22 мая 2026 года № 38772
title:
  rus: Об утверждении порядка использования региональной символики на территории города Туркестана
  kaz: Түркістан қаласының аумағында өңірлік нышанды пайдалану тәртібін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-05-20
approved_by:
- '166015000002'
version_date:
  kaz: 2026-05-20
  rus: 2026-05-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/226129/kaz/20.05.2026
  rus: https://zan.gov.kz/client/#!/doc/226129/rus/20.05.2026
