act_code: '50008'
requisite: Оңтүстік Қазақстан облысы Бәйдібек аудандық мәслихатының 2009 жылғы 21 желтоқсандағы N 26/143 шешімі. Оңтүстік Қазақстан облысы Бәйдібек ауданының Әділет басқармасында 2010 жылғы 19 қаңтарда N 14-5-88 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Бәйдібек ауданы мәслихатының 2012 жылғы 24 тамыздағы № 6/31 Шешімімен
title:
  rus: Шаян ауылының және аудан көлеміндегі елді мекендердің жер учаскелерін жеке меншікке сататын мемлекет немесе мемлекеттік жер пайдаланушылар жалға берген кезде жер пайдалануға құқық беретін аймақтық белдеуімен бағалық құнын түзету коэффициенттерін белгілеу туралы
  kaz: Шаян ауылының және аудан көлеміндегі елді мекендердің жер учаскелерін жеке меншікке сататын мемлекет немесе мемлекеттік жер пайдаланушылар жалға берген кезде жер пайдалануға құқық беретін аймақтық белдеуімен бағалық құнын түзету коэффициенттерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-21
approved_by:
- '166003000002'
version_date:
  kaz: 2009-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/50008/kaz/21.12.2009
