act_code: '21152'
requisite: Решение акима Южно-Казахстанской области от 9 августа 2004 года № 36. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 31 августа 2004 года № 1477
title:
  rus: Вопросы медицинского осмотра юношей допризывного возраста
  kaz: Әскерге дейiнгi жасөспiрiмдердi медициналық тексеруден өткiзу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-08-08
approved_by:
- '166000000003'
version_date:
  kaz: 2004-08-08
  rus: 2004-08-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/21152/kaz/08.08.2004
  rus: https://zan.gov.kz/client/#!/doc/21152/rus/08.08.2004
