act_code: '163814'
requisite: Решение Байдибекского районного маслихата Туркестанской области от 29 декабря 2021 года № 13/85
title:
  rus: О бюджетах сельских округов на 2021-2023 годы
  kaz: 2022 – 2024 жылдарға арналған ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '166003000002'
version_date:
  kaz: 2022-04-19
  rus: 2022-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/163814/kaz/19.04.2022
  rus: https://zan.gov.kz/client/#!/doc/163814/rus/19.04.2022
caused_by:
  code: '166890'
  requisite: Решение Байдибекского районного маслихата Туркестанской области от 19 апреля 2022 года № 17/107
  title:
    rus: О внесении изменений в решение маслихата района Байдибек от 29 декабря 2021 года № 13/85 «О бюджетах сельских округов на 2022-2024 годы»
    kaz: Бәйдібек аудандық мәслихатының 2021 жылғы 29 желтоқсандағы № 13/85 «2022-2024 жылдарға арналған ауылдық округтердің бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166890/rus
