act_code: '137722'
requisite: Решение Сайрамского районного маслихата Туркестанской области от 18 декабря 2019 года № 49-300/VI. Зарегистрировано Департаментом юстиции Туркестанской области 30 декабря 2019 года № 5339
title:
  rus: О районном бюджете на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-18
approved_by:
- '166008000002'
version_date:
  kaz: 2019-12-18
  rus: 2019-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/137722/kaz/18.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137722/rus/18.12.2019
