act_code: '100821'
requisite: Решение Шардаринского районного маслихата Южно-Казахстанской области от 25 февраля 2016 года № 54-311-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 29 марта 2016 года № 3667. Утратило силу решением Шардаринского районного маслихата Южно-Казахстанской области от 17 марта 2017 года № 13-92-VI
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» аппарата Шардаринского районного маслихата
  kaz: «Б» корпусы Шардара аудандық мәслихат аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2016-02-25
approved_by:
- '166013000002'
version_date:
  kaz: 2016-02-25
  rus: 2016-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/100821/kaz/25.02.2016
  rus: https://zan.gov.kz/client/#!/doc/100821/rus/25.02.2016
