act_code: '43573'
requisite: Оңтүстік Қазақстан облысы Кентау қалалық мәслихатының 2008 жылғы 26 желтоқсандағы N 113 шешімі. Оңтүстік Қазақстан облысы Кентау қаласының Әділет басқармасында 2009 жылғы 16 қаңтарда N 14-3-67 тіркелді
title:
  rus: 2009 жылға арналған қалалық бюджет туралы
  kaz: 2009 жылға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-26
approved_by:
- '166014000002'
version_date:
  kaz: 2009-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/43573/kaz/15.07.2009
caused_by:
  code: '47106'
  requisite: Оңтүстік Қазақстан облысы Кентау қалалық мәслихатының 2009 жылғы 15 шілдедегі N 163 шешімі. Оңтүстік Қазақстан облысы Кентау қаласының Әділет басқармасында 2009 жылғы 3 тамызда N 14-3-76 тіркелді
  title:
    rus: '"2009 жылға арналған қалалық бюджет туралы" Кентау қалалық мәслихатының 2008 жылғы 26 желтоқсандағы N 113 шешіміне өзгерістер мен толықтырулар енгізу туралы'
    kaz: '"2009 жылға арналған қалалық бюджет туралы" Кентау қалалық мәслихатының 2008 жылғы 26 желтоқсандағы N 113 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/47106/rus
