act_code: '43573'
requisite: Оңтүстік Қазақстан облысы Кентау қалалық мәслихатының 2008 жылғы 26 желтоқсандағы N 113 шешімі. Оңтүстік Қазақстан облысы Кентау қаласының Әділет басқармасында 2009 жылғы 16 қаңтарда N 14-3-67 тіркелді
title:
  rus: 2009 жылға арналған қалалық бюджет туралы
  kaz: 2009 жылға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-26
approved_by:
- '166014000002'
version_date:
  kaz: 2009-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/43573/kaz/24.02.2009
caused_by:
  code: '44438'
  requisite: Оңтүстік Қазақстан облысы Кентау қалалық мәслихатының 2009 жылғы 24 ақпандағы N 128 шешімі. Оңтүстік Қазақстан облысы Кентау қаласының Әділет басқармасында 2009 жылғы 26 ақпанда N 14-3-69 тіркелді
  title:
    rus: '"2009 жылға арналған қалалық бюджет туралы" Кентау қалалық мәслихатының 2008 жылғы 26 желтоқсандағы N 113 шешіміне өзгерістер мен толықтырулар енгізу туралы'
    kaz: '"2009 жылға арналған қалалық бюджет туралы" Кентау қалалық мәслихатының 2008 жылғы 26 желтоқсандағы N 113 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/44438/rus
