act_code: '152555'
requisite: Решение Тюлькубасского районного маслихата Туркестанской области от 21 декабря 2020 года № 64/6-06. Зарегистрировано Департаментом юстиции Туркестанской области 29 января 2021 года № 6046. Утратило силу решением Тюлькубасского районного маслихата Туркестанской области от 3 ноября 2023 года № 8/3-08 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Тюлькубасского района
  kaz: Түлкібас ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекеленген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-12-21
approved_by:
- '166012000002'
version_date:
  kaz: 2022-11-28
  rus: 2022-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/152555/kaz/28.11.2022
  rus: https://zan.gov.kz/client/#!/doc/152555/rus/28.11.2022
caused_by:
  code: '175464'
  requisite: Решение Тюлькубасского районного маслихата Туркестанской области от 28 ноября 2022 года № 25/2-07. Зарегистрировано в Министерстве юстиции Республики Казахстан 12 декабря 2022 года № 31065. Утратило силу решением Тюлькубасского районного маслихата Туркестанской области от 3 ноября 2023 года № 8/3-08 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата Тюлькубасского района от 21 декабря 2020 года № 64/6-06 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Түлкібас ауданы мәслихатының 2020 жылғы 21 желтоқсандағы № 64/6-06 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидасын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/175464/rus
