act_code: '152555'
requisite: Решение Тюлькубасского районного маслихата Туркестанской области от 21 декабря 2020 года № 64/6-06. Зарегистрировано Департаментом юстиции Туркестанской области 29 января 2021 года № 6046. Утратило силу решением Тюлькубасского районного маслихата Туркестанской области от 3 ноября 2023 года № 8/3-08 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Тюлькубасского района
  kaz: Түлкібас ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекеленген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-12-21
approved_by:
- '166012000002'
version_date:
  kaz: 2020-12-21
  rus: 2020-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/152555/kaz/21.12.2020
  rus: https://zan.gov.kz/client/#!/doc/152555/rus/21.12.2020
