act_code: '98828'
requisite: Решение Байдибекского районного маслихата Южно-Казахстанской области от 20 января 2016 года № 45/249. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 3 февраля 2016 года № 3566
title:
  rus: О предоставлении в 2016 году подъемного пособия и бюджетного кредита на приобретение или строительства жилья специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, прибывшим для работы и проживания в сельские населенные пункты Байдибекского района
  kaz: Бәйдібек ауданының ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік  кешен саласындағы мамандарға 2016 жылы көтерме жәрдемақы және тұрғын үй сатып алу немесе салу үшін бюджеттік кредит беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-01-20
approved_by:
- '166003000002'
version_date:
  kaz: 2017-01-01
  rus: 2017-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/98828/kaz/01.01.2017
  rus: https://zan.gov.kz/client/#!/doc/98828/rus/01.01.2017
