act_code: '129898'
requisite: Решение акима сельского округа Майлыкент Тюлькубасского района Туркестанской области от 27 марта 2019 года № 26. Зарегистрировано Департаментом юстиции Туркестанской области 28 марта 2019 года № 4951
title:
  rus: О переименовании микрорайонов Майлыкентского сельского округа
  kaz: Майлыкент ауылдық округіне қарасты шағынаудандарды қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-03-27
approved_by:
- '166012008002'
version_date:
  kaz: 2019-03-27
  rus: 2019-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/129898/kaz/27.03.2019
  rus: https://zan.gov.kz/client/#!/doc/129898/rus/27.03.2019
