act_code: '49506'
requisite: Оңтүстік Қазақстан облысы Сарыағаш аудандық мәслихатының 2009 жылғы 23 желтоқсандағы N 30-196-IV шешімі. Оңтүстік Қазақстан облысы Сарыағаш ауданының Әділет басқармасында 2009 жылғы 25 желтоқсанда N 14-11-115 тіркелді
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '166009000002'
version_date:
  kaz: 2010-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/49506/kaz/19.03.2010
caused_by:
  code: '51505'
  requisite: Оңтүстік Қазақстан облысы Сарыағаш аудандық мәслихат сессиясының 2010 жылғы 19 наурыздағы N 34-224-IV шешімі. Оңтүстік Қазақстан облысы Сарыағаш ауданының Әділет басқармасында 2010 жылғы 26 наурызда N 14-11-121 тіркелді
  title:
    rus: Сарыағаш аудандық мәслихатының 2009 жылғы 23 желтоқсандағы N 30-196-IV "2010-2012 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Сарыағаш аудандық мәслихатының 2009 жылғы 23 желтоқсандағы N 30-196-IV "2010-2012 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/51505/rus
