act_code: '55526'
requisite: Оңтүстік Қазақстан облысы Арыс қалалық мәслихатының 2010 жылғы 20 тамыздағы N 36/224-IV шешімі. Оңтүстік Қазақстан облысы Арыс қаласының Әділет басқармасында 2010 жылғы 26 тамызда N 14-2-98 тіркелді
title:
  rus: Арыс қалалық мәслихатының 2009 жылғы 21 желтоқсандағы N 28/164-IV "2010-2012 жылдарға арналған қалалық бюджет туралы" шешіміне өзгерістер  енгізу туралы
  kaz: Арыс қалалық мәслихатының 2009 жылғы 21 желтоқсандағы N 28/164-IV "2010-2012 жылдарға арналған қалалық бюджет туралы" шешіміне өзгерістер  енгізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-20
approved_by:
- '166016000002'
version_date:
  kaz: 2010-08-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/55526/kaz/20.08.2010
