act_code: '191222'
requisite: Решение Байдибекского районного маслихата Туркестанской области от 29 декабря 2023 года № 12/56
title:
  rus: О бюджетах сельских округов на 2024-2026 годы
  kaz: 2024–2026 жылдарға арналған ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-29
approved_by:
- '166003000002'
version_date:
  kaz: 2024-05-09
  rus: 2024-05-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/191222/kaz/09.05.2024
  rus: https://zan.gov.kz/client/#!/doc/191222/rus/09.05.2024
caused_by:
  code: '196612'
  requisite: Решение Байдибекского районного маслихата Туркестанской области от 9 мая 2024 года № 12/56
  title:
    rus: О внесении изменений в решение маслихата района Байдибек от 27 декабря 2023 года № 12/56 «О бюджетах сельских округов на 2024-2026 годы»
    kaz: Бәйдібек аудандық мәслихатының 2023 жылғы 27 желтоқсандағы «2024–2026 жылдарға арналған ауылдық округтердің бюджеттері туралы» № 12/56 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/196612/rus
