act_code: '172052'
requisite: Решение Созакского районного маслихата Туркестанской области от 23 сентября 2022 года № 127. Зарегистрировано в Министерстве юстиции Республики Казахстан 26 сентября 2022 года № 29803. Утратило силу решением Созакского районного маслихата Туркестанской области от 25 февраля 2026 года № 246 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов по Созакскому району
  kaz: Созақ ауданы бойынша тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-09-23
approved_by:
- '166010000002'
version_date:
  kaz: 2022-09-23
  rus: 2022-09-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/172052/kaz/23.09.2022
  rus: https://zan.gov.kz/client/#!/doc/172052/rus/23.09.2022
