act_code: '208327'
requisite: Решение акима Карасуского сельского округа Сайрамского района Туркестанской области от 3 марта 2025 года № 38
title:
  rus: О присвоении названи (наименований) улицам села Ақбай
  kaz: Ақбай елді мекеніндегі көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-03-03
approved_by:
- '166008009002'
version_date:
  kaz: 2025-03-03
  rus: 2025-03-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/208327/kaz/03.03.2025
  rus: https://zan.gov.kz/client/#!/doc/208327/rus/03.03.2025
