act_code: '151828'
requisite: Решение Казыгуртского районного маслихата Туркестанской области от 31 декабря 2020 года № 67/410-VI. Зарегистрировано Департаментом юстиции Туркестанской области 12 января 2021 года № 6021
title:
  rus: О бюджете сельских округов на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған ауылдық округтердің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-31
approved_by:
- '166004000002'
version_date:
  kaz: 2021-04-15
  rus: 2021-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/151828/kaz/15.04.2021
  rus: https://zan.gov.kz/client/#!/doc/151828/rus/15.04.2021
caused_by:
  code: '155397'
  requisite: Решение Казыгуртского районного маслихата Туркестанской области от 15 апреля 2021 года № 7/32-VII. Зарегистрировано Департаментом юстиции Туркестанской области 27 апреля 2021 года № 6179
  title:
    rus: О внесении изменений в решение Казыгуртского районного маслихата от 31 декабря 2020 года № 67/410-VІ «О бюджете сельских округов на 2021-2023 годы»
    kaz: Қазығұрт аудандық мәслихатының 2020 жылғы 31 желтоқсандағы № 67/410-VІ «2021-2023 жылдарға арналған ауылдық округтердің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/155397/rus
