act_code: '177026'
requisite: Решение Жетысайского районного маслихата Туркестанской области от 27 декабря 2022 года № 28-176-VIІ
title:
  rus: О районном бюджете на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '166017000002'
version_date:
  kaz: 2022-12-27
  rus: 2022-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/177026/kaz/27.12.2022
  rus: https://zan.gov.kz/client/#!/doc/177026/rus/27.12.2022
