act_code: '213942'
requisite: Решение акима сельского округа Шаульдер Отрарского района Туркестанской области от 5 сентября 2025 года № 103
title:
  rus: О присвоении наименований улицам
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-05
approved_by:
- '166007014002'
version_date:
  kaz: 2025-12-15
  rus: 2025-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/213942/kaz/15.12.2025
  rus: https://zan.gov.kz/client/#!/doc/213942/rus/15.12.2025
caused_by:
  code: '219157'
  requisite: Решение акима сельского округа Шаульдер Отрарского района Туркестанской области от 15 декабря 2025 года № 152
  title:
    rus: О внесении изменений в решение акима Шаульдерского сельского округа № 103 от 05.09.2025 года «О наименовании улиц»
    kaz: Көшелерге атау беру туралы Шәуілдір ауыл округі әкімінің 05.09.2025 жылғы № 103 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/219157/rus
