act_code: '193189'
requisite: Решение Туркестанского городского маслихата Туркестанской области от 9 февраля 2024 года № 13/62-VIII. Зарегистрировано в Департаменте юстиции Туркестанской области 12 февраля 2024 года № 6455-13
title:
  rus: Об оказании в 2024 году дополнительной социальной помощи ветеранам войны в Афганистане к 35-летию вывода ограниченного контингента Советских войск из Демократической Республики Афганистан
  kaz: 2024 жылы Ауғанстан Демократиялық Республикасынан Кеңес әскерлері шектеулі контингентінің шығарылғанына 35-жылдығына орай Ауғанстан соғысының ардагерлеріне қосымша әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-09
approved_by:
- '166015000002'
version_date:
  kaz: 2024-02-09
  rus: 2024-02-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/193189/kaz/09.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193189/rus/09.02.2024
