act_code: '111848'
requisite: Решение Тюлькубасского районного маслихата Южно-Казахстанской области от 14 апреля 2017 года № 13/2-06. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 2 мая 2017 года № 4083. Утратило силу решением Тюлькубасского районного маслихата Туркестанской области от 28 декабря 2020 года № 65/4-06 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи по Тюлькубасскому району
  kaz: Түлкібас ауданы бойынша тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-04-14
approved_by:
- '166012000002'
version_date:
  kaz: 2017-04-14
  rus: 2017-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/111848/kaz/14.04.2017
  rus: https://zan.gov.kz/client/#!/doc/111848/rus/14.04.2017
