act_code: '159250'
requisite: Решение Жетысайского районного маслихата Туркестанской области от 1 октября 2021 года № 11-77-VII. Утратило силу решением Жетысайского районного маслихата Туркестанской области от 10 октября 2023 года № 7-50-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей города районного значения, поселка, села, улицы, многоквартирного жилого дома для участия в сходе местного сообщества в Жетысайском районе
  kaz: Жетісай ауданында бөлек жергілікті қоғамдастық жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін аудандық маңызы бар қала, кент, ауыл, көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің санын айқындау тәртібін бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2021-10-01
approved_by:
- '166017000002'
version_date:
  kaz: 2021-10-01
  rus: 2021-10-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/159250/kaz/01.10.2021
  rus: https://zan.gov.kz/client/#!/doc/159250/rus/01.10.2021
