act_code: '53729'
requisite: Оңтүстік Қазақстан облысы Кентау қаласының әкімдігі Хантағы ауылы әкімінің 2010 жылғы 19 шілдедегі N 6 шешімі. Оңтүстік Қазақстан облысы Кентау қаласының Әділет басқармасында 2010 жылғы 29 шілдеде N 14-3-96 тіркелді
title:
  rus: Хантағы ауылындағы Совет және Серафимович көшелерінің атауын өзгерту туралы
  kaz: Хантағы ауылындағы Совет және Серафимович көшелерінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-19
approved_by:
- '166014004001'
version_date:
  kaz: 2010-07-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/53729/kaz/19.07.2010
