act_code: '92261'
requisite: Решение Ордабасинского районного маслихата Южно-Казахстанской области от 30 июня 2015 года № 43/9. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 21 июля 2015 года № 3254. Утратило силу решением Ордабасинского районного маслихата Туркестанской области от 3 октября 2023 года № 7/2 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении правил проведения раздельных сходов местного сообщества в Ордабасинского района
  kaz: Ордабасы ауданында бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2015-06-30
approved_by:
- '166006000002'
version_date:
  kaz: 2023-10-03
  rus: 2023-10-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/92261/kaz/03.10.2023
  rus: https://zan.gov.kz/client/#!/doc/92261/rus/03.10.2023
caused_by:
  code: '186918'
  requisite: Решение Ордабасинского районного маслихата Туркестанской области от 3 октября 2023 года № 7/2. Зарегистрировано в Департаменте юстиции Туркестанской области 5 октября 2023 года № 6370-13
  title:
    rus: О признании утратившим силу решения Ордабасинского районного маслихата от 30 июня 2015 года № 43/9 «Об утверждении порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей села, улицы, многоквартирного жилого дома для участия в сходе местного сообщества в Ордабасинском районе»
    kaz: Ордабасы аудандық мәслихатының 2015 жылғы 30 маусымдағы № 43/9 «Ордабасы ауданында жергілікті қоғамдастық бөлек жиынына қатысу үшін ауыл, көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің санын айқындау тәртібін бекіту туралы» шешімінің күші жойылды деп тану туралы
  link: https://zan.gov.kz/client/#!/doc/186918/rus
