act_code: '152629'
requisite: Решение Келесского районного маслихата Туркестанской области от 23 декабря 2020 года № 34-260-VI. Зарегистрировано Департаментом юстиции Туркестанской области 29 января 2021 года № 6048. Утратило силу решением Келесского районного маслихата Туркестанской области от 22 сентября 2023 года № 5-60-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-12-23
approved_by:
- '166018000002'
version_date:
  kaz: 2021-04-27
  rus: 2021-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/152629/kaz/27.04.2021
  rus: https://zan.gov.kz/client/#!/doc/152629/rus/27.04.2021
caused_by:
  code: '156004'
  requisite: Решение Келесского районного маслихата Туркестанской области от 27 апреля 2021 года № 4-38-VII. Зарегистрировано Департаментом юстиции Туркестанской области 17 мая 2021 года № 6221. Утратило силу решением Келесского районного маслихата Туркестанской области от 22 сентября 2023 года № 5-60-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнения в решение Келесского районного маслихата от 23 декабря 2020 года № 34-260-VІ «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Келес аудандық мәслихатының 2020 жылғы 23 желтоқсандағы № 34-260-VI «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидасын бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/156004/rus
