act_code: '162197'
requisite: Решение Казыгуртского районного маслихата Туркестанской области от 24 декабря 2021 года № 20/83-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 декабря 2021 года № 26027
title:
  rus: О районном бюджете на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '166004000002'
version_date:
  kaz: 2022-05-19
  rus: 2022-05-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/162197/kaz/19.05.2022
  rus: https://zan.gov.kz/client/#!/doc/162197/rus/19.05.2022
caused_by:
  code: '167945'
  requisite: Решение Казыгуртского районного маслихата Туркестанской области от 19 мая 2022 года № 26/118-VII
  title:
    rus: О внесении изменений в решение Казыгуртского районного маслихата от 24 декабря 2021 года № 20/83-VII «О районном бюджете на 2022-2024 годы»
    kaz: Қазығұрт аудандық мәслихатының 2021 жылғы 24 желтоқсандағы № 20/83-VII «2022-2024 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/167945/rus
