act_code: '206905'
requisite: Решение акима сельского округа Абай Жетысайского района Туркестанской области от 30 января 2025 года № 4
title:
  rus: О присвоении наименовании улицам
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-01-30
approved_by:
- '166017008002'
version_date:
  kaz: 2025-01-30
  rus: 2025-01-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/206905/kaz/30.01.2025
  rus: https://zan.gov.kz/client/#!/doc/206905/rus/30.01.2025
