act_code: '138307'
requisite: Решение Толебийского районного маслихата Туркестанской области от 26 декабря 2019 года № 48/266-VI. Зарегистрировано Департаментом юстиции Туркестанской области 10 января 2020 года № 5361
title:
  rus: О районном бюджете на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-26
approved_by:
- '166011000002'
version_date:
  kaz: 2020-05-06
  rus: 2020-05-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/138307/kaz/06.05.2020
  rus: https://zan.gov.kz/client/#!/doc/138307/rus/06.05.2020
caused_by:
  code: '142918'
  requisite: Решение Толебийского районного маслихата Туркестанской области от 6 мая 2020 года № 52/289-VI. Зарегистрировано Департаментом юстиции Туркестанской области 15 мая 2020 года № 5617
  title:
    rus: О внесении изменений в решение Толебийского районного маслихата от 26 декабря 2019 года № 48/266-VI «О районном бюджете на 2020-2022 годы»
    kaz: Төлеби аудандық мәслихатының 2019 жылғы 26 желтоқсандағы № 48/266-VI «2020-2022 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/142918/rus
