act_code: '127718'
requisite: Решение Шардаринского районного маслихата Туркестанской области от 21 декабря 2018 года № 35-227-VI. Зарегистрировано Департаментом юстиции Туркестанской области 28 декабря 2018 года № 4863
title:
  rus: О районном бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-21
approved_by:
- '166013000002'
version_date:
  kaz: 2019-04-19
  rus: 2019-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/127718/kaz/19.04.2019
  rus: https://zan.gov.kz/client/#!/doc/127718/rus/19.04.2019
caused_by:
  code: '130935'
  requisite: Решение Шардаринского районного маслихата Туркестанской области от 19 апреля 2019 года № 41-267-VI. Зарегистрировано Департаментом юстиции Туркестанской области 23 апреля 2019 года № 4983
  title:
    rus: О внесении изменений в решение Шардаринского районного маслихата от 21 декабря 2018 года № 35-227-VІ «О районном бюджете на 2019-2021 годы»
    kaz: Шардара аудандық мәслихатының 2018 жылғы 21 желтоқсандағы № 35-227-VІ «2019-2021 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130935/rus
