act_code: '146916'
requisite: Решение Шардаринского районного маслихата Туркестанской области от 18 сентября 2020 года № 65-392-VI. Зарегистрировано Департаментом юстиции Туркестанской области 30 сентября 2020 года № 5820. Утратило силу решением Шардаринского районного маслихата Туркестанской области от 12 декабря 2023 года № 13-62-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи по Шардаринскому району
  kaz: Шардара ауданы бойынша тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-18
approved_by:
- '166013000002'
version_date:
  kaz: 2020-09-18
  rus: 2020-09-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/146916/kaz/18.09.2020
  rus: https://zan.gov.kz/client/#!/doc/146916/rus/18.09.2020
