act_code: '51015'
requisite: Оңтүстік Қазақстан облысы Созақ ауданы әкімдігі Шолаққорған ауылы әкімінің 2010 жылғы 15 ақпандағы N 23 шешімі. Оңтүстік Қазақстан облысы Созақ ауданының Әділет басқармасында 2010 жылғы 3 наурызда N 14-12-89 тіркелді
title:
  rus: Есіркеп Өмірбековке көше атын беру туралы
  kaz: Есіркеп Өмірбековке көше атын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-15
approved_by:
- '166010001001'
version_date:
  kaz: 2010-02-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/51015/kaz/15.02.2010
