act_code: '6626'
requisite: Решение акима Южно-Казахстанской области от 21 февраля 2000 года N 55. Зарегистрировано Управлением юстиции Южно-Казахстанской области 14 июля 2000 года № 174. Утратило силу решением акима Южно-Казахстанской области от 28 августа 2001 года № 199
title:
  rus: Об утверждении правил финансирования государственного заказа за счет областного бюджета
  kaz: Мемлекеттік тапсырысты облыстық бюджеттің есебінен қаржыландыру Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2000-02-21
approved_by:
- '166000000003'
version_date:
  kaz: 2000-02-21
  rus: 2000-02-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/6626/kaz/21.02.2000
  rus: https://zan.gov.kz/client/#!/doc/6626/rus/21.02.2000
