act_code: '94478'
requisite: Решение Туркестанского городского маслихата Южно-Казахстанской области от 25 сентября 2015 года № 45/256-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 16 октября 2015 года № 3363. Утратило силу решением Туркестанского городского маслихата Южно-Казахстанской области от 3 февраля 2016 года № 53/299-V
title:
  rus: О повышении ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения на территории города Туркестан
  kaz: Түркістан қаласының аумағында пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының мөлшерлемесін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-09-25
approved_by:
- '166015000002'
version_date:
  kaz: 2015-09-25
  rus: 2015-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/94478/kaz/25.09.2015
  rus: https://zan.gov.kz/client/#!/doc/94478/rus/25.09.2015
