act_code: '133162'
requisite: Решение Туркестанского областного маслихата от 13 июня 2019 года № 38/409-VI. Зарегистрировано Департаментом юстиции Туркестанской области 1 июля 2019 года № 5118
title:
  rus: Об утверждении целевых показателей качества окружающей среды Туркестанской области на 2019-2023 годы
  kaz: Түркістан облысының 2019-2023 жылдарға арналған қоршаған орта сапасының нысаналы көрсеткіштерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-06-13
approved_by:
- '166000000002'
version_date:
  kaz: 2019-06-13
  rus: 2019-06-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/133162/kaz/13.06.2019
  rus: https://zan.gov.kz/client/#!/doc/133162/rus/13.06.2019
