act_code: '178051'
requisite: Решение Толебийского районного маслихата Туркестанской области от 29 декабря 2022 года № 24/137-VII
title:
  rus: О бюджетах города, сельских округов на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған қала, ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-29
approved_by:
- '166011000002'
version_date:
  kaz: 2022-12-29
  rus: 2022-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/178051/kaz/29.12.2022
  rus: https://zan.gov.kz/client/#!/doc/178051/rus/29.12.2022
