act_code: '72555'
requisite: Решение Мактааральского районного маслихата Южно-Казахстанской области от 29 марта 2013 года № 15-80-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 4 мая 2013 года № 2280. Утратило силу решением Мактааральского районного маслихата Туркестанской области от 7 октября 2022 года № 25-170-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки в населенных пунктах Мактааральского района
  kaz: Мақтаарал ауданының елді мекендеріндегі бағалау аймақтарының шекараларын және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-03-29
approved_by:
- '166005000002'
version_date:
  kaz: 2015-10-01
  rus: 2015-10-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/72555/kaz/01.10.2015
  rus: https://zan.gov.kz/client/#!/doc/72555/rus/01.10.2015
caused_by:
  code: '94931'
  requisite: Решение Мактааральского районного маслихата Южно-Казахстанской области от 1 октября 2015 года № 47-302-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 30 октября 2015 года № 3394. Утратило силу решением Мактааральского районного маслихата Туркестанской области от 7 октября 2022 года № 25-170-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Мактааральского районного маслихата от 29 марта 2013 года №15-80-V «Об утверждении границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки в населенных пунктах Мактааральского района»
    kaz: «Мақтаарал ауданының елді мекендеріндегі бағалау аймақтарының шекараларын және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы» Мақтаарал аудандық мәслихатының  2013 жылғы 29 наурыздағы №15-80-V шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/94931/rus
