act_code: '21153'
requisite: Решение акима Южно-Казахстанской области от 9 августа 2004 года № 37. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 31 августа 2004 года № 1478
title:
  rus: О проведении приписки граждан к призывным участкам
  kaz: Азаматтарды әскерге шақыру учаскелерiне тiркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-08-08
approved_by:
- '166000000003'
version_date:
  kaz: 2004-08-08
  rus: 2004-08-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/21153/kaz/08.08.2004
  rus: https://zan.gov.kz/client/#!/doc/21153/rus/08.08.2004
