act_code: '140013'
requisite: Решение Отрарского районного маслихата Туркестанской области от 13 февраля 2020 года № 52/247-VI. Зарегистрировано Департаментом юстиции Туркестанской области 24 февраля 2020 года № 5439. Утратило силу решением Отрарского районного маслихата Туркестанской области от 24 июня 2020 года № 56/267-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-02-13
approved_by:
- '166007000002'
version_date:
  kaz: 2020-02-13
  rus: 2020-02-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/140013/kaz/13.02.2020
  rus: https://zan.gov.kz/client/#!/doc/140013/rus/13.02.2020
