act_code: '144995'
requisite: Решение Отрарского районного маслихата Туркестанской области от 24 июня 2020 года № 56/266-VI. Зарегистрировано Департаментом юстиции Туркестанской области 16 июля 2020 года № 5718
title:
  rus: Об определении специальных мест, а также порядок использования специальных мест для организации и проведения мирных собраний
  kaz: Бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, сондай-ақ арнайы орындарды пайдалану тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-24
approved_by:
- '166007000002'
version_date:
  kaz: 2020-09-07
  rus: 2020-09-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/144995/kaz/07.09.2020
  rus: https://zan.gov.kz/client/#!/doc/144995/rus/07.09.2020
caused_by:
  code: '146206'
  requisite: Решение Отрарского районного маслихата Туркестанской области от 7 сентября 2020 года № 58/276-VI. Зарегистрировано Департаментом юстиции Туркестанской области 8 сентября 2020 года № 5786
  title:
    rus: О внесении изменений в решение маслихата Отрарского района от 24 июня 2020 года № 56/266-VI «О порядке организации и проведения мирных собраний в Отрарском районе»
    kaz: Отырар ауданының мәслихатының 2020 жылғы 24 маусымдағы № 56/266-VI «Отырар ауданында бейбіт жиналыстарды ұйымдастыру және өткізу тәртібі туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146206/rus
