act_code: '144995'
requisite: Решение Отрарского районного маслихата Туркестанской области от 24 июня 2020 года № 56/266-VI. Зарегистрировано Департаментом юстиции Туркестанской области 16 июля 2020 года № 5718
title:
  rus: Об определении специальных мест, а также порядок использования специальных мест для организации и проведения мирных собраний
  kaz: Бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, сондай-ақ арнайы орындарды пайдалану тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-24
approved_by:
- '166007000002'
version_date:
  kaz: 2024-07-12
  rus: 2024-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/144995/kaz/12.07.2024
  rus: https://zan.gov.kz/client/#!/doc/144995/rus/12.07.2024
caused_by:
  code: '198775'
  requisite: Решение Отрарского районного маслихата Туркестанской области от 12 июля 2024 года № 17/94-VIII. Зарегистрировано в Департаменте юстиции Туркестанской области 16 июля 2024 года № 6554-13
  title:
    rus: О внесении изменений в решение Отырарского районного маслихата № 56/266-VI от 24 июня 2020 года «О порядке организации и проведения мирных собраний в Отрарском районе»
    kaz: Отырар аудандық мәслихатының 2020 жылғы 24 маусымдағы № 56/266-VI «Отырар ауданында бейбіт жиналыстарды ұйымдастыру және өткізу тәртібі туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198775/rus
