act_code: '43297'
requisite: Оңтүстік Қазақстан облысы Мақтаарал аудандық мәслихатының 2008 жылғы 25 желтоқсандағы N 14-100-IV шешімі. Оңтүстік Қазақстан облысы Мақтаарал ауданының Әділет басқармасында 2009 жылғы 8 қаңтарда N 14-7-70 тіркелді
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-25
approved_by:
- '166005000002'
version_date:
  kaz: 2010-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/43297/kaz/12.02.2010
