act_code: '43297'
requisite: Оңтүстік Қазақстан облысы Мақтаарал аудандық мәслихатының 2008 жылғы 25 желтоқсандағы N 14-100-IV шешімі. Оңтүстік Қазақстан облысы Мақтаарал ауданының Әділет басқармасында 2009 жылғы 8 қаңтарда N 14-7-70 тіркелді
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-25
approved_by:
- '166005000002'
version_date:
  kaz: 2009-10-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/43297/kaz/30.10.2009
caused_by:
  code: '48406'
  requisite: Оңтүстік Қазақстан облысы Мақтаарал аудандық мәслихатының 2009 жылғы 30 қазандағы N 25-184-IV шешімі. Оңтүстік Қазақстан облысы Мақтаарал ауданы Әділет басқармасында 2009 жылғы 4 қарашада N 14-7-106 тіркелді
  title:
    rus: Мақтаарал аудандық мәслихатының 2008 жылғы 25 желтоқсандағы "2009 жылға арналған аудандық бюджет туралы" N 14-100-IV шешіміне өзгерістер енгізу туралы
    kaz: Мақтаарал аудандық мәслихатының 2008 жылғы 25 желтоқсандағы "2009 жылға арналған аудандық бюджет туралы" N 14-100-IV шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/48406/rus
