act_code: '151323'
requisite: Решение Сарыагашского районного маслихата Туркестанской области от 22 декабря 2020 года № 59-520-VI. Зарегистрировано Департаментом юстиции Туркестанской области 31 декабря 2020 года № 6003
title:
  rus: «О районном бюджете на 2021-2023 годы»
  kaz: 2021-2023 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-22
approved_by:
- '166009000002'
version_date:
  kaz: 2020-12-22
  rus: 2020-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/151323/kaz/22.12.2020
  rus: https://zan.gov.kz/client/#!/doc/151323/rus/22.12.2020
