act_code: '37854'
requisite: Оңтүстік Қазақстан облысы Бәйдібек аудандық мәслихатының 2007 жылғы 25 желтоқсандағы N 4/20 шешімі. Оңтүстік Қазақстан облысы Бәйдібек ауданының Әділет басқармасында 2008 жылғы 1 ақпанда N 14-5-55 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Бәйдібек аудандық мәслихатының 2009 жылғы 30 маусымдағы N 20/118 Шешімімен
title:
  rus: Бәйдібек ауданы бойынша аз қамтамасыз етілген азаматтарға тұрғын үй көмегін көрсетудің мөлшері мен тәртібі туралы Қағидасы
  kaz: Бәйдібек ауданы бойынша аз қамтамасыз етілген азаматтарға тұрғын үй көмегін көрсетудің мөлшері мен тәртібі туралы Қағидасы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-25
approved_by:
- '166003000002'
version_date:
  kaz: 2007-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/37854/kaz/25.12.2007
