act_code: '195712'
requisite: Решение акима сельского округа Жанабазар Казыгуртского района Туркестанской области от 16 апреля 2024 года № 13. Утратило силу решением акима сельского округа Жанабазар Казыгуртского района Туркестанской области от 21 июня 2024 года № 25 (вводится в действие после дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мер на территории населенного пункта Тилектес и Карабастау сельского округа Жанабазар
  kaz: Жаңабазар ауыл округі, Тілектес және Қарабастау елді мекендерінің аумағына шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-16
approved_by:
- '166004002002'
version_date:
  kaz: 2024-04-16
  rus: 2024-04-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/195712/kaz/16.04.2024
  rus: https://zan.gov.kz/client/#!/doc/195712/rus/16.04.2024
