act_code: '204118'
requisite: Решение Казыгуртского районного маслихата Туркестанской области от 12 декабря 2024 года № 21/130-VIII. Зарегистрировано в Департаменте юстиции Туркестанской области 13 декабря 2024 года № 6630-13
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов по Казыгуртскому району
  kaz: Қазығұрт ауданы бойынша тұрғын үй сертификаттарының мөлшерін және алушылар санаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-12
approved_by:
- '166004000002'
version_date:
  kaz: 2024-12-12
  rus: 2024-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/204118/kaz/12.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204118/rus/12.12.2024
