act_code: '88832'
requisite: Решение Созакского районного маслихата Южно-Казахстанской области от 19 марта 2015 года № 243. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 15 апреля 2015 года № 3129. Утратило силу решением Созакского районного маслихата Южно-Казахстанской области от 31 марта 2017 года № 82
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов по селу Шолаккорган Созакского района
  kaz: Созақ ауданы Шолаққорған ауылы бойынша коммуналдық қалдықтардың пайда болу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-03-19
approved_by:
- '166010000002'
version_date:
  kaz: 2015-03-19
  rus: 2015-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/88832/kaz/19.03.2015
  rus: https://zan.gov.kz/client/#!/doc/88832/rus/19.03.2015
