act_code: '211730'
requisite: Решение Тюлькубасского районного маслихата Туркестанской области от 27 июня 2025 года № 35/11-08
title:
  rus: О поощрительной надбавке к должностным окладам работников организаций, финансируемых из местного бюджета
  kaz: Жергілікті бюджеттен қаржыландырылатын «Түлкібас аудандық газ инспекциясы» КММ қызметкерлерінің лауазымдық айлықақыларына ынталандыру үстемақы белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-06-27
approved_by:
- '166012000002'
version_date:
  kaz: 2025-06-27
  rus: 2025-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/211730/kaz/27.06.2025
  rus: https://zan.gov.kz/client/#!/doc/211730/rus/27.06.2025
