act_code: '113662'
requisite: Решение Толебийского районного маслихата Южно-Казахстанской области от 20 июня 2017 года № 16/87-VI. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 11 июля 2017 года № 4140
title:
  rus: Об утверждении положения о награждении Почетной грамотой Толебийского района
  kaz: Төлеби ауданының Құрмет грамотасымен наградтау туралы ережені бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2017-06-20
approved_by:
- '166011000002'
version_date:
  kaz: 2024-12-25
  rus: 2024-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/113662/kaz/25.12.2024
  rus: https://zan.gov.kz/client/#!/doc/113662/rus/25.12.2024
caused_by:
  code: '204934'
  requisite: Решение Толебийского районного маслихата Туркестанской области от 25 декабря 2024 года № 21/115-VIII. Зарегистрировано в Департаменте юстиции Туркестанской области 27 декабря 2024 года № 6642-13
  title:
    rus: О внесении изменений в решение Толебийского районного маслихата от 20 июня 2017 года № 16/87-VI «Об утверждении положения о награждении Почетной грамотой Толебийского района»
    kaz: Төлеби аудандық мәслихатының 2017 жылғы 20 маусымдағы № 16/87-VI «Төлеби ауданының Құрмет грамотасымен наградтау туралы ережені бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/204934/rus
