act_code: '216250'
requisite: Решение акима сельского округа Отырар Отрарского района Туркестанской области от 20 октября 2025 года № 87
title:
  rus: Об установлении публичного сервитута товариществу с ограниченной ответственностью «Туркестан текстиль» для размещения газопроводных сетей
  kaz: «Түркістан тоқыма» жауапкершілігі шектеулі серіктестігіне газ құбыры желілерін орналастыру үшін қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-10-20
approved_by:
- '166007012002'
version_date:
  kaz: 2025-10-20
  rus: 2025-10-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/216250/kaz/20.10.2025
  rus: https://zan.gov.kz/client/#!/doc/216250/rus/20.10.2025
