act_code: '23737'
requisite: Решение Маслихата Южно-Казахстанской области от 29 марта 2005 года N 14/140-III. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 25 апреля 2005 года за N 1909. Утратило силу решением Южно-Казахстанского областного маслихата от 7 декабря 2012 года № 9/82-V
title:
  rus: Об утверждении ставок платы за пользование водными ресурсами поверхностных источников в Южно-Казахстанской области
  kaz: Оңтүстік Қазақстан облысындағы жер үсті көздеріндегі су ресурстарын пайдаланғаны үшін төлемақы ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-03-29
approved_by:
- '166000000002'
version_date:
  kaz: 2005-03-29
  rus: 2005-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/23737/kaz/29.03.2005
  rus: https://zan.gov.kz/client/#!/doc/23737/rus/29.03.2005
