act_code: '129955'
requisite: Решение акима сельского округа Акбиик Тюлькубасского района Туркестанской области от 27 марта 2019 года № 10. Зарегистрировано Департаментом юстиции Туркестанской области 28 марта 2019 года № 4950
title:
  rus: О присвоении наименований безымянным улицам населенных пунктов в сельском округе Акбиик
  kaz: Ақбиік ауылдық округіндегі елді мекендердегі атаусыз көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-03-27
approved_by:
- '166012009002'
version_date:
  kaz: 2019-11-07
  rus: 2019-11-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/129955/kaz/07.11.2019
  rus: https://zan.gov.kz/client/#!/doc/129955/rus/07.11.2019
caused_by:
  code: '136199'
  requisite: Решение акима Акбиикского сельского округа акимата Тюлькубасского района Туркестанской области от 7 ноября 2019 года № 46. Зарегистрировано Департаментом юстиции Туркестанской области 13 ноября 2019 года № 5241
  title:
    rus: О внесении изменений в решение акима сельского округа Акбиик от 27 марта 2019 года № 10 «О присвоении наименований безымянной улицам населенных пунктов в сельском округе Акбиик»
    kaz: Ақбиік ауылдық округі әкімінің 2019 жылғы 27 наурыздағы № 10 «Ақбиік ауылдық округіндегі елді мекендердегі атаусыз көшелерге атау беру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136199/rus
