act_code: '60718'
requisite: Решение маслихата Шардаринского района Южно-Казахстанской области от 4 октября 2011 года N 47-355-IV. Зарегистрировано Управлением юстиции Шардаринского района Южно-Казахстанской области 7 октября 2011 года N 14-15-120
title:
  rus: О предоставлении подъемного пособия и социальной поддержки для приобретения жилья специалистам здравоохранения, образования, социального обеспечения, культуры и спорта, прибывшим для работы и проживания в сельские населенные пункты Шардаринского района в 2011 году
  kaz: Шардара ауданының ауылдық елді мекендеріне 2011 жылы жұмыс iстеу және тұру үшiн келген денсаулық сақтау, бiлiм беру, әлеуметтiк қамсыздандыру, мәдениет және спорт мамандарына көтерме жәрдемақы және тұрғын үй сатып алу үшiн әлеуметтiк қолдауды ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-10-04
approved_by:
- '166013000002'
version_date:
  kaz: 2012-01-01
  rus: 2012-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/60718/kaz/01.01.2012
  rus: https://zan.gov.kz/client/#!/doc/60718/rus/01.01.2012
