act_code: '66484'
requisite: Решение Шардаринского районного маслихата Южно-Казахстанской области от 12 июня 2012 года № 5-35-V. Зарегистрировано Управлением юстиции Шардаринского района Южно-Казахстанской области 4 июля 2012 года № 14-15-141. Утратило силу в связи с истечением срока применения - (письмо Шардаринского районного маслихата Южно-Казахстанской области от 30 января 2013 года № 10)
title:
  rus: О предоставлении в 2012 году подъемного пособия и социальной поддержки для приобретения или строительства жилья специалистам здравоохранения, образования, социального обеспечения, культуры, спорта и ветеринарии, прибывшим для работы и проживания в сельские населенные пункты Шардаринского района
  kaz: Шардара ауданының ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет спорт және ветеринария мамандарына 2012 жылы көтерме жәрдемақы және тұрғын үй алу немесе салу үшін әлеуметтік қолдауды ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-06-12
approved_by:
- '166013000002'
version_date:
  kaz: 2012-06-12
  rus: 2012-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/66484/kaz/12.06.2012
  rus: https://zan.gov.kz/client/#!/doc/66484/rus/12.06.2012
