act_code: '37443'
requisite: Оңтүстік Қазақстан облысы Шардара аудандық мәслихатының 2007 жылғы 24 желтоқсандағы N 4-27-IV Шешімі. Оңтүстік Қазақстан облысы Шардара ауданының Әділет басқармасында 2008 жылғы 22 қаңтарда N 14-15-52 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Шардара аудандық маслихатының 2009 жылғы 28 қаңтардағы N 15-110-IV Шешімімен
title:
  rus: Аз қамтамасыз етілген азаматтарға тұрғын үй көмегін беру Қағидасын бекіту туралы
  kaz: Аз қамтамасыз етілген азаматтарға тұрғын үй көмегін беру Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-24
approved_by:
- '166013000002'
version_date:
  kaz: 2007-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/37443/kaz/24.12.2007
