act_code: '43352'
requisite: Оңтүстік Қазақстан облысы Бәйдібек аудандық мәслихатының 2008 жылғы 23 желтоқсандағы N 14/75 Шешімі. Оңтүстік Қазақстан облысы Бәйдібек ауданының Әділет басқармасында 2009 жылғы 5 қаңтарда N 14-5-66 тіркелді
title:
  rus: 2009 жылға арналған аудан бюджеті туралы
  kaz: 2009 жылға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-23
approved_by:
- '166003000002'
version_date:
  kaz: 2009-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/43352/kaz/20.04.2009
caused_by:
  code: '45477'
  requisite: Оңтүстік Қазақстан облысы Бәйдібек аудандық мәслихатының 2009 жылғы 20 сәуірдегі N 18/103 шешімі. Оңтүстік Қазақстан облысы Бәйдібек ауданының Әділет басқармасында 2009 жылғы 27 сәуірде N 14-5-75 тіркелді
  title:
    rus: Бәйдібек аудандық мәслихатының 23 желтоқсан 2008 жылғы "2009 жылға арналған аудан бюджеті туралы" N 14/75 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Бәйдібек аудандық мәслихатының 23 желтоқсан 2008 жылғы "2009 жылға арналған аудан бюджеті туралы" N 14/75 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/45477/rus
