act_code: '100322'
requisite: Решение Туркестанского городского маслихата Южно-Казахстанской области от 1 марта 2016 года № 54/302-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 14 марта 2016 года № 3630. Утратило силу решением Туркестанского городского маслихата Южно-Казахстанской области от 19 марта 2018 года № 28/154-VI
title:
  rus: О дополнительном регламентировании порядка проведения собраний, митингов, шествий, пикетов и демонстраций
  kaz: Жиналыстар, митингілер, шерулер, пикеттер және демонстрациялар өткізу тәртібін қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-03-01
approved_by:
- '166015000002'
version_date:
  kaz: 2016-03-01
  rus: 2016-03-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/100322/kaz/01.03.2016
  rus: https://zan.gov.kz/client/#!/doc/100322/rus/01.03.2016
