act_code: '59419'
requisite: Оңтүстік Қазақстан облысы Мақтаарал ауданы әкімдігі Атакент кенті әкімінің 2011 жылғы 2 маусымдағы № 58 шешімі. Оңтүстік Қазақстан облысы Мақтаарал ауданының Әділет басқармасында 2011 жылғы 23 маусымда № 14-7-145 тіркелді
title:
  rus: Көшенің атын өзгерту туралы
  kaz: Көшенің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-06-02
approved_by:
- '166005021001'
version_date:
  kaz: 2011-06-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/59419/kaz/02.06.2011
