act_code: '162264'
requisite: Решение Толебийского районного маслихата Туркестанской области от 23 декабря 2021 года № 13/74-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 декабря 2021 года № 26089
title:
  rus: О районном бюджете на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-23
approved_by:
- '166011000002'
version_date:
  kaz: 2022-12-06
  rus: 2022-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/162264/kaz/06.12.2022
  rus: https://zan.gov.kz/client/#!/doc/162264/rus/06.12.2022
caused_by:
  code: '177027'
  requisite: Решение Толебийского районного маслихата Туркестанской области от 6 декабря 2022 года № 22/123-VII
  title:
    rus: О внесении изменений в решение Толебийского районного маслихата от 23 декабря 2021 года № 13/74-VII «О районном бюджете на 2022-2024 годы»
    kaz: Төлеби аудандық мәслихатының 2021 жылғы 23 желтоқсандағы № 13/74-VII «2022-2024 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/177027/rus
