act_code: '144480'
requisite: Решение Туркестанского городского маслихата Туркестанской области от 26 июня 2020 года № 64/313-VI. Зарегистрировано Департаментом юстиции Туркестанской области 2 июля 2020 года № 5692
title:
  rus: О порядке организации и проведения мирных собраний в городе Туркестан
  kaz: Түркістан қаласында бейбіт жиналыстарды ұйымдастыру және өткізу тәртібі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-26
approved_by:
- '166015000002'
version_date:
  kaz: 2020-08-07
  rus: 2020-08-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/144480/kaz/07.08.2020
  rus: https://zan.gov.kz/client/#!/doc/144480/rus/07.08.2020
caused_by:
  code: '145477'
  requisite: Решение Туркестанского городского маслихата Туркестанской области от 7 августа 2020 года № 65/317-VI. Зарегистрировано Департаментом юстиции Туркестанской области 13 августа 2020 года № 5753
  title:
    rus: О внесении изменений и дополнения в решение Туркестанского городского маслихата от 26 июня 2020 года № 64/313-VI «О порядке организации и проведения мирных собраний в городе Туркестан»
    kaz: Түркістан қалалық мәслихатының 2020 жылғы 26 маусымдағы № 64/313-VI «Түркістан қаласында бейбіт жиналыстарды ұйымдастыру және өткізу тәртібі туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/145477/rus
