act_code: '69749'
requisite: Решение Мактааральского районного маслихата Южно-Казахстанской области от 21 декабря 2012 года № 12-55-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 9 января 2013 года № 2202
title:
  rus: О районном бюджете на 2013-2015 годы
  kaz: 2013-2015 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-21
approved_by:
- '166005000002'
version_date:
  kaz: 2013-11-21
  rus: 2013-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/69749/kaz/21.11.2013
  rus: https://zan.gov.kz/client/#!/doc/69749/rus/21.11.2013
caused_by:
  code: '75523'
  requisite: Решение Мактааральского районного маслихата Южно-Казахстанской области от 21 ноября 2013 года № 24-128-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 25 ноября 2013 года № 2415
  title:
    rus: О внесении изменений в решение Мактааральского районного маслихата от 21 декабря 2012 года № 12-55-V "О районном бюджете на 2013-2015 годы"
    kaz: Мақтаарал аудандық мәслихатының 2012 жылғы 21 желтоқсандағы № 12-55-V "2013-2015 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/75523/rus
