act_code: '50011'
requisite: Оңтүстік Қазақстан облысы Түлкібас ауданы әкімдігі Рысқұлов ауылдық округі әкімінің 2010 жылғы 11 қаңтардағы N 1 шешімі. Оңтүстік Қазақстан облысы Түлкібас ауданының Әділет басқармасында 2010 жылғы 15 қаңтарда N 14-14-97 тіркелді
title:
  rus: Көше атын беру туралы
  kaz: Көше атын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-01-11
approved_by:
- '166012011001'
version_date:
  kaz: 2010-01-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/50011/kaz/11.01.2010
