act_code: '71955'
requisite: Решение Созакского районного маслихата Южно-Казахстанской области от 27 марта 2013 года № 87. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 11 апреля 2013 года № 2261
title:
  rus: О предоставлении в 2013 году подъемного пособия и социальной поддержки для приобретения или строительства жилья специалистам здравоохранения, образования, социального обеспечения, культуры, спорта и ветеринарии, прибывшим для работы и проживания в сельские населенные пункты Созакского района
  kaz: Созақ ауданының ауылдық елді мекендеріне жұмыс істеу және тұру үшін  келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет,  спорт және ветеринария мамандарына 2013 жылы көтерме жәрдемақы және  тұрғын үй сатып алу немесе салу үшін әлеуметтік қолдауды ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-03-27
approved_by:
- '166010000002'
version_date:
  kaz: 2013-03-27
  rus: 2013-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/71955/kaz/27.03.2013
  rus: https://zan.gov.kz/client/#!/doc/71955/rus/27.03.2013
