act_code: '68513'
requisite: Решение Арысского городского маслихата Южно-Казахстанской области от 25 сентября 2012 года № 8/44-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 9 ноября 2012 года № 2127
title:
  rus: О схеме зонирования земель города Арыс
  kaz: Арыс қаласының жерді аймақтарға бөлу схемасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-09-25
approved_by:
- '166016000002'
version_date:
  kaz: 2012-09-25
  rus: 2012-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/68513/kaz/25.09.2012
  rus: https://zan.gov.kz/client/#!/doc/68513/rus/25.09.2012
