act_code: '63005'
requisite: Решение Кентауского городского маслихата Южно-Казахстанской области от 20 декабря 2011 года N 352. Зарегистрировано Управлением юстиции города Кентау Южно-Казахстанской области 30 декабря 2011 года N 14-3-122
title:
  rus: О городском бюджете на 2012-2014 годы
  kaz: 2012-2014 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-20
approved_by:
- '166014000002'
version_date:
  kaz: 2012-01-10
  rus: 2012-01-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/63005/kaz/10.01.2012
  rus: https://zan.gov.kz/client/#!/doc/63005/rus/10.01.2012
caused_by:
  code: '62905'
  requisite: Решение Кентауского городского маслихата Южно-Казахстанской области от 10 января 2012 года N 361. Зарегистрировано Управлением юстиции города Кентау Южно-Казахстанской области 25 января 2012 года N 14-3-123
  title:
    rus: О внесении изменений в решение Кентауского городского маслихата от 20 декабря 2011 года № 352 "О городском бюджете на 2012-2014 годы"
    kaz: Кентау қалалық мәслихатының 2011 жылғы 20 желтоқсандағы № 352 "2012-2014 жылдарға арналған қалалық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/62905/rus
