act_code: '128117'
requisite: Решение Келесского районного маслихата Туркестанской области от 24 декабря 2018 года № 8-51-VI. Зарегистрировано Департаментом юстиции Туркестанской области 27 декабря 2018 года № 4857
title:
  rus: О районном бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-24
approved_by:
- '166018000002'
version_date:
  kaz: 2018-12-24
  rus: 2018-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/128117/kaz/24.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128117/rus/24.12.2018
