act_code: '212031'
requisite: Решение Сарыагашского районного маслихата Туркестанской области от 27 июня 2025 года № 32-241-VIII
title:
  rus: Об утверждении плана по управлению пастбищами и их использованию Сарыагашского района на 2025-2029 годы
  kaz: Сарыағаш ауданының жайылымдарды басқару және оларды пайдалану жөніндегі 2025-2029 жылдарға арналған жоспарын бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2025-06-27
approved_by:
- '166009000002'
version_date:
  kaz: 2025-06-27
  rus: 2025-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/212031/kaz/27.06.2025
  rus: https://zan.gov.kz/client/#!/doc/212031/rus/27.06.2025
