act_code: '126672'
requisite: Решение Кентауского городского маслихата Туркестанской области от 28 ноября 2018 года № 219. Зарегистрировано Департаментом юстиции Туркестанской области 11 декабря 2018 года № 4832
title:
  rus: О социальной помощи работникам государственных организаций в сельской местности
  kaz: Ауылдық елді мекендердегі мемлекеттік ұйымдарының мамандарына әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-28
approved_by:
- '166014000002'
version_date:
  kaz: 2018-11-28
  rus: 2018-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/126672/kaz/28.11.2018
  rus: https://zan.gov.kz/client/#!/doc/126672/rus/28.11.2018
