act_code: '47132'
requisite: Оңтүстік Қазақстан облысы Түлкібас ауданы әкімдігі Шақпақ ауылдық округі әкімінің 2009 жылғы 24 шілдедегі N 20 шешімі. Оңтүстік Қазақстан облысы Түлкібас ауданының Әділет басқармасында 2009 жылғы 31 шілдеде N 14-14-82 тіркелді
title:
  rus: Шақпақ баба ауылындағы бұрынғы "Школьная" көшесін Сапаров Естібайдың атымен өзгерту туралы
  kaz: Шақпақ баба ауылындағы бұрынғы "Школьная" көшесін Сапаров Естібайдың атымен өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-07-24
approved_by:
- '166012010001'
version_date:
  kaz: 2009-07-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/47132/kaz/24.07.2009
