act_code: '73656'
requisite: Решение от 27.06.2013 № 17-100-V, Маслихат Мактааральского района. Утратило силу решением Мактааральского районного маслихата Южно-Казахстанской области от 24 июня 2015 года № 45-284-V
title:
  rus: О корректировке базовых ставок земельного налога по Мактааральскому району
  kaz: Мақтаарал ауданы бойынша жер салығының базалық ставкаларын түзету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-06-27
approved_by:
- '166005000002'
version_date:
  kaz: 2013-06-27
  rus: 2013-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/73656/kaz/27.06.2013
  rus: https://zan.gov.kz/client/#!/doc/73656/rus/27.06.2013
