act_code: '80461'
requisite: Решение Мактааральского районного маслихата Южно-Казахстанской области от 25 апреля 2014 года № 30-171-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 4 июня 2014 года № 2679. Утратило силу решением Мактааральского районного маслихата Южно-Казахстанской области от 20 июня 2016 года № 4-21-VI
title:
  rus: Об утверждении регламента Мактааральского районного маслихата
  kaz: Мақтаарал аудандық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-25
approved_by:
- '166005000002'
version_date:
  kaz: 2014-04-25
  rus: 2014-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/80461/kaz/25.04.2014
  rus: https://zan.gov.kz/client/#!/doc/80461/rus/25.04.2014
