act_code: '50576'
requisite: Оңтүстік Қазақстан облысы Түлкібас ауданы әкімдігі Машат ауылдық округі әкімінің 2010 жылғы 29 қаңтардағы N 1 шешімі. Оңтүстік Қазақстан облысы Түлкібас ауданының Әділет басқармасында 2010 жылғы 8 ақпанда N 14-14-100 тіркелді
title:
  rus: Көше атын беру туралы
  kaz: Көше атын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-01-29
approved_by:
- '166012001001'
version_date:
  kaz: 2010-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/50576/kaz/29.01.2010
