act_code: '38962'
requisite: Оңтүстік Қазақстан облысы Мақтаарал ауданы Асықата кенті әкімінің 2007 жылғы 4 сәуірдегі N 57 шешімі. Оңтүстік Қазақстан облысы Мақтаарал ауданының Әділет басқармасында 2007 жылғы 30 сәуірде N 14-7-41 тіркелді
title:
  rus: Асықата кентіндегі Төлеби көшесіне Зейнеп Таспанбетованың есімін беру туралы
  kaz: Асықата кентіндегі Төлеби көшесіне Зейнеп Таспанбетованың есімін беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-04-04
approved_by:
- '166005008001'
version_date:
  kaz: 2007-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/38962/kaz/04.04.2007
