act_code: '191966'
requisite: Решение акима сельского округа Караспан Ордабасинского района Туркестанской области от 8 января 2024 года № 3
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-01-08
approved_by:
- '166006004002'
version_date:
  kaz: 2024-01-08
  rus: 2024-01-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/191966/kaz/08.01.2024
  rus: https://zan.gov.kz/client/#!/doc/191966/rus/08.01.2024
