act_code: '97300'
requisite: Решение акима сельского округа Созак Созакского района Южно-Казахстанской области от 28 декабря 2015 года № 74. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 8 января 2016 года № 3517
title:
  rus: О присвоении наименования улице
  kaz: Көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-28
approved_by:
- '166010006001'
version_date:
  kaz: 2015-12-28
  rus: 2015-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/97300/kaz/28.12.2015
  rus: https://zan.gov.kz/client/#!/doc/97300/rus/28.12.2015
