act_code: '194976'
requisite: Решение акима сельского округа Жидели акимата города Арысь Туркестанской области от 27 марта 2024 года № 10
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитутты белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-27
approved_by:
- '166016006002'
version_date:
  kaz: 2024-03-27
  rus: 2024-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/194976/kaz/27.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194976/rus/27.03.2024
