act_code: '56237'
requisite: Оңтүстік Қазақстан облысы Бәйдібек аудандық мәслихатының 2010 жылғы 21 желтоқсандағы N 39/219 шешімі. Оңтүстік Қазақстан облысы Әділет департаментінде 2010 жылғы 28 желтоқсанда N 14-5-105 тіркелді
title:
  rus: 2011-2013 жылдарға арналған аудан бюджеті туралы
  kaz: 2011-2013 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-21
approved_by:
- '166003000002'
version_date:
  kaz: 2011-08-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/56237/kaz/12.08.2011
caused_by:
  code: '60092'
  requisite: Оңтүстік Қазақстан облысы Бәйдібек аудандық мәслихатының 2011 жылғы 12 тамыздағы N 46/269 шешімі. Оңтүстік Қазақстан облысы Бәйдібек ауданының Әділет басқармасында 2011 жылғы 18 тамызда N 14-5-114 тіркелді
  title:
    rus: Бәйдібек аудандық мәслихатының 21 желтоқсан 2010 жылғы № 39/219 "2011-2013 жылдарға арналған аудан бюджеті туралы" шешіміне өзгерістер енгізу туралы
    kaz: Бәйдібек аудандық мәслихатының 21 желтоқсан 2010 жылғы № 39/219 "2011-2013 жылдарға арналған аудан бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/60092/rus
