act_code: '145415'
requisite: Решение Байдибекского районного маслихата Туркестанской области от 23 июня 2020 года № 53/324. Зарегистрировано Департаментом юстиции Туркестанской области 7 августа 2020 года № 5745
title:
  rus: О порядке организации и проведения мирных собраний в районе Байдибек
  kaz: Бәйдібек ауданында бейбіт жиналыстарды ұйымдастыру және өткізу тәртібі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-23
approved_by:
- '166003000002'
version_date:
  kaz: 2020-06-23
  rus: 2020-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/145415/kaz/23.06.2020
  rus: https://zan.gov.kz/client/#!/doc/145415/rus/23.06.2020
