act_code: '29788'
requisite: Оңтүстік Қазақстан облысы Түлкібас ауданы әкімдігінің 2006 жылғы 4 қыркүйектегі № 46 шешімі. Оңтүстік Қазақстан облысы Түлкібас ауданының Әділет басқармасында 2006 жылғы 11 қыркүйекте № 14-14-25 болып тіркелді
title:
  rus: «Советский» көшесінің атын «Бекишев Кенес Кусаинович» атындағы көше деп өзгерту туралы
  kaz: «Советский» көшесінің атын «Бекишев Кенес Кусаинович» атындағы көше деп өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-09-04
approved_by:
- '166012000001'
version_date:
  kaz: 2006-09-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/29788/kaz/04.09.2006
