act_code: '79110'
requisite: Решение Созакского районного маслихата Южно-Казахстанской области от 27 марта 2014 года № 162. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 23 апреля 2014 года № 2623. Утратило силу решением Созакского районного маслихата Южно-Казахстанской области от 23 июня 2016 года № 24
title:
  rus: Об утверждении регламента Созакского районного маслихата
  kaz: Созақ аудандық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-03-27
approved_by:
- '166010000002'
version_date:
  kaz: 2014-03-27
  rus: 2014-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/79110/kaz/27.03.2014
  rus: https://zan.gov.kz/client/#!/doc/79110/rus/27.03.2014
