act_code: '45512'
requisite: Решение от 31.03.2009 № 136, Маслихат города Кентау
title:
  rus: Тіркелген салық ставкалары туралы
  kaz: Тіркелген салық ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-03-31
approved_by:
- '166014000002'
version_date:
  kaz: 2009-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/45512/kaz/31.03.2009
