act_code: '2120'
requisite: Решение акима Южно-Казахстанской области от 18 декабря 1998 года № 383. Зарегистрировано Управлением юстиции Южно-Казахстанской области 28 января 1999 года № 65. Утратило силу решением акима Южно-Казахстанской области от 28 ноября 2001 года № 225
title:
  rus: Об утверждении нормы отпуска тепловой энергии и перечня работ по содержанию и эксплуатации жилища при предоставлении льгот отдельным категориям граждан
  kaz: Азаматтардың жекелеген санаттарына жеңiлдiктер беру кезiнде жылу энергиясын босату мөлшерiн және тұрғын үй-жайларды ұстау және пайдалану жөнiндегi жұмыстардың тiзбесiн бекiту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-12-18
approved_by:
- '166000000003'
version_date:
  kaz: 1998-12-18
  rus: 1998-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/2120/kaz/18.12.1998
  rus: https://zan.gov.kz/client/#!/doc/2120/rus/18.12.1998
