act_code: '197678'
requisite: Решение акима сельского округа Кызылкия Казыгуртского района Туркестанской области от 13 июня 2024 года № 58
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-06-13
approved_by:
- '166004008002'
version_date:
  kaz: 2024-06-13
  rus: 2024-06-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/197678/kaz/13.06.2024
  rus: https://zan.gov.kz/client/#!/doc/197678/rus/13.06.2024
