act_code: '85588'
requisite: Решение Сарыагашского районного маслихата Южно-Казахстанской области от 22 декабря 2014 года № 38-321-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 31 декабря 2014 года № 2940
title:
  rus: О районном бюджете на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-22
approved_by:
- '166009000002'
version_date:
  kaz: 2015-01-28
  rus: 2015-01-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/85588/kaz/28.01.2015
  rus: https://zan.gov.kz/client/#!/doc/85588/rus/28.01.2015
caused_by:
  code: '86399'
  requisite: Решение Сарыагашского районного маслихата Южно-Казахстанской области от 28 января 2015 года № 39-324-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 29 января 2015 года № 2986. Утратило силу в связи с истечением срока применения - (письмо аппарата Сарыагашского районного маслихата Южно-Казахстанской области от 28 декабря 2015 года № 449)
  title:
    rus: О внесении изменений в решение Сарыагашского районного маслихата от 22 декабря 2014 года № 38-321-V "О районном бюджете на 2015-2017 годы"
    kaz: Сарыағаш аудандық мәслихатының 2014 жылғы 22 желтоқсандағы № 38-321-V "2015-2017 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/86399/rus
