act_code: '86428'
requisite: Решение Мактааральского районного маслихата Южно-Казахстанской области от 24 декабря 2014 года № 38-227-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 28 января 2015 года № 2982. Утратило силу решением Мактааральского районного маслихата Южно-Казахстанской области от 20 июня 2016 года № 4-21-VI
title:
  rus: Об утверждении положения государственного учреждения "Аппарат Мактааральского районного маслихата"
  kaz: '"Мақтаарал аудандық мәслихатының аппараты" мемлекеттік мекемесінің ережесін бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '166005000002'
version_date:
  kaz: 2014-12-24
  rus: 2014-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/86428/kaz/24.12.2014
  rus: https://zan.gov.kz/client/#!/doc/86428/rus/24.12.2014
