act_code: '92180'
requisite: Решение Ордабасинского районного маслихата Южно-Казахстанской области от 30 июня 2015 года № 43/12. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 23 июля 2015 года № 3274. Утратило силу решением Ордабасинского районного маслихата Южно-Казахстанской области от 20 января 2016 года № 51/3
title:
  rus: 'Об утверждении Методики ежегодной оценки деятельности административных государственных служащих аппарата Ордабасинского районного маслихата корпуса «Б» '
  kaz: '«Б» корпусындағы Ордабасы аудандық мәслихат аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін жыл сайынғы бағалаудың әдістемесін бекіту туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-06-30
approved_by:
- '166006000002'
version_date:
  kaz: 2015-10-27
  rus: 2015-10-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/92180/kaz/27.10.2015
  rus: https://zan.gov.kz/client/#!/doc/92180/rus/27.10.2015
caused_by:
  code: '95435'
  requisite: Решение Ордабасинского районного маслихата Южно-Казахстанской области от 27 октября 2015 года № 46/3. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 5 ноября 2015 года № 3417. Утратило силу решением Ордабасинского районного маслихата Южно-Казахстанской области от 20 января 2016 года № 51/3
  title:
    rus: О внесении изменения в решение Ордабасинского районного маслихата от 30 июня 2015 года № 43/12 «Об утверждении Методики ежегодной оценки деятельности административных государственных служащих аппарата Ордабасинского районного маслихата корпуса «Б»»
    kaz: ««Б» корпусындағы Ордабасы аудандық мәслихат аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін жыл сайынғы бағалаудың әдістемесін бекіту туралы» Ордабасы аудандық мәслихатының 2015 жылғы 30 маусымдағы № 43/12 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/95435/rus
