act_code: '124829'
requisite: Решение Кентауского городского маслихата Туркестанской области от 26 сентября 2018 года № 202. Зарегистрировано Департаментом юстиции Туркестанской области 27 сентября 2018 года № 4745
title:
  rus: О бюджете сельских округов города Кентау на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған Кентау қаласы ауыл округтерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-09-26
approved_by:
- '166014000002'
version_date:
  kaz: 2018-11-28
  rus: 2018-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/124829/kaz/28.11.2018
  rus: https://zan.gov.kz/client/#!/doc/124829/rus/28.11.2018
caused_by:
  code: '127029'
  requisite: Решение Кентауского городского маслихата Туркестанской области от 28 ноября 2018 года № 220. Зарегистрировано Департаментом юстиции Туркестанской области 11 декабря 2018 года № 4830
  title:
    rus: О внесении изменений в решение Кентауского городского маслихата от 26 сентября 2018 года № 202 «О бюджете сельских округов города Кентау на 2018-2020 годы»
    kaz: Кентау қалалық мәслихатының 2018 жылғы 26 қыркүйектегі № 202 «2018-2020 жылдарға арналған Кентау қаласы ауыл округтерінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/127029/rus
