act_code: '217594'
requisite: Решение Кентауского городского маслихата Туркестанской области от 27 ноября 2025 года № 223
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» аппарата Кентауского городского маслихата
  kaz: «Б» корпусы Кентау қалалық мәслихат аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-27
approved_by:
- '166014000002'
version_date:
  kaz: 2025-11-27
  rus: 2025-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/217594/kaz/27.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217594/rus/27.11.2025
