act_code: '92253'
requisite: Решение акима Южно-Казахстанской области от 16 июля 2015 года № 36. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 29 июля 2015 года № 3292. Утратило силу решением акима Южно-Казахстанской области от 2 июня 2016 года № 13
title:
  rus: Об определении объема субсидий на субсидирование стоимости услуг по подаче воды сельскохозяйственным товаропроизводителям по районам
  kaz: Аудандар бойынша ауыл шаруашылығы тауарын өндірушілерге су беру жөніндегі қызметтердің құнын субсидиялауға арналған субсидиялар көлемін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-07-16
approved_by:
- '166000000001'
version_date:
  kaz: 2015-07-16
  rus: 2015-07-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/92253/kaz/16.07.2015
  rus: https://zan.gov.kz/client/#!/doc/92253/rus/16.07.2015
