act_code: '175987'
requisite: Решение Тюлькубасского районного маслихата Туркестанской области от 23 декабря 2022 года № 27/1-07
title:
  rus: О районном бюджете на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-23
approved_by:
- '166012000002'
version_date:
  kaz: 2023-11-03
  rus: 2023-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/175987/kaz/03.11.2023
  rus: https://zan.gov.kz/client/#!/doc/175987/rus/03.11.2023
caused_by:
  code: '187925'
  requisite: Решение Тюлькубасского районного маслихата Туркестанской области от 3 ноября 2023 года № 8/1-08
  title:
    rus: О внесении изменений в решение Тюлькубасского районного маслихата от 23 декабря 2022 года № 27/1-07 «О районном бюджете на 2023-2025 годы»
    kaz: Түлкібас аудандық мәслихатының 2022 жылғы 23 желтоқсандағы № 27/1-07 «2023-2025 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/187925/rus
