act_code: '45474'
requisite: Оңтүстік Қазақстан облысы Түлкібас аудандық мәслихатының 2009 жылғы 31 наурыздағы N 17/5-04 шешімі. Оңтүстік Қазақстан облысы Түлкібас ауданының Әділет басқармасында 2009 жылғы 27 сәуірде N 14-14-72 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Түлкібас аудандық мәслихатының 2012 жылғы 5 қарашадағы N 9/9-05 Шешімімен
title:
  rus: Аудан көлемінде ауыл шаруашылық мақсатындағы жерлерге салынатын жер салық ставкалары туралы
  kaz: Аудан көлемінде ауыл шаруашылық мақсатындағы жерлерге салынатын жер салық ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-03-31
approved_by:
- '166012000002'
version_date:
  kaz: 2009-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/45474/kaz/31.03.2009
