act_code: '45474'
requisite: Оңтүстік Қазақстан облысы Түлкібас аудандық мәслихатының 2009 жылғы 31 наурыздағы N 17/5-04 шешімі. Оңтүстік Қазақстан облысы Түлкібас ауданының Әділет басқармасында 2009 жылғы 27 сәуірде N 14-14-72 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Түлкібас аудандық мәслихатының 2012 жылғы 5 қарашадағы N 9/9-05 Шешімімен
title:
  rus: Аудан көлемінде ауыл шаруашылық мақсатындағы жерлерге салынатын жер салық ставкалары туралы
  kaz: Аудан көлемінде ауыл шаруашылық мақсатындағы жерлерге салынатын жер салық ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-03-31
approved_by:
- '166012000002'
version_date:
  kaz: 2010-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/45474/kaz/22.12.2010
caused_by:
  code: '56373'
  requisite: Оңтүстік Қазақстан облысы Түлкібас аудандық мәслихатының 2010 жылғы 22 желтоқсандағы N 37/9-04 шешімі. Оңтүстік Қазақстан облысы Түлкібас ауданының Әділет басқармасында 2010 жылғы 29 желтоқсанда N 14-14-142 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Түлкібас аудандық мәслихатының 2012 жылғы 5 қарашадағы № 9/9-05 шешімімен
  title:
    rus: Түлкібас аудандық мәслихатының 2009 жылғы 31 наурыздағы N 17/5-04 "Аудан көлемінде ауыл шаруашылық мақсатындағы жерлерге салынатын жер салық ставкалары туралы" шешіміне өзгеріс енгізу туралы
    kaz: Түлкібас аудандық мәслихатының 2009 жылғы 31 наурыздағы N 17/5-04 "Аудан көлемінде ауыл шаруашылық мақсатындағы жерлерге салынатын жер салық ставкалары туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/56373/rus
