act_code: '54635'
requisite: Оңтүстік Қазақстан облысы Түлкібас ауданы әкімдігі Ақбиік ауылдық округі әкімінің 2010 жылғы 6 қыркүйектегі N 25 шешімі. Оңтүстік Қазақстан облысы Түлкібас ауданының Әділет басқармасында 2010 жылғы 22 қыркүйекте N 14-14-127 тіркелді
title:
  rus: Көшенің атын өзгерту туралы
  kaz: Көшенің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-06
approved_by:
- '166012009001'
version_date:
  kaz: 2010-09-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/54635/kaz/06.09.2010
