act_code: '128949'
requisite: Решение Жетысайского районного маслихата Туркестанской области от 27 декабря 2018 года № 10-51-VI. Зарегистрировано Департаментом юстиции Туркестанской области 30 января 2019 года № 4895. Утратило силу решением Жетысайского районного маслихата Туркестанской области от 31 декабря 2020 года № 41-220-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи по Жетысайскому району
  kaz: Жетісай ауданы бойынша тұрғын үй көмегiн көрсетудiң мөлшерi мен тәртiбiн айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-27
approved_by:
- '166017000002'
version_date:
  kaz: 2018-12-27
  rus: 2018-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/128949/kaz/27.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128949/rus/27.12.2018
