act_code: '177555'
requisite: Решение Отрарского районного маслихата Туркестанской области от 26 декабря 2022 года № 24/131-VII
title:
  rus: О бюджетах сельских округов на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған ауылдық округтердің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-26
approved_by:
- '166007000002'
version_date:
  kaz: 2023-11-10
  rus: 2023-11-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/177555/kaz/10.11.2023
  rus: https://zan.gov.kz/client/#!/doc/177555/rus/10.11.2023
caused_by:
  code: '188260'
  requisite: Решение Отрарского районного маслихата Туркестанской области от 10 ноября 2023 года № 8/49-VIІІ
  title:
    rus: О внесении изменений в решение Отырарского районного маслихата от 26 декабря 2022 года № 24/131-VІІ «О бюджетах сельских округов на 2023-2025 годы»
    kaz: Отырар аудандық мәслихатының 2022 жылғы 26 желтоқсандағы «2023-2025 жылдарға арналған ауылдық округтердің бюджеттері туралы» № 24/131-VII шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/188260/rus
