act_code: '194875'
requisite: Решение Арысского городского маслихата Туркестанской области от 20 марта 2024 года № 16/101-VІІІ. Зарегистрировано в Департаменте юстиции Туркестанской области 28 марта 2024 года № 6497-13
title:
  rus: Об определении размера и правил оказания жилищной помощи в городе Арыс
  kaz: Арыс қаласында тұрғын үй көмегін көрсетудің мөлшері мен қағидасын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-20
approved_by:
- '166016000002'
version_date:
  kaz: 2026-03-10
  rus: 2026-03-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/194875/kaz/10.03.2026
  rus: https://zan.gov.kz/client/#!/doc/194875/rus/10.03.2026
caused_by:
  code: '223071'
  requisite: Решение Арысского городского маслихата Туркестанской области от 10 марта 2026 года № 44/256-VІІІ. Зарегистрировано в Министерстве юстиции Республики Казахстан 11 марта 2026 года № 38119
  title:
    rus: О внесении изменений в решение маслихата города Арыс от 20 марта 2024 года № 16/101-VІІІ «Об определении размера и порядка оказания жилищной помощи в городе Арыс»
    kaz: Арыс қалалық мәслихатының 2024 жылғы 20 наурыздағы № 16/101-VІІІ «Арыс қаласында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/223071/rus
