act_code: '204930'
requisite: Решение Толебийского районного маслихата Туркестанской области от 25 декабря 2024 года № 21/119-VIII. Зарегистрировано в Департаменте юстиции Туркестанской области 27 декабря 2024 года № 6640-13
title:
  rus: Об утверждении ставок туристского взноса для иностранцев за 2025 год по Толебийскому району
  kaz: Төлеби ауданы бойынша шетелдіктер үшін 2025 жылға арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '166011000002'
version_date:
  kaz: 2024-12-25
  rus: 2024-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/204930/kaz/25.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204930/rus/25.12.2024
