act_code: '53760'
requisite: Оңтүстік Қазақстан облысы Сарыағаш ауданы әкімдігі Ақтөбе ауылдық округі әкімінің 2010 жылғы 24 маусымдағы N 77 Шешімі. Оңтүстік Қазақстан облысы Сарыағаш ауданы Әділет басқармасында 2010 жылғы 30 шілдеде N 14-11-135 тіркелді
title:
  rus: Ақтөбе ауылдық округі Қызыл әскер ауылындағы көшеге атау беру туралы
  kaz: Ақтөбе ауылдық округі Қызыл әскер ауылындағы көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-24
approved_by:
- '166009004001'
version_date:
  kaz: 2010-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/53760/kaz/24.06.2010
