act_code: '195476'
requisite: Решение акима сельского округа Караспан Ордабасинского района Туркестанской области от 5 апреля 2024 года № 33. Утратило силу решением акима сельского округа Караспан Ордабасинского района Туркестанской области от 11 июня 2024 года № 52 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-05
approved_by:
- '166006004002'
version_date:
  kaz: 2024-04-05
  rus: 2024-04-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/195476/kaz/05.04.2024
  rus: https://zan.gov.kz/client/#!/doc/195476/rus/05.04.2024
