act_code: '215199'
requisite: Решение Казыгуртского районного маслихата Туркестанской области от 30 сентября 2025 года № 32/191-VIII
title:
  rus: О предоставлении в 2025 подъемного пособия и бюджетного кредита на приобретение или строительство жилья в специалистам  в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, государственным служащим аппаратов акимов сел, поселков, сельских округов, прибывшим для работы и проживания в сельские населенные пункты Казыгуртского  района»
  kaz: Қазығұрт ауданының ауылдық елді мекендеріне жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға, ауылдар, кенттер, ауылдық округтер әкімдері аппараттарының мемлекеттік қызметшілеріне 2025 жылы көтерме жәрдемақы және тұрғын үй сатып алу немесе салу үшін бюджеттік кредит беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-30
approved_by:
- '166004000002'
version_date:
  kaz: 2025-09-30
  rus: 2025-09-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/215199/kaz/30.09.2025
  rus: https://zan.gov.kz/client/#!/doc/215199/rus/30.09.2025
