act_code: '76378'
requisite: Решение Шымкентского городского маслихата Южно-Казахстанской области от 24 декабря 2013 года № 30/190-5с. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 31 декабря 2013 года № 2476
title:
  rus: О бюджете города Шымкент на 2014-2016 годы
  kaz: 2014-2016 жылдарға арналған Шымкент қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-24
approved_by:
- '166002000002'
version_date:
  kaz: 2014-11-03
  rus: 2014-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/76378/kaz/03.11.2014
  rus: https://zan.gov.kz/client/#!/doc/76378/rus/03.11.2014
caused_by:
  code: '84077'
  requisite: Решение Шымкентского городского маслихата Южно-Казахстанской области от 3 ноября 2014 года № 42/288-5с. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 6 ноября 2014 года № 2867
  title:
    rus: О внесении изменений и дополнений в решение Шымкентского городского маслихата от 24 декабря 2013 года № 30/190-5с "О бюджете города Шымкент на 2014-2016 годы"
    kaz: Шымкент қалалық мәслихатының 2013 жылғы 24 желтоқсандағы № 30/190-5с "2014-2016 жылдарға арналған Шымкент қаласының бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/84077/rus
