act_code: '214173'
requisite: Решение акима сельского округа Коссейт Шардаринского района Туркестанской области от 11 сентября 2025 года № 42
title:
  rus: О присвоении наименований безымянным улицам
  kaz: Атауы жоқ көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-11
approved_by:
- '166013003002'
version_date:
  kaz: 2025-09-11
  rus: 2025-09-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/214173/kaz/11.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214173/rus/11.09.2025
