act_code: '204328'
requisite: Решение акима сельского округа Шолаккорган Созакского района Туркестанской области от 18 декабря 2024 года № 214
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-18
approved_by:
- '166010001002'
version_date:
  kaz: 2024-12-18
  rus: 2024-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/204328/kaz/18.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204328/rus/18.12.2024
