act_code: '49648'
requisite: Оңтүстік Қазақстан облысы Арыс қалалық мәслихатының 2009 жылғы 21 желтоқсандағы N 28/164-IV шешімі. Оңтүстік Қазақстан облысы Арыс қаласының Әділет басқармасында 2009 жылғы 29 желтоқсанда N 14-2-86 тіркелді
title:
  rus: 2010-2012 жылдарға арналған қалалық бюджет туралы
  kaz: 2010-2012 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-21
approved_by:
- '166016000002'
version_date:
  kaz: 2010-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/49648/kaz/24.05.2010
caused_by:
  code: '52917'
  requisite: Оңтүстік Қазақстан облысы Арыс қалалық мәслихатының 2010 жылғы 24 мамырдағы N 34/208-IV шешімі. Оңтүстік Қазақстан облысы Арыс қаласының Әділет басқармасында 2010 жылғы 29 мамырда N 14-2-94 тіркелді
  title:
    rus: Арыс қалалық мәслихатының 2009 жылғы 21 желтоқсандағы N 28/164-IV "2010-2012 жылдарға арналған қалалық бюджет туралы" шешіміне өзгерістер енгізу туралы
    kaz: Арыс қалалық мәслихатының 2009 жылғы 21 желтоқсандағы N 28/164-IV "2010-2012 жылдарға арналған қалалық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/52917/rus
