act_code: '54079'
requisite: Оңтүстік Қазақстан облысы Қазығұрт ауданы әкімдігі Шанақ ауылдық округі әкімінің 2010 жылғы 22 маусымдағы N 5 шешімі. Оңтүстік Қазақстан облысы Қазығұрт ауданының Әділет басқармасында 2010 жылғы 21 шілдеде N 14-6-112 тіркелді
title:
  rus: Ауыл округінің құрамдас бөліктеріне атау беру туралы
  kaz: Ауыл округінің құрамдас бөліктеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-22
approved_by:
- '166004013001'
version_date:
  kaz: 2010-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/54079/kaz/22.06.2010
