act_code: '121104'
requisite: Решение Отрарского районного маслихата Южно-Казахстанской области от 30 марта 2018 года № 25/126-VI. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 19 апреля 2018 года № 4555. Утратило силу решением Отрарского районного маслихата Туркестанской области от 6 августа 2024 года № 18/102-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламента собрания местного сообщества сельских округов Отрарского района
  kaz: Отырар аудандық ауылдық округтерінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-03-30
approved_by:
- '166007000002'
version_date:
  kaz: 2021-09-23
  rus: 2021-09-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/121104/kaz/23.09.2021
  rus: https://zan.gov.kz/client/#!/doc/121104/rus/23.09.2021
caused_by:
  code: '159329'
  requisite: Решение Отрарского районного маслихата Туркестанской области от 23 сентября 2021 года № 8/45-VII. Утратило силу решением Отрарского районного маслихата Туркестанской области от 6 августа 2024 года № 18/103-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесений изменения в решение маслихата Отрарского района от 30 марта 2018 года № 25/126-VI «Об утверждении регламента собрания местного сообщества сельских округов Отрарского района»
    kaz: Отырар ауданының мәслихатының 2018 жылғы 30 наурыздағы № 25/126-VI «Отырар аудандық ауылдық округтерінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/159329/rus
