act_code: '85586'
requisite: Решение Казыгуртского районного маслихата Южно-Казахстанской области от 24 декабря 2014 года № 40/259-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 29 декабря 2014 года № 2931
title:
  rus: О районном бюджете на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '166004000002'
version_date:
  kaz: 2015-03-30
  rus: 2015-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/85586/kaz/30.03.2015
  rus: https://zan.gov.kz/client/#!/doc/85586/rus/30.03.2015
caused_by:
  code: '88830'
  requisite: Решение Казыгуртского районного маслихата Южно-Казахстанской области от 30 марта 2015 года № 42/283-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 9 апреля 2015 года № 3117. Утратило силу в связи с истечением срока применения - (письмо Казыгуртского районного маслихата Южно-Казахстанской области от 25 января 2016 года № 15
  title:
    rus: О внесении изменений в решение Казыгуртского районного маслихата от 24 декабря 2014 года № 40/259-V "О районном бюджете на 2015-2017 годы"
    kaz: '"2015-2017 жылдарға арналған аудандық бюджет туралы" Қазығұрт аудандық мәслихатының 2014 жылғы 24 желтоқсандағы № 40/259-V шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/88830/rus
