act_code: '44899'
requisite: Оңтүстік Қазақстан облысы Мақтаарал аудандық мәслихатының 2009 жылғы 19 ақпандағы № 19-131-IV шешімі. Оңтүстік Қазақстан облысы Мақтаарал ауданының Әділет басқармасында 2009 жылғы 16 наурызда № 14-7-74 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Мақтаарал аудандық мәслихатының 2013 жылғы 29 наурыздағы № 15-90-V шешімімен
title:
  rus: Елді мекендердің жерлеріне салынатын базалық салық ставкалары туралы
  kaz: Елді мекендердің жерлеріне салынатын базалық салық ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-19
approved_by:
- '166005000002'
version_date:
  kaz: 2009-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/44899/kaz/19.02.2009
