act_code: '187791'
requisite: Решение Сауранского районного маслихата Туркестанской области от 27 октября 2023 года № 74. Зарегистрировано в Департаменте юстиции Туркестанской области 1 ноября 2023 года № 6388-13. Утратило силу решением Сауранского районного маслихата Туркестанской области от 14 февраля 2025 года № 212 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтiк көмек көрсетудің, оның мөлшерлерiн белгiлеудің және мұқтаж азаматтардың жекелеген санаттарының тiзбесiн айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-10-27
approved_by:
- '166019000002'
version_date:
  kaz: 2024-09-27
  rus: 2024-09-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/187791/kaz/27.09.2024
  rus: https://zan.gov.kz/client/#!/doc/187791/rus/27.09.2024
caused_by:
  code: '201130'
  requisite: Решение Сауранского районного маслихата Туркестанской области от 27 сентября 2024 года № 185. Зарегистрировано в Департаменте юстиции Туркестанской области 30 сентября 2024 года № 6595-13. Утратило силу решением Сауранского районного маслихата Туркестанской области от 14 февраля 2025 года № 212 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата района Сауран от 27 октября 2023 года № 74 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Сауран аудандық мәслихатының 2023 жылғы 27 қазандағы № 74 «Әлеуметтiк көмек көрсетудің, оның мөлшерлерiн белгiлеудің және мұқтаж азаматтардың жекелеген санаттарының тiзбесiн айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/201130/rus
