act_code: '85051'
requisite: Решение областного маслихата Южно-Казахстанской области от 11 декабря 2014 года № 34/258-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 15 декабря 2014 года № 2919
title:
  rus: Об областном бюджете на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-11
approved_by:
- '166000000002'
version_date:
  kaz: 2015-12-09
  rus: 2015-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/85051/kaz/09.12.2015
  rus: https://zan.gov.kz/client/#!/doc/85051/rus/09.12.2015
caused_by:
  code: '96376'
  requisite: Решение областного маслихата Южно-Казахстанской области от 9 декабря 2015 года № 44/375-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 11 декабря 2015 года № 3452. Утратило силу в связи с истечением срока применения - (письмо областного маслихата Южно-Казахстанской области от 11 января 2016 года № 23)
  title:
    rus: О внесении изменений в решение Южно-Казахстанского областного маслихата от 11 декабря 2014 года № 34/258-V "Об областном бюджете на 2015-2017 годы"
    kaz: '"2015-2017 жылдарға арналған облыстық бюджет туралы" Оңтүстік Қазақстан облыстық мәслихатының 2014 жылғы 11 желтоқсандағы № 34/258-V шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/96376/rus
