act_code: '55485'
requisite: Оңтүстік Қазақстан облысы Сарыағаш ауданы Абай ауылы әкімінің 2010 жылғы 13 қазандағы N 1300 шешімі. Оңтүстік Қазақстан облысы Сарыағаш ауданының Әділет басқармасында 2010 жылғы 19 қарашада N 14-11-153 тіркелді
title:
  rus: Абай ауылындағы атауы жоқ көшелерге атау беру және көше атауын өзгерту туралы
  kaz: Абай ауылындағы атауы жоқ көшелерге атау беру және көше атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-13
approved_by:
- '166009002001'
version_date:
  kaz: 2010-10-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/55485/kaz/13.10.2010
