act_code: '120867'
requisite: Решение Казыгуртского районного маслихата Южно-Казахстанской области от 30 марта 2018 года № 27/176-VI. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 18 апреля 2018 года № 4548
title:
  rus: Об утверждении регламента собрания местного сообщества сел, сельских округов Казыгуртского района
  kaz: Қазығұрт аудандық ауыл, ауылдық округтерінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-03-30
approved_by:
- '166004000002'
version_date:
  kaz: 2021-09-08
  rus: 2021-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/120867/kaz/08.09.2021
  rus: https://zan.gov.kz/client/#!/doc/120867/rus/08.09.2021
caused_by:
  code: '158466'
  requisite: Решение Казыгуртского районного маслихата Туркестанской области от 8 сентября 2021 года № 14/65-VII
  title:
    rus: О внесении изменений в решение Казыгуртского районного маслихата от 30 марта 2018 года № 27/176-VI «Об утверждении регламента собрания местного сообщества сел, сельских округов Казыгуртского района»
    kaz: Қазығұрт аудандық мәслихатының 2018 жылғы 30 наурыздағы № 27/176-VI «Қазығұрт аудандық ауыл, ауылдық округтерінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158466/rus
