act_code: '165938'
requisite: Решение Жетысайского районного маслихата Туркестанской области от 15 марта 2022 года № 18-106-VII. Утратило силу решением Жетысайского районного маслихата Туркестанской области от 8 июля 2022 года № 23-148-VII (вводится в действие после дня его первого официального опубликования)
title:
  rus: Об установлении повышенные на двадцать пять процентов должностные оклады и тарифные ставки специалистам в области социального обеспечения, культуры, спорта, являющимся гражданскими служащими и работающим в сельской местности
  kaz: Азаматтық қызметшілер болып табылатын және ауылдық жерде жұмыс iстейтiн әлеуметтiк қамсыздандыру, мәдениет, спорт саласындағы мамандарға жиырма бес пайызға жоғарылатылған лауазымдық айлықақылар мен тарифтiк мөлшерлемелерді белгiлеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-03-15
approved_by:
- '166017000002'
version_date:
  kaz: 2022-03-15
  rus: 2022-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/165938/kaz/15.03.2022
  rus: https://zan.gov.kz/client/#!/doc/165938/rus/15.03.2022
