act_code: '36810'
requisite: Оңтүстік Қазақстан облысы Созақ аудандық мәслихатының 2007 жылғы 26 желтоқсандағы № 24 шешімі. Оңтүстік Қазақстан облысы Созақ ауданының Әділет басқармасында 2008 жылғы 15 қаңтарда № 14-12-46 болып тіркелді
title:
  rus: 2008 жылға арналған аудандық бюджет туралы
  kaz: 2008 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-26
approved_by:
- '166010000002'
version_date:
  kaz: 2007-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/36810/kaz/26.12.2007
