act_code: '170736'
requisite: Решение Кентауского городского маслихата Туркестанской области от 9 августа 2022 года № 159. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 августа 2022 года № 29118
title:
  rus: О признании утратившим силу решения Кентауского городского маслихата от 5 декабря 2017 года № 114 «Об утверждении Правил управления бесхозяйными отходами, признанными решением суда поступившими в коммунальную собственность на территории города Кентау»
  kaz: Кентау қалалық мәслихатының 2017 жылғы 5 желтоқсандағы № 114 «Кентау қаласы аумағында сот шешімімен коммуналдық меншікке түскен болып танылған иесіз қалдықтарды басқару Қағидаларын бекіту туралы» шешімінің күшін жою деп тану туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-08-09
approved_by:
- '166014000002'
version_date:
  kaz: 2022-08-09
  rus: 2022-08-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/170736/kaz/09.08.2022
  rus: https://zan.gov.kz/client/#!/doc/170736/rus/09.08.2022
