act_code: '56145'
requisite: Оңтүстік Қазақстан облысы Мақтаарал аудандық мәслихатының 2010 жылғы 22 желтоқсандағы N 40-259-IV шешімі. Оңтүстік Қазақстан облысы Мақтаарал ауданы Әділет басқармасында 2010 жылғы 27 желтоқсанда N 14-7-131 тіркелді
title:
  rus: 2011-2013 жылдарға арналған аудандық бюджет туралы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-22
approved_by:
- '166005000002'
version_date:
  kaz: 2011-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/56145/kaz/09.11.2011
caused_by:
  code: '61299'
  requisite: Решение Мактааральского районного маслихата Южно-Казахстанской области от 9 ноября 2011 года N 51-348-IV. Зарегистрировано Управлением юстиции Мактааральского района Южно-Казахстанской области 15 ноября 2011 года N 14-7-152
  title:
    rus: О внесении изменений в решение Мактааральского районного маслихата от 22 декабря 2010 года № 40-259-IV "О районном бюджете на 2011-2013 годы"
    kaz: Мақтаарал аудандық мәслихатының 2010 жылғы 22 желтоқсандағы № 40-259-IV  "2011-2013 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер  енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/61299/rus
