act_code: '98977'
requisite: Решение акима Толебийского района Южно-Казахстанской области от 31 декабря 2015 года № 14. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 22 января 2016 года № 3547. Утратило силу решением акима Толебийсского района Туркестанской области от 9 ноября 2018 года № 08
title:
  rus: Об образовании избирательных участков на территории Толебийского района
  kaz: Төлеби ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-31
approved_by:
- '166011000001'
version_date:
  kaz: 2015-12-31
  rus: 2015-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/98977/kaz/31.12.2015
  rus: https://zan.gov.kz/client/#!/doc/98977/rus/31.12.2015
