act_code: '43102'
requisite: Решение Шымкентского городского маслихата Южно-Казахстанской области от 23 декабря 2008 года N 16/161-4с. Зарегистрировано Управлением юстиции города Шымкента Южно-Казахстанской области 29 декабря 2008 года N 14-1-85
title:
  rus: О бюджете города Шымкента на 2009 год
  kaz: 2009 жылға арналған Шымкент қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-23
approved_by:
- '166002000002'
version_date:
  kaz: 2009-01-27
  rus: 2009-01-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/43102/kaz/27.01.2009
  rus: https://zan.gov.kz/client/#!/doc/43102/rus/27.01.2009
caused_by:
  code: '44050'
  requisite: Решение Шымкентского городского маслихата Южно-Казахстанской области от 27 января 2009 года N 17/174-4с. Зарегистрировано Управлением юстиции города Шымкента Южно-Казахстанской области 30 января 2009 года N 14-1-88
  title:
    rus: О внесении изменений и дополнений в решение городского маслихата от 23 декабря 2008 года N 16/161-4с "О бюджете города Шымкента на 2009 год"
    kaz: Қалалық мәслихатының 2008 жылғы 23 желтоқсандағы N 16/161-4с "2009 жылға арналған Шымкент қаласының бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/44050/rus
