act_code: '177694'
requisite: Решение Жетысайского районного маслихата Туркестанской области от 30 декабря 2022 года № 29-190-VII
title:
  rus: О бюджете города, поселка и сельских округов на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған қала, кент және ауылдық округтердің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-30
approved_by:
- '166017000002'
version_date:
  kaz: 2022-12-30
  rus: 2022-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/177694/kaz/30.12.2022
  rus: https://zan.gov.kz/client/#!/doc/177694/rus/30.12.2022
