act_code: '177694'
requisite: Решение Жетысайского районного маслихата Туркестанской области от 30 декабря 2022 года № 29-190-VII
title:
  rus: О бюджете города, поселка и сельских округов на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған қала, кент және ауылдық округтердің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-30
approved_by:
- '166017000002'
version_date:
  kaz: 2023-11-20
  rus: 2023-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/177694/kaz/20.11.2023
  rus: https://zan.gov.kz/client/#!/doc/177694/rus/20.11.2023
caused_by:
  code: '188910'
  requisite: Решение Жетысайского районного маслихата Туркестанской области от 20 ноября 2023 года № 9-58-VIІІ
  title:
    rus: О внесении изменений в решение Жетысайского районного маслихата от 30 декабря 2022 года № 29-190-VII «О бюджете города, поселка и сельских округов на 2023-2025 годы»
    kaz: Жетісай аудандық мәслихатының 2022 жылғы 30 желтоқсандағы № 29-190-VII «2023-2025 жылдарға арналған қала, кент және ауылдық округтердің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/188910/rus
