act_code: '163189'
requisite: Решение Созакского районного маслихата Туркестанской области от 28 декабря 2021 года № 74
title:
  rus: О бюджете сельских округов и поселков на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған ауылдық округтер және кенттер бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-28
approved_by:
- '166010000002'
version_date:
  kaz: 2022-09-30
  rus: 2022-09-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/163189/kaz/30.09.2022
  rus: https://zan.gov.kz/client/#!/doc/163189/rus/30.09.2022
caused_by:
  code: '172360'
  requisite: Решение Созакского районного маслихата Туркестанской области от 30 сентября 2022 года № 131
  title:
    rus: О внесении изменений в решение Сузакского районного маслихата от 28 декабря 2021 года № 74 «О бюджете сельских округов и поселков на 2022-2024 годы»
    kaz: Созақ аудандық мәслихатының 2021 жылғы 28 желтоқсандағы № 74 «2022-2024 жылдарға арналған ауылдық округтер және кенттер бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172360/rus
