act_code: '73778'
requisite: Решение областного маслихата Южно-Казахстанской области от 26 июня 2013 года № 14/125-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 31 июля 2013 года № 2351. Утратило силу решением Туркестанского областного маслихата от 30 октября 2020 года № 53/548-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил содержания и выгула собак и кошек в городах и других населенных пунктах Южно-Казахстанской области
  kaz: Оңтүстік Қазақстан облысының қалаларында және басқа да елді мекендерінде иттер мен мысықтарды асырау және серуендету Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2013-06-26
approved_by:
- '166000000002'
version_date:
  kaz: 2014-12-11
  rus: 2014-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/73778/kaz/11.12.2014
  rus: https://zan.gov.kz/client/#!/doc/73778/rus/11.12.2014
caused_by:
  code: '85912'
  requisite: Решение областного маслихата Южно-Казахстанской области от 11 декабря 2014 года № 34/266-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 6 января 2015 года № 2951. Утратило силу решением Туркестанского областного маслихата от 30 октября 2020 года № 53/548-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Южно-Казахстанского областного маслихата от 26 июня 2013 года № 14/125-V "Об утверждении Правил содержания и выгула собак и кошек в городах и других населенных пунктах Южно-Казахстанской области"
    kaz: Оңтүстік Қазақстан облыстық мәслихатының 2013 жылғы 26 маусымдағы № 14/125-V "Оңтүстік Қазақстан облысының қалаларында және басқа да елді мекендерінде иттер мен мысықтарды асырау және серуендету Қағидаларын бекіту туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/85912/rus
