act_code: '191893'
requisite: Решение акима Машатского сельского округа акимата Тюлькубасского района Туркестанской области от 3 января 2024 года № 1
title:
  rus: Об утверждении квалификационных требований для административных государственных должностей
  kaz: Мемлекеттік әкімшілік лауазымдарға арналған біліктілік талаптарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-01-03
approved_by:
- '166012001002'
version_date:
  kaz: 2024-01-03
  rus: 2024-01-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/191893/kaz/03.01.2024
  rus: https://zan.gov.kz/client/#!/doc/191893/rus/03.01.2024
