act_code: '207499'
requisite: Решение Жетысайского районного маслихата Туркестанской области от 25 февраля 2025 года № 26-156-VIII
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества, количественного состава представителей жителей города, поселка и сельского округа для участия в сходе местного сообщества в Жетысайском районе
  kaz: Жетісай ауданы бойынша жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін қала, кент және ауылдық округ тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-02-25
approved_by:
- '166017000002'
version_date:
  kaz: 2025-02-25
  rus: 2025-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/207499/kaz/25.02.2025
  rus: https://zan.gov.kz/client/#!/doc/207499/rus/25.02.2025
