act_code: '202850'
requisite: Решение Мактааральского районного маслихата Туркестанской области от 18 ноября 2024 года № 23-145-VIII. Зарегистрировано в Департаменте юстиции Туркестанской области 19 ноября 2024 года № 6620-13
title:
  rus: Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Мактааральского района
  kaz: Мақтаарал ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебiнен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету тәртібі мен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-11-18
approved_by:
- '166005000002'
version_date:
  kaz: 2024-11-18
  rus: 2024-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/202850/kaz/18.11.2024
  rus: https://zan.gov.kz/client/#!/doc/202850/rus/18.11.2024
