act_code: '128970'
requisite: Решение Тюлькубасского районного маслихата Туркестанской области от 21 декабря 2018 года № 34/9-06. Зарегистрировано Департаментом юстиции Туркестанской области 11 января 2019 года № 4884. Утратило силу решением Тюлькубасского районного маслихата Туркестанской области от 23 июня 2020 года № 56/3-06 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения
  kaz: Пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерге жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемесін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-21
approved_by:
- '166012000002'
version_date:
  kaz: 2018-12-21
  rus: 2018-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/128970/kaz/21.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128970/rus/21.12.2018
