act_code: '147183'
requisite: Решение Тюлькубасского районного маслихата Туркестанской области от 14 сентября 2020 года № 59/2-06. Зарегистрировано Департаментом юстиции Туркестанской области 7 октября 2020 года № 5827
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию в Тюлькубасском районе на 2020-2021 годы
  kaz: Түлкібас ауданының жайылымдарды басқару және оларды пайдалану жөніндегі 2020-2021 жылдарға арналған жоспарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-14
approved_by:
- '166012000002'
version_date:
  kaz: 2020-09-14
  rus: 2020-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/147183/kaz/14.09.2020
  rus: https://zan.gov.kz/client/#!/doc/147183/rus/14.09.2020
