act_code: '44898'
requisite: Оңтүстік Қазақстан облысы Мақтаарал аудандық мәслихатының 2009 жылғы 19 ақпандағы N 19-130-IV шешімі. Оңтүстік Қазақстан облысы Мақтаарал ауданының Әділет басқармасында 2009 жылғы 16 наурызда N 14-7-73 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Мақтаарал аудандық мәслихатының 2015 жылғы 31 наурыздағы № 42-255-V шешімімен
title:
  rus: Бірыңғай тіркелген салық ставкаларынын белгілеу туралы
  kaz: Бірыңғай тіркелген салық ставкаларынын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-19
approved_by:
- '166005000002'
version_date:
  kaz: 2009-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/44898/kaz/19.02.2009
