act_code: '116911'
requisite: Решение Ордабасинского районного маслихата Южно-Казахстанской области от 24 ноября 2017 года № 19/2. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 14 декабря 2017 года № 4320. Утратило силу решением Ордабасинского районного маслихата Туркестанской области от 19 февраля 2024 года № 12/1 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов, тарифов на сбор, вывоз, утилизацию, переработку и захоронение твердых бытовых отходов по Ордабасинскому району
  kaz: Ордабасы ауданы бойынша коммуналдық қалдықтардың түзілу мен жинақталу нормаларын, тұрмыстық қатты қалдықтарды жинауға, әкетуге, кәдеге жаратуға, қайта өңдеуге және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-11-24
approved_by:
- '166006000002'
version_date:
  kaz: 2020-09-29
  rus: 2020-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/116911/kaz/29.09.2020
  rus: https://zan.gov.kz/client/#!/doc/116911/rus/29.09.2020
caused_by:
  code: '147257'
  requisite: Решение Ордабасинского районного маслихата Туркестанской области от 29 сентября 2020 года № 68/7. Зарегистрировано Департаментом юстиции Туркестанской области 8 октября 2020 года № 5830. Утратило силу решением Ордабасинского районного маслихата Туркестанской области от 19 февраля 2024 года № 12/1 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Ордабасинского районного маслихата от 24 ноября 2017 года № 19/2 «Об утверждении норм образования и накопления коммунальных отходов, тарифов на сбор, вывоз, утилизацию, переработку и захоронение твердых бытовых отходов по Ордабасинскому району»
    kaz: Ордабасы аудандық мәслихатының 2017 жылғы 24 қарашадағы № 19/2 «Ордабасы ауданы бойынша коммуналдық қалдықтардың түзілу мен жинақталу нормаларын, тұрмыстық қатты қалдықтарды жинауға, әкетуге, кәдеге жаратуға, қайта өңдеуге және көмуге арналған тарифтерді бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/147257/rus
