act_code: '39796'
requisite: Решение Шымкентского городского маслихата Южно-Казахстанской области от 14 апреля 2008 года N 9/81-4с. Зарегистрировано Управлением юстиции города Шымкента Южно-Казахстанской области 27 мая 2008 года N 14-1-76. Утратило силу - решением Шымкентского городского маслихата Южно-Казахстанской области от 20 февраля 2009 года N 18/183-4c
title:
  rus: О ставках фиксированного суммарного налога для отдельных видов предпринимательской деятельности
  kaz: Кәсіпкерлік қызметтің жекелеген түрлеріне арналған тіркелген жиынтық салық ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-04-14
approved_by:
- '166002000002'
version_date:
  kaz: 2008-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/39796/kaz/14.04.2008
