act_code: '108912'
requisite: Решение Сарыагашского районного маслихата Южно-Казахстанской области от 23 декабря 2016 года № 8-72-VI. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 5 января 2017 года № 3951
title:
  rus: О районном бюджете на 2017-2019 годы
  kaz: 2017-2019 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-23
approved_by:
- '166009000002'
version_date:
  kaz: 2016-12-23
  rus: 2016-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/108912/kaz/23.12.2016
  rus: https://zan.gov.kz/client/#!/doc/108912/rus/23.12.2016
