act_code: '137379'
requisite: Решение Туркестанского областного маслихата от 9 декабря 2019 года № 44/477-VI. Зарегистрировано Департаментом юстиции Туркестанской области 23 декабря 2019 года № 5312
title:
  rus: Об определении перечня социально значимых сообщений Туркестанской области
  kaz: Түркістан облысы бойынша әлеуметтік маңызы бар қатынастардың тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-09
approved_by:
- '166000000002'
version_date:
  kaz: 2019-12-09
  rus: 2019-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/137379/kaz/09.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137379/rus/09.12.2019
