act_code: '55211'
requisite: Оңтүстік Қазақстан облысы Қазығұрт ауданы әкімдігінің 2010 жылғы 27 қыркүйектегі N 32 Шешімі. Оңтүстік Қазақстан облысы Қазығұрт ауданының Әділет басқармасында 2010 жылғы 29 қазанда N 14-6-118 тіркелді
title:
  rus: Қазығұрт ауданының 1994 жылы туылған азаматтарын 2011 жылы шақыру учаскесіне тіркеуді жүргізу туралы
  kaz: Қазығұрт ауданының 1994 жылы туылған азаматтарын 2011 жылы шақыру учаскесіне тіркеуді жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-27
approved_by:
- '166004000001'
version_date:
  kaz: 2010-09-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/55211/kaz/27.09.2010
