act_code: '195855'
requisite: Решение Созакского районного маслихата Туркестанской области от 19 апреля 2024 года № 109. Зарегистрировано в Департаменте юстиции Туркестанской области 19 апреля 2024 года № 6517-13
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Созакском районе
  kaz: Созақ ауданында тұрғын үй көмегін көрсету мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-19
approved_by:
- '166010000002'
version_date:
  kaz: 2024-04-19
  rus: 2024-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/195855/kaz/19.04.2024
  rus: https://zan.gov.kz/client/#!/doc/195855/rus/19.04.2024
