act_code: '186422'
requisite: Решение Шардаринского районного маслихата Туркестанской области от 20 сентября 2023 года № 8-45-VIII. Зарегистрировано в Департаменте юстиции Туркестанской области 20 сентября 2023 года № 6347-13. Утратило силу решением Шардаринского районного маслихата Туркестанской области от 7 февраля 2025 года № 33-176-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-09-20
approved_by:
- '166013000002'
version_date:
  kaz: 2024-09-27
  rus: 2024-09-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/186422/kaz/27.09.2024
  rus: https://zan.gov.kz/client/#!/doc/186422/rus/27.09.2024
caused_by:
  code: '201295'
  requisite: Решение Шардаринского районного маслихата Туркестанской области от 27 сентября 2024 года № 26-138-VIII. Зарегистрировано в Департаменте юстиции Туркестанской области 2 октября 2024 года № 6606-13. Утратило силу решением Шардаринского районного маслихата Туркестанской области от 7 февраля 2025 года № 33-176-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Шардаринского районного маслихата от 20 сентября 2023 года № 8-45-VIII «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Шардара аудандық мәслихатының 2023 жылғы 20 қыркүйектегі № 8-45-VIII «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/201295/rus
