act_code: '76622'
requisite: Решение Созакского районного маслихата Южно-Казахстанской области от 23 декабря 2013 года № 132. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 10 января 2014 года № 2490
title:
  rus: О районном бюджете на 2014-2016 годы
  kaz: 2014-2016 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-23
approved_by:
- '166010000002'
version_date:
  kaz: 2014-08-13
  rus: 2014-08-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/76622/kaz/13.08.2014
  rus: https://zan.gov.kz/client/#!/doc/76622/rus/13.08.2014
caused_by:
  code: '82079'
  requisite: Решение Созакского районного маслихата Южно-Казахстанской области от 13 августа 2014 года № 199. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 19 августа 2014 года № 2782
  title:
    rus: О внесении изменений в решение Созакского районного маслихата от 23 декабря 2013 года № 132 "О районном бюджете на 2014-2016 годы"
    kaz: Созақ аудандық мәслихатының 2013 жылғы 23 желтоқсандағы № 132 "2014-2016 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/82079/rus
