act_code: '186317'
requisite: Решение акима Рыскуловского сельского округа Тюлькубасского района Туркестанской области от 19 сентября 2023 года № 37
title:
  rus: О переименовании улицы и присвоении наименований безымянным улицам
  kaz: Көшені қайта атау және атауы жоқ көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-09-19
approved_by:
- '166012011002'
version_date:
  kaz: 2023-09-19
  rus: 2023-09-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/186317/kaz/19.09.2023
  rus: https://zan.gov.kz/client/#!/doc/186317/rus/19.09.2023
