act_code: '169815'
requisite: Решение Отрарского районного маслихата Туркестанской области от 8 июля 2022 года № 18/98-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 14 июля 2022 года № 28802
title:
  rus: Об установлении повышенных на двадцать пять процентов должностных окладов и тарифных ставок специалистам в области социального обеспечения, культуры и спорта, являющимся гражданскими служащими и работающим в сельской местности Отырарского района
  kaz: Отырар ауданының азаматтық қызметшілер болып табылатын және ауылдық жерде жұмыс iстейтiн әлеуметтiк қамсыздандыру, мәдениет және спорт саласындағы мамандарға жиырма бес пайызға жоғарылатылған лауазымдық айлықақылар мен тарифтік мөлшерлемелер белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-07-08
approved_by:
- '166007000002'
version_date:
  kaz: 2022-07-08
  rus: 2022-07-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/169815/kaz/08.07.2022
  rus: https://zan.gov.kz/client/#!/doc/169815/rus/08.07.2022
