act_code: '195420'
requisite: Решение Сайрамского районного маслихата Туркестанской области от 5 апреля 2024 года № 15-115/VIII. Зарегистрировано в Департаменте юстиции Туркестанской области 9 апреля 2024 года № 6512-13
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Сайрамском районе
  kaz: Сайрам ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-05
approved_by:
- '166008000002'
version_date:
  kaz: 2024-04-05
  rus: 2024-04-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/195420/kaz/05.04.2024
  rus: https://zan.gov.kz/client/#!/doc/195420/rus/05.04.2024
