act_code: '175579'
requisite: Решение Туркестанского областного маслихата от 13 декабря 2022 года № 19/233-VII
title:
  rus: Об объемах трансфертов общего характера между областным бюджетом и районными (городов областного значения) бюджетами на 2023-2025 годы
  kaz: Облыстық бюджет және аудандық (облыстық маңызы бар қалалар) бюджеттердің арасындағы 2023-2025 жылдарға арналған жалпы сипаттағы трансферттердің көлемі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-13
approved_by:
- '166000000002'
version_date:
  kaz: 2022-12-13
  rus: 2022-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/175579/kaz/13.12.2022
  rus: https://zan.gov.kz/client/#!/doc/175579/rus/13.12.2022
