act_code: '195288'
requisite: Решение акима сельского округа Карабау Казыгуртского района Туркестанской области от 4 апреля 2024 года № 12. Утратило силу решением акима сельского округа Карабау Казыгуртского района Туркестанской области от 14 июня 2024 года № 16 (вводится в действие после дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-04
approved_by:
- '166004007002'
version_date:
  kaz: 2024-04-04
  rus: 2024-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/195288/kaz/04.04.2024
  rus: https://zan.gov.kz/client/#!/doc/195288/rus/04.04.2024
