act_code: '62278'
requisite: Решение Шымкентского городского маслихата Южно-Казахстанской области от 21 декабря 2011 года N 61/479-4c. Зарегистрировано Управлением юстиции города Шымкента Южно-Казахстанской области 27 декабря 2011 года N 14-1-150
title:
  rus: О бюджете города Шымкент на 2012-2014 годы
  kaz: 2012-2014 жылдарға арналған Шымкент қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-21
approved_by:
- '166002000002'
version_date:
  kaz: 2012-06-14
  rus: 2012-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/62278/kaz/14.06.2012
  rus: https://zan.gov.kz/client/#!/doc/62278/rus/14.06.2012
caused_by:
  code: '66247'
  requisite: Решение Шымкентского городского маслихата Южно-Казахстанской области от 14 июня 2012 года № 8/57-5c. Зарегистрировано Управлением юстиции города Шымкента Южно-Казахстанской области 25 июня 2012 года № 14-1-161
  title:
    rus: О внесении изменений и дополнений в решение городского маслихата от 21 декабря 2011 года № 61/479-4с "О бюджете города Шымкент на 2012-2014 годы"
    kaz: '"2012-2014 жылдарға арналған Шымкент қаласының бюджеті туралы" қалалық мәслихаттың 2011 жылғы 21 желтоқсандағы № 61/479-4с шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/66247/rus
