act_code: '57056'
requisite: Оңтүстік Қазақстан облысы Кентау қалалық мәслихатының 2010 жылғы 22 желтоқсандағы N 271 Шешімі. Оңтүстік Қазақстан облысы Кентау қаласының Әділет басқармасында 2011 жылғы 24 қаңтарда N 14-3-107 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Кентау қалалық мәслихатының 2012 жылғы 5 маусымдағы № 35 Шешімімен
title:
  rus: Кентау қаласы мен қала маңын және елді мекендердің аумағын абаттандыру, көріктендіру ережесін бекіту туралы
  kaz: Кентау қаласы мен қала маңын және елді мекендердің аумағын абаттандыру, көріктендіру ережесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-22
approved_by:
- '166014000002'
version_date:
  kaz: 2010-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/57056/kaz/22.12.2010
