act_code: '55212'
requisite: Оңтүстік Қазақстан облысы Қазығұрт ауданы әкімдігі Қазығұрт ауылдық округі әкімінің 2010 жылғы 27 қыркүйектегі N 80 шешімі. Оңтүстік Қазақстан облысы Қазығұрт ауданының Әділет басқармасында 2010 жылғы 29 қазанда N 14-6-119 тіркелді
title:
  rus: Қазығұрт ауылы округіндегі атауы жоқ көшелерге атау беру жайлы
  kaz: Қазығұрт ауылы округіндегі атауы жоқ көшелерге атау беру жайлы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-27
approved_by:
- '166004005001'
version_date:
  kaz: 2010-09-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/55212/kaz/27.09.2010
