act_code: '11255'
requisite: Решение Южно-Казахстанского областного маслихата от 27 декабря 2001 года № 15/166-II. Зарегистрировано в Управлении юстиции Южно-Казахстанской области 25 января 2002 года № 483. Утратило силу решением маслихата Южно-Казахстанской области от 23 июня 2005 года № 15/161-III
title:
  rus: Об установлении размеров платы за побочные лесные пользования на территории лесного фонда области
  kaz: Облыстық орман қоры аумағында орманды жанама пайдаланудың төлемақыларының мөлшерiн белгiлеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-12-27
approved_by:
- '166000000002'
version_date:
  kaz: 2001-12-27
  rus: 2001-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/11255/kaz/27.12.2001
  rus: https://zan.gov.kz/client/#!/doc/11255/rus/27.12.2001
