act_code: '96882'
requisite: Решение от 29.12.2015 № 43/248-V, Маслихат Отырарского района
title:
  rus: Признать утратившим силу решение Отрарского районного маслихата от 27 марта 2015 года № 35/205-V «Об утверждении норм образования и накопления коммунальных отходов, тарифов на сбор, вывоз, захоронение и утилизацию отходов по Отрарскому району
  kaz: Аудандық мәслихаттың 2015 жылғы 27 наурыздағы № 35/205-V «Отырар ауданы бойынша коммуналдық қалдықтардың пайда болу және жинақталу нормаларын және коммуналдық қалдықтарды жинау, әкету, көму, кәдеге жарату тарифтерін бекіту туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-29
approved_by:
- '166007000002'
version_date:
  kaz: 2015-12-29
  rus: 2015-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/96882/kaz/29.12.2015
  rus: https://zan.gov.kz/client/#!/doc/96882/rus/29.12.2015
