act_code: '183322'
requisite: Решение Туркестанского городского маслихата Туркестанской области от 27 июня 2023 года № 3/19-VIII. Утратило силу решением Туркестанского городского маслихата Туркестанской области от 28 ноября 2025 года № 35/162-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» аппарата Туркестанского городского маслихата
  kaz: «Б» корпусы Түркістан қалалық мәслихат аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-06-27
approved_by:
- '166015000002'
version_date:
  kaz: 2023-06-27
  rus: 2023-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/183322/kaz/27.06.2023
  rus: https://zan.gov.kz/client/#!/doc/183322/rus/27.06.2023
