act_code: '56366'
requisite: Оңтүстік Қазақстан облысы Ордабасы ауданы әкімдігі Қараспан ауылдық округі әкімінің 2010 жылғы 22 қарашадағы N 59 Шешімі. Оңтүстік Қазақстан облысы Ордабасы ауданы Әділет басқармасында 2010 жылғы 24 желтоқсанда N 14-8-95 тіркелді
title:
  rus: Көше атын беру туралы
  kaz: Көше атын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-22
approved_by:
- '166006004001'
version_date:
  kaz: 2010-11-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/56366/kaz/22.11.2010
