act_code: '205321'
requisite: Решение Мактааральского районного маслихата Туркестанской области от 24 декабря 2024 года № 24-153-VIII. Зарегистрировано в Департаменте юстиции Туркестанской области 30 декабря 2024 года № 6645-13
title:
  rus: Об утверждении ставок туристского взноса для иностранцев по Мактааральскому району
  kaz: Мақтаарал ауданы бойынша шетелдіктер үшін туристік жарнаның мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-24
approved_by:
- '166005000002'
version_date:
  kaz: 2024-12-24
  rus: 2024-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/205321/kaz/24.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205321/rus/24.12.2024
