act_code: '39260'
requisite: Решение областного маслихата Южно-Казахстанской области от 11 апреля 2008 года № 6/86-IV. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 29 апреля 2008 года № 1983. Утратило силу решением Туркестанского областного маслихата от 29 мая 2020 года № 49/516-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О дополнительном предоставлении лекарственных средств отдельным категориям граждан при амбулаторном лечении бесплатно
  kaz: Азаматтардың жекелеген санаттарына амбулаториялық емдеу кезінде тегін дәрілік заттарды қосымша беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-04-11
approved_by:
- '166000000002'
version_date:
  rus: 2013-06-26
source:
  rus: https://zan.gov.kz/client/#!/doc/39260/rus/26.06.2013
caused_by:
  code: '73655'
  requisite: Решение областного маслихата Южно-Казахстанской области от 26 июня 2013 года № 14/128-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 23 июля 2013 года № 2338. Утратило силу решением Туркестанского областного маслихата от 29 мая 2020 года № 49/516-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Южно-Казахстанского областного маслихата от 11 апреля 2008 года № 6/86-IV "О дополнительном представлении лекарственных средств отдельным категориям граждан при амбулаторном лечении бесплатно"
    kaz: Оңтүстік Қазақстан облыстық мәслихатының 2008 жылғы 11 сәуірдегі № 6/86-ІV "Азаматтардың жекелеген санаттарына амбулаториялық емдеу кезінде тегін дәрілік заттарды қосымша беру туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/73655/rus
