act_code: '39260'
requisite: Решение областного маслихата Южно-Казахстанской области от 11 апреля 2008 года № 6/86-IV. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 29 апреля 2008 года № 1983. Утратило силу решением Туркестанского областного маслихата от 29 мая 2020 года № 49/516-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О дополнительном предоставлении лекарственных средств отдельным категориям граждан при амбулаторном лечении бесплатно
  kaz: Азаматтардың жекелеген санаттарына амбулаториялық емдеу кезінде тегін дәрілік заттарды қосымша беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-04-11
approved_by:
- '166000000002'
version_date:
  kaz: 2015-12-09
  rus: 2015-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/39260/kaz/09.12.2015
  rus: https://zan.gov.kz/client/#!/doc/39260/rus/09.12.2015
caused_by:
  code: '97290'
  requisite: Решение Южно-Казахстанского областного маслихата № 44/370-IV от 9 декабря 2015 года. Зарегистрировано Департаментом юстиции Южно-Казахстанской области от 6 января 2016 года № 3511. Утратило силу решением Туркестанского областного маслихата от 29 мая 2020 года № 49/516-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении дополнения в решение Южно-Казахстанского областного маслихата от 11 апреля 2008 года № 6/86-ІV «О дополнительном предоставлении лекарственных средств отдельным  категориям граждан при амбулаторном лечении бесплатно»
    kaz: «Азаматтардың жекелеген санаттарына амбулаториялық емдеу кезінде тегін дәрілік заттарды қосымша беру туралы» Оңтүстік Қазақстан облыстық мәслихатының 2008 жылғы 11 сәуірдегі № 6/86-ІV шешіміне толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/97290/rus
