act_code: '39260'
requisite: Решение областного маслихата Южно-Казахстанской области от 11 апреля 2008 года № 6/86-IV. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 29 апреля 2008 года № 1983. Утратило силу решением Туркестанского областного маслихата от 29 мая 2020 года № 49/516-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О дополнительном предоставлении лекарственных средств отдельным категориям граждан при амбулаторном лечении бесплатно
  kaz: Азаматтардың жекелеген санаттарына амбулаториялық емдеу кезінде тегін дәрілік заттарды қосымша беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-04-11
approved_by:
- '166000000002'
version_date:
  kaz: 2018-06-21
  rus: 2018-06-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/39260/kaz/21.06.2018
  rus: https://zan.gov.kz/client/#!/doc/39260/rus/21.06.2018
caused_by:
  code: '123311'
  requisite: Решение Южно-Казахстанского областного маслихата от 21 июня 2018 года № 25/291-VI. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 9 июля 2018 года № 4670. Утратило силу решением Туркестанского областного маслихата от 29 мая 2020 года № 49/516-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении дополнений в решение Южно-Казахстанского областного маслихата от 11 апреля 2008 года № 6/86-ІV "О дополнительном предоставлении лекарственных средств отдельным категориям граждан при амбулаторном лечении бесплатно"
    kaz: Оңтүстік Қазақстан облыстық мәслихатының 2008 жылғы 11 сәуірдегі № 6/86-ІV "Азаматтардың жекелеген санаттарына амбулаториялық емдеу кезінде тегін дәрілік заттарды қосымша беру туралы" шешіміне толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123311/rus
