act_code: '193313'
requisite: Решение Байдибекского районного маслихата Туркестанской области от 14 февраля 2024 года № 13/64
title:
  rus: Об утверждении тарифов на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по району Байдибек
  kaz: Бәйдібек ауданы бойынша тұрмыстық қатты қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-14
approved_by:
- '166003000002'
version_date:
  kaz: 2024-02-14
  rus: 2024-02-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/193313/kaz/14.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193313/rus/14.02.2024
