act_code: '74377'
requisite: Решение от 21.08.2013 №18/2-05, Маслихат Тюлькубасского района. Утратило силу решением Тюлькубасского районного маслихата Южно-Казахстанской области от 30 июня 2015 года № 41/9-05
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-08-21
approved_by:
- '166012000002'
version_date:
  kaz: 2013-08-21
  rus: 2013-08-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/74377/kaz/21.08.2013
  rus: https://zan.gov.kz/client/#!/doc/74377/rus/21.08.2013
