act_code: '45041'
requisite: Решение Шымкентского городского маслихата Южно-Казахстанской области от 20 февраля 2009 года N 18/183-4с. Зарегистрировано управлением юстиции города Шымкента Южно-Казахстанской области 24 марта 2009 года N 14-1-92. Утратило силу решением Шымкентского городского маслихата Южно-Казахстанской области от 29 мая 2018 года № 28/241-6с
title:
  rus: О единых ставках фиксированного налога
  kaz: Бiрыңғай тiркелген салық мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-20
approved_by:
- '166002000002'
version_date:
  kaz: 2009-02-20
  rus: 2009-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/45041/kaz/20.02.2009
  rus: https://zan.gov.kz/client/#!/doc/45041/rus/20.02.2009
