act_code: '53922'
requisite: Оңтүстік Қазақстан облысы Отырар ауданы мәслихатының 2010 жылғы 28 маусымдағы N 32/199-IV шешімі. Оңтүстік Қазақстан облысы Отырар ауданының Әділет басқармасында 2010 жылғы 10 тамызда N 14-9-117 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Отырар аудандық мәслихатының 2012 жылғы 7 маусымдағы № 4/31-V Шешімімен
title:
  rus: Отырар ауданының елді мекендерінде жануарларды ұстау, иттер мен мысықтарды серуендету туралы Қағидасын бекіту туралы
  kaz: Отырар ауданының елді мекендерінде жануарларды ұстау, иттер мен мысықтарды серуендету туралы Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-28
approved_by:
- '166007000002'
version_date:
  kaz: 2010-06-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/53922/kaz/28.06.2010
