act_code: '220252'
requisite: Решение Сайрамского районного маслихата Туркестанской области от 30 декабря 2025 года № 36-246/VІІІ
title:
  rus: О бюджетах сельских округов Сайрамского района на 2026-2028 годы
  kaz: Сайрам ауданы ауылдық округтерінің 2026-2028 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-30
approved_by:
- '166008000002'
version_date:
  kaz: 2025-12-30
  rus: 2025-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/220252/kaz/30.12.2025
  rus: https://zan.gov.kz/client/#!/doc/220252/rus/30.12.2025
