act_code: '176057'
requisite: Решение Созакского районного маслихата Туркестанской области от 23 декабря 2022 года № 145
title:
  rus: О районном бюджете на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-23
approved_by:
- '166010000002'
version_date:
  kaz: 2023-05-16
  rus: 2023-05-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/176057/kaz/16.05.2023
  rus: https://zan.gov.kz/client/#!/doc/176057/rus/16.05.2023
caused_by:
  code: '181853'
  requisite: Решение Созакского районного маслихата Туркестанской области от 16 мая 2023 года № 10
  title:
    rus: О внесении изменений в решение Созакского районного маслихата от 23 декабря 2022 года № 145 «О районном бюджете на 2023-2025 годы»
    kaz: Созақ аудандық мәслихатының 2022 жылғы 23 желтоқсандағы № 145 «2023-2025 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/181853/rus
