act_code: '86306'
requisite: Решение Толебийского районного маслихата Южно-Казахстанской области от 23 декабря 2014 года № 38/180-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 27 января 2015 года № 2975. Утратило силу решением Толебийского районного маслихата Южно-Казахстанской области от 27 марта 2015 года № 40/193-V
title:
  rus: Об утверждении Методики ежегодной оценки деятельности административных государственных служащих аппарата Төлебийского районного маслихата корпуса "Б"
  kaz: '"Б" корпусындағы Төлеби аудандық мәслихат аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін жыл сайынғы бағалаудың әдістемесін бекіту туралы'
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2014-12-23
approved_by:
- '166011000002'
version_date:
  kaz: 2014-12-23
  rus: 2014-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/86306/kaz/23.12.2014
  rus: https://zan.gov.kz/client/#!/doc/86306/rus/23.12.2014
