act_code: '30767'
requisite: Оңтүстік Қазақстан облысы Түлкібас аудандық мәслихатының 2006 жылғы 21 желтоқсандағы № 34/1 шешімі. Оңтүстік Қазақстан облысы Түлкібас ауданының Әділет басқармасында 2006 жылғы 22 желтоқсанда № 14-14-30 болып тіркелді
title:
  rus: 2007 жылға арналған аудандық бюджет туралы
  kaz: 2007 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-21
approved_by:
- '166012000002'
version_date:
  kaz: 2006-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/30767/kaz/21.12.2006
