act_code: '364'
requisite: Решение акима Южно-Казахстанской области от 3 сентября 1996 года № 180. Зарегистрировано Управлением юстиции Южно-Казахстанской области 10 ноября 1997 года № 15. Утратило силу решением акима Южно-Казахстанской области от 5 октября 2001 года № 211
title:
  rus: О реализации постановления Правительства Республики Казахстан от 29 декабря 1995 года № 1894 "О реализации постановления Президента Республики Казахстан от 17 апреля 1995 года № 2201"
  kaz: Қазақстан Республикасы Үкiметiтнiң 1995 жылғы 29 желтоқсандағы "Қазақстан Республикасы Президентiнiң 1995 жылғы 17 сәуірдегi № 2201 қаулысын жүзеге асыру туралы" № 1894 қаулысын iске асыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1996-09-02
approved_by:
- '166000000003'
version_date:
  kaz: 1996-09-02
  rus: 1996-09-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/364/kaz/02.09.1996
  rus: https://zan.gov.kz/client/#!/doc/364/rus/02.09.1996
