act_code: '93041'
requisite: Решение Мактааральского районного маслихата Южно-Казахстанской области от 21 июля 2015 года № 46-290-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 19 августа 2015 года № 3320. Утратило силу решением Мактааральского районного маслихата Туркестанской области от 15 июня 2022 года № 22-141-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей города районного значения, поселка, села, улицы, многоквартирного жилого дома для участия в сходе местного сообщества в Мактааральском районе
  kaz: Мақтаарал ауданында бөлек жергілікті қоғамдастық жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін аудандық маңызы бар қала, кент, ауыл, көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің санын айқындау тәртібін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-07-21
approved_by:
- '166005000002'
version_date:
  kaz: 2015-07-21
  rus: 2015-07-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/93041/kaz/21.07.2015
  rus: https://zan.gov.kz/client/#!/doc/93041/rus/21.07.2015
