act_code: '7624'
requisite: Решение акима Южно-Казахстанской области от 4 декабря 2000 года № 430. Зарегистрировано Управлением юстиции Южно-Казахстанской области 15 декабря 2000 года № 221. Утратило силу решением акима Южно-Казахстанской области от 10 января 2003 года № 4
title:
  rus: О составе комиссии по аккредитации
  kaz: Аккредитациялау жөнiндегi комиссия құрамы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-12-04
approved_by:
- '166000000003'
version_date:
  kaz: 2000-12-04
  rus: 2000-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/7624/kaz/04.12.2000
  rus: https://zan.gov.kz/client/#!/doc/7624/rus/04.12.2000
