act_code: '43552'
requisite: Оңтүстік Қазақстан облысы Созақ аудандық мәслихатының 2008 жылғы 24 желтоқсандағы N 86 шешімі. Оңтүстік Қазақстан облысы Созақ ауданының Әділет басқармасында 2009 жылғы 15 қаңтарда N 14-12-67 тіркелді
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '166010000002'
version_date:
  kaz: 2011-03-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/43552/kaz/14.03.2011
