act_code: '99489'
requisite: Решение Байдибекского районного маслихата Южно-Казахстанской области от 9 февраля 2016 года № 47/259. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 24 февраля 2016 года № 3599. Утратило силу решением Байдибекского районного маслихата Туркестанской области от 25 апреля 2019 года № 39/241
title:
  rus: О предоставлении социальной помощи на приобретение топлива специалистам государственных организаций социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Байдибекского района
  kaz: Бәйдібек ауданының ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт ветеринария ұйымдарының мамандарына отын сатып алуға әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-02-09
approved_by:
- '166003000002'
version_date:
  kaz: 2016-02-09
  rus: 2016-02-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/99489/kaz/09.02.2016
  rus: https://zan.gov.kz/client/#!/doc/99489/rus/09.02.2016
