act_code: '17001'
requisite: Решение Южно-Казахстанского областного маслихата от 11 сентября 2003 года № 30/279-II. Зарегистрировано Управлением юстиции Южно-Казахстанской области 18 сентября 2003 года № 966
title:
  rus: О внесений изменений и дополнений в решение Южно-Казахстанского областного маслихата от 27 декабря 2002 года N 26/230-II "Об областном бюджете на 2003 год", зарегистрированное в управлении юстиции Южно-Казахстанской области 9 января 2003 года N 776
  kaz: Оңтүстiк Қазақстан облыстық мәслихаттың 2002 жылғы 27 желтоқсандағы N 26/230-II "2003 жылға арналған облыстық бюджет туралы" Оңтүстiк Қазақстан облыстық әдiлет басқармасында 2003 жылғы 9 қаңтарда 776-нөмiрiмен тiркелген шешiмiне өзгерiстер мен толықтырулар енгiзу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-09-10
approved_by:
- '166000000002'
version_date:
  kaz: 2003-09-10
  rus: 2003-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/17001/kaz/10.09.2003
  rus: https://zan.gov.kz/client/#!/doc/17001/rus/10.09.2003
