act_code: '193541'
requisite: Решение Казыгуртского районного маслихата Туркестанской области от 21 февраля 2024 года № 11/73-VIII
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества в Казыгуртском районе
  kaz: Қазығұрт ауданында жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-21
approved_by:
- '166004000002'
version_date:
  kaz: 2024-02-21
  rus: 2024-02-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/193541/kaz/21.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193541/rus/21.02.2024
