act_code: '54651'
requisite: Оңтүстік Қазақстан облысы Қазығұрт ауданы әкімдігі Қазығұрт ауылдық округі әкімінің 2010 жылғы 19 тамыздағы N 63 шешімі. Оңтүстік Қазақстан облысы Қазығұрт ауданының Әділет басқармасында 2010 жылғы 20 қыркүйекте N 14-6-116 тіркелді
title:
  rus: Қазығұрт ауылы округіне қарасты Келес көшесінің атауын өзгерту жайлы
  kaz: Қазығұрт ауылы округіне қарасты Келес көшесінің атауын өзгерту жайлы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-19
approved_by:
- '166004005001'
version_date:
  kaz: 2010-08-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/54651/kaz/19.08.2010
