act_code: '132912'
requisite: Решение акима сельского округа Ж.Ералиев Жетысайского района Туркестанской области от 26 июня 2019 года № 74. Зарегистрировано Департаментом юстиции Туркестанской области 26 июня 2019 года № 5095. Утратило силу решением акима сельского округа Ж.Ералиев Жетысайского района Туркестанской области от 28 августа 2019 года № 90
title:
  rus: Об установлении ограничительных мероприятий на территории улицы Бейбитшилик в населенном пункте Абай сельского округа Ж.Ералиев Жетысайского района
  kaz: Жетісай ауданының Ж.Ералиев ауылдық округі Абай елді мекені Бейбітшілік көшесінің аумағына шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-06-26
approved_by:
- '166017002002'
version_date:
  kaz: 2019-06-26
  rus: 2019-06-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/132912/kaz/26.06.2019
  rus: https://zan.gov.kz/client/#!/doc/132912/rus/26.06.2019
