act_code: '165877'
requisite: Решение Арысского городского маслихата Туркестанской области от 18 марта 2022 года № 21/107-VІІ. Зарегистрировано в Министерстве юстиции Республики Казахстан 31 марта 2022 года № 27319
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2022 год по городу Арыс
  kaz: Арыс қаласы бойынша шетелдіктер үшін 2022 жылға арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-03-18
approved_by:
- '166016000002'
version_date:
  kaz: 2022-03-18
  rus: 2022-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/165877/kaz/18.03.2022
  rus: https://zan.gov.kz/client/#!/doc/165877/rus/18.03.2022
