act_code: '68355'
requisite: Решение Ордабасинского районного маслихата Южно-Казахстанской области от 10 октября 2012 года № 8/2. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 2 ноября 2012 года № 2123. Утратило силу решением Ордабасинского районного маслихата Южно-Казахстанской области от 20 декабря 2013 года № 26/13
title:
  rus: Об утверждении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) по Ордабасинскому району
  kaz: Ордабасы ауданы бойынша аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшері мен тәртібін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-10-10
approved_by:
- '166006000002'
version_date:
  kaz: 2012-10-10
  rus: 2012-10-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/68355/kaz/10.10.2012
  rus: https://zan.gov.kz/client/#!/doc/68355/rus/10.10.2012
