act_code: '108183'
requisite: Решение Казыгуртского районного маслихата Южно-Казахстанской области от 7 декабря 2016 года № 11/58-VI. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 12 декабря 2016 года № 3915. Утратило силу решением Казыгуртского районного маслихата Туркестанской области от 18 октября 2023 года № 6/40-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О выплате единовременной денежной компенсаций на покрытие расходов за коммунальные услуги педагогическим работникам образования, работающим в сельской местности за счет средств местного бюджета
  kaz: Ауылдық жерде жұмыс істейтін білім берудің педагог қызметкерлеріне коммуналдық қызмет көрсетулерге шығыстарды жабуға жергілікті бюджет қаражаты есебінен біржолғы ақшалай  өтемақы төлеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-07
approved_by:
- '166004000002'
version_date:
  kaz: 2016-12-07
  rus: 2016-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/108183/kaz/07.12.2016
  rus: https://zan.gov.kz/client/#!/doc/108183/rus/07.12.2016
