act_code: '222116'
requisite: Решение Кентауского городского маслихата Туркестанской области от 13 февраля 2026 года № 256
title:
  rus: О предоставлении в 2026 году подъемного пособия и бюджетного кредита на приобретение или строительство жилья специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта, агропромышленного комплекса, государственным служащим аппаратов акимов сел, сельских округов, прибывшим для работы и проживания в сельские населенные пункты города Кентау
  kaz: Кентау қаласының ауылдық елді мекендерде жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт, агроөнеркәсіптік кешен саласындағы мамандарға, ауылдар, ауылдық округтер әкімдері аппараттарының мемлекеттік қызметшілеріне 2026 жылы көтерме  жәрдемақы және тұрғын үй сатып алу немесе салу үшiн бюджеттiк кредит беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-02-13
approved_by:
- '166014000002'
version_date:
  kaz: 2026-02-13
  rus: 2026-02-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/222116/kaz/13.02.2026
  rus: https://zan.gov.kz/client/#!/doc/222116/rus/13.02.2026
