act_code: '54883'
requisite: Оңтүстік Қазақстан облысы Түлкібас ауданы әкімдігі Кемербастау ауылдық округі әкімінің 2010 жылғы 22 қыркүйектегі N 49 шешімі. Оңтүстік Қазақстан облысы Түлкібас ауданының Әділет басқармасында 2010 жылғы 14 қазанда N 14-14-130 тіркелді
title:
  rus: Көшенің атын өзгерту туралы
  kaz: Көшенің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-22
approved_by:
- '166012007001'
version_date:
  kaz: 2010-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/54883/kaz/22.09.2010
