act_code: '56143'
requisite: Оңтүстік Қазақстан облысы Мақтаарал ауданы әкімдігі Бірлік ауылдық округі әкімінің 2010 жылғы 29 қарашадағы N 34 шешімі. Оңтүстік Қазақстан облысы Мақтаарал ауданы Әділет басқармасында 2010 жылғы 27 желтоқсанда N 14-7-129 тіркелді
title:
  rus: Көше атауларын өзгерту туралы
  kaz: Көше атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-29
approved_by:
- '166005023001'
version_date:
  kaz: 2010-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/56143/kaz/29.11.2010
