act_code: '7642'
requisite: Решение акима Южно-Казахстанской области от 14 ноября 2000 года № 391. Зарегистрировано Управлением юстиции Южно-Казахстанской области 19 декабря 2000 года № 225. Утратило силу решением акима Южно-Казахстанской области от 16 июля 2004 года № 32
title:
  rus: О проведении тендера по государственной закупке автомобильной техники и мебели
  kaz: Автокөлікті және жиһазды мемлекеттік сатып алу бойынша тендер өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-11-14
approved_by:
- '166000000003'
version_date:
  kaz: 2000-11-14
  rus: 2000-11-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/7642/kaz/14.11.2000
  rus: https://zan.gov.kz/client/#!/doc/7642/rus/14.11.2000
