act_code: '58385'
requisite: Оңтүстік Қазақстан облысы Түлкібас ауданы әкімдігі Арыс ауылдық округі әкімінің 2011 жылғы 13 сәуірдегі № 19 шешімі. Оңтүстік Қазақстан облысы Түлкібас ауданының Әділет басқармасында 2011 жылғы 22 сәуірде № 14-14-150 тіркелді
title:
  rus: Көшенің атын өзгерту туралы
  kaz: Көшенің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-04-13
approved_by:
- '166012002001'
version_date:
  kaz: 2011-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/58385/kaz/13.04.2011
