act_code: '155394'
requisite: Решение акима Аккумского сельского округа акимата Толебийского района Туркестанской области от 26 апреля 2021 года № 05. Зарегистрировано Департаментом юстиции Туркестанской области 26 апреля 2021 года № 6178
title:
  rus: О признании утратившим силу решение акима Аккумского сельского округа от 18 марта 2021 года № 3 «Об установлении ограничительных мероприятий по бруцеллезу улицы Капал батыр в населенном пункте Аккум Аккумского сельского округа»
  kaz: Аққұм ауылдық округі әкімінің 2021 жылғы 18 наурыздағы № 3 «Аққұм ауылдық округі Аққұм елді мекені Қапал батыр көшесінде бруцеллез бойынша шектеу шараларын белгілеу туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-26
approved_by:
- '166011003002'
version_date:
  kaz: 2021-04-26
  rus: 2021-04-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/155394/kaz/26.04.2021
  rus: https://zan.gov.kz/client/#!/doc/155394/rus/26.04.2021
