act_code: '55698'
requisite: Оңтүстік Қазақстан облысы Шардара аудандық мәслихатының 2010 жылғы 28 қазандағы N 37-281-IV шешімі. Оңтүстік Қазақстан облысы Шардара ауданының Әділет басқармасында 2010 жылғы 3 желтоқсанда N 14-15-105 тіркелді. Күші жойылды - Шардара аудандық мәслихатының 2012 жылғы 24 ақпандағы N 2-11-V Шешімімен
title:
  rus: Ауданның елді мекендеріндегі аймақтардың шекаралары мен жер телімдері үшін ақы төлеудің базалық ставкаларына қолданылатын түзету коэффициенттерін бекіту туралы
  kaz: Ауданның елді мекендеріндегі аймақтардың шекаралары мен жер телімдері үшін ақы төлеудің базалық ставкаларына қолданылатын түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-28
approved_by:
- '166013000002'
version_date:
  kaz: 2010-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/55698/kaz/28.10.2010
