act_code: '85449'
requisite: Решение Созакского районного маслихата Южно-Казахстанской области от 24 декабря 2014 года № 221. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 30 декабря 2014 года № 2938
title:
  rus: О районном бюджете на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '166010000002'
version_date:
  kaz: 2015-12-14
  rus: 2015-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/85449/kaz/14.12.2015
  rus: https://zan.gov.kz/client/#!/doc/85449/rus/14.12.2015
caused_by:
  code: '96404'
  requisite: Решение Созакского районного маслихата Южно-Казахстанской области от 14 декабря 2015 года № 302. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 15 декабря 2015 года № 3464. Утратило силу в связи с истечением срока применения - (письмо Созакского районного маслихата Южно-Казахстанской области от 19 января 2016 года № 13)
  title:
    rus: О внесении изменений в решение Созакского районного маслихата от 24 декабря 2014 года № 221 "О районном бюджете на 2015-2017 годы"
    kaz: '"2015-2017 жылдарға арналған аудандық бюджет туралы" Созақ аудандық мәслихатының 2014 жылғы 24 желтоқсандағы № 221 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/96404/rus
