act_code: '28347'
requisite: Решение Шымкентского городского маслихата от 31 мая 2006 года N 29/260-3с. Зарегистрировано Управлением юстиции города Шымкента 8 июня 2006 года за N 14-1-32
title:
  rus: Об утверждении перечня земельных участков, предлагаемых для продажи на торгах (конкурсах, аукционах)
  kaz: Об утверждении перечня земельных участков, предлагаемых для продажи на торгах (конкурсах, аукционах)
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-05-31
approved_by:
- '166002000002'
version_date:
  rus: 2006-12-21
source:
  rus: https://zan.gov.kz/client/#!/doc/28347/rus/21.12.2006
