act_code: '44680'
requisite: Оңтүстік Қазақстан облысы Сайрам аудандық мәслихат сессиясының 2009 жылғы 27 қаңтардағы N 14-169/IV шешімі. Оңтүстік Қазақстан облысы Сайрам ауданының Әділет басқармасында 2009 жылғы 6 наурызда N 14-10-112 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Сайрам аудандық мәслихатының 2012 жылғы 21 желтоқсандағы № 13-86/V Шешімімен
title:
  rus: Сайрам ауданы бойынша біржолғы талондардың құнын белгілеу туралы
  kaz: Сайрам ауданы бойынша біржолғы талондардың құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-27
approved_by:
- '166008000002'
version_date:
  kaz: 2009-01-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/44680/kaz/27.01.2009
