act_code: '55794'
requisite: Оңтүстік Қазақстан облысы Түлкібас ауданы әкімдігі Арыс ауылдық округі әкімінің 2010 жылғы 3 желтоқсандағы N 24 шешімі. Оңтүстік Қазақстан облысы Түлкібас ауданының Әділет басқармасында 2010 жылғы 8 желтоқсанда N 14-14-135 тіркелді
title:
  rus: Көшенің атын өзгерту туралы
  kaz: Көшенің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-03
approved_by:
- '166012002001'
version_date:
  kaz: 2010-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/55794/kaz/03.12.2010
