act_code: '137695'
requisite: Решение Келесского районного маслихата Туркестанской области от 18 декабря 2019 года № 20-140-VI. Зарегистрировано Департаментом юстиции Туркестанской области 27 декабря 2019 года № 5329
title:
  rus: О районном бюджете на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-18
approved_by:
- '166018000002'
version_date:
  kaz: 2020-10-28
  rus: 2020-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/137695/kaz/28.10.2020
  rus: https://zan.gov.kz/client/#!/doc/137695/rus/28.10.2020
caused_by:
  code: '148410'
  requisite: Решение Келесского районного маслихата Туркестанской области от 28 октября 2020 года № 32-237-VI. Зарегистрировано Департаментом юстиции Туркестанской области 11 ноября 2020 года № 5877
  title:
    rus: О внесении изменений в решение Келесского районного маслихата от 18 декабря 2019 года № 20-140-VI «О районном бюджете на 2020-2022 годы»
    kaz: Келес аудандық мәслихатының 2019 жылғы 18 желтоқсандағы № 20-140-VI «2020-2022 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148410/rus
