act_code: '54628'
requisite: Оңтүстік Қазақстан облысы Түлкібас ауданы әкімдігі Машат ауылдық округі әкімінің 2010 жылғы 7 қыркүйектегі N 17 шешімі. Оңтүстік Қазақстан облысы Түлкібас ауданының Әділет басқармасында 2010 жылғы 22 қыркүйекте N 14-14-120 тіркелді
title:
  rus: Машат ауылындағы "Октябрь" көшесін Мырзабаев Тәшімнің атына өзгерту туралы
  kaz: Машат ауылындағы "Октябрь" көшесін Мырзабаев Тәшімнің атына өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-07
approved_by:
- '166012001001'
version_date:
  kaz: 2010-09-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/54628/kaz/07.09.2010
