act_code: '54016'
requisite: Оңтүстік Қазақстан облысы Сарыағаш ауданы әкімдігі Жылға ауылдық округі әкімінің 2010 жылғы 13 шілдедегі N 10 шешімі. Оңтүстік Қазақстан облысы Сарыағаш ауданының Әділет басқармасында 2010 жылғы 13 тамызда N 14-11-142 тіркелді
title:
  rus: Көшеге атау беру туралы
  kaz: Көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-13
approved_by:
- '166009018001'
version_date:
  kaz: 2010-07-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/54016/kaz/13.07.2010
