act_code: '36213'
requisite: Решение Южно-Казахстанского областного маслихата от 13 декабря 2007 года N 3/14-IV. Зарегистрировано департаментом Южно-Казахстанской области 24 декабря 2007 года за N 1968
title:
  rus: Об областном бюджете на 2008 год
  kaz: 2008 жылға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-13
approved_by:
- '166000000002'
version_date:
  kaz: 2008-01-29
  rus: 2008-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/36213/kaz/29.01.2008
  rus: https://zan.gov.kz/client/#!/doc/36213/rus/29.01.2008
caused_by:
  code: '37140'
  requisite: Решение Южно-Казахстанского областного маслихата N 4/53-IV от 29 января 2008 года. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 29 января 2008 года за N 1973. Утратило силу в связи с истечением срока применения - письмо Южно-Казахстанского областного маслихата от 2 ноября 2009 года N 802-1
  title:
    rus: О внесении изменений и дополнений в решение Южно-Казахстанского областного маслихата от 13 декабря 2007 года N 3/14-IV "Об областном бюджете на 2008 год"
    kaz: '"2008 жылға арналған облыстық бюджет туралы" Оңтүстік Қазақстан облыстық мәслихаттың 2007 жылғы 13 желтоқсандағы N 3/14-IV шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/37140/rus
