act_code: '46239'
requisite: Оңтүстік Қазақстан облысы Отырар аудандық мәслихатының 2009 жылғы 13 сәуірдегі N 18/117-IV шешімі. Оңтүстік Қазақстан облысы Отырар ауданының Әділет басқармасында 2009 жылғы 1 маусымда N 14-9-85 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Отырар аудандық мәслихатының 2012 жылғы 21 желтоқсандағы № 9/62-V Шешімімен
title:
  rus: Қызметі дүркін-дүркін сипатта болатын және базарларда тауарлар өткізу, жұмыстар орындау, қызметтер көрсету жөніндегі қызметтерді жүзеге асыратын Қазақстан Республикасының азаматтары, оралмандар, дара кәсіпкерлер мен заңды тұлғалар үшін біржолғы талон мөлшері туралы
  kaz: Қызметі дүркін-дүркін сипатта болатын және базарларда тауарлар өткізу, жұмыстар орындау, қызметтер көрсету жөніндегі қызметтерді жүзеге асыратын Қазақстан Республикасының азаматтары, оралмандар, дара кәсіпкерлер мен заңды тұлғалар үшін біржолғы талон мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-13
approved_by:
- '166007000002'
version_date:
  kaz: 2012-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/46239/kaz/06.03.2012
caused_by:
  code: '64393'
  requisite: Решение Отрарского районного маслихата Южно-Казахстанской области от 6 марта 2012 года N 2/15-V. Зарегистрировано Управлением юстиции Отрарского района Южно-Казахстанской области 4 апреля 2012 года N 14-9-158. Утратило силу решением Отрарского районного маслихата Южно-Казахстанской области от 21 декабря 2012 года № 9/62-V
  title:
    rus: О внесении изменений в решение Отрарского районного маслихта от 13 апреля 2009 года № 18/117-ІV "О размере стоимости разового талона для физических лиц, индивидуальных предпринимателей и юридических лиц, деятельность которых носит эпизодический характер и осуществляющих деятельность по реализации товаров, выполнению работ, оказанию услуг на рынках"
    kaz: Отырар аудандық мәслихаттың 2009 жылғы 13 сәуірдегі № 18/117-ІV "Қызметі дүркін-дүркін сипатта болатын және базарларда тауарлар өткізу, жұмыстар орындау, қызметтер көрсету жөніндегі қызметтерді жүзеге асыратын жеке тұлғалар, дара кәсіпкерлер мен заңды тұлғалар үшін біржолғы талон құнының мөлшері туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/64393/rus
