act_code: '49647'
requisite: Оңтүстік Қазақстан облысы Шардара аудандық мәслихатының 2009 жылғы 23 желтоқсандағы N 25-181-IV шешімі. Оңтүстік Қазақстан облысы Шардара ауданының Әділет басқармасында 2009 жылғы 31 желтоқсанда N 14-15-84 тіркелді
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '166013000002'
version_date:
  kaz: 2010-01-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/49647/kaz/22.01.2010
caused_by:
  code: '50551'
  requisite: Оңтүстік Қазақстан облысы Шардара аудандық мәслихатының 2010 жылғы 22 қаңтардағы N 27-198-IV шешімі. Оңтүстік Қазақстан облысы Шардара ауданының Әділет басқармасында 2010 жылғы 4 ақпанда N 14-15-87 тіркелді
  title:
    rus: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Шардара аудандық мәслихатының 2009 жылғы 23 желтоқсандағы N 25-181-IV шешіміне өзгерістер мен толықтырулар енгізу туралы'
    kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Шардара аудандық мәслихатының 2009 жылғы 23 желтоқсандағы N 25-181-IV шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/50551/rus
