act_code: '49647'
requisite: Оңтүстік Қазақстан облысы Шардара аудандық мәслихатының 2009 жылғы 23 желтоқсандағы N 25-181-IV шешімі. Оңтүстік Қазақстан облысы Шардара ауданының Әділет басқармасында 2009 жылғы 31 желтоқсанда N 14-15-84 тіркелді
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '166013000002'
version_date:
  kaz: 2010-05-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/49647/kaz/26.05.2010
caused_by:
  code: '53065'
  requisite: Оңтүстік Қазақстан облысы Шардара аудандық мәслихатының 2010 жылғы 26 мамырдағы N 31-231-IV шешімі. Оңтүстік Қазақстан облысы Шардара ауданының Әділет басқармасында 2010 жылғы 11 маусымда N 14-15-94 тіркелді
  title:
    rus: Шардара аудандық мәслихатының 2009 жылғы 23 желтоқсандағы N 25-181-IV "2010-2012 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
    kaz: Шардара аудандық мәслихатының 2009 жылғы 23 желтоқсандағы N 25-181-IV "2010-2012 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/53065/rus
