act_code: '194721'
requisite: Решение Сауранского районного маслихата Туркестанской области от 19 марта 2024 года № 140. Зарегистрировано в Департаменте юстиции Туркестанской области 26 марта 2024 года № 6488-13. Утратило силу решением Сауранского районного маслихата Туркестанской области от 15 апреля 2026 года № 328 (вводится в действие с 01.01.2026)
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога в районе Сауран
  kaz: Сауран ауданында бөлшек салықтың арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-19
approved_by:
- '166019000002'
version_date:
  kaz: 2024-03-19
  rus: 2024-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/194721/kaz/19.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194721/rus/19.03.2024
