act_code: '85580'
requisite: Решение Ордабасинского районного маслихата Южно-Казахстанской области от 24 декабря 2014 года № 39/1. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 31 декабря 2014 года № 2941
title:
  rus: О районном бюджете на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '166006000002'
version_date:
  kaz: 2015-01-26
  rus: 2015-01-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/85580/kaz/26.01.2015
  rus: https://zan.gov.kz/client/#!/doc/85580/rus/26.01.2015
caused_by:
  code: '86681'
  requisite: Решение Ордабасинского районного маслихата Южно-Казахстанской области от 26 января 2015 года № 40/1. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 30 января 2015 года № 2993. Утратило силу в связи с истечением срока применения - (письмо Ордабасинского районного маслихата Южно-Казахстанской области от 5 февраля 2016 года № 17)
  title:
    rus: О внесении изменений и дополнений в решение Ордабасинского районного маслихата от 24 декабря 2014 года № 39/1 "О районном бюджете на 2015-2017 годы"
    kaz: Ордабасы аудандық мәслихатының 2014 жылғы 24 желтоқсандағы № 39/1 "2015-2017 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/86681/rus
