act_code: '58828'
requisite: Оңтүстік Қазақстан облысы Созақ аудандық мәслихатының 2011 жылғы 29 сәуірдегі N 268 шешімі. Оңтүстік Қазақстан облысы Созақ ауданының Әділет басқармасында 2011 жылғы 17 мамырда N 14-12-121 тіркелді
title:
  rus: Созақ ауданының ауылдық елді мекендеріне 2011 жылы жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына көтерме жәрдемақы және тұрғын үй сатып алу үшін әлеуметтік қолдауды ұсыну туралы
  kaz: Созақ ауданының ауылдық елді мекендеріне 2011 жылы жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына көтерме жәрдемақы және тұрғын үй сатып алу үшін әлеуметтік қолдауды ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-04-29
approved_by:
- '166010000002'
version_date:
  kaz: 2012-04-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/58828/kaz/02.04.2012
