act_code: '38487'
requisite: Оңтүстік Қазақстан облысы Мақтаарал ауданы Қарақай ауылдық оқругі әкімінің 2007 жылғы 12 желтоқсандағы N 38 шешімі. Оңтүстік Қазақстан облысы Мақтаарал ауданының Әділет басқармасында 2007 жылғы 19 желтоқсанда N 14-7-52 тіркелді
title:
  rus: Қарақай елді мекеніндегі М.Горький көшесінің атауын өзгерту туралы
  kaz: Қарақай елді мекеніндегі М.Горький көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-12
approved_by:
- '166005002001'
version_date:
  kaz: 2007-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/38487/kaz/12.12.2007
