act_code: '203551'
requisite: Решение акима сельского округа Дермене акимата города Арысь Туркестанской области от 4 декабря 2024 года № 53
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитутты белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-04
approved_by:
- '166016003002'
version_date:
  kaz: 2024-12-04
  rus: 2024-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/203551/kaz/04.12.2024
  rus: https://zan.gov.kz/client/#!/doc/203551/rus/04.12.2024
