act_code: '64342'
requisite: Решение Ордабасинского районного маслихата Южно-Казахстанской области от 12 марта 2012 года N 2/6. Зарегистрировано Управлением юстиции Ордабасинского района 4 апреля 2012 года N 14-8-125. Утратило силу в связи с истечением срока применения - (письмо Ордабасинского районного маслихата Южно-Казахстанской области от 31 января 2013 года № 32)
title:
  rus: О предоставлении в 2012 году подъемного пособия и социальной поддержки для приобретения жилья специалистам здравоохранения, образования, социального обеспечения, культуры и спорта, прибывшим для работы и проживания в сельские населенные пункты Ордабасинского района
  kaz: Ордабасы ауданының ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына 2012 жылы көтерме жәрдемақы және тұрғын үй сатып алу үшін әлеуметтік қолдауды ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-03-12
approved_by:
- '166006000002'
version_date:
  kaz: 2012-03-12
  rus: 2012-03-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/64342/kaz/12.03.2012
  rus: https://zan.gov.kz/client/#!/doc/64342/rus/12.03.2012
