act_code: '61298'
requisite: Решение маслихата Созакского района Южно-Казахстанской области от 21 октября 2011 года N 289. Зарегистрировано Управлением юстиции Созакского района Южно-Казахстанской области 15 ноября 2011 года N 14-12-129. Утратило силу решением Созакского районного маслихата Южно-Казахстанской области от 24 декабря 2014 года № 232
title:
  rus: О корректировке базовых ставок земельного налога
  kaz: Жер салығының базалық ставкаларын түзету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-10-21
approved_by:
- '166010000002'
version_date:
  kaz: 2013-06-25
  rus: 2013-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/61298/kaz/25.06.2013
  rus: https://zan.gov.kz/client/#!/doc/61298/rus/25.06.2013
caused_by:
  code: '73562'
  requisite: Решение Созакского районного маслихата Южно-Казахстанской области от 25 июня 2013 года № 110. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 19 июля 2013 года № 2328. Утратило силу решением Созакского районного маслихата Южно-Казахстанской области от 24 декабря 2014 года № 232
  title:
    rus: О внесении изменений в решение Созакского районного маслихата от 21 октября 2011 года № 289 "О корректировке базовых ставок земельного налога"
    kaz: Созақ аудандық мәслихатының 2011 жылғы 21 қазандағы № 289 "Жер салығының базалық ставкаларын түзету туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/73562/rus
