act_code: '76813'
requisite: Решение от 10.12.2013 №21/184-V, Маслихат Южно-Казахстанской области. Утратило силу решением областного маслихата Южно-Казахстанской области от 25 июня 2015 года № 38/322-V
title:
  rus: Об утверждении схемы и порядка перевозки в общеобразовательные школы детей, проживающих в отдаленных населенных пунктах Южно-Казахстанской области
  kaz: Оңтүстік Қазақстан облысының шалғайдағы елдi мекендерінде тұратын балаларды жалпы бiлiм беретiн мектептерге тасымалдаудың схемасы мен тәртiбiн бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-10
approved_by:
- '166000000002'
version_date:
  kaz: 2013-12-10
  rus: 2013-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/76813/kaz/10.12.2013
  rus: https://zan.gov.kz/client/#!/doc/76813/rus/10.12.2013
