act_code: '108514'
requisite: Решение Тюлькубасского районного маслихата Южно-Казахстанской области от 21 декабря 2016 года № 8/1-06. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 26 декабря 2016 года № 3928
title:
  rus: О районном бюджете на 2017-2019 годы
  kaz: 2017-2019 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-21
approved_by:
- '166012000002'
version_date:
  kaz: 2017-11-03
  rus: 2017-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/108514/kaz/03.11.2017
  rus: https://zan.gov.kz/client/#!/doc/108514/rus/03.11.2017
caused_by:
  code: '115852'
  requisite: Решение Тюлькубасского районного маслихата Южно-Казахстанской области от 3 ноября 2017 года № 19/1-06. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 9 ноября 2017 года № 4254
  title:
    rus: О внесении изменений в решение Тюлькубасского районного маслихата от 21 декабря 2016 года № 8/1-06 «О районном бюджете на 2017-2019 годы»
    kaz: Түлкібас аудандық мәслихатының 2016 жылғы 21 желтоқсандағы № 8/1-06 «2017-2019 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/115852/rus
