act_code: '51702'
requisite: Оңтүстік Қазақстан облысы Отырар ауданы әкімдігі Шәуілдір ауылы округі әкімінің 2010 жылғы 6 сәуірдегі N 61 шешімі. Оңтүстік Қазақстан облысы Отырар ауданының Әділет басқармасында 2010 жылғы 14 сәуірде N 14-9-105 тіркелді
title:
  rus: Көшеге ат қою туралы
  kaz: Көшеге ат қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-06
approved_by:
- '166007014001'
version_date:
  kaz: 2010-04-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/51702/kaz/06.04.2010
