act_code: '49064'
requisite: Оңтүстік Қазақстан облысы Түлкібас аудандық мәслихатының 2009 жылғы 4 қарашадағы N 24/5-04 Шешімі. Оңтүстік Қазақстан облысы Түлкібас ауданының Әділет басқармасында 2009 жылғы 4 желтоқсанда N 14-14-92 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Түлкібас аудандық мәслихатының 2012 жылғы 11 маусымдағы N 5/11-05 Шешімімен
title:
  rus: Түлкібас ауданының елді мекендерде иттерді және мысықтарды күтіп-ұстау және оларды серуендету туралы Қағидасын бекіту туралы
  kaz: Түлкібас ауданының елді мекендерде иттерді және мысықтарды күтіп-ұстау және оларды серуендету туралы Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-11-04
approved_by:
- '166012000002'
version_date:
  kaz: 2009-11-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/49064/kaz/04.11.2009
