act_code: '182796'
requisite: Решение акима Рыскуловского сельского округа Тюлькубасского района Туркестанской области от 8 июня 2023 года № 19
title:
  rus: Об утверждении квалификационных требований для административных государственных должностей
  kaz: Мемлекеттік әкімшілік лауазымдарға арналған біліктілік талаптарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-06-08
approved_by:
- '166012011002'
version_date:
  kaz: 2023-06-08
  rus: 2023-06-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/182796/kaz/08.06.2023
  rus: https://zan.gov.kz/client/#!/doc/182796/rus/08.06.2023
