act_code: '184911'
requisite: Решение Туркестанского городского маслихата Туркестанской области от 11 августа 2023 года № 5/26-VIII
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов, тарифов для населения на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по городу Туркестан
  kaz: Түркістан қаласы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын, халық үшін тұрмыстық қатты қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-08-11
approved_by:
- '166015000002'
version_date:
  kaz: 2023-08-11
  rus: 2023-08-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/184911/kaz/11.08.2023
  rus: https://zan.gov.kz/client/#!/doc/184911/rus/11.08.2023
