act_code: '5971'
requisite: Решение акима Южно-Казахстанской области от 1 сентября 1999 года № 46. Зарегистрировано Управлением юстиции Южно-Казахстанской области 27 апреля 2000 года № 150. Утратило силу решением акима Южно-Казахстанской области от 19 апреля 2001 года № 149
title:
  rus: О создании комиссии по развитию малого предпринимательства при акиме области
  kaz: Облыс әкiмiнiң жанындағы шағын кәсiпкерлiктi дамыту жөнiндегi комиссиясын құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-08-31
approved_by:
- '166000000003'
version_date:
  kaz: 1999-08-31
  rus: 1999-08-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/5971/kaz/31.08.1999
  rus: https://zan.gov.kz/client/#!/doc/5971/rus/31.08.1999
