act_code: '52146'
requisite: Оңтүстік Қазақстан облысы Созақ ауданы әкімдігі Таукент поселкесі әкімінің 2010 жылғы 30 наурыздағы N 10 шешімі. Оңтүстік Қазақстан облысы Созақ ауданының Әділет басқармасында 2010 жылғы 30 сәуірде N 14-12-94 тіркелді
title:
  rus: Сыздықбек Тойшыұлына көше атын беру туралы
  kaz: Сыздықбек Тойшыұлына көше атын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-30
approved_by:
- '166010004001'
version_date:
  kaz: 2010-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/52146/kaz/30.03.2010
