act_code: '45479'
requisite: Оңтүстік Қазақстан облысы Түлкібас аудандық мәслихатының 2009 жылғы 31 наурыздағы N 17/9-04 шешімі. Оңтүстік Қазақстан облысы Түлкібас ауданының Әділет басқармасында 2009 жылғы 27 сәуірде N 14-14-76 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Түлкібас аудандық мәслихатының 2012 жылғы 21 желтоқсандағы № 11/7-05 Шешімімен
title:
  rus: Аудан көлемінде базар аумағындағы дүңгіршектердегі, стационарлық үй-жайлардағы (оқшауланған блоктардағы) сауданы қоспағанда, базарларда тауарлар өткізу, жұмыстар орындау, қызметтер көрсету жөніндегі қызметтерді жүзеге асыратын Қазақстан Республикасының азаматтары мен оралмандар, дара кәсіпкерлер мен заңды тұлғалар үшін бір жолғы талон құны туралы
  kaz: Аудан көлемінде базар аумағындағы дүңгіршектердегі, стационарлық үй-жайлардағы (оқшауланған блоктардағы) сауданы қоспағанда, базарларда тауарлар өткізу, жұмыстар орындау, қызметтер көрсету жөніндегі қызметтерді жүзеге асыратын Қазақстан Республикасының азаматтары мен оралмандар, дара кәсіпкерлер мен заңды тұлғалар үшін бір жолғы талон құны туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-03-31
approved_by:
- '166012000002'
version_date:
  kaz: 2009-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/45479/kaz/31.03.2009
