act_code: '168032'
requisite: Решение Келесского районного маслихата Туркестанской области от 11 мая 2022 года № 13-115-VII. Утратило силу решением Келесского районного маслихата Туркестанской области от 22 сентября 2023 года № 5-54-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества сельского округа Бирлесу Келесского района
  kaz: Келес ауданы Бірлесу ауылдық округінің бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауылдар тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-05-11
approved_by:
- '166018000002'
version_date:
  kaz: 2022-05-11
  rus: 2022-05-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/168032/kaz/11.05.2022
  rus: https://zan.gov.kz/client/#!/doc/168032/rus/11.05.2022
