act_code: '45039'
requisite: Решение Шымкентского городского маслихата Южно-Казахстанской области от 20 февраля 2009 года N 18/184-4с. Зарегистрировано Управлением юстиции города Шымкента Южно-Казахстанской области 24 марта 2009 года N 14-1-90. Утратило силу решением Шымкентского городского маслихата Южно-Казахстанской области от 20 февраля 2009 года № 18/184-4c
title:
  rus: О стоимости разовых талонов
  kaz: Біржолғы талондар құны туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-20
approved_by:
- '166002000002'
version_date:
  kaz: 2009-02-20
  rus: 2009-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/45039/kaz/20.02.2009
  rus: https://zan.gov.kz/client/#!/doc/45039/rus/20.02.2009
