act_code: '214759'
requisite: Решение Толебийского районного маслихата Туркестанской области от 24 сентября 2025 года № 28/171-VIII
title:
  rus: Об утверждении плана по управлению пастбищами и их использованию по Толебийском районе на 2025-2029 годы
  kaz: Төлеби ауданының жайылымдарды басқару және оларды пайдалану жөніндегі 2025-2029 жылдарға арналған жоспары туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2025-09-24
approved_by:
- '166011000002'
version_date:
  kaz: 2025-09-24
  rus: 2025-09-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/214759/kaz/24.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214759/rus/24.09.2025
