act_code: '43394'
requisite: Оңтүстік Қазақстан облысы Төлеби аудандық мәслихатының 2008 жылғы 26 желтоксандағы N 10/70-IV шешімі. Оңтүстік Қазақстан облысы Төлеби ауданының Әділет басқармасында 2009 жылғы 12 қантарда N 14-13-46 тіркелді
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-26
approved_by:
- '166011000002'
version_date:
  kaz: 2009-07-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/43394/kaz/13.07.2009
caused_by:
  code: '47051'
  requisite: Оңтүстік Қазақстан облысы Төлеби аудандық мәслихатының 2009 жылғы 13 шілдедегі N 17/127-IV шешімі. Оңтүстік Қазақстан облысы Төлеби ауданының Әділет басқармасында 2009 жылғы 27 шілдеде N 14-13-57 тіркелді
  title:
    rus: '"2009 жылға арналған аудандық бюджет туралы" Төлеби аудандық мәслихатының 2008 жылғы 26 желтоқсандағы N 10/70-IV шешіміне өзгерістер мен толықтырулар енгізу туралы'
    kaz: '"2009 жылға арналған аудандық бюджет туралы" Төлеби аудандық мәслихатының 2008 жылғы 26 желтоқсандағы N 10/70-IV шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/47051/rus
