act_code: '43394'
requisite: Оңтүстік Қазақстан облысы Төлеби аудандық мәслихатының 2008 жылғы 26 желтоксандағы N 10/70-IV шешімі. Оңтүстік Қазақстан облысы Төлеби ауданының Әділет басқармасында 2009 жылғы 12 қантарда N 14-13-46 тіркелді
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-26
approved_by:
- '166011000002'
version_date:
  kaz: 2009-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/43394/kaz/29.04.2009
caused_by:
  code: '45666'
  requisite: Оңтүстік Қазақстан облысы Төлеби аудандық мәслихатының 2009 жылғы 29 сәуірдегі N 15/113-IV шешімі. Оңтүстік Қазақстан облысы Төлеби ауданының Әділет басқармасында 2009 жылғы 8 мамырда N 14-13-54 тіркелді
  title:
    rus: '"2009 жылға арналған аудандық бюджет туралы" Төлеби аудандық мәслихатының 2008 жылғы 26 желтоқсандағы N 10/70-IV шешіміне өзгерістер мен толықтырулар енгізу туралы'
    kaz: '"2009 жылға арналған аудандық бюджет туралы" Төлеби аудандық мәслихатының 2008 жылғы 26 желтоқсандағы N 10/70-IV шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/45666/rus
