act_code: '8557'
requisite: Решение акима Южно-Казахстанской области от 2 апреля 2001 года № 133. Зарегистрировано Управлением юстиции Южно-Казахстанской области 10 апреля 2001 года № 263
title:
  rus: Об очередном призыве граждан на срочную военную службу в апреле-июне 2001 года
  kaz: Азаматтарды 2001 жылғы сәуiр-маусымында мерзiмдi әскери қызметке кезектi шақыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-04-01
approved_by:
- '166000000003'
version_date:
  kaz: 2001-04-01
  rus: 2001-04-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/8557/kaz/01.04.2001
  rus: https://zan.gov.kz/client/#!/doc/8557/rus/01.04.2001
