act_code: '164168'
requisite: Решение Сауранского районного маслихата Туркестанской области от 28 января 2022 года № 90. Утратило силу решением Сауранского районного маслихата Туркестанской области от 27 ноября 2025 года № 290 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» аппарата маслихата района Сауран
  kaz: «Б» корпусы Сауран аудандық мәслихат аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-01-28
approved_by:
- '166019000002'
version_date:
  kaz: 2023-08-28
  rus: 2023-08-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/164168/kaz/28.08.2023
  rus: https://zan.gov.kz/client/#!/doc/164168/rus/28.08.2023
caused_by:
  code: '185702'
  requisite: Решение Сауранского районного маслихата Туркестанской области от 28 августа 2023 года № 54. Утратило силу решением Сауранского районного маслихата Туркестанской области от 27 ноября 2025 года № 290 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнений в решение маслихата района Сауран от 28 января 2022 года № 90 «Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» аппарата маслихата района Сауран»
    kaz: Сауран аудандық мәслихатының 2022 жылғы 28 қаңтардағы № 90 «Б» корпусы Сауран аудандық мәслихат аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/185702/rus
