act_code: '85566'
requisite: Решение Туркестанского городского маслихата Южно-Казахстанской области от 19 декабря 2014 года № 38/202-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 31 декабря 2014 года № 2945
title:
  rus: О городском бюджете на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-19
approved_by:
- '166015000002'
version_date:
  kaz: 2015-12-11
  rus: 2015-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/85566/kaz/11.12.2015
  rus: https://zan.gov.kz/client/#!/doc/85566/rus/11.12.2015
caused_by:
  code: '96401'
  requisite: Решение Туркестанского городского маслихата Южно-Казахстанской области от 11 декабря 2015 года № 50/277-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 14 декабря 2015 года № 3460. Утратило силу в связи с истечением срока применения - (письмо Туркестанского городского маслихата Южно-Казахстанской области от 31 декабря 2015 года № 01-10/315)
  title:
    rus: О внесении изменений в решение Туркестанского городского маслихата от 19 декабря 2014 года № 38/202-V "О городском бюджете на 2015-2017 годы"
    kaz: '"2015-2017 жылдарға арналған қалалық бюджет туралы" Түркістан қалалық мәслихатының 2014 жылғы 19 желтоқсандағы № 38/202-V шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/96401/rus
