act_code: '126091'
requisite: Решение акима Казыгуртского района Туркестанской области от 5 ноября 2018 года № 7. Зарегистрировано Департаментом юстиции Туркестанской области 6 ноября 2018 года № 4772
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-05
approved_by:
- '166004000003'
version_date:
  kaz: 2018-11-05
  rus: 2018-11-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/126091/kaz/05.11.2018
  rus: https://zan.gov.kz/client/#!/doc/126091/rus/05.11.2018
