act_code: '43179'
requisite: Оңтүстік Қазақстан облысы Түлкібас аудандық мәслихатының 2008 жылғы 25 желтоқсандағы N 14/2-04 шешімі. Оңтүстік Қазақстан облысы Түлкібас ауданының Әділет басқармасында 2009 жылғы 6 қаңтарда N 14-14-61 тіркелді
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-25
approved_by:
- '166012000002'
version_date:
  kaz: 2009-02-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/43179/kaz/16.02.2009
caused_by:
  code: '44268'
  requisite: Оңтүстік Қазақстан облысы Түлкібас аудандық мәслихатының 2009 жылғы 16 ақпандағы N 16/2-04 шешімі. Оңтүстік Қазақстан облысы Түлкібас ауданының Әділет басқармасында 2009 жылғы 18 ақпанда N 14-14-67 тіркелді
  title:
    rus: Аудандық мәслихаттың 2008 жылғы 25 желтоқсандағы "2009 жылға арналған аудандық бюджет туралы" N 14//2-04 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Аудандық мәслихаттың 2008 жылғы 25 желтоқсандағы "2009 жылға арналған аудандық бюджет туралы" N 14//2-04 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/44268/rus
