act_code: '140204'
requisite: Решение акима сельского округа Жамбыл акимата Байдибекского района Туркестанской области от 24 февраля 2020 года № 5. Зарегистрировано Департаментом юстиции Туркестанской области 25 февраля 2020 года № 5441
title:
  rus: О присвоении наименовании улицам
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-02-24
approved_by:
- '166003008002'
version_date:
  kaz: 2020-02-24
  rus: 2020-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/140204/kaz/24.02.2020
  rus: https://zan.gov.kz/client/#!/doc/140204/rus/24.02.2020
