act_code: '18571'
requisite: Решение акима Южно-Казахстанской области от 4 февраля 2004 года № 3. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 10 февраля 2004 года № 1098
title:
  rus: Об утверждении внутренних Правил кредитования сельхозтоваропроизводителей Южно-Казахстанской области для проведения весенне-полевых и уборочных работ 2004 года
  kaz: Оңтүстік Қазақстан облысының ауыл шаруашылығы тауар өндірушілеріне 2004 жылғы көктемгі егіс және егін жинау жүмыстарын жүргізу үшін кредит берудің ішкі ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2004-02-04
approved_by:
- '166000000003'
version_date:
  kaz: 2004-02-04
  rus: 2004-02-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/18571/kaz/04.02.2004
  rus: https://zan.gov.kz/client/#!/doc/18571/rus/04.02.2004
