act_code: '35449'
requisite: Решение Шымкентского городского маслихата Южно-Казахстанской области N 4/22-4с от 22 октября 2007 года. Зарегистрировано управлением юстиции города Шымкента Южно-Казахстанской области 29 октября 2007 года за N 14-1-62. Утратило силу - решением Шымкентского городского маслихата Южно-Казахстанской области от 20 февраля 2009 года N 18/184-4c
title:
  rus: О стоимости разовых талонов
  kaz: Біржолғы талондар құны туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-10-22
approved_by:
- '166002000002'
version_date:
  kaz: 2007-10-22
  rus: 2007-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/35449/kaz/22.10.2007
  rus: https://zan.gov.kz/client/#!/doc/35449/rus/22.10.2007
