act_code: '147428'
requisite: Решение Тюлькубасского районного маслихата Туркестанской области от 29 сентября 2020 года № 60/2-06. Зарегистрировано Департаментом юстиции Туркестанской области 13 октября 2020 года № 5839. Утратило силу решением Тюлькубасского районного маслихата Туркестанской области от 22 июня 2023 года № 4/11-08 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов, тарифов на сбор, вывоз и захоронение твердых бытовых отходов по Тюлькубасскому району
  kaz: Түлкібас ауданы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын және тұрмыстық қатты қалдықтарын жинау, әкету және көму тарифтерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-29
approved_by:
- '166012000002'
version_date:
  kaz: 2020-09-29
  rus: 2020-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/147428/kaz/29.09.2020
  rus: https://zan.gov.kz/client/#!/doc/147428/rus/29.09.2020
