act_code: '61499'
requisite: Решение акима Ордабасинского района Южно-Казахстанской области от 14 ноября 2011 года № 30. Зарегистрировано Управлением юстиции Ордабасинского района Южно-Казахстанской области 21 ноября 2011 года № 14-8-114. Утратило силу решением акима Ордабасынского района Южно-Казахстанской области от 23 февраля 2015 года № 5
title:
  rus: Об образовании избирательных участков на территории Ордабасынского района
  kaz: Ордабасы ауданы аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-14
approved_by:
- '166006000001'
version_date:
  kaz: 2011-11-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/61499/kaz/14.11.2011
