act_code: '76125'
requisite: Решение Туркестанского городского маслихата Южно-Казахстанской области от 20 декабря 2013 года № 22/126-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 25 декабря 2013 года № 2452. Утратило силу решением Туркестанского городского маслихата Южно-Казахстанской области от 16 октября 2014 года № 35/193-V
title:
  rus: О льготном проезде на общественном транспорте (кроме такси) обучающихся и воспитанников всех организаций образования очной формы обучения
  kaz: Барлық білім беру ұйымдарының күндізгі оқу нысаны бойынша білім алушылары мен тәрбиеленушілерінің қоғамдық көлікте (таксиден басқа) жеңілдікпен жол жүрулері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-20
approved_by:
- '166015000002'
version_date:
  kaz: 2013-12-20
  rus: 2013-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/76125/kaz/20.12.2013
  rus: https://zan.gov.kz/client/#!/doc/76125/rus/20.12.2013
