act_code: '204899'
requisite: Решение Кентауского городского маслихата Туркестанской области от 25 декабря 2024 года № 165
title:
  rus: О бюджете села Карнак города Кентау на 2025-2027 годы
  kaz: Кентау қаласының Қарнақ ауылының 2025-2027 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '166014000002'
version_date:
  kaz: 2025-09-24
  rus: 2025-09-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/204899/kaz/24.09.2025
  rus: https://zan.gov.kz/client/#!/doc/204899/rus/24.09.2025
caused_by:
  code: '214755'
  requisite: Решение Кентауского городского маслихата Туркестанской области от 24 сентября 2025 года № 217
  title:
    rus: О внесении изменений в решение Кентауского городского маслихата от 25 декабря 2024 года № 165 «О бюджете села Карнак города Кентау на 2025-2027 годы»
    kaz: Кентау қалалық мәслихатының 2024 жылғы 25 желтоқсандағы № 165 «Кентау қаласының  Қарнақ  ауылының 2025-2027 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214755/rus
