act_code: '85935'
requisite: Решение от 19.12.2014 № 38/206-V, Маслихат г. Туркестана. Утратило силу решением Туркестанского городского маслихата Южно-Казахстанской области от 15 октября 2015 года № 46/266-V
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов, тарифов на сбор, вывоз, захоронение и утилизацию коммунальных отходов по городу Туркестан
  kaz: Түркістан қаласы бойынша коммуналдық қалдықтардың пайда болу және жинақталу нормаларын, коммуналдық қалдықтарды жинау, әкету, көму және кәдеге жарату тарифтерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-19
approved_by:
- '166015000002'
version_date:
  kaz: 2014-12-19
  rus: 2014-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/85935/kaz/19.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85935/rus/19.12.2014
