act_code: '53079'
requisite: Оңтүстік Қазақстан облысы Отырар ауданы әкімдігі Шәуілдір ауылы округі әкімінің 2010 жылғы 24 мамырдағы N 85 шешімі. Оңтүстік Қазақстан облысы Отырар ауданының Әділет басқармасында 2010 жылғы 14 маусымда N 14-9-112 тіркелді
title:
  rus: Көшеге ат қою туралы
  kaz: Көшеге ат қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-05-24
approved_by:
- '166007014001'
version_date:
  kaz: 2010-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/53079/kaz/24.05.2010
