act_code: '190100'
requisite: Решение Туркестанского областного маслихата от 13 декабря 2023 года № 7/85-VIII
title:
  rus: Об областном бюджете на 2024-2026 годы
  kaz: 2024-2026 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-13
approved_by:
- '166000000002'
version_date:
  kaz: 2024-10-24
  rus: 2024-10-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/190100/kaz/24.10.2024
  rus: https://zan.gov.kz/client/#!/doc/190100/rus/24.10.2024
caused_by:
  code: '202015'
  requisite: Решение Туркестанского областного маслихата от 24 октября 2024 года № 13/175-VIII
  title:
    rus: О внесении изменений в решение Туркестанского областного маслихата от 13 декабря 2023 года № 7/85-VІII «Об областном бюджете на 2024-2026 годы»
    kaz: «2024-2026 жылдарға арналған облыстық бюджет туралы» Түркістан облыстық мәслихатының 2023 жылғы 13 желтоқсандағы № 7/85-VІII шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/202015/rus
