act_code: '92753'
requisite: Решение Байдибекского районного маслихата Южно-Казахстанской области от 16 июля 2015 года № 38/214. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 3 августа 2015 года № 3304. Утратило силу решением Байдибекского районного маслихата Южно-Казахстанской области от 20 января 2016 года № 45/254
title:
  rus: Об утверждении Методики ежегодной оценки деятельности административных государственных служащих аппарата Байдибекского районного маслихата корпуса «Б»
  kaz: «Б» корпусындағы Бәйдібек аудандық мәслихат аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін жыл сайынғы бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-07-16
approved_by:
- '166003000002'
version_date:
  kaz: 2015-10-28
  rus: 2015-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/92753/kaz/28.10.2015
  rus: https://zan.gov.kz/client/#!/doc/92753/rus/28.10.2015
caused_by:
  code: '95846'
  requisite: Решение Байдибекского районного маслихата Южно-Казахстанской области от 28 октября 2015 года № 41/229. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 20 ноября 2015 года № 3434. Утратило силу решением Байдибекского районного маслихата Южно-Казахстанской области от 20 января 2016 года № 45/254
  title:
    rus: О внесении изменения в решение Байдибекского районного маслихата от 16 июля 2015 года № 38/214 «Об утверждении Методики ежегодной оценки деятельности административных государственных служащих аппарата Байдибекского районного маслихата корпуса «Б»»
    kaz: ««Б» корпусындағы Бәйдібек аудандық мәслихат аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін жыл сайынғы бағалаудың әдістемесін бекіту туралы» Бәйдібек аудандық мәслихатының 2015 жылғы 16 шілдедегі № 38/214 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/95846/rus
