act_code: '119011'
requisite: Решение Туркестанского городского маслихата Южно-Казахстанской области от 9 февраля 2018 года № 27/145-VI. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 23 февраля 2018 года № 4461. Утратило силу решением Туркестанского городского маслихата Туркестанской области от 11 августа 2023 года № 5/27-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов, тарифов на сбор, вывоз, утилизацию, переработку и захоронение твердых бытовых отходов по городу Туркестан
  kaz: Түркістан қаласы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын, тұрмыстық қатты қалдықтарды жинауға, әкетуге, кәдеге жаратуға, қайта өңдеуге және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-02-09
approved_by:
- '166015000002'
version_date:
  kaz: 2019-10-09
  rus: 2019-10-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/119011/kaz/09.10.2019
  rus: https://zan.gov.kz/client/#!/doc/119011/rus/09.10.2019
caused_by:
  code: '135473'
  requisite: Решение Туркестанского городского маслихата Туркестанской области от 9 октября 2019 года № 56/276-VI. Зарегистрировано Департаментом юстиции Туркестанской области 17 октября 2019 года № 5223. Утратило силу решением Туркестанского городского маслихата Туркестанской области от 11 августа 2023 года № 5/27-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Туркестанского городского маслихата от 9 февраля 2018 года № 27/145-VI «Об утверждении норм образования и накопления коммунальных отходов, тарифов на сбор, вывоз, утилизацию, переработку и захоронение твердых бытовых отходов по городу Туркестан»
    kaz: Түркістан қалалық мәслихатының 2018 жылғы 9 ақпандағы № 27/145-VI «Түркістан қаласы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын, тұрмыстық қатты қалдықтарды жинауға, әкетуге, кәдеге жаратуға, қайта өңдеуге және көмуге арналған тарифтерді бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/135473/rus
