act_code: '79845'
requisite: Решение Тюлькубасского районного маслихата Южно-Казахстанской области от 15 апреля 2014 года № 27/8-05. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 14 мая 2014 года № 2657
title:
  rus: Об утверждении положения о награждении Почетной грамотой Тюлькубасского района
  kaz: Түлкібас ауданының Құрмет грамотасымен наградтау туралы ережені бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-15
approved_by:
- '166012000002'
version_date:
  kaz: 2024-08-07
  rus: 2024-08-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/79845/kaz/07.08.2024
  rus: https://zan.gov.kz/client/#!/doc/79845/rus/07.08.2024
caused_by:
  code: '199574'
  requisite: Решение Тюлькубасского районного маслихата Туркестанской области от 7 августа 2024 года № 22/4-08. Зарегистрировано в Департаменте юстиции Туркестанской области 8 августа 2024 года № 6572-13
  title:
    rus: О внесении изменении в решение Тюлькубасского районного маслихата от 15 апреля 2014 года № 27/8-05 «Об утверждении положения о награждении Почетной грамотой Тюлькубасского района»
    kaz: Аудандық мәслихаттың 2014 жылғы 15 сәуірдегі № 27/8-05 «Түлкібас ауданының Құрмет грамотасымен наградтау туралы ережені бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/199574/rus
