act_code: '79845'
requisite: Решение Тюлькубасского районного маслихата Южно-Казахстанской области от 15 апреля 2014 года № 27/8-05. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 14 мая 2014 года № 2657
title:
  rus: Об утверждении положения о награждении Почетной грамотой Тюлькубасского района
  kaz: Түлкібас ауданының Құрмет грамотасымен наградтау туралы ережені бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-15
approved_by:
- '166012000002'
version_date:
  kaz: 2014-04-15
  rus: 2014-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/79845/kaz/15.04.2014
  rus: https://zan.gov.kz/client/#!/doc/79845/rus/15.04.2014
