act_code: '31683'
requisite: Оңтүстік Қазақстан облыстық мәслихатының 2007 жылғы 30 қаңтардағы N 29/331-III шешімі. Оңтүстік Қазақстан облысының әділет департаментінде 2007 жылғы 2 ақпанда N 1949 тіркелді
title:
  rus: Оңтүстік Қазақстан облысы бойынша қоршаған ортаны ластағаны үшін 2007 жылға төленетін төлемнің ставкаларын белгілеу туралы
  kaz: Оңтүстік Қазақстан облысы бойынша қоршаған ортаны ластағаны үшін 2007 жылға төленетін төлемнің ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-01-30
approved_by:
- '166000000002'
version_date:
  kaz: 2007-01-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/31683/kaz/30.01.2007
