act_code: '28673'
requisite: Шымкент қалалық мәслихатының 2006 жылғы 31 мамырдағы N 29/259-3с шешімі. Шымкент қаласының Әділет басқармасында 2006 жылғы 20 маусымда N 14-1-34 тіркелді. Күші жойылды - Шымкент қалалық мәслихатының 2010 жылғы 31 наурыздағы N 33/307-4с Шешімімен
title:
  rus: Шымкент қаласының тұрғын үй қорын, өзге де ғимараттар мен тұрғын үй-азаматтық мақсаттағы құрылыстарды, инженерлiк коммуникацияларды күтiп-ұстаудың аумақтық Қағидасын бекіту туралы
  kaz: Шымкент қаласының тұрғын үй қорын, өзге де ғимараттар мен тұрғын үй-азаматтық мақсаттағы құрылыстарды, инженерлiк коммуникацияларды күтiп-ұстаудың аумақтық Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-05-31
approved_by:
- '166002000002'
version_date:
  kaz: 2006-05-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/28673/kaz/31.05.2006
