act_code: '140663'
requisite: Решение Толебийского районного маслихата Туркестанской области от 4 марта 2020 года № 50/275-VI. Зарегистрировано Департаментом юстиции Туркестанской области 26 марта 2020 года № 5519. Утратило силу решением Толебийского районного маслихата Туркестанской области от 14 августа 2024 года № 15/85-VIII (вводится в действие по истечении десяти календарынх дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Толебийского района
  kaz: Төлеби ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекеленген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-03-04
approved_by:
- '166011000002'
version_date:
  kaz: 2020-06-23
  rus: 2020-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/140663/kaz/23.06.2020
  rus: https://zan.gov.kz/client/#!/doc/140663/rus/23.06.2020
caused_by:
  code: '145337'
  requisite: Решение Толебийского районного маслихата Туркестанской области от 23 июня 2020 года № 53/297-VI. Зарегистрировано Департаментом юстиции Туркестанской области 5 августа 2020 года № 5741. Утратило силу решением Толебийского районного маслихата Туркестанской области от 14 августа 2024 года № 15/85-VIII (вводится в действие по истечении десяти календарынх дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Толебийского районного маслихата от 4 марта 2020 года № 50/275-VI «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Толебийского района»
    kaz: Төлеби аудандық мәслихатының 2020 жылғы 4 наурыздағы № 50/275-VІ «Әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидасын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/145337/rus
