act_code: '79107'
requisite: Решение Байдибекского районного маслихата Южно-Казахстанской области от 4 апреля 2014 года № 23/121. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 23 апреля 2014 года № 2621. Утратило силу решением Байдибекского районного маслихата Туркестанской области от 28 августа 2020 года № 55/333 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) по Байдибекскому району
  kaz: Бәйдібек ауданы бойынша аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегiн көрсетудiң мөлшерi мен тәртiбiн бекiту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-04
approved_by:
- '166003000002'
version_date:
  kaz: 2014-04-04
  rus: 2014-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/79107/kaz/04.04.2014
  rus: https://zan.gov.kz/client/#!/doc/79107/rus/04.04.2014
