act_code: '52370'
requisite: Оңтүстік Қазақстан облысы Түлкібас ауданы әкімдігі Келтемашат ауылдық округі әкімінің 2010 жылғы 16 сәуірдегі N 21 шешімі. Оңтүстік Қазақстан облысы Түлкібас ауданының Әділет басқармасында 2010 жылғы 12 мамырда N 14-14-107 тіркелді
title:
  rus: Жиынбай ауылындағы аты жоқ көшеге Мыңбаев Айнабектің атын беру туралы
  kaz: Жиынбай ауылындағы аты жоқ көшеге Мыңбаев Айнабектің атын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-16
approved_by:
- '166012012001'
version_date:
  kaz: 2010-04-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/52370/kaz/16.04.2010
