act_code: '43353'
requisite: Оңтүстік Қазақстан облысы Отырар аудандық мәслихатының 2008 жылғы 25 желтоқсандағы N 15/89-IV шешімі. Оңтүстік Қазақстан облысы Отырар ауданының Әділет басқармасында 2009 жылғы 9 қаңтарда N 14-9-70 тіркелді
title:
  rus: 2009 жылға арналған аудан бюджеті туралы
  kaz: 2009 жылға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-25
approved_by:
- '166007000002'
version_date:
  kaz: 2009-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/43353/kaz/20.02.2009
caused_by:
  code: '45015'
  requisite: Оңтүстік Қазақстан облысы Отырар аудандық мәслихатының 2009 жылғы 20 ақпандағы N 17/106-IV шешімі. Оңтүстік Қазақстан облысы Отырар ауданының Әділет басқармасында 2009 жылғы 24 ақпанда N 14-9-73 тіркелді
  title:
    rus: Отырар аудандық мәслихатының 2008 жылғы 25 желтоқсандағы N 15/89-ІV "2009  жылға арналған аудан бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Отырар аудандық мәслихатының 2008 жылғы 25 желтоқсандағы N 15/89-ІV "2009  жылға арналған аудан бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/45015/rus
