act_code: '413'
requisite: Решение акима Южно-Казахстанской области от 3 ноября 1997 года № 218. Зарегистрировано Управлением юстиции Южно-Казахстанской области 4 февраля 1998 года № 22. Утратило силу решением акима Южно-Казахстанской области от 27 апреля 2000 года № 25
title:
  rus: О реализации постановления Правительства Республики Казахстан от 31 июля 1997 года № 1195 "Об утверждении Порядка и условий лицензирования производства этилового спирта и алкогольной продукции, хранения и реализации этилового спирта, а также хранения и оптовой реализации алкогольной продукции (кроме пива)"
  kaz: '"Арақ-шарап өнiмдерiн және этил спиртiн өндiрудi лицензиялаудың, этил спиртiн сақтау және сату, сондай-ақ арақ-шарап өнiмдерiн /сырадан басқа/ сақтау және көтерме сауда шарттары мен тәртiбiн бекiту туралы" Қазақстан Республикасы Үкiметiнiң 1997 жылғы 31 шiлдедегi № 1195 қаулысын жүзеге асыру туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 1997-11-03
approved_by:
- '166000000003'
version_date:
  kaz: 1997-11-03
  rus: 1997-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/413/kaz/03.11.1997
  rus: https://zan.gov.kz/client/#!/doc/413/rus/03.11.1997
