act_code: '120403'
requisite: Решение Южно-Казахстанского областного маслихата от 20 марта 2018 года № 21/250-VI. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 10 апреля 2018 года № 4512. Утратило силу решением Туркестанского областного маслихата от 28 апреля 2023 года № 2/20-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса "Б" аппарата Южно-Казахстанского областного маслихата
  kaz: Оңтүстік Қазақстан облыстық мәслихаты аппаратының "Б" корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2018-03-20
approved_by:
- '166000000002'
version_date:
  kaz: 2018-12-12
  rus: 2018-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/120403/kaz/12.12.2018
  rus: https://zan.gov.kz/client/#!/doc/120403/rus/12.12.2018
caused_by:
  code: '128401'
  requisite: Решение Туркестанского областного маслихата от 12 декабря 2018 года № 33/360-VI. Зарегистрировано Департаментом юстиции Туркестанской области 9 января 2019 года № 4873. Утратило силу решением Туркестанского областного маслихата от 28 апреля 2023 года № 2/20-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Южно-Казахстанского областного маслихата от 20 марта 2018 года № 21/250-VІ «Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» аппарата Южно-Казахстанского областного маслихата»
    kaz: Оңтүстік Қазақстан облыстық мәслихатының 2018 жылғы 20 наурыздағы № 21/250-VІ «Оңтүстік Қазақстан облыстық мәслихаты аппаратының «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/128401/rus
