act_code: '140463'
requisite: Решение Шардаринского районного маслихата Туркестанской области от 3 марта 2020 года № 54-339-VI. Зарегистрировано Департаментом юстиции Туркестанской области 18 марта 2020 года № 5505. Утратило силу решением Шардаринского районного маслихата Туркестанской области от 20 сентября 2023 года № 8-45-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-03-03
approved_by:
- '166013000002'
version_date:
  kaz: 2023-05-12
  rus: 2023-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/140463/kaz/12.05.2023
  rus: https://zan.gov.kz/client/#!/doc/140463/rus/12.05.2023
caused_by:
  code: '182127'
  requisite: Решение Шардаринского районного маслихата Туркестанской области от 12 мая 2023 года № 3-17-VIII. Зарегистрировано Департаментом юстиции Туркестанской области 24 мая 2023 года № 6294-13. Утратило силу решением Шардаринского районного маслихата Туркестанской области от 20 сентября 2023 года № 8-45-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Шардаринского районного маслихата от 3 марта 2020 года № 54-339-VI «Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Шардара аудандық мәслихатының 2020 жылғы 3 наурыздағы № 54-339-VI «Әлеуметтiк көмек көрсетудің, оның мөлшерлерiн белгiлеу және мұқтаж азаматтардың жекелеген санаттарының тiзбесiн айқындау Қағидаларын бекiту туралы» шешiмiне өзгерістер енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/182127/rus
