act_code: '68238'
requisite: Решение Толебийского районного маслихата Южно-Казахстанской области от 28 сентября 2012 года № 9/49-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 25 октября 2012 года № 2116. Утратило силу решением Толебийского районного маслихата Южно-Казахстанской области от 23 января 2014 года № 27/129-V
title:
  rus: Об утверждении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) по Толебийскому району
  kaz: Төлеби ауданы бойынша аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшері мен тәртібін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-09-28
approved_by:
- '166011000002'
version_date:
  kaz: 2013-12-12
  rus: 2013-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/68238/kaz/12.12.2013
  rus: https://zan.gov.kz/client/#!/doc/68238/rus/12.12.2013
caused_by:
  code: '76284'
  requisite: Решение Толебийского районного маслихата Южно-Казахстанской области от 12 декабря 2013 года № 25/113-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 25 декабря 2013 года № 2454. Утратило силу решением Толебийского районного маслихата Южно-Казахстанской области от 23 января 2014 года № 27/129-V
  title:
    rus: О внесении изменений в решение Толебийского районного маслихата от 28 сентября 2012 года № 9/49-V "Об утверждении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) Толебийскому району"
    kaz: Төлеби аудандық мәслихатының 2012 жылғы 28 қыркүйектегі № 9/49-V "Төлеби ауданы бойынша аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшері мен тәртібін бекіту туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/76284/rus
