act_code: '11967'
requisite: Решение акима Южно-Казахстанской области от 11 апреля 2002 года № 30. Зарегистрировано Управлением юстиции Южно-Казахстанской области 25 апреля 2002 года № 553
title:
  rus: О создании комиссии
  kaz: Комиссия құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-04-10
approved_by:
- '166000000003'
version_date:
  kaz: 2002-04-10
  rus: 2002-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/11967/kaz/10.04.2002
  rus: https://zan.gov.kz/client/#!/doc/11967/rus/10.04.2002
