act_code: '151220'
requisite: Решение Кентауского городского маслихата Туркестанской области от 21 декабря 2020 года № 408. Зарегистрировано Департаментом юстиции Туркестанской области 31 декабря 2020 года № 5992
title:
  rus: О городском бюджете на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-21
approved_by:
- '166014000002'
version_date:
  kaz: 2021-08-04
  rus: 2021-08-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/151220/kaz/04.08.2021
  rus: https://zan.gov.kz/client/#!/doc/151220/rus/04.08.2021
caused_by:
  code: '157757'
  requisite: Решение Кентауского городского маслихата Туркестанской области от 4 августа 2021 года № 65. Зарегистрировано в Министерстве юстиции Республики Казахстан 10 августа 2021 года № 23925
  title:
    rus: О внесении изменений в решение Кентауского городского маслихата от 21 декабря 2020 года № 408 «О городском бюджете на 2021-2023 годы»
    kaz: Кентау қалалық мәслихатының 2020 жылғы 21 желтоқсандағы № 408 «2021-2023 жылдарға арналған қалалық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/157757/rus
