act_code: '167747'
requisite: Решение акима Кайнарбулакского сельского округа Сайрамского района Туркестанской области от 12 мая 2022 года № 45. Зарегистрировано в Министерстве юстиции Республики Казахстан 17 мая 2022 года № 28077
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-05-12
approved_by:
- '166008008002'
version_date:
  kaz: 2022-05-12
  rus: 2022-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/167747/kaz/12.05.2022
  rus: https://zan.gov.kz/client/#!/doc/167747/rus/12.05.2022
