act_code: '49447'
requisite: Оңтүстік Қазақстан облысы Шардара ауданы әкімдігі Қауысбек Тұрысбеков ауылдық округі әкімінің 2009 жылғы 25 қарашадағы N 26 шешімі. Оңтүстік Қазақстан облысы Шардара ауданының Әділет басқармасында 2009 жылғы 24 желтоқсанда N 14-15-83 тіркелді
title:
  rus: Көшелерге ат қою туралы
  kaz: Көшелерге ат қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-11-25
approved_by:
- '166013002001'
version_date:
  kaz: 2009-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/49447/kaz/25.11.2009
