act_code: '62281'
requisite: Решение Тюлькубасского районного маслихата Южно-Казахстанской области от 21 декабря 2011 года N 48/1-04. Зарегистрировано Управлением юстиции Тюлькубасского района Южно-Казахстанской области 28 декабря 2011 года N 14-14-163
title:
  rus: О районном бюджете на 2012-2014 годы
  kaz: 2012-2014 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-21
approved_by:
- '166012000002'
version_date:
  kaz: 2012-04-13
  rus: 2012-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/62281/kaz/13.04.2012
  rus: https://zan.gov.kz/client/#!/doc/62281/rus/13.04.2012
caused_by:
  code: '64758'
  requisite: Решение Тюлькубасского районного маслихата Южно-Казахстанской области от 13 апреля 2012 года № 4/1-05. Зарегистрировано Управлением юстиции Тюлькубасского района Южно-Казахстанской области 18 апреля 2012 года № 14-14-169
  title:
    rus: О внесении изменений в решение Тюлькубасского районного маслихата от 21 декабря 2011 года № 48/1-04 "О районном бюджете на 2012-2014 годы"
    kaz: Түлкібас аудандық мәслихатының 2011 жылғы 21 желтоқсандағы № 48/1-04 "2012-2014 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер  енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/64758/rus
