act_code: '56235'
requisite: Оңтүстік Қазақстан облысы Төлеби аудандық мәслихатының 2010 жылғы 22 желтоқсандағы N 34/218-IV шешімі. Оңтүстік Қазақстан облысы Әділет департаментінде 2010 жылғы 29 желтоқсанда N 14-13-80 тіркелді
title:
  rus: 2011-2013 жылдарға арналған аудандық бюджет туралы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-22
approved_by:
- '166011000002'
version_date:
  kaz: 2011-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/56235/kaz/29.03.2011
caused_by:
  code: '58141'
  requisite: Оңтүстік Қазақстан облысы Төлеби аудандық мәслихатының 2011 жылғы 29 наурыздағы N 36/253-IV шешімі. Оңтүстік Қазақстан облысы Төлеби ауданының Әділет басқармасында 2011 жылғы 8 сәуірде N 14-13-89 тіркелді
  title:
    rus: '"2011-2013 жылдарға арналған аудандық бюджет туралы" Төлеби аудандық мәслихатының 2010 жылғы 22 желтоқсандағы N 34/218-IV шешіміне өзгерістер енгізу туралы'
    kaz: '"2011-2013 жылдарға арналған аудандық бюджет туралы" Төлеби аудандық мәслихатының 2010 жылғы 22 желтоқсандағы N 34/218-IV шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/58141/rus
