act_code: '127945'
requisite: Решение Сайрамского районного маслихата Туркестанской области от 27 декабря 2018 года № 33-219/VI. Зарегистрировано Департаментом юстиции Туркестанской области 28 декабря 2018 года № 4869. Утратило силу решением Сайрамского районного маслихата Туркестанской области от 6 марта 2019 года № 38-244/VI
title:
  rus: О предоставлении социальной помощи на оплату коммунальных услуг и приобретение топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Сайрамского района
  kaz: Сайрам ауданының ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебінен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алуға әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-27
approved_by:
- '166008000002'
version_date:
  kaz: 2018-12-27
  rus: 2018-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/127945/kaz/27.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127945/rus/27.12.2018
