act_code: '128851'
requisite: Решение Сайрамского районного маслихата Туркестанской области от 8 января 2019 года № 36-232/VI. Зарегистрировано Департаментом юстиции Туркестанской области 9 января 2019 года № 4872
title:
  rus: О бюджетах сельских округов Сайрамского района на 2019-2021 годы
  kaz: Сайрам ауданы ауылдық округтерінің 2019-2021 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-08
approved_by:
- '166008000002'
version_date:
  kaz: 2019-03-29
  rus: 2019-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/128851/kaz/29.03.2019
  rus: https://zan.gov.kz/client/#!/doc/128851/rus/29.03.2019
caused_by:
  code: '130629'
  requisite: Решение Сайрамского районного маслихата Туркестанской области от 29 марта 2019 года № 40-255/VI. Зарегистрировано Департаментом юстиции Туркестанской области 11 апреля 2019 года № 4973
  title:
    rus: О внесении изменений в решение Сайрамского районного маслихата от 8 января 2019 года № 36-232/VI «О бюджетах сельских округов Сайрамского района на 2019-2021 годы»
    kaz: Сайрам аудандық мәслихатының 2019 жылғы 8 қаңтардағы № 36-232/VI «Сайрам ауданы ауылдық округтерінің 2019-2021 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130629/rus
