act_code: '37260'
requisite: Оңтүстік Қазақстан облысы Түркістан қалалық мәслихатының 2007 жылғы 24 желтоқсандағы N 3/19-IV шешімі. Оңтүстік Қазақстан облысы Түркістан қаласының Әділет басқармасында 2008 жылғы 26 қаңтарда N 14-4-45 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Түркістан қалалық мәслихатының 2009 жылғы 30 маусымдағы N 19/156-IV шешімімен
title:
  rus: Түркістан қаласы бойынша аз қамтамасыз етілген азаматтарға тұрғын үй көмегін көрсету Қағидасын бекіту туралы
  kaz: Түркістан қаласы бойынша аз қамтамасыз етілген азаматтарға тұрғын үй көмегін көрсету Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-24
approved_by:
- '166015000002'
version_date:
  kaz: 2007-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/37260/kaz/24.12.2007
