act_code: '139877'
requisite: Решение акима сельского округа Куркелес Сарыагашского района Туркестанской области от 26 февраля 2020 года № 16. Зарегистрировано Департаментом юстиции Туркестанской области 26 февраля 2020 года № 5447
title:
  rus: О присвоении наименовании улицам
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-02-26
approved_by:
- '166009022002'
version_date:
  kaz: 2022-04-28
  rus: 2022-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/139877/kaz/28.04.2022
  rus: https://zan.gov.kz/client/#!/doc/139877/rus/28.04.2022
caused_by:
  code: '167872'
  requisite: Решение акима сельского округа Куркелес Сарыагашского района Туркестанской области от 28 апреля 2022 года № 83. Зарегистрировано в Министерстве юстиции Республики Казахстан 18 мая 2022 года № 28100
  title:
    rus: О внесении изменений в решение акима сельского округа Куркелес Сарыагашского района от 26 февраля 2020 года № 16 «О присвоении наименовании улицам»
    kaz: Сарыағаш ауданы Құркелес ауылдық округі әкімінің 2020 жылғы 26 ақпандағы № 16 «Көшелерге атау беру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/167872/rus
