act_code: '104791'
requisite: Решение Туркестанского городского маслихата Южно-Казахстанской области от 29 июня 2016 года № 5/20-VI. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 13 июля 2016 года № 3777. Утратило силу решением Туркестанского городского маслихата Южно-Казахстанской области от 21 февраля 2017 года № 13/77-VI
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов, тарифов на сбор, вывоз, утилизацию, переработку и захоронение твердых бытовых отходов по городу Туркестан
  kaz: Түркістан қаласы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын, тұрмыстық қатты қалдықтарды жинауға, әкетуге, кәдеге жаратуға, қайта өңдеуге және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-06-29
approved_by:
- '166015000002'
version_date:
  kaz: 2016-06-29
  rus: 2016-06-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/104791/kaz/29.06.2016
  rus: https://zan.gov.kz/client/#!/doc/104791/rus/29.06.2016
