act_code: '49290'
requisite: Решение областного маслихата Южно-Казахстанской области N 23/248-IV от 11 декабря 2009 года. Зарегистрировано Департаментом юстиции Южно-Казахстанской области от 20 декабря 2009 года за N 2018
title:
  rus: Об областном бюджете на 2010-2012 годы
  kaz: 2010-2012 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-11
approved_by:
- '166000000002'
version_date:
  kaz: 2010-09-24
  rus: 2010-09-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/49290/kaz/24.09.2010
  rus: https://zan.gov.kz/client/#!/doc/49290/rus/24.09.2010
caused_by:
  code: '54686'
  requisite: Решение областного маслихата Южно-Казахстанской области N 33/330-IV от 24 сентября 2010 года. Зарегистрировано Департаментом юстиции Южно-Казахстанской области от 5 октября 2010 года за N 2037
  title:
    rus: О внесении изменений в решение Южно-Казахстанского областного маслихата от 11 декабря 2009 года N 23/248-IV "Об областном бюджете на 2010-2012 годы"
    kaz: '"2010-2012 жылдарға арналған облыстық бюджет туралы" Оңтүстік Қазақстан облыстық мәслихатының 2009 жылғы 11 желтоқсандағы N 23/248-IV шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/54686/rus
