act_code: '227825'
requisite: Решение Сауранского районного маслихата Туркестанской области от 14 июля 2026 года № 362
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-07-14
approved_by:
- '166019000002'
version_date:
  kaz: 2026-07-14
  rus: 2026-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/227825/kaz/14.07.2026
  rus: https://zan.gov.kz/client/#!/doc/227825/rus/14.07.2026
