act_code: '176229'
requisite: Решение Сайрамского районного маслихата Туркестанской области от 27 декабря 2022 года № 25-148/VII
title:
  rus: О бюджетах сельских округов Сайрамского района на 2023-2025 годы
  kaz: Сайрам ауданы ауылдық округтерінің 2023-2025 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '166008000002'
version_date:
  kaz: 2023-12-20
  rus: 2023-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/176229/kaz/20.12.2023
  rus: https://zan.gov.kz/client/#!/doc/176229/rus/20.12.2023
caused_by:
  code: '191263'
  requisite: Решение Сайрамского районного маслихата Туркестанской области от 20 декабря 2023 года № 9-63/VIII
  title:
    rus: О внесении изменений в решение Сайрамского районного маслихата от 27 декабря 2022 года № 25-148/VII «О бюджетах сельских округов Сайрамского района на 2023-2025 годы»
    kaz: Сайрам аудандық мәслихатының 2022 жылғы 27 желтоқсандағы № 25-148/VII «Сайрам ауданы ауылдық округтерінің 2023-2025 жылдарға арналған бюджеттері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/191263/rus
