act_code: '79679'
requisite: Решение Казыгуртского районного маслихата Южно-Казахстанской области от 11 апреля 2014 года № 30/201-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 12 мая 2014 года № 2654. Утратило силу решением Казыгуртского районного маслихата Южно-Казахстанской области от 8 июля 2016 года № 6/32-VI
title:
  rus: Об утверждении регламента Казыгуртского районного маслихата
  kaz: Қазығұрт аудандық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-11
approved_by:
- '166004000002'
version_date:
  kaz: 2015-03-30
  rus: 2015-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/79679/kaz/30.03.2015
  rus: https://zan.gov.kz/client/#!/doc/79679/rus/30.03.2015
caused_by:
  code: '88834'
  requisite: Решение Казыгуртского районного маслихата Южно-Казахстанской области от 30 марта 2015 года № 42/291-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 16 апреля 2015 года № 3134. Утратило силу решением Казыгуртского районного маслихата Южно-Казахстанской области от 8 июля 2016 года № 6/32-VI
  title:
    rus: О внесении изменения в решение Казыгуртского районного маслихата от 11 апреля 2014 года № 30/201-V "Об утверждении регламента Казыгуртского районного маслихата"
    kaz: '"Қазығұрт аудандық мәслихатының регламентін бекіту туралы" Қазығұрт аудандық мәслихатының 2014 жылғы 11 сәуірдегі № 30/201-V шешіміне өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/88834/rus
