act_code: '85564'
requisite: Решение акима города Жетысай Мактааральского района Южно-Казахстанской области от 15 декабря 2014 года № 506. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 24 декабря 2014 года № 2927
title:
  rus: Об установлении ограничительных мероприятий на улице Байботаева города Жетысай Мактаральского района
  kaz: Мақтарал ауданы Жетісай қаласы Байботаев көшесінде шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-15
approved_by:
- '166005001001'
version_date:
  kaz: 2014-12-15
  rus: 2014-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/85564/kaz/15.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85564/rus/15.12.2014
