act_code: '52077'
requisite: Оңтүстік Қазақстан облысы Сайрам аудандық мәслихат сессиясының 2010 жылғы 20 сәуірдегі N 31-290/IV шешімі. Оңтүстік Қазақстан облысы Сайрам ауданының Әділет басқармасында 2010 жылғы 23 сәуірде N 14-10-138 тіркелді
title:
  rus: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Сайрам аудандық мәслихатының 2009 жылғы 23 желтоқсандағы N 25-249/IV шешіміне өзгертулер енгізу туралы'
  kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Сайрам аудандық мәслихатының 2009 жылғы 23 желтоқсандағы N 25-249/IV шешіміне өзгертулер енгізу туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-20
approved_by:
- '166008000002'
version_date:
  kaz: 2011-05-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/52077/kaz/25.05.2011
