act_code: '150913'
requisite: Решение Толебийского районного маслихата Туркестанской области от 21 декабря 2020 года № 59/322-VI. Зарегистрировано Департаментом юстиции Туркестанской области 30 декабря 2020 года № 5982
title:
  rus: О районном бюджете на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-21
approved_by:
- '166011000002'
version_date:
  kaz: 2021-08-09
  rus: 2021-08-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/150913/kaz/09.08.2021
  rus: https://zan.gov.kz/client/#!/doc/150913/rus/09.08.2021
caused_by:
  code: '157983'
  requisite: Решение Толебийского районного маслихата Туркестанской области от 9 августа 2021 года № 7/41-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 19 августа 2021 года № 24036
  title:
    rus: О внесении изменений в решение Толебийского районного маслихата от 21 декабря 2020 года № 59/322-VI «О районном бюджете на 2021-2023 годы»
    kaz: Төлеби аудандық мәслихатының 2020 жылғы 21 желтоқсандағы № 59/322-VI «2021-2023 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/157983/rus
