act_code: '53259'
requisite: Оңтүстік Қазақстан облысы Қазығұрт ауданы әкімдігі Қазығұрт ауылдық округі әкімінің 2010 жылғы 5 мамырдағы N 34 шешімі. Оңтүстік Қазақстан облысы Қазығұрт ауданының Әділет басқармасында 2010 жылғы 11 маусымда N 14-6-102 тіркелді
title:
  rus: '"Болашақ" мөлтек ауданында орналасқан көшеге атау беру жайлы'
  kaz: '"Болашақ" мөлтек ауданында орналасқан көшеге атау беру жайлы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-05-05
approved_by:
- '166004005001'
version_date:
  kaz: 2010-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/53259/kaz/05.05.2010
