act_code: '16238'
requisite: Оңтүстік Қазақстан облысы Түркістан қалалық мәслихатының 2003 жылғы 10 маусымдағы N 29-129-II шешімі. Оңтүстік Қазақстан облысының Әділет басқармасында 2003 жылғы 11 шілдеде N 924 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Түркістан қалалық мәслихатының 2007 жылғы 24 желтоқсандағы N 3/33-IV Шешімімен
title:
  rus: Халықтық аз қамтамасыз етілген азаматтарына тұрғын үйді ұстау мен коммуналдық қызмет көрсетуге ақы төлеу тұрғын үй көмегін беру тәртібі туралы
  kaz: Халықтық аз қамтамасыз етілген азаматтарына тұрғын үйді ұстау мен коммуналдық қызмет көрсетуге ақы төлеу тұрғын үй көмегін беру тәртібі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-06-09
approved_by:
- '166015000002'
version_date:
  kaz: 2003-06-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/16238/kaz/09.06.2003
