act_code: '186622'
requisite: Решение акима сельского округа Дермене акимата города Арысь Туркестанской области от 26 сентября 2023 года № 83
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитутты белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-09-26
approved_by:
- '166016003002'
version_date:
  kaz: 2023-09-26
  rus: 2023-09-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/186622/kaz/26.09.2023
  rus: https://zan.gov.kz/client/#!/doc/186622/rus/26.09.2023
