act_code: '60825'
requisite: Решение маслихата Байдибекского района Южно-Казахстанской области от 27 сентября 2011 года N 47/278. Зарегистрировано Управлением юстиции Байдибекского района Южно-Казахстанской области 14 октября 2011 года N 14-5-117. Утратило силу - решением Байдибекского районного маслихата Южно-Казахстанской области от 8 июня 2012 года № 4/22
title:
  rus: Об утверждении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) по району Байдибек
  kaz: Бәйдібек ауданы бойынша аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшері мен тәртібін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-09-27
approved_by:
- '166003000002'
version_date:
  kaz: 2011-09-27
  rus: 2011-09-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/60825/kaz/27.09.2011
  rus: https://zan.gov.kz/client/#!/doc/60825/rus/27.09.2011
