act_code: '52322'
requisite: Оңтүстік Қазақстан облысы Шардара аудандық мәслихатының 2010 жылғы 18 наурыздағы N 29-208-IV шешімі. Оңтүстік Қазақстан облысы Шардара ауданының Әділет басқармасында 2010 жылғы 7 мамырда N 14-15-91 тіркелді. Күші жойылды - Шардара аудандық мәслихатының 2012 жылғы 17 сәуірдегі N 4-29-V Шешімімен
title:
  rus: Тұрғын үй көмегін көрсетудің мөлшерін және тәртібін бекіту туралы
  kaz: Тұрғын үй көмегін көрсетудің мөлшерін және тәртібін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-18
approved_by:
- '166013000002'
version_date:
  kaz: 2011-10-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/52322/kaz/04.10.2011
caused_by:
  code: '60805'
  requisite: Оңтүстік Қазақстан облысы Шардара аудандық мәслихатының 2011 жылғы 4 қазандағы N 47-354-IV шешімі. Оңтүстік Қазақстан облысы Шардара ауданының Әділет басқармасында 2011 жылғы 14 қазанда N 14-15-122 тіркелді. Күші жойылды - Шардара аудандық мәслихатының 2012 жылғы 17 сәуірдегі N 4-29-V Шешімімен
  title:
    rus: Шардара аудандық мәслихатының 2010 жылғы 18 наурыздағы № 29-208-ІV "Тұрғын үй көмегін көрсетудің мөлшері және тәртібін бекіту туралы" шешіміне толықтырулар енгізу туралы
    kaz: Шардара аудандық мәслихатының 2010 жылғы 18 наурыздағы № 29-208-ІV "Тұрғын үй көмегін көрсетудің мөлшері және тәртібін бекіту туралы" шешіміне толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/60805/rus
