act_code: '468'
requisite: Решение акима Южно-Казахстанской области от 19 марта 1998 года № 135. Зарегистрировано Управлением юстиции Южно-Казахстанской области 13 апреля 1998 года № 25
title:
  rus: Об охране нерестующей рыбы на рыбохозяйственных водоемах области
  kaz: Облыстық балық өсiрiлетiн су қоймаларындағы уылдырық шашатын балықты қорғау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-03-19
approved_by:
- '166000000003'
version_date:
  kaz: 1998-03-19
  rus: 1998-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/468/kaz/19.03.1998
  rus: https://zan.gov.kz/client/#!/doc/468/rus/19.03.1998
