act_code: '186590'
requisite: Решение Келесского районного маслихата Туркестанской области от 22 сентября 2023 года № 5-60-VIII. Зарегистрировано в Департаменте юстиции Туркестанской области 27 сентября 2023 года № 6356-13. Утратило силу решением Келесского районного маслихата Туркестанской области от 5 марта 2025 года № 23-177-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-09-22
approved_by:
- '166018000002'
version_date:
  kaz: 2024-02-19
  rus: 2024-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/186590/kaz/19.02.2024
  rus: https://zan.gov.kz/client/#!/doc/186590/rus/19.02.2024
caused_by:
  code: '193543'
  requisite: Решение Келесского районного маслихата Туркестанской области от 19 февраля 2024 года № 11-91-VIII. Зарегистрировано в Департаменте юстиции Туркестанской области 21 февраля 2024 года № 6463-13. Утратило силу решением Келесского районного маслихата Туркестанской области от 5 марта 2025 года № 23-177-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Келесского районного маслихата от 22 сентября 2023 года № 5-60-VІІІ «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Келес аудандық мәслихатының 2023 жылғы 22 қыркүйектегі № 5-60-VIІІ «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/193543/rus
