act_code: '219156'
requisite: Решение Туркестанского областного маслихата от 15 декабря 2025 года № 20/269-VIII
title:
  rus: Об объемах трансфертов общего характера между областным бюджетом и районными (городов областного значения) бюджетами на 2026-2028 годы
  kaz: Облыстық бюджет және аудандық (облыстық маңызы бар қалалар) бюджеттердің арасындағы 2026-2028 жылдарға арналған жалпы сипаттағы трансферттердің көлемі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-15
approved_by:
- '166000000002'
version_date:
  kaz: 2025-12-15
  rus: 2025-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/219156/kaz/15.12.2025
  rus: https://zan.gov.kz/client/#!/doc/219156/rus/15.12.2025
