act_code: '105267'
requisite: Решение Казыгуртского районного маслихата Южно-Казахстанской области от 8 июля 2016 года № 6/22-VI. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 2 августа 2016 года № 3817. Утратило силу решением Казыгуртского районного маслихата Южно-Казахстанской области от 9 апреля 2018 года № 28/188-VI
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения
  kaz: Пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерге жер салығының базалық мөлшерлемесін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-07-08
approved_by:
- '166004000002'
version_date:
  kaz: 2016-07-08
  rus: 2016-07-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/105267/kaz/08.07.2016
  rus: https://zan.gov.kz/client/#!/doc/105267/rus/08.07.2016
