act_code: '136496'
requisite: Решение Сайрамского районного маслихата Туркестанской области от 21 ноября 2019 года № 47-294/VI. Зарегистрировано Департаментом юстиции Туркестанской области 28 ноября 2019 года № 5268
title:
  rus: Об утверждении проекта (схемы) зонирования земель Сайрамского района
  kaz: Сайрам ауданының жерлерді аймақтарға бөлу жобасын (схемасын) бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-11-21
approved_by:
- '166008000002'
version_date:
  kaz: 2023-09-27
  rus: 2023-09-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/136496/kaz/27.09.2023
  rus: https://zan.gov.kz/client/#!/doc/136496/rus/27.09.2023
caused_by:
  code: '186837'
  requisite: Решение Сайрамского районного маслихата Туркестанской области от 27 сентября 2023 года № 7-52/VIII. Зарегистрировано в Департаменте юстиции Туркестанской области 29 сентября 2023 года № 6361-13
  title:
    rus: О внесении изменение в решение Сайрамского районного маслихата от 21 ноября 2019 года № 47-294/VI «Об утверждении проекта (схемы) зонирования земель Сайрамского района»
    kaz: Сайрам аудандық мәслихатының 2019 жылғы 21 қарашадағы № 47-294/VI «Сайрам ауданының жерлерді аймақтарға бөлу жобасын (схемасын) бекіту туралы» шешiмiне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/186837/rus
