act_code: '126070'
requisite: Решение акима Шардаринского района Туркестанской области от 19 ноября 2018 года № 09. Зарегистрировано Департаментом юстиции Туркестанской области 22 ноября 2018 года № 4792. Утратило силу решением акима Шардаринского района Туркестанской области от 26 февраля 2020 года № 05 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков на территории Шардаринского района
  kaz: Шардара ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-19
approved_by:
- '166013000003'
version_date:
  kaz: 2018-11-19
  rus: 2018-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/126070/kaz/19.11.2018
  rus: https://zan.gov.kz/client/#!/doc/126070/rus/19.11.2018
