act_code: '54138'
requisite: Оңтүстік Қазақстан облысы Түлкібас аудандық мәслихатының 2010 жылғы 19 тамыздағы N 34/1-04 шешімі. Оңтүстік Қазақстан облысы Түлкібас ауданының Әділет басқармасында 2010 жылғы 25 тамызда N 14-14-114 тіркелді
title:
  rus: Түлкібас аудандық мәслихатының 2009 жылғы 21 желтоқсандағы N 26/1-04 "2010-2012 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер  енгізу туралы
  kaz: Түлкібас аудандық мәслихатының 2009 жылғы 21 желтоқсандағы N 26/1-04 "2010-2012 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер  енгізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-19
approved_by:
- '166012000002'
version_date:
  kaz: 2010-08-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/54138/kaz/19.08.2010
