act_code: '118622'
requisite: Решение Сайрамского районного маслихата Южно-Казахстанской области от 28 декабря 2017 года № 23-159/VI. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 11 января 2018 года № 4400
title:
  rus: О бюджете Аксукентского, Акбулакского, Арыского, Жибек Жолинского, Кайнарбулакского, Карабулакского, Карамуртского, Карасуского, Кутарыского, Колкентского, Манкентского сельских округов Сайрамского района на 2018-2020 годы
  kaz: Сайрам ауданы Ақсукент, Ақбұлақ, Арыс, Жібек жолы, Қайнарбұлақ, Қарабұлақ, Қарамұрт, Қарасу, Құтарыс, Көлкент, Манкент ауылдық округтерінің 2018-2020 жылдарға арналған бюджеті  туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-28
approved_by:
- '166008000002'
version_date:
  kaz: 2018-06-28
  rus: 2018-06-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/118622/kaz/28.06.2018
  rus: https://zan.gov.kz/client/#!/doc/118622/rus/28.06.2018
caused_by:
  code: '123576'
  requisite: Решение Сайрамского районного маслихата Южно-Казахстанской области от 28 июня 2018 года № 29-190/VI. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 10 июля 2018 года № 4675
  title:
    rus: О внесении изменений в решение Сайрамского районного маслихата от 28 декабря 2017 года № 23-159/VI «О бюджете Аксукентского, Акбулакского, Арысского, Жибек Жолинского, Кайнарбулакского, Карабулакского, Карамуртского, Карасуского, Кутарысского, Колкентского, Манкентского сельских округов Сайрамского района на 2018-2020 годы»
    kaz: Сайрам аудандық мәслихатының 2017 жылғы 28 желтоқсандағы № 23-159/VI «Сайрам ауданы Ақсукент, Ақбұлақ, Арыс, Жібек жолы, Қайнарбұлақ, Қарабұлақ, Қарамұрт, Қарасу, Құтарыс, Көлкент, Манкент ауылдық округтерінің 2018-2020 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123576/rus
