act_code: '192435'
requisite: Решение акима Киелитасского сельского округа Толебийского района Туркестанской области от 4 января 2024 года № 01
title:
  rus: О снятии ограничительных мероприятий по заболеванию бешенства на улице Ынтымак в населенном пункте Киелитас, Киелитасского сельского округа
  kaz: Киелітас ауылдық округі, Киелітас елді мекені, Ынтымақ көшесінде құтыру ауруы бойынша шектеу шараларын алып тастау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-01-04
approved_by:
- '166011011002'
version_date:
  kaz: 2024-01-04
  rus: 2024-01-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/192435/kaz/04.01.2024
  rus: https://zan.gov.kz/client/#!/doc/192435/rus/04.01.2024
