act_code: '94554'
requisite: Решение Казыгуртского районного маслихата Южно-Казахстанской области от 28 сентября 2015 года № 46/319-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 14 октября 2015 года № 3361. Утратило силу решением Казыгуртского районного маслихата Южно-Казахстанской области от 22 января 2016 года № 50/350-V
title:
  rus: 'О повышении ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения '
  kaz: Пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының мөлшерлемесін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-09-28
approved_by:
- '166004000002'
version_date:
  kaz: 2015-09-28
  rus: 2015-09-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/94554/kaz/28.09.2015
  rus: https://zan.gov.kz/client/#!/doc/94554/rus/28.09.2015
