act_code: '49438'
requisite: Решение Шымкентского городского маслихата Южно-Казахстанской области от 24 декабря 2009 года N 28/261-4с. Зарегистрировано Управлением юстиции города Шымкента Южно-Казахстанской области 24 декабря 2009 года N 14-1-103
title:
  rus: О бюджете города Шымкент на 2010-2012 годы
  kaz: 2010-2012 жылдарға арналған Шымкент қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-24
approved_by:
- '166002000002'
version_date:
  kaz: 2010-08-23
  rus: 2010-08-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/49438/kaz/23.08.2010
  rus: https://zan.gov.kz/client/#!/doc/49438/rus/23.08.2010
caused_by:
  code: '54207'
  requisite: Решение Шымкентского городского маслихата Южно-Казахстанской области от 23 августа 2010 года N 38/346-4с. Зарегистрировано Управлением юстиции города Шымкента Южно-Казахстанской области 27 августа 2010 года N 14-1-117
  title:
    rus: О внесении изменений в решение городского маслихата от 24 декабря 2009 года N 28/261-4с "О бюджете города Шымкент на 2010-2012 годы"
    kaz: '"2010-2012 жылдарға арналған Шымкент қаласының бюджеті туралы" Қалалық мәслихаттың 2009 жылғы 24 желтоқсандағы N 28/261-4с шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/54207/rus
