act_code: '37898'
requisite: Оңтүстік Қазақстан облысы Қазығұрт аудандық мәслихатының 2007 жылғы 25 желтоқсандағы N 5/34-IV шешімі. Оңтүстік Қазақстан облысы Қазығұрт ауданының Әділет басқармасында 2008 жылғы 9 қаңтарда N 14-6-55 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Қазығұрт аудандық мәслихатының 2009 жылғы 3 сәуірдегі N 18/129-IV Шешімімен
title:
  rus: Қазығұрт ауданы бойынша аз қамтамасыз етілген азаматтарға тұрғын үй көмегін беру Қағидасын бекіту туралы
  kaz: Қазығұрт ауданы бойынша аз қамтамасыз етілген азаматтарға тұрғын үй көмегін беру Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-25
approved_by:
- '166004000002'
version_date:
  kaz: 2007-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/37898/kaz/25.12.2007
