act_code: '223580'
requisite: Решение Мактааральского районного маслихата Туркестанской области от 27 марта 2026 года № 40-245-VIІI
title:
  rus: Об установлении стимулирующей надбавки к должностным окладам работников КГУ «Молодежный ресурсный центр» отдела «Внутренняя политика Мактааральского района», финансируемого из местного бюджета
  kaz: Жергілікті бюджеттен қаржыландырылатын «Мақтаарал ауданының ішкі саясат» бөлімінің «Жастар ресурстық орталығы» КММ қызметкерлерінің лауазымдық айлықақыларына ынталандыру үстемақы белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-03-27
approved_by:
- '166005000002'
version_date:
  kaz: 2026-03-27
  rus: 2026-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/223580/kaz/27.03.2026
  rus: https://zan.gov.kz/client/#!/doc/223580/rus/27.03.2026
