act_code: '54881'
requisite: Оңтүстік Қазақстан облысы Түлкібас ауданы әкімдігі Келтемашат ауылдық округі әкімінің 2010 жылғы 22 қыркүйектегі N 31 шешімі. Оңтүстік Қазақстан облысы Түлкібас ауданының Әділет басқармасында 2010 жылғы 14 қазанда N 14-14-128 тіркелді
title:
  rus: Көшелердің атын өзгерту туралы
  kaz: Көшелердің атын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-22
approved_by:
- '166012012001'
version_date:
  kaz: 2010-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/54881/kaz/22.09.2010
