act_code: '78110'
requisite: Решение Мактааральского районного маслихата Южно-Казахстанской области от 24 февраля 2014 года № 28-150-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 17 марта 2014 года № 2573. Утратило силу решением Мактааральского районного маслихата Южно-Казахстанской области от 20 июня 2016 года № 4-21-VI
title:
  rus: Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-24
approved_by:
- '166005000002'
version_date:
  kaz: 2015-01-28
  rus: 2015-01-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/78110/kaz/28.01.2015
  rus: https://zan.gov.kz/client/#!/doc/78110/rus/28.01.2015
caused_by:
  code: '86936'
  requisite: Решение Мактааральского районного маслихата Южно-Казахстанской области от 28 января 2015 года № 39-238-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 23 февраля 2015 года № 3050. Утратило силу решением Мактааральского районного маслихата Южно-Казахстанской области от 20 июня 2016 года № 4-21-VI
  title:
    rus: О внесении изменений и дополнений в решение Мактааральского районного маслихата от 24 февраля 2014 года №28-150-V «Об утверждении правил  оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Мақтаарал аудандық мәслихатының 2014 жылғы 24 ақпандағы №28-150-V «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидасын бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/86936/rus
