act_code: '97001'
requisite: Решение Туркестанского городского маслихата Южно-Казахстанской области от 22 декабря 2015 года № 51/279-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 30 декабря 2015 года № 3493. Срок действия решения - до 1 января 2017 года
title:
  rus: О городском бюджете на 2016-2018 годы
  kaz: 2016-2018 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-22
approved_by:
- '166015000002'
version_date:
  kaz: 2016-07-11
  rus: 2016-07-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/97001/kaz/11.07.2016
  rus: https://zan.gov.kz/client/#!/doc/97001/rus/11.07.2016
caused_by:
  code: '104955'
  requisite: Решение Туркестанского городского маслихата Южно-Казахстанской области от 11 июля 2016 года № 6/26-VI. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 19 июля 2016 года № 3798
  title:
    rus: О внесении изменений в решение Туркестанского городского маслихата от 22 декабря 2015 года № 51/279-V «О городском бюджете на 2016-2018 годы»
    kaz: «2016-2018 жылдарға арналған қалалық бюджет туралы» Түркістан қалалық мәслихатының 2015 жылғы 22 желтоқсандағы № 51/279-V шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/104955/rus
