act_code: '92919'
requisite: 'Совместное решение Ордабасинского районного маслихата Южно-Казахстанской области от 23 июля 2015 года № 44/3 и постановление акимата Ордабасинского района Южно-Казахстанской области от 26 февраля 2015 года № 96. '
title:
  rus: Об изменении границ населенных пунктов Ордабасинского района
  kaz: Ордабасы ауданы бойынша елді мекендердің шекараларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-07-23
approved_by:
- '166006000002'
version_date:
  kaz: 2015-07-23
  rus: 2015-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/92919/kaz/23.07.2015
  rus: https://zan.gov.kz/client/#!/doc/92919/rus/23.07.2015
