act_code: '51384'
requisite: Оңтүстік Қазақстан облысы Сайрам аудандық мәслихат сессиясының 2010 жылғы 18 наурыздағы N 29-272/IV шешімі. Оңтүстік Қазақстан облысы Сайрам ауданының Әділет басқармасында 2010 жылғы 25 наурызда N 14-10-135 тіркелді
title:
  rus: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Сайрам аудандық мәслихатының 2009 жылғы 23 желтоқсандағы N 25-249/IV шешіміне өзгертулер енгізу туралы'
  kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Сайрам аудандық мәслихатының 2009 жылғы 23 желтоқсандағы N 25-249/IV шешіміне өзгертулер енгізу туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-18
approved_by:
- '166008000002'
version_date:
  kaz: 2011-05-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/51384/kaz/25.05.2011
