act_code: '163738'
requisite: Решение Мактааральского районного маслихата Туркестанской области от 29 декабря 2021 года № 17-95-VII
title:
  rus: О бюджете поселков и сельских округов на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған кенттер мен ауылдық округтердің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '166005000002'
version_date:
  kaz: 2022-12-05
  rus: 2022-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/163738/kaz/05.12.2022
  rus: https://zan.gov.kz/client/#!/doc/163738/rus/05.12.2022
caused_by:
  code: '175452'
  requisite: Решение Мактааральского районного маслихата Туркестанской области от 5 декабря 2022 года № 27-181-VII
  title:
    rus: О внесении изменений в решение Мактааральского районного маслихата от 29 декабря 2021 года № 17-95-VII «О бюджете поселков и сельских округов на 2022-2024 годы»
    kaz: Мақтаарал аудандық мәслихатының 2021 жылғы 29 желтоқсандағы № 17-95-VII «2022-2024 жылдарға арналған кенттер мен ауылдық округтердің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/175452/rus
