act_code: '51814'
requisite: Оңтүстік Қазақстан облысы Отырар ауданы әкімдігі Қоғам ауыл округі әкімінің 2010 жылғы 5 сәуірдегі N 22 шешімі. Оңтүстік Қазақстан облысы Отырар ауданының Әділет басқармасында 2010 жылғы 20 сәуірде N 14-9-107 тіркелді
title:
  rus: Көшеге ат қою туралы
  kaz: Көшеге ат қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-05
approved_by:
- '166007006001'
version_date:
  kaz: 2010-04-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/51814/kaz/05.04.2010
