act_code: '46013'
requisite: Оңтүстік Қазақстан облысы Отырар ауданы әкімдігі Талапты ауылдық округі әкімінің 2009 жылғы 14 сәуірдегі N 5 шешімі. Оңтүстік Қазақстан облысы Отырар ауданының Әділет басқармасында 2009 жылғы 18 мамырда N 14-9-81 тіркелді
title:
  rus: Көшеге ат қою туралы
  kaz: Көшеге ат қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-14
approved_by:
- '166007010001'
version_date:
  kaz: 2009-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/46013/kaz/14.04.2009
