act_code: '32232'
requisite: Решение Маслихата Южно-Казахстанской области от 28 февраля 2007 года N 30/350-III. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 12 марта 2007 года за N 1952. Утратило силу решением Туркестанского областного маслихата от 28 апреля 2023 года № 2/27-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О предоставлении жителям Южно-Казахстанской области бесплатного проезда за пределы населенного пункта на лечение за счет бюджетных средств
  kaz: Оңтүстік Қазақстан облысының тұрғындарына елдi мекен шегiнен тыс жерлерге емделу үшiн бюджет қаражаты есебiнен тегiн жол жүруі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-02-28
approved_by:
- '166000000002'
version_date:
  kaz: 2007-05-31
  rus: 2007-05-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/32232/kaz/31.05.2007
  rus: https://zan.gov.kz/client/#!/doc/32232/rus/31.05.2007
caused_by:
  code: '33723'
  requisite: Решение Маслихата Южно-Казахстанской области от 31 мая 2007 года N 33/368-III. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 19 июня 2007 года за N 1955. Утратило силу решением Туркестанского областного маслихата от 28 апреля 2023 года № 2/27-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Южно-Казахстанского областного маслихата от 28 февраля 2007 года N 30/350-III "О предоставлении жителям Южно-Казахстанской области бесплатного проезда за пределы населенного пункта на лечение за счет бюджетных средств"
    kaz: '"Оңтүстік Қазақстан облысының тұрғындарына елді мекен шегінен тыс жерлерге емделу үшін бюджет қаражаты есебінен тегін жол жүруі туралы" Оңтүстік Қазақстан облыстық мәслихатының 2007 жылғы 28 ақпандағы N 30/350-ІІІ шешіміне өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/33723/rus
