act_code: '98984'
requisite: Решение Туркестанского городского маслихата Южно-Казахстанской области от 20 января 2016 года № 52/291-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 8 февраля 2016 года № 3567. Утратило силу решением Туркестанского городского маслихата Южно-Казахстанской области от 29 июня 2016 года № 5/19-VI
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов, тарифов на сбор, вывоз, захоронение и утилизацию твердых бытовых отходов по городу Туркестан
  kaz: Түркістан қаласы бойынша коммуналдық қалдықтардың пайда болу және жинақталу нормаларын, тұрмыстық қатты қалдықтарды жинау, әкету, көму және кәдеге жарату тарифтерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-01-20
approved_by:
- '166015000002'
version_date:
  kaz: 2016-01-20
  rus: 2016-01-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/98984/kaz/20.01.2016
  rus: https://zan.gov.kz/client/#!/doc/98984/rus/20.01.2016
