act_code: '163661'
requisite: Решение Казыгуртского районного маслихата Туркестанской области от 30 декабря 2021 года № 21/91-VII
title:
  rus: О бюджете сельских округов на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған ауылдық округтердің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '166004000002'
version_date:
  kaz: 2022-12-02
  rus: 2022-12-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/163661/kaz/02.12.2022
  rus: https://zan.gov.kz/client/#!/doc/163661/rus/02.12.2022
caused_by:
  code: '175829'
  requisite: Решение Казыгуртского районного маслихата Туркестанской области от 2 декабря 2022 года № 34/149-VII
  title:
    rus: О внесении изменений в решение Казыгуртского районного маслихата «О бюджете сельских округов на 2022-2024 годы» от 30 декабря 2021 года № 21/91-VІI
    kaz: Қазығұрт аудандық мәслихатының «2022-2024 жылдарға арналған ауылдық округтердің бюджеті туралы» 2021 жылғы 30 желтоқсандағы № 21/91-VIІ шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/175829/rus
