act_code: '44316'
requisite: Оңтүстік Қазақстан облысы Арыс қалалық мәслихатының 2009 жылғы 23 қаңтардағы N 16/101-IV шешімі. Оңтүстік Қазақстан облысы Арыс қаласының Әділет басқармасында 2009 жылғы 20 ақпанда N 14-2-69 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Арыс қалалық мәслихатының 2012 жылғы 21 желтоқсандағы № 11/59-V Шешімімен
title:
  rus: Біржолғы талондардың құнын белгілеу туралы
  kaz: Біржолғы талондардың құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-23
approved_by:
- '166016000002'
version_date:
  kaz: 2009-01-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/44316/kaz/23.01.2009
