act_code: '140972'
requisite: Решение Туркестанского городского маслихата Туркестанской области от 27 марта 2020 года № 62/306-VI. Зарегистрировано Департаментом юстиции Туркестанской области 1 апреля 2020 года № 5536. Утратило силу решением Туркестанского городского маслихата Туркестанской области от 10 ноября 2020 года № 69/332-VI (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан города Туркестан
  kaz: Түркістан қаласының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-03-27
approved_by:
- '166015000002'
version_date:
  kaz: 2020-03-27
  rus: 2020-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/140972/kaz/27.03.2020
  rus: https://zan.gov.kz/client/#!/doc/140972/rus/27.03.2020
