act_code: '159710'
requisite: Решение акима Жетысайского района Туркестанской области от 14 октября 2021 года № 13. Зарегистрировано в Министерстве юстиции Республики Казахстан 22 октября 2021 года № 24857
title:
  rus: Об образовании избирательных участков на территории Жетысайского района
  kaz: Жетісай ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-10-14
approved_by:
- '166017000003'
version_date:
  kaz: 2025-01-21
  rus: 2025-01-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/159710/kaz/21.01.2025
  rus: https://zan.gov.kz/client/#!/doc/159710/rus/21.01.2025
caused_by:
  code: '206717'
  requisite: Решение акима Жетысайского района Туркестанской области от 21 января 2025 года № 1. Зарегистрировано в Департаменте юстиции Туркестанской области 22 января 2025 года № 6656-13
  title:
    rus: О внесении изминения в решение акима Жетысайского района от 14 октября 2021 года № 13 «Об образовании избирательных участков на территории Жетысайского района»
    kaz: Жетісай ауданы әкімінің 2021 жылғы 14 қазандағы № 13 «Жетісай ауданының аумағында сайлау учаскелерін құру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/206717/rus
