act_code: '51787'
requisite: Оңтүстік Қазақстан облысы Қазығұрт аудандық мәслихатының 2010 жылғы 18 наурыздағы N 31/232-IV шешімі. Оңтүстік Қазақстан облысы Қазығұрт ауданының Әділет басқармасында 2010 жылғы 16 сәуірде N 14-6-97 тіркелді
title:
  rus: Қазығұрт ауданына 2010 жылы  жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына көтерме жәрдемақы және тұрғын үй сатып алу үшін әлеуметтік қолдауды ұсыну туралы
  kaz: Қазығұрт ауданына 2010 жылы  жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына көтерме жәрдемақы және тұрғын үй сатып алу үшін әлеуметтік қолдауды ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-18
approved_by:
- '166004000002'
version_date:
  kaz: 2010-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/51787/kaz/03.11.2010
caused_by:
  code: '55817'
  requisite: Оңтүстік Қазақстан облысы Қазығұрт аудандық мәслихатының 2010 жылғы 3 қарашадағы N 37/276-IV шешімі. Оңтүстік Қазақстан облысы Қазығұрт ауданының Әділет басқармасында 2010 жылғы 9 желтоқсанда N 14-6-122 тіркелді
  title:
    rus: Қазығұрт аудандық мәслихатының 2010 жылғы 18 наурыздағы "Қазығұрт ауданына 2010 жылы жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына көтерме жәрдемақы және тұрғын үй сатып алу үшін әлеуметтік қолдауды ұсыну туралы" № 31/232-ІV шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Қазығұрт аудандық мәслихатының 2010 жылғы 18 наурыздағы "Қазығұрт ауданына 2010 жылы жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына көтерме жәрдемақы және тұрғын үй сатып алу үшін әлеуметтік қолдауды ұсыну туралы" № 31/232-ІV шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/55817/rus
