act_code: '55994'
requisite: Решение областного маслихата Южно-Казахстанской области от 10 декабря 2010 года N 35/349-IV. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 21 декабря 2010 года N 2042
title:
  rus: Об областном бюджете на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-10
approved_by:
- '166000000002'
version_date:
  kaz: 2011-10-31
  rus: 2011-10-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/55994/kaz/31.10.2011
  rus: https://zan.gov.kz/client/#!/doc/55994/rus/31.10.2011
caused_by:
  code: '61086'
  requisite: Решение областного маслихата Южно-Казахстанской области N 46/446-IV от 31 октября 2011 года. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 4 ноября 2011 года N 2059
  title:
    rus: О внесении изменений и дополнения в решение Южно-Казахстанского областного маслихата от 10 декабря 2010 года № 35/349-IV "Об областном бюджете на 2011-2013 годы"
    kaz: '"2011-2013 жылдарға арналған облыстық бюджет туралы" Оңтүстік Қазақстан облыстық мәслихатының 2010 жылғы 10 желтоқсандағы № 35/349-IV шешіміне өзгерістер мен толықтыру енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/61086/rus
