act_code: '151940'
requisite: Решение Кентауского городского маслихата Туркестанской области от 31 декабря 2020 года № 419. Зарегистрировано Департаментом юстиции Туркестанской области 14 января 2021 года № 6024
title:
  rus: О бюджете сел и сельских округов города Кентау на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Кентау қаласы ауыл және ауыл округтерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-31
approved_by:
- '166014000002'
version_date:
  kaz: 2021-03-10
  rus: 2021-03-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/151940/kaz/10.03.2021
  rus: https://zan.gov.kz/client/#!/doc/151940/rus/10.03.2021
caused_by:
  code: '153816'
  requisite: Решение Кентауского городского маслихата Туркестанской области от 10 марта 2021 года № 20. Зарегистрировано Департаментом юстиции Туркестанской области 25 марта 2021 года № 6122
  title:
    rus: О внесении изменений в решение Кентауского городского маслихата от 31 декабря 2020 года № 419 «О бюджете сел и сельских округов города Кентау на 2021-2023 годы»
    kaz: Кентау қалалық мәслихатының 2020 жылғы 31 желтоқсандағы № 419 «2021-2023 жылдарға арналған Кентау қаласы ауыл және ауыл округтерінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/153816/rus
