act_code: '137978'
requisite: Решение Кентауского городского маслихата Туркестанской области от 30 декабря 2019 года № 334. Зарегистрировано Департаментом юстиции Туркестанской области 8 января 2020 года № 5353
title:
  rus: О бюджете сел и сельских округов города Кентау на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Кентау қаласы ауыл және ауыл округтерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-30
approved_by:
- '166014000002'
version_date:
  kaz: 2020-06-25
  rus: 2020-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/137978/kaz/25.06.2020
  rus: https://zan.gov.kz/client/#!/doc/137978/rus/25.06.2020
caused_by:
  code: '144459'
  requisite: Решение Кентауского городского маслихата Туркестанской области от 25 июня 2020 года № 369. Зарегистрировано Департаментом юстиции Туркестанской области 2 июля 2020 года № 5689
  title:
    rus: О внесении изменений в решение Кентауского городского маслихата от 30 декабря 2019 года № 334 «О бюджете сел и сельских округов города Кентау на 2020-2022 годы»
    kaz: Кентау қалалық мәслихатының 2019 жылғы 30 желтоқсандағы № 334 «2020-2022 жылдарға арналған Кентау қаласы ауыл және ауыл округтерінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/144459/rus
