act_code: '74819'
requisite: Решение Тюлькубасского районного маслихата Южно-Казахстанской области от 30 сентября 2013 года № 19/4-05. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 18 октября 2013 года № 2381. Утратило силу решением Тюлькубасского районного маслихата Туркестанской области от 18 марта 2019 года № 37/9-06
title:
  rus: О предоставлении социальной помощи на приобретение топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Тюлькубасского района
  kaz: Түлкібас ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына отын сатып алуға әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-09-30
approved_by:
- '166012000002'
version_date:
  kaz: 2014-12-23
  rus: 2014-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/74819/kaz/23.12.2014
  rus: https://zan.gov.kz/client/#!/doc/74819/rus/23.12.2014
caused_by:
  code: '86134'
  requisite: Решение Тюлькубасского районного маслихата Южно-Казахстанской области от 23 декабря 2014 года № 36/10-05. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 21 января 2015 года № 2968. Утратило силу решением Тюлькубасского районного маслихата Туркестанской области от 18 марта 2019 года № 37/9-06
  title:
    rus: О внесении изменения в решение Тюлькубасского районного маслихата от 30 сентября 2013 года №19/4-05 «О предоставлении социальной помощи на приобретение топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Тюлькубасского района»
    kaz: Түлкібас аудандық мәслихатының 2013 жылғы 30 қыркүйектегі №19/4-05 «Түлкібас ауданының ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына отын сатып алуға әлеуметтік көмек беру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/86134/rus
