act_code: '161986'
requisite: Решение Туркестанского областного маслихата от 10 декабря 2021 года № 13/129-VIІ. Зарегистрировано в Министерстве юстиции Республики Казахстан 22 декабря 2021 года № 25922. Утратило силу решением Туркестанского областного маслихата от 15 декабря 2025 года № 20/280-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении размера платы за один кубический метр поданной питьевой воды населению из особо важных групповых и локальных систем водоснабжения, являющихся безальтернативными источниками питьевого водоснабжения по Туркестанской области
  kaz: Түркістан облысы бойынша ауызсумен жабдықтаудың баламасыз көздері болып табылатын сумен жабдықтаудың ерекше маңызды топтық және оқшау жүйелерінен халыққа берілген ауызсудың бір текше метрі үшін төлемақы мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-10
approved_by:
- '166000000002'
version_date:
  kaz: 2021-12-10
  rus: 2021-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/161986/kaz/10.12.2021
  rus: https://zan.gov.kz/client/#!/doc/161986/rus/10.12.2021
