act_code: '351'
requisite: Решение акима Южно-Казахстанской области от 12 октября 1995 года № 33. Зарегистрировано Управлением юстиции Южно-Казахстанской области 6 октября 1997 года № 1
title:
  rus: Об очередном призыве граждан на срочную военную службу в октябре-декабре 1995 года
  kaz: Азаматтарды 1995 жылғы қазан-желтоқсанда мерзiмдi әскери қызметке кезектi шақыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1995-10-12
approved_by:
- '166000000003'
version_date:
  kaz: 1995-10-12
  rus: 1995-10-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/351/kaz/12.10.1995
  rus: https://zan.gov.kz/client/#!/doc/351/rus/12.10.1995
