act_code: '7101'
requisite: Решение акима Южно-Казахстанской области от 6 октября 2000 года № 352. Зарегистрировано Управлением юстиции Южно-Казахстанской области 13 октября 2000 года № 187
title:
  rus: Об очередном призыве граждан на срочную военную службу в октябре-декабре 2000 года
  kaz: Азаматтарды 2000 жылғы қазан-желтоқсанда мерзiмдi әскери қызметке кезектi шақыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-10-05
approved_by:
- '166000000003'
version_date:
  kaz: 2000-10-05
  rus: 2000-10-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/7101/kaz/05.10.2000
  rus: https://zan.gov.kz/client/#!/doc/7101/rus/05.10.2000
