act_code: '55263'
requisite: Оңтүстік Қазақстан облысы Түлкібас ауданы әкімдігі Майлыкент ауылдық округі әкімінің 2010 жылғы 3 қарашадағы N 155 шешімі. Оңтүстік Қазақстан облысы Түлкібас ауданының Әділет басқармасында 2010 жылғы 9 қарашада N 14-14-133 тіркелді
title:
  rus: Көшелердің аттарын өзгерту туралы
  kaz: Көшелердің аттарын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-03
approved_by:
- '166012008001'
version_date:
  kaz: 2010-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/55263/kaz/03.11.2010
