act_code: '69953'
requisite: Решение областного маслихата Южно-Казахстанской области от 7 декабря 2012 года № 9/82-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области от 11 января 2013 года № 2205
title:
  rus: Об утверждении ставок платы за пользование водными ресурсами поверхностных источников в Южно-Казахстанской области
  kaz: Оңтүстік Қазақстан облысында жер үсті көздерінің су ресурстарын пайдаланғаны үшін төлемақы ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-07
approved_by:
- '166000000002'
version_date:
  kaz: 2012-12-07
  rus: 2012-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/69953/kaz/07.12.2012
  rus: https://zan.gov.kz/client/#!/doc/69953/rus/07.12.2012
