act_code: '359'
requisite: Решение акима Южно-Казахстанской области от 2 апреля 1996 года № 60. Зарегистрировано Управлением юстиции Южно-Казахстанской области 20 октября 1997 года № 8
title:
  rus: Об очередном призыве граждан на срочную военную службу в апреле-июне 1996 года
  kaz: Азаматтарды 1996 жылғы сәуiр-маусымда мерзiмдi әскери қызметке кезектi шақыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1996-04-01
approved_by:
- '166000000003'
version_date:
  kaz: 1996-04-01
  rus: 1996-04-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/359/kaz/01.04.1996
  rus: https://zan.gov.kz/client/#!/doc/359/rus/01.04.1996
