act_code: '220216'
requisite: Решение Арысского городского маслихата Туркестанской области от 23 декабря 2025 года № 41/237-VІІІ
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов в городе Арыс
  kaz: Арыс қаласында тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2025-12-23
approved_by:
- '166016000002'
version_date:
  kaz: 2025-12-23
  rus: 2025-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/220216/kaz/23.12.2025
  rus: https://zan.gov.kz/client/#!/doc/220216/rus/23.12.2025
