act_code: '208567'
requisite: Решение Кентауского городского маслихата Туркестанской области от 28 марта 2025 года № 178. Зарегистрировано в Департаменте юстиции Туркестанской области 31 марта 2025 года № 6672-13
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-03-28
approved_by:
- '166014000002'
version_date:
  kaz: 2026-03-03
  rus: 2026-03-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/208567/kaz/03.03.2026
  rus: https://zan.gov.kz/client/#!/doc/208567/rus/03.03.2026
caused_by:
  code: '222798'
  requisite: Решение Кентауского городского маслихата Туркестанской области от 3 марта 2026 года № 264. Утратило силу решением Кентауского городского маслихата Туркестанской области от 15 июля 2026 года № 292 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Кентауского городского маслихата от 28 марта 2025 года № 178 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Кентау қалалық мәслихатының 2025 жылғы 28 наурыздағы № 178 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/222798/rus
