act_code: '46238'
requisite: Оңтүстік Қазақстан облысы Отырар аудандық мәслихатының 2009 жылғы 13 сәуірдегі N 18/116-IV шешімі. Оңтүстік Қазақстан облысы Отырар ауданының Әділет басқармасында 2009 жылғы 1 маусымда N 14-9-84 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Отырар аудандық мәслихатының 2012 жылғы 5 қарашадағы № 7/50-V Шешімімен
title:
  rus: Отырар ауданының аймақтардың шекаралары мен жерге ақы төлеудің базалық салық ставкаларына түзету коэффициенттерін белгілеу туралы
  kaz: Отырар ауданының аймақтардың шекаралары мен жерге ақы төлеудің базалық салық ставкаларына түзету коэффициенттерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-13
approved_by:
- '166007000002'
version_date:
  kaz: 2009-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/46238/kaz/13.04.2009
