act_code: '49103'
requisite: Оңтүстік Қазақстан облысы Арыс қалалық мәслихатының 2009 жылғы 5 қарашадағы N 25/158-IV шешімі. Оңтүстік Қазақстан облысы Арыс қаласының Әділет басқармасында 2009 жылғы 4 желтоқсанда N 14-2-84 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Арыс қалалық мәслихатының 2017 жылғы 24 наурыздағы № 11/78-VI шешімімен
title:
  rus: Ауылдық елді мекендерде тұратын мамандарға әлеуметтік көмек беру туралы
  kaz: Ауылдық елді мекендерде тұратын мамандарға әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-11-05
approved_by:
- '166016000002'
version_date:
  kaz: 2012-06-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/49103/kaz/13.06.2012
caused_by:
  code: '66483'
  requisite: Решение Арысского городского маслихата Южно-Казахстанской области от 13 июня 2012 года № 4/31-V. Зарегистрировано Управлением юстиции города Арыс Южно-Казахстанской области 4 июля 2012 года № 14-2-133. Утратило силу решением Арысского городского маслихата Южно-Казахстанской области от 24 марта 2017 года № 11/78-VI
  title:
    rus: О внесении изменения в решение Арысского городского маслихата от 5 ноября 2009 года № 25/158-ІV "Об оказании социальной помощи специалистам, проживающим в сельских населенных пунктах"
    kaz: Арыс қалалық мәслихатының 2009 жылғы 5 қарашадағы № 25/158-ІV "Ауылдық елді мекендерде тұратын мамандарға әлеуметтік көмек беру туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/66483/rus
