act_code: '198447'
requisite: Решение Сарыагашского районного маслихата Туркестанской области от 27 июня 2024 года № 19-150-VIII
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества в районе Сарыагаш Туркестанской области
  kaz: Түркістан облысы Сарыағаш ауданы бойынша жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауылдар тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-06-27
approved_by:
- '166009000002'
version_date:
  kaz: 2024-06-27
  rus: 2024-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/198447/kaz/27.06.2024
  rus: https://zan.gov.kz/client/#!/doc/198447/rus/27.06.2024
