act_code: '124902'
requisite: Решение Толебийского районного маслихата Туркестанской области от 19 сентября 2018 года № 29/165-VI. Зарегистрировано Департаментом юстиции Туркестанской области 26 сентября 2018 года № 4743
title:
  rus: О признании утратившим силу решения Толебийского районного маслихата 19 апреля 2017 года № 14/80-VI «О предоставлении социальной помощи на приобретение топлива специалистам государственных организаций социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Толебийского района»
  kaz: Төлеби аудандық мәслихатының 2017 жылғы 19 сәуірдегі № 14/80-VI «Төлеби ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына отын сатып алуға әлеуметтік көмек беру туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-09-19
approved_by:
- '166011000002'
version_date:
  kaz: 2018-09-19
  rus: 2018-09-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/124902/kaz/19.09.2018
  rus: https://zan.gov.kz/client/#!/doc/124902/rus/19.09.2018
