act_code: '60662'
requisite: Решение Туркестанского городского маслихата Южно-Казахстанской области от 14 сентября 2011 года N 49/331-IV. Зарегистрировано Управлением юстиции города Туркестан Южно-Казахстанской области 4 октября 2011 года N 14-4-103. Утратило силу решением Туркестанского городского маслихата Южно-Казахстанской области от 20 декабря 2012 года № 10/63-V
title:
  rus: Об установлении стоимости разовых талонов
  kaz: Бір жолғы талондардың құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-09-14
approved_by:
- '166015000002'
version_date:
  kaz: 2011-09-14
  rus: 2011-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/60662/kaz/14.09.2011
  rus: https://zan.gov.kz/client/#!/doc/60662/rus/14.09.2011
