act_code: '97418'
requisite: Решение акима Кемербастауского сельского округа Тюлькубасского района Южно-Казахстанской области от 18 декабря 2015 года № 34. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 24 декабря 2015 года № 3480
title:
  rus: О присвоении наименования безымянной улице
  kaz: Атауы жоқ көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-18
approved_by:
- '166012007001'
version_date:
  kaz: 2015-12-18
  rus: 2015-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/97418/kaz/18.12.2015
  rus: https://zan.gov.kz/client/#!/doc/97418/rus/18.12.2015
