act_code: '128646'
requisite: Решение Мактааральского районного маслихата Туркестанской области от 29 декабря 2018 года № 44-289-VI. Зарегистрировано Департаментом юстиции Туркестанской области 10 января 2019 года № 4879
title:
  rus: О бюджете поселков и сельских округов на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған кенттер мен ауылдық округтердің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-29
approved_by:
- '166005000002'
version_date:
  kaz: 2018-12-29
  rus: 2018-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/128646/kaz/29.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128646/rus/29.12.2018
