act_code: '410'
requisite: Решение акима Южно-Казахстанской области от 18 июня 1997 года № 142. Зарегистрировано Управлением юстиции Южно-Казахстанской области 10 ноября 1997 года № 19. Утратило силу решением акима Южно-Казахстанской области от 15 декабря 2004 года № 49
title:
  rus: О создании комиссии по возмещению ущерба реабилитированным гражданам
  kaz: Ақталған азаматтардың шеккен зияндарына өтемақы төлеу жөнiндегi комиссия құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1997-06-17
approved_by:
- '166000000003'
version_date:
  kaz: 1997-06-17
  rus: 1997-06-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/410/kaz/17.06.1997
  rus: https://zan.gov.kz/client/#!/doc/410/rus/17.06.1997
