act_code: '137972'
requisite: Решение Сарыагашского районного маслихата Туркестанской области от 20 декабря 2019 года № 46-417-VI. Зарегистрировано Департаментом юстиции Туркестанской области 31 декабря 2019 года № 5347
title:
  rus: «О районном бюджете на 2020-2022 годы»
  kaz: 2020-2022 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-20
approved_by:
- '166009000002'
version_date:
  kaz: 2020-03-06
  rus: 2020-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/137972/kaz/06.03.2020
  rus: https://zan.gov.kz/client/#!/doc/137972/rus/06.03.2020
caused_by:
  code: '140669'
  requisite: Решение Сарыагашского районного маслихата Туркестанской области от 6 марта 2020 года № 48-437-VI. Зарегистрировано Департаментом юстиции Туркестанской области 27 марта 2020 года № 5529
  title:
    rus: О внесении изменений в решение Сарыагашского районного маслихата от 20 декабря 2019 года № 46-417-VI «О районном бюджете на 2020-2022 годы»
    kaz: Сарыағаш аудандық мәслихатының 2019 жылғы 20 желтоқсандағы № 46-417-VI «2020-2022 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/140669/rus
