act_code: '45065'
requisite: Оңтүстік Қазақстан облысы Бәйдібек аудандық мәслихатының 2009 жылғы 17 ақпандағы N 16/95 шешімі. Оңтүстік Қазақстан облысы Бәйдібек ауданының Әділет басқармасында 2009 жылғы 12 наурызда N 14-5-72 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Бәйдібек аудандық мәслихатының 2012 жылғы 21 желтоқсандағы № 9/48 Шешімімен
title:
  rus: Бір жолғы талондар құнын белгілеу туралы
  kaz: Бір жолғы талондар құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-17
approved_by:
- '166003000002'
version_date:
  kaz: 2009-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/45065/kaz/21.12.2009
caused_by:
  code: '49941'
  requisite: Оңтүстік Қазақстан облысы Бәйдібек аудандық мәслихатының 2009 жылғы 21 желтоқсандағы N 26/139 шешімі. Оңтүстік Қазақстан облысы Бәйдібек ауданының Әділет басқармасында 2010 жылғы 12 қаңтарда N 14-5-86 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Бәйдібек аудандық мәслихатының 2012 жылғы 21 желтоқсандағы № 9/48 Шешімімен
  title:
    rus: Бәйдібек аудандық мәслихатының 2009 жылғы 17 ақпандағы "Бір жолғы талон негізінде кәсіпкерлік жасаушы жеке тұлғаларға кәсіпкерлік қызмет түрлері бойынша бір жолғы талондар құнын белгілеу туралы" № 16/95 шешіміне өзгерістер енгізу туралы
    kaz: Бәйдібек аудандық мәслихатының 2009 жылғы 17 ақпандағы "Бір жолғы талон негізінде кәсіпкерлік жасаушы жеке тұлғаларға кәсіпкерлік қызмет түрлері бойынша бір жолғы талондар құнын белгілеу туралы" № 16/95 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/49941/rus
