act_code: '45065'
requisite: Оңтүстік Қазақстан облысы Бәйдібек аудандық мәслихатының 2009 жылғы 17 ақпандағы N 16/95 шешімі. Оңтүстік Қазақстан облысы Бәйдібек ауданының Әділет басқармасында 2009 жылғы 12 наурызда N 14-5-72 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Бәйдібек аудандық мәслихатының 2012 жылғы 21 желтоқсандағы № 9/48 Шешімімен
title:
  rus: Бір жолғы талондар құнын белгілеу туралы
  kaz: Бір жолғы талондар құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-17
approved_by:
- '166003000002'
version_date:
  kaz: 2009-02-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/45065/kaz/17.02.2009
