act_code: '76123'
requisite: Решение акима сельского округа Турбат Казыгуртского района Южно-Казахстанской области от 5 декабря 2013 года № 116. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 24 декабря 2013 года № 2450. Утратило силу решением акима сельского округа Турбат Казыгуртского района Южно-Казахстанской области от 3 февраля 2014 года № 5
title:
  rus: Об установлении ветеринарного режима с введением ограничительных мероприятий на территории населенных пунктов Турбат и Енбек сельского округа Турбат
  kaz: Тұрбат ауыл округі Тұрбат және Еңбек елді мекендерінің аумағына шектеу iс-шараларын енгiзе отырып ветеринариялық режим белгiлеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-05
approved_by:
- '166004010001'
version_date:
  kaz: 2013-12-05
  rus: 2013-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/76123/kaz/05.12.2013
  rus: https://zan.gov.kz/client/#!/doc/76123/rus/05.12.2013
