act_code: '182232'
requisite: Решение Созакского районного маслихата Туркестанской области от 24 мая 2023 года № 26. Зарегистрировано Департаментом юстиции Туркестанской области 30 мая 2023 года № 6301-13
title:
  rus: Об утверждении минимального размера расходов на управление объектом кондоминиума и содержание общего имущества объекта кондоминиума на 2023 год
  kaz: 2023 жылға кондоминиум объектісін басқаруға және кондоминиум объектісінің ортақ мүлкін күтіп-ұстауға арналған шығыстардың ең төмен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-05-24
approved_by:
- '166010000002'
version_date:
  kaz: 2023-05-24
  rus: 2023-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/182232/kaz/24.05.2023
  rus: https://zan.gov.kz/client/#!/doc/182232/rus/24.05.2023
