act_code: '56773'
requisite: Оңтүстік Қазақстан облысы Кентау қалалық мәслихатының 2010 жылғы 22 желтоқсандағы N 268 шешімі. Оңтүстік Қазақстан облысы Кентау қаласының Әділет басқармасында 2011 жылғы 12 қаңтарда N 14-3-103 тіркелді
title:
  rus: 2011-2013 жылдарға арналған қалалық бюджет туралы
  kaz: 2011-2013 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-22
approved_by:
- '166014000002'
version_date:
  kaz: 2011-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/56773/kaz/09.11.2011
caused_by:
  code: '61376'
  requisite: Решение маслихата города Кентау Южно-Казахстанской области от 9 ноября 2011 года N 343. Зарегистрировано Управлением юстиции города Кентау Южно-Казахстанской области 16 ноября 2011 года N 14-3-118
  title:
    rus: О внесении изменений в решение Кентауского городского маслихата от 22 декабря 2010 года № 268 "О городском бюджете на 2011-2013 годы"
    kaz: Кентау қалалық мәслихатының 2010 жылғы 22 желтоқсандағы № 268 "2011-2013 жылдарға арналған қалалық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/61376/rus
