act_code: '83009'
requisite: Решение Туркестанского городского маслихата Южно-Казахстанской области от 8 августа 2014 года № 32/178-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 8 сентября 2014 года № 2800. Утратило силу решением Туркестанского городского маслихата Туркестанской области от 30 марта 2022 года № 15/86-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей села, улицы, многоквартирного жилого дома для участия в сходе местного сообщества в городе Туркестан
  kaz: Түркістан қаласында бөлек жергілікті қоғамдастық жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше, көппәтерлі тұрғын үй тұрғындары өкілдерінің санын айқындау тәртібін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-08-08
approved_by:
- '166015000002'
version_date:
  kaz: 2014-08-08
  rus: 2014-08-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/83009/kaz/08.08.2014
  rus: https://zan.gov.kz/client/#!/doc/83009/rus/08.08.2014
