act_code: '162645'
requisite: Решение Кентауского городского маслихата Туркестанской области от 29 декабря 2021 года № 109
title:
  rus: О бюджете села Хантаги города Кентау на 2022-2024 годы
  kaz: Кентау қаласының Хантағы ауылының 2022-2024 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '166014000002'
version_date:
  kaz: 2021-12-29
  rus: 2021-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/162645/kaz/29.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162645/rus/29.12.2021
