act_code: '12423'
requisite: Решение акима Южно-Казахстанской области от 23 мая 2002 года № 43. Зарегистрировано Управлением юстиции Южно-Казахстанской области 10 июня 2002 года № 593
title:
  rus: Об утверждении перечня документов и показателей, необходимых для определения финансового состояния заявителя на осуществление деятельности по организации и проведению тотализаторов и казино
  kaz: Тотализаторлар мен казиноларды ұйымдастыру және өткiзу қызметiн жүзеге асыру үшiн өтiнiш берушiнiң қаржылық жағдайын анықтауға қажеттi құжаттар мен көрсеткiштер тiзiмiн бекiту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-05-22
approved_by:
- '166000000003'
version_date:
  kaz: 2002-05-22
  rus: 2002-05-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/12423/kaz/22.05.2002
  rus: https://zan.gov.kz/client/#!/doc/12423/rus/22.05.2002
