act_code: '76468'
requisite: Решение маслихата Сайрамского района Южно-Казахстанской области от 20 декабря 2013 года № 26-157/V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 9 января 2014 года № 2480
title:
  rus: О районном бюджете на 2014-2016 годы
  kaz: 2014-2016 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-20
approved_by:
- '166008000002'
version_date:
  kaz: 2014-04-18
  rus: 2014-04-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/76468/kaz/18.04.2014
  rus: https://zan.gov.kz/client/#!/doc/76468/rus/18.04.2014
caused_by:
  code: '79306'
  requisite: Решение Сайрамского районного маслихата Южно-Казахстанской области от 18 апреля 2014 года № 30-187/V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 25 апреля 2014 года № 2631
  title:
    rus: О внесении изменений в решение Сайрамского районного маслихата от 20 декабря 2013 года № 26-157/V "О районном бюджете на 2014-2016 годы"
    kaz: Сайрам аудандық мәслихатының 2013 жылғы 20 желтоқсандағы № 26-157/V "2014-2016 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/79306/rus
