act_code: '15061'
requisite: Решение акима Южно-Казахстанской области от 1 апреля 2003 года № 34. Зарегистрировано Управлением юстиции Южно-Казахстанской области 8 апреля 2003 года № 856
title:
  rus: О создании комиссии
  kaz: Комиссия құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-03-31
approved_by:
- '166000000003'
version_date:
  kaz: 2003-03-31
  rus: 2003-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/15061/kaz/31.03.2003
  rus: https://zan.gov.kz/client/#!/doc/15061/rus/31.03.2003
