act_code: '157096'
requisite: Решение акима Созакского района Туркестанской области от 16 июля 2021 года № 19. Зарегистрировано в Министерстве юстиции Республики Казахстан 19 июля 2021 года № 23600. Утратило силу решением акима Созакского района Туркестанской области от 25 декабря 2023 года № 51 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков на территории Созакского района
  kaz: Созақ ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-07-16
approved_by:
- '166010000003'
version_date:
  kaz: 2022-09-23
  rus: 2022-09-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/157096/kaz/23.09.2022
  rus: https://zan.gov.kz/client/#!/doc/157096/rus/23.09.2022
caused_by:
  code: '172408'
  requisite: Решение акима Созакского района Туркестанской области от 23 сентября 2022 года № 42. Зарегистрировано в Министерстве юстиции Республики Казахстан 30 сентября 2022 года № 29949. Утратило силу решением акима Созакского района Туркестанской области от 25 декабря 2023 года № 51 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение акима Созакского района Туркестанской области от 16 июля 2021 года № 19 «Об образовании избирательных участков на территорий Созакского района»
    kaz: Түркістан облысы Созақ ауданы әкімінің 2021 жылғы 16 шілдедегі № 19 «Созақ ауданының аумағында сайлау учаскелерін құру туралы» шешіміне өзгертулер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172408/rus
