act_code: '193040'
requisite: Решение акима сельского округа Жартытобе Созакского района Туркестанской области от 5 февраля 2024 года № 3
title:
  rus: О присвоении наименований безымянным улицам
  kaz: Атауы жоқ көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-05
approved_by:
- '166010002002'
version_date:
  kaz: 2024-02-05
  rus: 2024-02-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/193040/kaz/05.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193040/rus/05.02.2024
