act_code: '179352'
requisite: Решение акима сельского округа Бирлесу Келесского района Туркестанской области от 28 марта 2023 года № 12. Зарегистрировано Департаментом юстиции Туркестанской области 29 марта 2023 года № 6250-13
title:
  rus: О присвоении наименований безымянным улицам
  kaz: Атауы жоқ көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-03-28
approved_by:
- '166018007002'
version_date:
  kaz: 2023-03-28
  rus: 2023-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/179352/kaz/28.03.2023
  rus: https://zan.gov.kz/client/#!/doc/179352/rus/28.03.2023
