act_code: '140246'
requisite: Решение акима Первомаевского сельского округа Толебийского района Туркестанской области от 10 марта 2020 года № 14. Зарегистрировано Департаментом юстиции Туркестанской области 10 марта 2020 года № 5472
title:
  rus: О присвоении наименовании улицам
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-03-10
approved_by:
- '166011005002'
version_date:
  kaz: 2020-03-10
  rus: 2020-03-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/140246/kaz/10.03.2020
  rus: https://zan.gov.kz/client/#!/doc/140246/rus/10.03.2020
