act_code: '153597'
requisite: Решение акима Первомаевского сельского округа Толебийского района Туркестанской области от 18 марта 2021 года № 15. Зарегистрировано Департаментом юстиции Туркестанской области 18 марта 2021 года № 6105. Утратило силу решением акима Первомаевского сельского округа Толебийского района Туркестанской области от 22 октября 2021 года № 56 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий по бруцеллезу на улице Аль-Фараби в населенном пункте Загамбар Первомаевского сельского округа
  kaz: Бірінші Мамыр ауылдық округі Зағамбар елді мекені Әл-Фараби көшесінде бруцеллез бойынша шектеу шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-03-18
approved_by:
- '166011005002'
version_date:
  kaz: 2021-03-18
  rus: 2021-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/153597/kaz/18.03.2021
  rus: https://zan.gov.kz/client/#!/doc/153597/rus/18.03.2021
