act_code: '193692'
requisite: Решение Сайрамского районного маслихата Туркестанской области от 22 февраля 2024 года № 12-98/VIII. Зарегистрировано в Департаменте юстиции Туркестанской области 27 февраля 2024 года № 6471-13
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-22
approved_by:
- '166008000002'
version_date:
  kaz: 2025-04-22
  rus: 2025-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/193692/kaz/22.04.2025
  rus: https://zan.gov.kz/client/#!/doc/193692/rus/22.04.2025
caused_by:
  code: '209435'
  requisite: Решение Сайрамского районного маслихата Туркестанской области от 22 апреля 2025 года № 27-200/VIII. Зарегистрировано в Департаменте юстиции Туркестанской области 24 апреля 2025 года № 6688-13
  title:
    rus: О внесении изменения в решение Сайрамского районного маслихата от 22 февраля 2024 года № 12-98/VIII «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Сайрам аудандық мәслихатының 2024 жылғы 22 ақпандағы № 12-98/VIII «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидасын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209435/rus
