act_code: '139804'
requisite: Решение акима сельского округа Алгабас акимата Байдибекского района Туркестанской области от 20 февраля 2020 года № 02. Зарегистрировано Департаментом юстиции Туркестанской области 20 февраля 2020 года № 5435
title:
  rus: О присвоении найменования безымянной улице
  kaz: Атауы жоқ көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-02-20
approved_by:
- '166003003002'
version_date:
  kaz: 2020-02-20
  rus: 2020-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/139804/kaz/20.02.2020
  rus: https://zan.gov.kz/client/#!/doc/139804/rus/20.02.2020
