act_code: '127721'
requisite: Решение Отрарского районного маслихата Туркестанской области от 21 декабря 2018 года № 34/168-VI. Зарегистрировано Департаментом юстиции Туркестанской области 26 декабря 2018 года № 4855
title:
  rus: О районном бюджете на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-21
approved_by:
- '166007000002'
version_date:
  kaz: 2019-06-19
  rus: 2019-06-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/127721/kaz/19.06.2019
  rus: https://zan.gov.kz/client/#!/doc/127721/rus/19.06.2019
caused_by:
  code: '132948'
  requisite: Решение Отрарского районного маслихата Туркестанской области от 19 июня 2019 года № 42/201-VI. Зарегистрировано Департаментом юстиции Туркестанской области 28 июня 2019 года № 5111
  title:
    rus: О внесении изменений в решение Отрарского районного маслихата от 21 декабря 2018 года № 34/168-VІ «О районном бюджете на 2019-2021 годы»
    kaz: Отырар аудандық мәслихатының 2018 жылғы 21 желтоқсандағы № 34/168-VІ «2019-2021 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132948/rus
