act_code: '212019'
requisite: Решение Жетысайского районного маслихата Туркестанской области от 27 июня 2025 года № 30-187-VIII
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию в Жетысайском районе на 2025-2029 годы
  kaz: Жетісай ауданының жайылымдарды басқару және оларды пайдалану жөніндегі 2025-2029 жылдарға арналған жоспарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-06-27
approved_by:
- '166017000002'
version_date:
  kaz: 2025-06-27
  rus: 2025-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/212019/kaz/27.06.2025
  rus: https://zan.gov.kz/client/#!/doc/212019/rus/27.06.2025
