act_code: '50157'
requisite: Оңтүстік Қазақстан облысы Кентау қалалық мәслихатының 2009 жылғы 25 желтоқсандағы N 185 шешімі. Оңтүстік Қазақстан облысы Кентау қаласының Әділет басқармасында 2010 жылғы 18 қаңтарда N 14-3-81 тіркелді
title:
  rus: 2010-2012 жылдарға арналған қалалық бюджет туралы
  kaz: 2010-2012 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '166014000002'
version_date:
  kaz: 2010-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/50157/kaz/19.03.2010
caused_by:
  code: '51533'
  requisite: Оңтүстік Қазақстан облысы Кентау қалалық мәслихатының 2010 жылғы 19 наурыздағы N 206 шешімі. Оңтүстік Қазақстан облысы Кентау қаласының Әділет басқармасында 2010 жылғы 30 наурызда N 14-3-85 тіркелді
  title:
    rus: Кентау қалалық мәслихатының 2009 жылғы 25 желтоқсандағы N 185 "2010-2012 жылдарға арналған қалалық бюджет туралы" шешіміне өзгерістер енгізу туралы
    kaz: Кентау қалалық мәслихатының 2009 жылғы 25 желтоқсандағы N 185 "2010-2012 жылдарға арналған қалалық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/51533/rus
