act_code: '142514'
requisite: Решение акима Сайрамского района Туркестанской области от 30 апреля 2020 года № 14. Зарегистрировано Департаментом юстиции Туркестанской области 4 мая 2020 года № 5594
title:
  rus: Об образовании избирательных участков
  kaz: Сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-04-30
approved_by:
- '166008000003'
version_date:
  kaz: 2023-01-10
  rus: 2023-01-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/142514/kaz/10.01.2023
  rus: https://zan.gov.kz/client/#!/doc/142514/rus/10.01.2023
caused_by:
  code: '177763'
  requisite: Решение акима Сайрамского района Туркестанской области от 10 января 2023 года № 2. Зарегистрировано Департаментом юстиции Туркестанской области 10 января 2023 года № 6227
  title:
    rus: О внесении изменений и дополнений в решение акима Сайрамского района от 30 апреля 2020 года № 14 «Об образовании избирательных участков»
    kaz: Сайрам ауданы әкімінің 2020 жылғы 30 сәуірдегі № 14 «Сайлау учаскелерін құру туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/177763/rus
