act_code: '125338'
requisite: Решение Отрарского районного маслихата Туркестанской области от 27 сентября 2018 года № 30/157-VI. Зарегистрировано Департаментом юстиции Туркестанской области 11 октября 2018 года № 4760. Утратило силу решением Отрарского районного маслихата Туркестанской области от 13 февраля 2020 года № 52/246-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О предоставлении социальной помощи на оплату коммунальных услуг и приобретение топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Отрарского района
  kaz: Отырар ауданының ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебінен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алуға әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-09-27
approved_by:
- '166007000002'
version_date:
  kaz: 2018-09-27
  rus: 2018-09-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/125338/kaz/27.09.2018
  rus: https://zan.gov.kz/client/#!/doc/125338/rus/27.09.2018
