act_code: '198697'
requisite: Решение акима сельского округа Бирлик Келесского района Туркестанской области от 12 июля 2024 года № 33
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-07-12
approved_by:
- '166018010002'
version_date:
  kaz: 2024-07-12
  rus: 2024-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/198697/kaz/12.07.2024
  rus: https://zan.gov.kz/client/#!/doc/198697/rus/12.07.2024
