act_code: '60013'
requisite: Оңтүстік Қазақстан облысы Мақтаарал аудандық мәслихатының 2011 жылғы 10 тамыздағы N 48-328-IV шешімі. Оңтүстік Қазақстан облысы Мақтаарал ауданының Әділет басқармасында 2011 жылғы 12 тамызда N 14-7-148 тіркелді
title:
  rus: Мақтаарал аудандық мәслихатының 2010 жылғы 22 желтоқсандағы "2011-2013 жылдарға арналған аудандық бюджет туралы" № 40-259-IV шешіміне өзгерістер  енгізу туралы
  kaz: Мақтаарал аудандық мәслихатының 2010 жылғы 22 желтоқсандағы "2011-2013 жылдарға арналған аудандық бюджет туралы" № 40-259-IV шешіміне өзгерістер  енгізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-08-10
approved_by:
- '166005000002'
version_date:
  kaz: 2012-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/60013/kaz/01.01.2012
