act_code: '121126'
requisite: Решение Тюлькубасского районного маслихата Южно-Казахстанской области от 13 апреля 2018 года № 26/3-06. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 23 апреля 2018 года № 4565
title:
  rus: Об утверждении Регламента собрания местного сообщества сельских округов и поселков Тюлькубасского района
  kaz: Түлкібас ауданының ауылдық округтері мен кенттерінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-04-13
approved_by:
- '166012000002'
version_date:
  kaz: 2024-08-07
  rus: 2024-08-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/121126/kaz/07.08.2024
  rus: https://zan.gov.kz/client/#!/doc/121126/rus/07.08.2024
caused_by:
  code: '199539'
  requisite: Решение Тюлькубасского районного маслихата Туркестанской области от 7 августа 2024 года № 22/3-08
  title:
    rus: О внесении изменений в решение Тюлькубасского районного маслихата от 13 апреля 2018 года № 26/3-06 «Об утверждении Регламента собрания местного сообщества сельских и поселковых округов Тюлькубасского района»
    kaz: Түлкібас аудандық мәслихатының 2018 жылғы 13 сәуірдегі № 26/3-06 «Түлкібас ауданының ауылдық және поселкелік округтерінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/199539/rus
