act_code: '184919'
requisite: Решение акима поселка Таукент Созакского района Туркестанской области от 31 июля 2023 года № 22
title:
  rus: Об установление публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-07-31
approved_by:
- '166010004001'
version_date:
  kaz: 2023-07-31
  rus: 2023-07-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/184919/kaz/31.07.2023
  rus: https://zan.gov.kz/client/#!/doc/184919/rus/31.07.2023
