act_code: '153605'
requisite: Решение акима сельского округа Дарбаза Сарыагашского района Туркестанской области от 18 марта 2021 года № 12. Зарегистрировано Департаментом юстиции Туркестанской области 18 марта 2021 года № 6109. Утратило силу решением акима сельского округа Дарбаза Сарыагашского района Туркестанской области от 9 июня 2021 года № 25 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-03-18
approved_by:
- '166009011002'
version_date:
  kaz: 2021-03-18
  rus: 2021-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/153605/kaz/18.03.2021
  rus: https://zan.gov.kz/client/#!/doc/153605/rus/18.03.2021
