act_code: '44876'
requisite: Оңтүстік Қазақстан облысы Сарыағаш аудандық мәслихат сессиясының 2009 жылғы 23 ақпандағы N 21-8-128 шешімі. Оңтүстік Қазақстан облысы Сарыағаш ауданының Әділет басқармасында 2009 жылғы 16 наурызда N 14-11-97 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Сарыағаш аудандық мәслихат сессиясының 2012 жылғы 27 тамыздағы N 9-63-V Шешімімен
title:
  rus: Сарыағаш ауданы бойынша белгіленген жер салығының базалық ставкаларын белгілеу туралы
  kaz: Сарыағаш ауданы бойынша белгіленген жер салығының базалық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-23
approved_by:
- '166009000002'
version_date:
  kaz: 2009-02-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/44876/kaz/23.02.2009
