act_code: '117311'
requisite: Решение Шымкентского городского маслихата Южно-Казахстанской области от 25 декабря 2017 года № 24/192-6с. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 28 декабря 2017 года № 4348
title:
  rus: О бюджете города Шымкент на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған Шымкент қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-25
approved_by:
- '166002000002'
version_date:
  kaz: 2018-09-21
  rus: 2018-09-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/117311/kaz/21.09.2018
  rus: https://zan.gov.kz/client/#!/doc/117311/rus/21.09.2018
caused_by:
  code: '125011'
  requisite: Решение Шымкентского городского маслихата от 21 сентября 2018 года № 37/289-6с. Зарегистрировано Департаментом юстиции Туркестанской области 25 сентября 2018 года № 4738
  title:
    rus: О внесении изменений в решение Шымкентского городского маслихата от 25 декабря 2017 года № 24/192-6с «О бюджете города Шымкент на 2018-2020 годы»
    kaz: Шымкент қалалық мәслихатының 2017 жылғы 25 желтоқсандағы № 24/192-6с «2018-2020 жылдарға арналған Шымкент қаласының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/125011/rus
