act_code: '39799'
requisite: Оңтүстік Қазақстан облысы Төлеби аудандық мәслихатының 2008 жылғы 28 наурыздағы N 5/37-IV шешімі. Оңтүстік Қазақстан облысы Төлеби ауданының Әділет басқармасында 2008 жылғы 4 мамырда N 14-13-41 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Төлеби аудандық мәслихатының 2009 жылғы 12 ақпандағы № 12/88-IV Шешімімен
title:
  rus: Жергілікті маңызы бар жалпыға ортақ пайдаланатын автомобиль жолдарының бөлінген белдеулерінде орналастырылатын және елді мекендерде жарнама объектілері бойынша төлемақы ставкаларын белгілеу туралы
  kaz: Жергілікті маңызы бар жалпыға ортақ пайдаланатын автомобиль жолдарының бөлінген белдеулерінде орналастырылатын және елді мекендерде жарнама объектілері бойынша төлемақы ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-03-28
approved_by:
- '166011000002'
version_date:
  kaz: 2008-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/39799/kaz/28.03.2008
