act_code: '37855'
requisite: Оңтүстік Қазақстан облысы Сайрам аудандық мәслихат сессиясының 2007 жылғы 25 желтоқсандағы N 3-55/IV Шешімі. Оңтүстік Қазақстан облысы Сайрам ауданының Әділет басқармасында 2008 жылғы 4 ақпанда N 14-10-79 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Сайрам аудандық мәслихатының 2013 жылғы 20 желтоқсандағы № 26-167/V шешімімен
title:
  rus: Білім беру ұйымдарының күндізгі оқу нысанында оқитындар мен тәрбиеленушілер үшін қоғамдық көлікте жеңілдікпен жүру туралы
  kaz: Білім беру ұйымдарының күндізгі оқу нысанында оқитындар мен тәрбиеленушілер үшін қоғамдық көлікте жеңілдікпен жүру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-25
approved_by:
- '166008000002'
version_date:
  kaz: 2007-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/37855/kaz/25.12.2007
