act_code: '39643'
requisite: Оңтүстік Қазақстан облысы Шардара аудандық мәслихатының 2008 жылғы 23 сәуірдегі N 7-57-IV шешімі. Оңтүстік Қазақстан облысы Шардара ауданының Әділет басқармасында 2008 жылғы 19 мамырда N 14-15-58 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Шардара аудандық мәслихатының 2009 жылғы 19 ақпандағы N 16/113-IV Шешімімен
title:
  rus: Біржолғы талонның төлемақы ставкаларын белгілеу туралы
  kaz: Біржолғы талонның төлемақы ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-04-23
approved_by:
- '166013000002'
version_date:
  kaz: 2008-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/39643/kaz/23.04.2008
