act_code: '122408'
requisite: Решение Ордабасинского районного маслихата Южно-Казахстанской области от 15 мая 2018 года № 28/3. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 25 мая 2018 года № 4611. Утратило силу решением Ордабасинского районного маслихата Туркестанской области от 27 июня 2023 года № 4/9 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» аппарата Ордабасинского районного маслихата
  kaz: «Б» корпусы Ордабасы аудандық мәслихат аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2018-05-15
approved_by:
- '166006000002'
version_date:
  kaz: 2022-06-28
  rus: 2022-06-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/122408/kaz/28.06.2022
  rus: https://zan.gov.kz/client/#!/doc/122408/rus/28.06.2022
caused_by:
  code: '169575'
  requisite: Решение Ордабасинского районного маслихата Туркестанской области от 28 июня 2022 года № 25/10
  title:
    rus: О внесении изменений в решение Ордабасинского районного маслихата от 15 мая 2018 года № 28/3  «Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» аппарата Ордабасинского районного маслихата
    kaz: Ордабасы ауданының мәслихатының 2018 жылғы 15 мамырдағы № 28/3 «Б» корпусы Ордабасы ауданының мәслихат аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/169575/rus
