act_code: '190182'
requisite: Решение Кентауского городского маслихата Туркестанской области от 15 декабря 2023 года № 64
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества в городе Кентау
  kaz: Кентау қаласында жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-15
approved_by:
- '166014000002'
version_date:
  kaz: 2023-12-15
  rus: 2023-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/190182/kaz/15.12.2023
  rus: https://zan.gov.kz/client/#!/doc/190182/rus/15.12.2023
