act_code: '43396'
requisite: Оңтүстік Қазақстан облысы Шардара аудандық мәслихатының 2008 жылғы 25 желтоқсандағы N 13-94-IV шешімі. Оңтүстік Қазақстан облысы Шардара ауданының Әділет басқармасында 2009 жылғы 9 қаңтарда N 14-15-68 тіркелді
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-25
approved_by:
- '166013000002'
version_date:
  kaz: 2009-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/43396/kaz/27.04.2009
caused_by:
  code: '46008'
  requisite: Оңтүстік Қазақстан облысы Шардара аудандық мәслихатының 2009 жылғы 27 сәуірдегі N 18-137-IV шешімі. Оңтүстік Қазақстан облысы Шардара ауданының Әділет басқармасында 2009 жылғы 15 мамырда N 14-15-73 тіркелді
  title:
    rus: '"2009 жылға арналған аудандық бюджет туралы" Шардара аудандық мәслихатының 2008 жылғы 25 желтоқсандағы N 13-94-IV шешіміне өзгерістер мен толықтырулар енгізу туралы'
    kaz: '"2009 жылға арналған аудандық бюджет туралы" Шардара аудандық мәслихатының 2008 жылғы 25 желтоқсандағы N 13-94-IV шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/46008/rus
