act_code: '9640'
requisite: Решение областного маслихата Южно-Казахстанской области от 27 июня 2001 года за N 11/127-ІІ. Зарегистрировано управлением юстиции Южно-Казахстанской области от 27 июля 2001 года за N 326
title:
  rus: Об установлении границ оценочных зон и поправочных коэффициентов, применяемых к базовым ставкам платы за земельные участки в городах областного значения Туркестанской области
  kaz: Түркістан облысының облыстық маңызы бар қалаларында бағалау аймақтарының шекаралары және жер учаскелері үшін төлемақының базалық ставкасына қолданылатын түзету коэффициенттерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-06-27
approved_by:
- '166000000002'
version_date:
  kaz: 2021-12-10
  rus: 2021-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/9640/kaz/10.12.2021
  rus: https://zan.gov.kz/client/#!/doc/9640/rus/10.12.2021
caused_by:
  code: '161816'
  requisite: Решение Туркестанского областного маслихата от 10 декабря 2021 года № 13/138-VIІ. Зарегистрировано в Министерстве юстиции Республики Казахстан 20 декабря 2021 года № 25822
  title:
    rus: О внесении изменений в решение областного маслихата Южно-Казахстанской области от 27 июня 2001 года № 11/127-ІІ «Об установлении границ оценочных зон и поправочных коэффициентов, применяемых к базовым ставкам платы за земельные участки в городах областного значения Южно-Казахстанской области»
    kaz: Оңтүстік Қазақстан облыстық мәслихатының 2001 жылғы 27 маусымдағы № 11/127-ІІ «Оңтүстік Қазақстан облысының облыстық маңызы бар қалаларында бағалау аймақтарының шекаралары және жер учаскелері үшін төлемақының базалық ставкасына қолданылатын түзету коэффициенттерін белгілеу туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/161816/rus
