act_code: '22543'
requisite: Решение акима Южно-Казахстанской области от 12 января 2005 года № 3. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 13 января 2005 года № 1635. Утратило силу решением акима Южно-Казахстанской области от 10 марта 2006 года № 8
title:
  rus: О квалификационных требованиях к административным государственным должностям
  kaz: Мемлекеттiк әкiмшiлiк лауазымдарға қойылатын бiлiктiлiк талаптары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-01-12
approved_by:
- '166000000003'
version_date:
  kaz: 2005-01-12
  rus: 2005-01-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/22543/kaz/12.01.2005
  rus: https://zan.gov.kz/client/#!/doc/22543/rus/12.01.2005
