act_code: '190339'
requisite: Решение Кентауского городского маслихата Туркестанской области от 15 декабря 2023 года № 68. Зарегистрировано в Департаменте юстиции Туркестанской области 20 декабря 2023 года № 6423-13. Утратило силу решением Кентауского городского маслихата Туркестанской области от 28 марта 2025 года № 178 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-15
approved_by:
- '166014000002'
version_date:
  kaz: 2023-12-15
  rus: 2023-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/190339/kaz/15.12.2023
  rus: https://zan.gov.kz/client/#!/doc/190339/rus/15.12.2023
