act_code: '137499'
requisite: Решение Туркестанского городского маслихата Туркестанской области от 24 декабря 2019 года № 60/288-VI. Зарегистрировано Департаментом юстиции Туркестанской области 26 декабря 2019 года № 5325
title:
  rus: О городском бюджете на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-24
approved_by:
- '166015000002'
version_date:
  kaz: 2019-12-24
  rus: 2019-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/137499/kaz/24.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137499/rus/24.12.2019
