act_code: '85710'
requisite: Решение Толебийского районного маслихата Южно-Казахстанской области от 23 декабря 2014 года № 38/176-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 5 января 2015 года № 2948. Утратило силу в связи с истечением срока применения - (письмо Толебийского районного маслихата Южно-Казахстанской области от 6 января 2016 года № 01)
title:
  rus: О районном бюджете на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-23
approved_by:
- '166011000002'
version_date:
  kaz: 2015-10-30
  rus: 2015-10-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/85710/kaz/30.10.2015
  rus: https://zan.gov.kz/client/#!/doc/85710/rus/30.10.2015
caused_by:
  code: '95228'
  requisite: Решение Толебийского районного маслихата Южно-Казахстанской области от 30 октября 2015 года № 45/222-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 3 ноября 2015 года № 3409. Утратило силу в связи с истечением срока применения - (письмо Толебийского районного маслихата Южно-Казахстанской области от 6 января 2016 года № 01)
  title:
    rus: О внесении изменений в решение Толебийского районного маслихата от 23 декабря 2014 года № 38/176-V "О районном бюджете на 2015-2017 годы"
    kaz: '"2015-2017 жылдарға арналған аудандық бюджет туралы" Төлеби аудандық мәслихатының 2014 жылғы 23 желтоқсандағы № 38/176-V шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/95228/rus
