act_code: '45085'
requisite: Оңтүстік Қазақстан облысы Ордабасы аудандық мәслихатының 2009 жылғы 18 ақпандағы N 15/9 шешімі. Оңтүстік Қазақстан облысы Ордабасы ауданының Әділет басқармасында 2009 жылғы 26 наурызда N 14-8-65 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Ордабасы аудандық мәслихатының 2012 жылғы 20 желтоқсандағы № 11/9 Шешімімен
title:
  rus: Қызметі дүркін-дүркін сипатта болатын және базарларда тауарлар өткізу, жұмыстар орындау, қызметтер көрсету жөніндегі қызметтерді жүзеге асыратын жеке тұлғалар үшін біржолғы талон құнының мөлшері туралы
  kaz: Қызметі дүркін-дүркін сипатта болатын және базарларда тауарлар өткізу, жұмыстар орындау, қызметтер көрсету жөніндегі қызметтерді жүзеге асыратын жеке тұлғалар үшін біржолғы талон құнының мөлшері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-18
approved_by:
- '166006000002'
version_date:
  kaz: 2009-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/45085/kaz/18.02.2009
