act_code: '118800'
requisite: Решение акима сельского округа Шанак Казыгуртского района Южно-Казахстанской области от 5 февраля 2018 года № 2. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 8 февраля 2018 года № 4444
title:
  rus: О присвоении наименования улице
  kaz: Көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-02-05
approved_by:
- '166004013002'
version_date:
  kaz: 2018-02-05
  rus: 2018-02-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/118800/kaz/05.02.2018
  rus: https://zan.gov.kz/client/#!/doc/118800/rus/05.02.2018
