act_code: '135228'
requisite: Решение Туркестанского областного маслихата от 13 сентября 2019 года № 42/436-VI. Зарегистрировано Департаментом юстиции Туркестанской области 8 октября 2019 года № 5202. Утратило силу решением Туркестанского областного маслихата от 10 июля 2023 года № 4/49-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил содержания и защиты зеленых насаждений, Правил благоустройства территорий городов и населенных пунктов Туркестанской области
  kaz: Түркістан облысының жасыл екпелерді күтіп ұстаудың және қорғаудың Қағидаларын, қалалары мен елді мекендерінің аумақтарында абаттандырудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2019-09-13
approved_by:
- '166000000002'
version_date:
  kaz: 2019-09-13
  rus: 2019-09-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/135228/kaz/13.09.2019
  rus: https://zan.gov.kz/client/#!/doc/135228/rus/13.09.2019
