act_code: '55264'
requisite: Оңтүстік Қазақстан облысы Түлкібас аудандық маслихатының 2010 жылғы 3 қарашадағы N 36/3-04 шешімі. Оңтүстік Қазақстан облысы Түлкібас ауданының Әділет басқармасында 2010 жылғы 9 қарашада N 14-14-134 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Түлкібас аудандық мәслихатының 2012 жылғы 11 маусымдағы N 5/8-05 Шешімімен
title:
  rus: Аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшерін және тәртібін бекіту туралы
  kaz: Аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсетудің мөлшерін және тәртібін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-03
approved_by:
- '166012000002'
version_date:
  kaz: 2010-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/55264/kaz/03.11.2010
