act_code: '89524'
requisite: 'Совместное решение Казыгуртского районного маслихата Южно-Казахстанской области от 30 марта 2015 года № 42/286-V и постановление акимата Казыгуртского района Южно-Казахстанской области от 30 марта 2015 года № 3. '
title:
  rus: Об изменении границы населенного пункта Шарапхана сельского округа Шарапхана Казыгуртского района
  kaz: Қазығұрт ауданы, Шарапхана ауыл округі, Шарапхана елді мекенінің шекарасын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-03-30
approved_by:
- '166004000002'
version_date:
  kaz: 2015-03-30
  rus: 2015-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/89524/kaz/30.03.2015
  rus: https://zan.gov.kz/client/#!/doc/89524/rus/30.03.2015
