act_code: '117215'
requisite: Решение Туркестанского городского маслихата Южно-Казахстанской области от 21 декабря 2017 года № 23/125-VI. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 26 декабря 2017 года № 4338
title:
  rus: О городском бюджете на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-21
approved_by:
- '166015000002'
version_date:
  kaz: 2018-07-04
  rus: 2018-07-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/117215/kaz/04.07.2018
  rus: https://zan.gov.kz/client/#!/doc/117215/rus/04.07.2018
caused_by:
  code: '123440'
  requisite: Решение Туркестанского городского маслихата Южно-Казахстанской области от 4 июля 2018 года № 34/179-VI. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 10 июля 2018 года № 4673
  title:
    rus: О внесении изменений в решение Туркестанского городского маслихата от 21 декабря 2017 года № 23/125-VI "О городском бюджете на 2018-2020 годы"
    kaz: Түркістан қалалық мәслихатының 2017 жылғы 21 желтоқсандағы № 23/125-VI "2018-2020 жылдарға арналған қалалық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123440/rus
