act_code: '117215'
requisite: Решение Туркестанского городского маслихата Южно-Казахстанской области от 21 декабря 2017 года № 23/125-VI. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 26 декабря 2017 года № 4338
title:
  rus: О городском бюджете на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-21
approved_by:
- '166015000002'
version_date:
  kaz: 2018-06-12
  rus: 2018-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/117215/kaz/12.06.2018
  rus: https://zan.gov.kz/client/#!/doc/117215/rus/12.06.2018
caused_by:
  code: '122607'
  requisite: Решение Туркестанского городского маслихата Южно-Казахстанской области от 12 июня 2018 года № 31/168-VI. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 15 июня 2018 года № 4636
  title:
    rus: О внесении изменений в решение Туркестанского городского маслихата от 21 декабря 2017 года № 23/125-VІ "О городском бюджете на 2018-2020 годы"
    kaz: Түркістан қалалық мәслихатының 2017 жылғы 21 желтоқсандағы № 23/125-VІ "2018-2020 жылдарға арналған қалалық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/122607/rus
