act_code: '39832'
requisite: Решение Шымкентского городского маслихата Южно-Казахстанской области от 14 апреля 2008 года N 9/78-4с. Зарегистрировано Управлением юстиции города Шымкента Южно-Казахстанской области 27 мая 2008 года N 14-1-77. Утратило силу решением Шымкентского городского маслихата Южно-Казахстанской области от 17 мая 2012 года № 7/53-5с
title:
  rus: О правилах благоустройства территории города Шымкент
  kaz: Шымкент қаласының аумағын абаттандыру Қағидасы туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2008-04-14
approved_by:
- '166002000002'
version_date:
  kaz: 2011-06-13
  rus: 2011-06-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/39832/kaz/13.06.2011
  rus: https://zan.gov.kz/client/#!/doc/39832/rus/13.06.2011
caused_by:
  code: '59587'
  requisite: Решение Шымкентского городского маслихата Южно-Казахстанской области от 13 июня 2011 года N 50/419-4с. Зарегистрировано Управлением юстиции города Шымкента Южно-Казахстанской области 13 июля 2011 года N 14-1-140. Утратило силу решением Шымкентского городского маслихата Южно-Казахстанской области от 17 мая 2012 года № 7/53-5с
  title:
    rus: О внесении изменений и дополнений в решение Шымкентского городского маслихата от 14 апреля 2008 года N 9/78-4c "О правилах благоустройства территории города Шымкент"
    kaz: Қалалық мәслихаттың 2008 жылғы 14 сәуірдегі "Шымкент қаласының аумағын абаттандыру Қағидасы туралы" № 9/78-4с шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/59587/rus
