act_code: '144994'
requisite: Решение Тюлькубасского районного маслихата Туркестанской области от 23 июня 2020 года № 56/1-06. Зарегистрировано Департаментом юстиции Туркестанской области 16 июля 2020 года № 5717
title:
  rus: О порядке организации и проведения мирных собраний в Тюлькубасском районе
  kaz: Түлкібас ауданында бейбіт жиналыстарды ұйымдастыру және өткізу тәртібі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-23
approved_by:
- '166012000002'
version_date:
  kaz: 2020-06-23
  rus: 2020-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/144994/kaz/23.06.2020
  rus: https://zan.gov.kz/client/#!/doc/144994/rus/23.06.2020
