act_code: '214095'
requisite: Решение акима сельского округа Сызган Созакского района Туркестанской области от 9 сентября 2025 года № 41
title:
  rus: О названии улиц
  kaz: Көше атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-09
approved_by:
- '166010005002'
version_date:
  kaz: 2025-09-09
  rus: 2025-09-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/214095/kaz/09.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214095/rus/09.09.2025
