act_code: '58653'
requisite: Оңтүстік Қазақстан облысы Шардара аудандық мәслихатының 2011 жылғы 30 наурыздағы N 41-326-IV шешімі. Оңтүстік Қазақстан облысы Шардара ауданының Әділет басқармасында 2011 жылғы 29 сәуірде N 14-15-114 тіркелді. Күші жойылды - Шардара аудандық мәслихатының 2012 жылғы 24 ақпандағы N 2-11-V Шешімімен
title:
  rus: Елді мекендердің жерлеріне салынатын базалық салық ставкалары туралы
  kaz: Елді мекендердің жерлеріне салынатын базалық салық ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-03-30
approved_by:
- '166013000002'
version_date:
  kaz: 2011-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/58653/kaz/30.03.2011
