act_code: '88419'
requisite: Решение от 27.03.2015 №35/205-V, Маслихат Отырарского района. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 7 апреля 2015 года № 3112. Утратило силу решением Отрарского районного маслихата Южно-Казахстанской области от 29 декабря 2015 года № 43/248-V
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов, тарифов на сбор, вывоз, захоронение и утилизацию коммунальных отходов по Отрарскому району
  kaz: Отырар ауданы бойынша коммуналдық қалдықтардың пайда болу және жинақталу нормаларын, коммуналдық қалдықтарды жинау, әкету, көму және кәдеге жарату тарифтерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-03-27
approved_by:
- '166007000002'
version_date:
  kaz: 2015-03-27
  rus: 2015-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/88419/kaz/27.03.2015
  rus: https://zan.gov.kz/client/#!/doc/88419/rus/27.03.2015
