act_code: '118534'
requisite: Решение акима Байдибекского района Южно-Казахстанской области от 23 января 2018 года № 03. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 2 февраля 2018 года № 4438. Утратило силу постановлением акима Байдибекского района Туркестанской области от 26 октября 2018 года № 22
title:
  rus: Об объявлении на территории сельского округа Боралдай Байдибекского района чрезвычайных ситуаций местного масштаба
  kaz: Бәйдібек ауданының Боралдай ауылдық округі аумағында жергілікті ауқымдағы төтенше жағдай жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-01-23
approved_by:
- '166003000003'
version_date:
  kaz: 2018-01-23
  rus: 2018-01-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/118534/kaz/23.01.2018
  rus: https://zan.gov.kz/client/#!/doc/118534/rus/23.01.2018
