act_code: '100499'
requisite: Решение Арысского городского маслихата Южно-Казахстанской области от 4 марта 2016 года № 52/309-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 18 марта 2016 года № 3646. Утратило силу решением Арысского городского маслихата Южно-Казахстанской области от 24 марта 2017 года № 11/75-VI
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» аппарата Арысского городского маслихата
  kaz: «Б» корпусы Арыс қалалық мәслихат аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-03-04
approved_by:
- '166016000002'
version_date:
  kaz: 2016-03-04
  rus: 2016-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/100499/kaz/04.03.2016
  rus: https://zan.gov.kz/client/#!/doc/100499/rus/04.03.2016
