act_code: '126084'
requisite: Решение акима Байдибекского района Туркестанской области от 12 ноября 2018 года № 23. Зарегистрировано Департаментом юстиции Туркестанской области 14 ноября 2018 года № 4779. Утратило силу решением акима Байдибекского района Туркестанской области от 11 декабря 2020 года № 18 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об образовании избрательных участков на территории Байдибекского района
  kaz: Бәйдібек ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-12
approved_by:
- '166003000003'
version_date:
  kaz: 2018-11-12
  rus: 2018-11-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/126084/kaz/12.11.2018
  rus: https://zan.gov.kz/client/#!/doc/126084/rus/12.11.2018
