act_code: '38482'
requisite: Оңтүстік Қазақстан облысы Мақтаарал ауданы Аязхан Қалыбеков ауылдық округі әкімінің 2007 жылғы 17 қыркүйектегі N 2 шешімі. Оңтүстік Қазақстан облысы Мақтаарал ауданының Әділет басқармасында 2007 жылғы 20 қыркүйекте N 14-7-47 тіркелді
title:
  rus: Абат ауылындағы үшінші көшеге Қосалы Жұмановтың есімін беру туралы
  kaz: Абат ауылындағы үшінші көшеге Қосалы Жұмановтың есімін беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-09-17
approved_by:
- '166005004001'
version_date:
  kaz: 2007-09-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/38482/kaz/17.09.2007
