act_code: '176219'
requisite: Решение Казыгуртского районного маслихата Туркестанской области от 23 декабря 2022 года № 35/154-VII
title:
  rus: О районном бюджете на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-23
approved_by:
- '166004000002'
version_date:
  kaz: 2023-11-07
  rus: 2023-11-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/176219/kaz/07.11.2023
  rus: https://zan.gov.kz/client/#!/doc/176219/rus/07.11.2023
caused_by:
  code: '188116'
  requisite: Решение Казыгуртского районного маслихата Туркестанской области от 7 ноября 2023 года № 7/45-VIII
  title:
    rus: О внесении изменений в решение Казыгуртского районного маслихата от 23 декабря 2022 года № 35/154-VII «О районном бюджете на 2023-2025 годы»
    kaz: Қазығұрт аудандық мәслихатының 2022 жылғы 23 желтоқсандағы № 35/154-VII «2023-2025 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/188116/rus
