act_code: '33947'
requisite: Оңтүстiк Қазақстан облысы Кентау қалалық мәслихатының 2007 жылғы 28 мамырдағы № 235 шешiмi. Оңтүстік Қазақстан облысы Кентау қаласының Әділет басқармасында 2007 жылғы 25 маусымда № 14-3-41 болып тіркелді
title:
  rus: Жергілікті бюджеттен қаржыландырылатын, ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік ұйымдарының мамандарына отын сатып алуға әлеуметтік көмек беру туралы
  kaz: Жергілікті бюджеттен қаржыландырылатын, ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік ұйымдарының мамандарына отын сатып алуға әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-05-28
approved_by:
- '166014000002'
version_date:
  kaz: 2007-05-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/33947/kaz/28.05.2007
