act_code: '191299'
requisite: Решение Шардаринского районного маслихата Туркестанской области от 25 декабря 2023 года № 16-82-VIII
title:
  rus: «О бюджете города, сельских округов на 2024-2026 годы»
  kaz: «2024-2026 жылдарға арналған қала, ауылдық округтердің бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-25
approved_by:
- '166013000002'
version_date:
  kaz: 2024-07-02
  rus: 2024-07-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/191299/kaz/02.07.2024
  rus: https://zan.gov.kz/client/#!/doc/191299/rus/02.07.2024
caused_by:
  code: '198449'
  requisite: Решение Шардаринского районного маслихата Туркестанской области от 2 июля 2024 года № 25-128-VIII
  title:
    rus: О внесении изменений в решение Шардаринского районного маслихата от 25 декабря 2023 года № 16-82-VIII «О бюджете города, сельских округов на 2024-2026 годы»
    kaz: Шардара аудандық мәслихатының 2023 жылғы 25 желтоқсандағы № 16-82-VІІІ «2024-2026 жылдарға арналған қала, ауылдық округтердің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198449/rus
