act_code: '46009'
requisite: Оңтүстік Қазақстан облысы Шардара аудандық мәслихатының 2009 жылғы 27 сәуірдегі N 18-142-IV шешімі. Оңтүстік Қазақстан облысы Шардара ауданының Әділет басқармасында 2009 жылғы 20 мамырда N 14-15-74 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Шардара аудандық мәслихатының 2012 жылғы 21 желтоқсандағы № 11-76-V Шешімімен
title:
  rus: Біржолғы талондардың құнын белгілеу туралы
  kaz: Біржолғы талондардың құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-27
approved_by:
- '166013000002'
version_date:
  kaz: 2009-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/46009/kaz/27.04.2009
