act_code: '46009'
requisite: Оңтүстік Қазақстан облысы Шардара аудандық мәслихатының 2009 жылғы 27 сәуірдегі N 18-142-IV шешімі. Оңтүстік Қазақстан облысы Шардара ауданының Әділет басқармасында 2009 жылғы 20 мамырда N 14-15-74 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Шардара аудандық мәслихатының 2012 жылғы 21 желтоқсандағы № 11-76-V Шешімімен
title:
  rus: Біржолғы талондардың құнын белгілеу туралы
  kaz: Біржолғы талондардың құнын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-27
approved_by:
- '166013000002'
version_date:
  kaz: 2011-10-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/46009/kaz/04.10.2011
caused_by:
  code: '60804'
  requisite: Оңтүстік Қазақстан облысы Шардара аудандық мәслихатының 2011 жылғы 4 қазандағы N 47-353-IV шешімі. Оңтүстік Қазақстан облысы Шардара ауданының Әділет басқармасында 2011 жылғы 14 қазанда N 14-15-121 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Шардара аудандық мәслихатының 2012 жылғы 21 желтоқсандағы № 11-76-V Шешімімен
  title:
    rus: Шардара аудандық мәслихатының 2009 жылғы 27 сәуірдегі № 18-142-ІV "Біржолғы талонның төлемақы ставкаларын белгілеу туралы" шешіміне өзгерістер енгізу туралы
    kaz: Шардара аудандық мәслихатының 2009 жылғы 27 сәуірдегі № 18-142-ІV "Біржолғы талонның төлемақы ставкаларын белгілеу туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/60804/rus
