act_code: '117396'
requisite: Решение Тюлькубасского районного маслихата Южно-Казахстанской области от 22 декабря 2017 года № 21/1-06. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 29 декабря 2017 года № 4358
title:
  rus: О районном бюджете на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-22
approved_by:
- '166012000002'
version_date:
  kaz: 2018-09-14
  rus: 2018-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/117396/kaz/14.09.2018
  rus: https://zan.gov.kz/client/#!/doc/117396/rus/14.09.2018
caused_by:
  code: '124863'
  requisite: Решение Тюлькубасского районного маслихата Туркестанской области от 14 сентября 2018 года № 30/1-06. Зарегистрировано Департаментом юстиции Туркестанской области 25 сентября 2018 года № 4742
  title:
    rus: О внесении изменений в решение Тюлькубасского районного маслихата от 22 декабря 2017 года № 21/1-06 «О районном бюджете на 2018-2020 годы»
    kaz: Түлкібас аудандық мәслихатының 2017 жылғы 22 желтоқсандағы № 21/1-06 «2018-2020 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/124863/rus
