act_code: '55793'
requisite: Оңтүстік Қазақстан облысы Бәйдібек ауданы әкімдігі Боралдай ауылдық округі әкімінің 2010 жылғы 2 қарашадағы N 102 шешімі. Оңтүстік Қазақстан облысы Бәйдібек ауданының Әділет басқармасында 2010 жылғы 7 желтоқсанда N 14-5-103 тіркелді
title:
  rus: Көшеге ат қою туралы
  kaz: Көшеге ат қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-02
approved_by:
- '166003007001'
version_date:
  kaz: 2010-11-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/55793/kaz/02.11.2010
