act_code: '51534'
requisite: Оңтүстік Қазақстан облысы Арыс қалалық мәслихатының 2010 жылғы 19 наурыздағы N 32/194-IV шешімі. Оңтүстік Қазақстан облысы Арыс қаласының Әділет басқармасында 2010 жылғы 30 наурызда N 14-2-90 тіркелді
title:
  rus: Арыс қалалық мәслихатының 2009 жылғы 21 желтоқсандағы N 28/164-IV "2010-2012 жылдарға арналған қалалық бюджет туралы" шешіміне өзгерістер  енгізу туралы
  kaz: Арыс қалалық мәслихатының 2009 жылғы 21 желтоқсандағы N 28/164-IV "2010-2012 жылдарға арналған қалалық бюджет туралы" шешіміне өзгерістер  енгізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-19
approved_by:
- '166016000002'
version_date:
  kaz: 2010-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/51534/kaz/19.03.2010
