act_code: '48785'
requisite: Оңтүстік Қазақстан облысы Шардара ауданы әкімдігі Жаушықұм ауылдық округі әкімінің 2009 жылғы 11 қарашадағы N 16 Шешімі. Оңтүстік Қазақстан облысы Шардара ауданының Әділет басқармасында 2009 жылғы 25 қарашада N 14-15-80 тіркелді
title:
  rus: Жаушықұм ауылдық округіне қарасты Құйған, Жаушықұм, Бағыскөл, Қалғансыр ауылдарындағы көшелерге атау беру туралы
  kaz: Жаушықұм ауылдық округіне қарасты Құйған, Жаушықұм, Бағыскөл, Қалғансыр ауылдарындағы көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-11-11
approved_by:
- '166013011001'
version_date:
  kaz: 2009-11-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/48785/kaz/11.11.2009
