act_code: '131691'
requisite: Решение Арысского городского маслихата Туркестанской области от 8 мая 2019 года № 36/251-VI. Зарегистрировано Департаментом юстиции Туркестанской области 16 мая 2019 года № 5053. Утратило силу решением Арысского городского маслихата Туркестанской области от 12 сентября 2019 года № 39/274-VI
title:
  rus: О дополнительном регламентировании порядка проведения мирных собраний, митингов, шествий, пикетов и демонстраций
  kaz: Бейбіт жиналыстар, митингілер, шерулер, пикеттер мен демонстрациялар өткізу тәртібін қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-05-08
approved_by:
- '166016000002'
version_date:
  kaz: 2019-05-08
  rus: 2019-05-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/131691/kaz/08.05.2019
  rus: https://zan.gov.kz/client/#!/doc/131691/rus/08.05.2019
