act_code: '100465'
requisite: Решение Туркестанского городского маслихата Южно-Казахстанской области от 15 марта 2016 года № 55/308-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 17 марта 2016 года № 3643. Утратило силу решением Туркестанского городского маслихата Южно-Казахстанской области от 17 апреля 2017 года № 15/87-VI
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» аппарата Туркестанского городского маслихата
  kaz: «Б» корпусы Түркістан қалалық мәслихат аппаратының мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2016-03-15
approved_by:
- '166015000002'
version_date:
  kaz: 2016-03-15
  rus: 2016-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/100465/kaz/15.03.2016
  rus: https://zan.gov.kz/client/#!/doc/100465/rus/15.03.2016
