act_code: '101052'
requisite: Решение акима Жибек-Жолынского сельского округа Сайрамского района Южно-Казахстанской области от 29 февраля 2016 года № 6. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 7 апреля 2016 года № 3695
title:
  rus: О присвоении имени Асана Алсеитова безымянной улице села Жибек жолы Сайрамского района
  kaz: Сайрам ауданы, Жібек жолы ауылындағы атауы жоқ көшеге Асан Алсеитовтың есімін беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-02-29
approved_by:
- '166008006001'
version_date:
  kaz: 2016-02-29
  rus: 2016-02-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/101052/kaz/29.02.2016
  rus: https://zan.gov.kz/client/#!/doc/101052/rus/29.02.2016
