act_code: '116702'
requisite: Решение Южно-Казахстанского областного маслихата от 11 декабря 2017 года № 18/209-VI. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 12 декабря 2017 года № 4305
title:
  rus: Об областном бюджете на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-11
approved_by:
- '166000000002'
version_date:
  kaz: 2018-11-09
  rus: 2018-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/116702/kaz/09.11.2018
  rus: https://zan.gov.kz/client/#!/doc/116702/rus/09.11.2018
caused_by:
  code: '126282'
  requisite: Решение Туркестанского областного маслихата от 9 ноября 2018 года № 31/336-VI. Зарегистрировано Департаментом юстиции Туркестанской области 14 ноября 2018 года № 4780
  title:
    rus: О внесении изменений в решение Южно-Казахстанского областного маслихата от 11 декабря 2017 года № 18/209-VI «Об областном бюджете на 2018-2020 годы»
    kaz: Оңтүстік Қазақстан облыстық мәслихатының 2017 жылғы 11 желтоқсандағы № 18/209-VI «2018-2020 жылдарға арналған облыстық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/126282/rus
