act_code: '47244'
requisite: Оңтүстік Қазақстан облысы Түркістан қалалық мәслихатының 2009 жылғы 30 маусымдағы N 19/152-IV шешімі. Оңтүстік Қазақстан облысы Түркістан қаласының Әділет басқармасында 2009 жылғы 7 мамызда N 14-4-71 тіркелді. Күші жойылды - Оңтүстік Қазақстан облысы Түркістан қалалық мәслихатының 2010 жылғы 14 қыркүйектегі № 37/252-IV шешімімен
title:
  rus: Түркістан қаласында жануарларды ұстау Қағидасын бекіту туралы
  kaz: Түркістан қаласында жануарларды ұстау Қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-06-30
approved_by:
- '166015000002'
version_date:
  kaz: 2009-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/47244/kaz/30.06.2009
