act_code: '39874'
requisite: Решение Шымкентского городского маслихата от 14 апреля 2008 года N 9/79-4с. Зарегистрировано Управлением юстиции города Шымкента 27 мая 2008 года N 14-1-78. Утратило силу решением Шымкентского городского маслихата Южно-Казахстанской области от 15 апреля 2010 года N 34/315-4c
title:
  rus: О Правилах содержания и защиты зеленых насаждений города Шымкента
  kaz: Шымкент қаласының жасыл желектерді күтіп ұстау мен қорғау Қағидасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-04-14
approved_by:
- '166002000002'
version_date:
  kaz: 2008-04-14
  rus: 2008-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/39874/kaz/14.04.2008
  rus: https://zan.gov.kz/client/#!/doc/39874/rus/14.04.2008
