act_code: '128496'
requisite: Решение Созакского районного маслихата Туркестанской области от 27 декабря 2018 года № 216. Зарегистрировано Департаментом юстиции Туркестанской области 10 января 2019 года № 4877
title:
  rus: О бюджете сельских округов и поселков на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған ауылдық округтер және кенттер бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-27
approved_by:
- '166010000002'
version_date:
  kaz: 2019-12-04
  rus: 2019-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/128496/kaz/04.12.2019
  rus: https://zan.gov.kz/client/#!/doc/128496/rus/04.12.2019
caused_by:
  code: '136852'
  requisite: Решение Созакского районного маслихата Туркестанской области от 4 декабря 2019 года № 281. Зарегистрировано Департаментом юстиции Туркестанской области 6 декабря 2019 года № 5288
  title:
    rus: О внесении изменений в решение Созакского районного маслихата от 27 декабря 2018 года № 216 «О бюджете сельских округов и поселков на 2019-2021 годы»
    kaz: Созақ аудандық мәслихатының 2018 жылғы 27 желтоқсандағы № 216 «2019-2021 жылдарға арналған ауылдық округтер және кенттер бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136852/rus
