act_code: '168589'
requisite: Решение Мактааральского районного маслихата Туркестанской области от 11 апреля 2022 года № 19-115-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 12 апреля 2022 года № 27536. Утратило силу решением Мактааральского районного маслихата Туркестанской области от 3 ноября 2023 года № 8-59-VIII (вводится в действие по истечении десяти календарных дней со дня его первого официального опубликования)
title:
  rus: Об установлении специалистам в области социального обеспечения и культуры, являющимся гражданскими служащими и работающим в сельских населенных пунктах, а также специалистам, работающим в государственных организациях, финансируемых из местных бюджетов повышенные на двадцать пять процентов оклады и тарифные ставки по сравнению со ставками специалистов, занимающихся этими видами деятельности в городских условиях
  kaz: Азаматтық қызметші болып табылатын және ауылдық елдi мекендерде жұмыс iстейтiн әлеуметтiк қамсыздандыру және мәдениет саласындағы мамандарға, сондай-ақ жергілікті бюджеттерден қаржыландырылатын мемлекеттік ұйымдарда жұмыс істейтін мамандарға қызметтiң осы түрлерiмен қалалық жағдайда айналысатын мамандардың мөлшерлемелерімен салыстырғанда жиырма бес пайызға жоғарылатылған айлықақылар мен тарифтiк мөлшерлемелер белгiлеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-04-11
approved_by:
- '166005000002'
version_date:
  kaz: 2022-04-11
  rus: 2022-04-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/168589/kaz/11.04.2022
  rus: https://zan.gov.kz/client/#!/doc/168589/rus/11.04.2022
