act_code: '97298'
requisite: Решение Толебийского районного маслихата Южно-Казахстанской области от 11 декабря 2015 года № 46/228-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 24 декабря 2015 года № 3482. Утратило силу решением Толебийского районного маслихата Южно-Казахстанской области от 22 апреля 2016 года № 2/10-VI
title:
  rus: О повышении ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения
  kaz: Пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының мөлшерлемесін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-11
approved_by:
- '166011000002'
version_date:
  kaz: 2015-12-11
  rus: 2015-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/97298/kaz/11.12.2015
  rus: https://zan.gov.kz/client/#!/doc/97298/rus/11.12.2015
