act_code: '54387'
requisite: Оңтүстік Қазақстан облысы Отырар ауданы әкімдігі Отырар ауылдық округі әкімінің 2010 жылғы 16 тамыздағы N 36 шешімі. Оңтүстік Қазақстан облысы Отырар ауданының Әділет басқармасында 2010 жылғы 10 қыркүйекте N 14-9-121 тіркелді
title:
  rus: Көшеге ат қою туралы
  kaz: Көшеге ат қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-08-16
approved_by:
- '166007012001'
version_date:
  kaz: 2010-08-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/54387/kaz/16.08.2010
