act_code: '105278'
requisite: Решение Казыгуртского районного маслихата Южно-Казахстанской области от 8 июля 2016 года № 6/21-VI. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 2 августа 2016 года № 3816. Утратило силу решением Казыгуртского районного маслихата Туркестанской области от 27 февраля 2020 года № 54/336-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2016-07-08
approved_by:
- '166004000002'
version_date:
  kaz: 2019-04-19
  rus: 2019-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/105278/kaz/19.04.2019
  rus: https://zan.gov.kz/client/#!/doc/105278/rus/19.04.2019
caused_by:
  code: '130822'
  requisite: Решение Казыгуртского районного маслихата Туркестанской области от 19 апреля 2019 года № 43/276-VI. Зарегистрировано Департаментом юстиции Туркестанской области 22 апреля 2019 года № 4979. Утратило силу решением Казыгуртского районного маслихата Туркестанской области от 27 февраля 2020 года № 54/336-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Казыгуртского районного маслихата от 08 июля 2016 года № 6/21-VІ «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Қазығұрт аудандық мәслихатының 2016 жылғы 08 шілдедегі № 6/21-VІ «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидасын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130822/rus
