act_code: '125819'
requisite: Решение акима Отрарского района Туркестанской области от 2 ноября 2018 года № 11. Зарегистрировано Департаментом юстиции Туркестанской области 7 ноябаря 2018 года № 4774
title:
  rus: Об образовании избирательных участков на территории Отрарского района
  kaz: Отырар ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-02
approved_by:
- '166007000003'
version_date:
  kaz: 2018-11-02
  rus: 2018-11-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/125819/kaz/02.11.2018
  rus: https://zan.gov.kz/client/#!/doc/125819/rus/02.11.2018
