act_code: '816'
requisite: Решение акима Южно-Казахстанской области от 8 апреля 1998 года № 158. Зарегистрировано Управлением юстиции Южно-Казахстанской области 22 июня 1998 года № 27
title:
  rus: Об очередном призыве граждан на срочную военную службу в апреле-июне 1998 года
  kaz: 1998 жылғы сәуір-маусымда азаматтарды мерзімді әскери қызметке кезекті шақыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-04-07
approved_by:
- '166000000003'
version_date:
  kaz: 1998-04-07
  rus: 1998-04-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/816/kaz/07.04.1998
  rus: https://zan.gov.kz/client/#!/doc/816/rus/07.04.1998
