act_code: '131189'
requisite: Решение Казыгуртского районного маслихата Туркестанской области от 30 апреля 2019 года № 44/282-VI. Зарегистрировано Департаментом юстиции Туркестанской области 30 апреля 2019 года № 5017. Утратило силу решением Казыгуртского районного маслихата Туркестанской области от 22 июня 2020 года № 59/362-VI (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О дополнительном регламентировании порядка проведения мирных собраний, митингов, шествий, пикетов и демонстраций
  kaz: Бейбіт жиналыстар, митингілер, шерулер, пикеттер және демонстрациялар өткізу тәртібін қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-04-30
approved_by:
- '166004000002'
version_date:
  kaz: 2019-04-30
  rus: 2019-04-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/131189/kaz/30.04.2019
  rus: https://zan.gov.kz/client/#!/doc/131189/rus/30.04.2019
