act_code: '162707'
requisite: Решение Келесского районного маслихата Туркестанской области от 24 декабря 2021 года № 10-85-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 30 декабря 2021 года № 26265
title:
  rus: О районном бюджете на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '166018000002'
version_date:
  kaz: 2022-05-24
  rus: 2022-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/162707/kaz/24.05.2022
  rus: https://zan.gov.kz/client/#!/doc/162707/rus/24.05.2022
caused_by:
  code: '168367'
  requisite: Решение Келесского районного маслихата Туркестанской области от 24 мая 2022 года № 14-119-VII
  title:
    rus: О внесении изменений в решение Келесского районного маслихата от 24 декабря 2021 года № 10-85-VIІ «О районном бюджете на 2022-2024 годы»
    kaz: Келес аудандық мәслихатының 2021 жылғы 24 желтоқсандағы № 10-85-VIІ «2022-2024 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/168367/rus
