act_code: '205917'
requisite: Решение Арысского городского маслихата Туркестанской области от 27 декабря 2024 года № 28/159-VІІІ
title:
  rus: О бюджетах сельских округов на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған ауылдық округтердің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '166016000002'
version_date:
  kaz: 2024-12-27
  rus: 2024-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/205917/kaz/27.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205917/rus/27.12.2024
