act_code: '79260'
requisite: Решение Отрарского районного маслихата Южно-Казахстанской области от 31 марта 2014 года № 24/145-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 29 апреля 2014 года № 2645. Утратило силу решением Отрарского районного маслихата Южно-Казахстанской области от 11 июля 2016 года № 3/19-VI
title:
  rus: Об утверждении регламента Отрарского районного маслихата
  kaz: Отырар аудандық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-03-31
approved_by:
- '166007000002'
version_date:
  kaz: 2014-03-31
  rus: 2014-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/79260/kaz/31.03.2014
  rus: https://zan.gov.kz/client/#!/doc/79260/rus/31.03.2014
