act_code: '187948'
requisite: Решение Ордабасинского районного маслихата Туркестанской области от 2 ноября 2023 года № 8/3. Зарегистрировано в Департаменте юстиции Туркестанской области 6 ноября 2023 года № 6391-13
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-11-02
approved_by:
- '166006000002'
version_date:
  kaz: 2025-04-28
  rus: 2025-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/187948/kaz/28.04.2025
  rus: https://zan.gov.kz/client/#!/doc/187948/rus/28.04.2025
caused_by:
  code: '209741'
  requisite: Решение Ордабасинского районного маслихата Туркестанской области от 28 апреля 2025 года № 31/2. Зарегистрировано в Департаменте юстиции Туркестанской области 2 мая 2025 года № 6697-13
  title:
    rus: О внесении изменения в решение Ордабасынского районного маслихата Туркестанской области от 2 ноября 2023 года № 8/3 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Түркістан облысы Ордабасы аудандық мәслихатының 2023 жылғы 2 қарашадағы № 8/3 «Әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209741/rus
