act_code: '187948'
requisite: Решение Ордабасинского районного маслихата Туркестанской области от 2 ноября 2023 года № 8/3. Зарегистрировано в Департаменте юстиции Туркестанской области 6 ноября 2023 года № 6391-13
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-11-02
approved_by:
- '166006000002'
version_date:
  kaz: 2024-02-19
  rus: 2024-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/187948/kaz/19.02.2024
  rus: https://zan.gov.kz/client/#!/doc/187948/rus/19.02.2024
caused_by:
  code: '193423'
  requisite: Решение Ордабасинского районного маслихата Туркестанской области от 19 февраля 2024 года № 12/4. Зарегистрировано в Департаменте юстиции Туркестанской области 20 февраля 2024 года № 6462-13
  title:
    rus: О внесении изменений в решение Ордабасынского районного маслихата от 2 ноября 2023 года № 8/3 «Об утверждении правил оказания социальной помощи, определения ее размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Ордабасы аудандық мәслихатының 2023 жылғы 2 қарашадағы № 8/3 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/193423/rus
