act_code: '36546'
requisite: Оңтүстік Қазақстан облысы Бәйдібек аудандық мәслихатының 2007 жылғы 25 желтоқсандағы № 4/15 шешімі. Оңтүстік Қазақстан облысы Бәйдібек ауданының Әділет басқармасында 2008 жылғы 9 қаңтарда № 14-5-54 болып тіркелді
title:
  rus: 2008 жылға арналған аудан бюджеті туралы
  kaz: 2008 жылға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-25
approved_by:
- '166003000002'
version_date:
  kaz: 2007-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/36546/kaz/25.12.2007
