act_code: '95460'
requisite: Решение Тюлькубасского районного маслихата Южно-Казахстанской области от 27 октября 2015 года № 44/3-05. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 13 ноября 2015 года № 3426. Утратило силу решением Тюлькубасского районного маслихата Южно-Казахстанской области от 20 января 2016 года № 47/3-05
title:
  rus: 'О повышении ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения '
  kaz: Пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының мөлшерлемесін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-10-27
approved_by:
- '166012000002'
version_date:
  kaz: 2015-10-27
  rus: 2015-10-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/95460/kaz/27.10.2015
  rus: https://zan.gov.kz/client/#!/doc/95460/rus/27.10.2015
