act_code: '358'
requisite: Решение акима Южно-Казахстанской области от 21 марта 1996 года № 49. Зарегистрировано Управлением юстиции Южно-Казахстанской области 20 октября 1997 года № 7. Утратило силу решением акима Южно-Казахстанской области от 28 ноября 2001 года № 225
title:
  rus: О выполнении Постановления Правительства Республики Казахстан от 28 ноября 1995 года № 1600 "О мерах по улучшению сборов средств в Пенсионный фонд республики Казахстан и обеспечению выплат пенсий и пособий"
  kaz: Қазақстан Республикасы Үкiметiнiң 1995 жылғы 28 қарашадағы "Қазақстан Республикасының Зейнетақы қорына қаражат жинауды жақсарту және зейнетақы мен жәрдемақыны төлеудi қамтамасыз ету жөнiндегi шаралар туралы" № 1600 Қаулысын орындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1996-03-21
approved_by:
- '166000000003'
version_date:
  kaz: 1996-03-21
  rus: 1996-03-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/358/kaz/21.03.1996
  rus: https://zan.gov.kz/client/#!/doc/358/rus/21.03.1996
