act_code: '43023'
requisite: Оңтүстік Қазақстан облысы Сарыағаш аудандық мәслихат сессиясының 2008 жылғы 24 желтоқсандағы N 18-4-103 шешімі. Оңтүстік Қазақстан облысы Сарыағаш ауданының Әділет басқармасында 2008 жылғы 25 желтоқсанда N 14-11-93 тіркелді
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '166009000002'
version_date:
  kaz: 2011-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/43023/kaz/18.05.2011
