act_code: '43023'
requisite: Оңтүстік Қазақстан облысы Сарыағаш аудандық мәслихат сессиясының 2008 жылғы 24 желтоқсандағы N 18-4-103 шешімі. Оңтүстік Қазақстан облысы Сарыағаш ауданының Әділет басқармасында 2008 жылғы 25 желтоқсанда N 14-11-93 тіркелді
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '166009000002'
version_date:
  kaz: 2009-12-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/43023/kaz/01.12.2009
caused_by:
  code: '49107'
  requisite: Оңтүстік Қазақстан облысы Сарыағаш аудандық мәслихат сессиясының 2009 жылғы 1 желтоқсандағы N 29-194-IV шешімі. Оңтүстік Қазақстан облысы Сарыағаш ауданының Әділет басқармасында 2009 жылғы 2 желтоқсанда N 14-11-114 тіркелді
  title:
    rus: Сарыағаш аудандық мәслихатының 2008 жылғы 24 желтоқсандағы N 18-4-103 "2009 жылға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
    kaz: Сарыағаш аудандық мәслихатының 2008 жылғы 24 желтоқсандағы N 18-4-103 "2009 жылға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/49107/rus
