act_code: '166652'
requisite: Решение Кентауского городского маслихата Туркестанской области от 30 марта 2022 года № 132. Зарегистрировано в Министерстве юстиции Республики Казахстан 19 апреля 2022 года № 27622
title:
  rus: О признании утратившим силу решение Кентауского городского маслихата «О повышении базовых ставок земельного налога и ставок единого земельного налога на неиспользуемые земли сельскохозяйственного назначения» от 25 сентября 2020 года № 376
  kaz: Кентау қалалық мәслихатының «Пайдаланылмайтын ауыл шаруашылығы  мақсатындағы жерлерге жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін арттыру туралы» 2020 жылғы 25 қыркүйектегі № 376 шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-03-30
approved_by:
- '166014000002'
version_date:
  kaz: 2022-03-30
  rus: 2022-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/166652/kaz/30.03.2022
  rus: https://zan.gov.kz/client/#!/doc/166652/rus/30.03.2022
