act_code: '162712'
requisite: Решение Жетысайского районного маслихата Туркестанской области от 24 декабря 2021 года № 16-94-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 31 декабря 2021 года № 26291
title:
  rus: О районном бюджете на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '166017000002'
version_date:
  kaz: 2022-09-28
  rus: 2022-09-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/162712/kaz/28.09.2022
  rus: https://zan.gov.kz/client/#!/doc/162712/rus/28.09.2022
caused_by:
  code: '172565'
  requisite: Решение Жетысайского районного маслихата Туркестанской области от 28 сентября 2022 года № 24-150-VII
  title:
    rus: О внесении изменений в решение Жетысайского районного маслихата от 24 декабря 2021 года № 16-94-VII «О районном бюджете на 2022-2024 годы»
    kaz: Жетісай аудандық мәслихатының 2021 жылғы 24 желтоқсандағы № 16-94-VII «2022-2024 жылдарға арналған аудандық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172565/rus
