act_code: '129780'
requisite: Решение акима сельского округа Кемербастау Тюлькубасского района Туркестанской области от 14 марта 2019 года № 12. Зарегистрировано Департаментом юстиции Туркестанской области 19 марта 2019 года № 4940
title:
  rus: О присвоении наименований безымянным улицам населенных пунктов в сельском округе Кемербастау
  kaz: Кемербастау ауылдық округіндегі елді мекендердегі атаусыз көшелерге атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-03-14
approved_by:
- '166012007002'
version_date:
  kaz: 2019-03-14
  rus: 2019-03-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/129780/kaz/14.03.2019
  rus: https://zan.gov.kz/client/#!/doc/129780/rus/14.03.2019
