act_code: '204822'
requisite: Решение Туркестанского городского маслихата Туркестанской области от 24 декабря 2024 года № 27/115-VIII
title:
  rus: О городском бюджете на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-24
approved_by:
- '166015000002'
version_date:
  kaz: 2024-12-24
  rus: 2024-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/204822/kaz/24.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204822/rus/24.12.2024
