act_code: '204822'
requisite: Решение Туркестанского городского маслихата Туркестанской области от 24 декабря 2024 года № 27/115-VIII
title:
  rus: О городском бюджете на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған қалалық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-24
approved_by:
- '166015000002'
version_date:
  kaz: 2025-12-08
  rus: 2025-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/204822/kaz/08.12.2025
  rus: https://zan.gov.kz/client/#!/doc/204822/rus/08.12.2025
caused_by:
  code: '218830'
  requisite: Решение Туркестанского городского маслихата Туркестанской области от 8 декабря 2025 года № 36/167-VIII
  title:
    rus: О внесении изменений в решение Туркестанского городского маслихата от 24 декабря 2024 года № 27/115-VІІІ «О городском бюджете на 2025-2027 годы»
    kaz: Түркістан қалалық мәслихатының 2024 жылғы 24 желтоқсандағы № 27/115-VІІІ «2025-2027 жылдарға арналған қалалық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/218830/rus
