act_code: '154426'
requisite: Решение Туркестанского областного маслихата от 19 марта 2021 года № 3/28-VIІ. Зарегистрировано Департаментом юстиции Туркестанской области 6 апреля 2021 года № 6145
title:
  rus: Об утверждении Правил выпаса сельскохозяйственных животных в Туркестанской области
  kaz: Түркістан облысында ауыл шаруашылығы жануарларын жаюдың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-03-19
approved_by:
- '166000000002'
version_date:
  kaz: 2021-03-19
  rus: 2021-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/154426/kaz/19.03.2021
  rus: https://zan.gov.kz/client/#!/doc/154426/rus/19.03.2021
