act_code: '128850'
requisite: Решение Сайрамского районного маслихата Туркестанской области от 28 декабря 2018 года № 36-234/VI. Зарегистрировано Департаментом юстиции Туркестанской области 21 января 2019 года № 4893
title:
  rus: О льготном проезде на общественном транспорте (кроме такси) обучающихся и воспитанников всех организаций образования очной формы обучения
  kaz: Барлық білім беру ұйымдарының күндізгі оқу нысаны бойынша білім алушылары мен тәрбиеленушілерінің қоғамдық көлікте (таксиден басқа) жеңілдікпен жол жүрулері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-28
approved_by:
- '166008000002'
version_date:
  kaz: 2018-12-28
  rus: 2018-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/128850/kaz/28.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128850/rus/28.12.2018
