act_code: '128349'
requisite: Решение Арысского городского маслихата Туркестанской области от 29 декабря 2018 года № 31/220-VI. Зарегистрировано Департаментом юстиции Туркестанской области 11 января 2019 года № 4880
title:
  rus: О бюджетах сельских округов на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған ауылдық округтердің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-29
approved_by:
- '166016000002'
version_date:
  kaz: 2019-11-29
  rus: 2019-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/128349/kaz/29.11.2019
  rus: https://zan.gov.kz/client/#!/doc/128349/rus/29.11.2019
caused_by:
  code: '136838'
  requisite: Решение Арысского городского маслихата Туркестанской области от 29 ноября 2019 года № 42/294-VI. Зарегистрировано Департаментом юстиции Туркестанской области 6 декабря 2019 года № 5286
  title:
    rus: О внесении изменений в решение маслихата города Арыс от 29 декабря 2018 года № 31/220-VІ «О бюджетах сельских округов на 2019-2021 годы»
    kaz: Арыс қалалық мәслихатының 2018 жылғы 29 желтоқсандағы № 31/220-VІ «2019-2021 жылдарға арналған ауылдық округтердің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136838/rus
