act_code: '53849'
requisite: Оңтүстік Қазақстан облысы Шардара ауданы әкімдігі Қазақстан ауылдық округі әкімінің 2010 жылғы 6 шілдедегі N 32 шешімі. Оңтүстік Қазақстан облысы Шардара ауданының Әділет басқармасында 2010 жылғы 6 тамызда N 14-15-98 тіркелді
title:
  rus: Қазақстан ауылдық округіндегі көшелерге атау беру туралы
  kaz: Қазақстан ауылдық округіндегі көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-07-06
approved_by:
- '166013006001'
version_date:
  kaz: 2010-07-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/53849/kaz/06.07.2010
