act_code: '151011'
requisite: Решение Отрарского районного маслихата Туркестанской области от 22 декабря 2020 года № 64/295-VI. Зарегистрировано Департаментом юстиции Туркестанской области 30 декабря 2020 года № 5990
title:
  rus: О районном бюджете на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-22
approved_by:
- '166007000002'
version_date:
  kaz: 2020-12-22
  rus: 2020-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/151011/kaz/22.12.2020
  rus: https://zan.gov.kz/client/#!/doc/151011/rus/22.12.2020
