act_code: '119009'
requisite: Решение акима сельского округа Коксу Шардаринского района Южно-Казахстанской области от 1 февраля 2018 года № 03. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 19 февраля 2018 года № 4456
title:
  rus: О присвоении наименовании улицам
  kaz: Көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-02-01
approved_by:
- '166013004002'
version_date:
  kaz: 2018-02-01
  rus: 2018-02-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/119009/kaz/01.02.2018
  rus: https://zan.gov.kz/client/#!/doc/119009/rus/01.02.2018
