act_code: '195635'
requisite: Решение акима сельского округа Шолаккорган Созакского района Туркестанской области от 15 апреля 2024 года № 62. Утратило силу решением акима сельского округа Шолаккорган Созакского района Туркестанской области от 17 июня 2024 года № 108 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-15
approved_by:
- '166010001002'
version_date:
  kaz: 2024-04-15
  rus: 2024-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/195635/kaz/15.04.2024
  rus: https://zan.gov.kz/client/#!/doc/195635/rus/15.04.2024
