act_code: '94834'
requisite: Решение Кентауского городского маслихата Южно-Казахстанской области от 30 сентября 2015 года № 258. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 23 октября 2015 года № 3381. Утратило силу решением Кентауского городского маслихата Южно-Казахстанской области от 4 февраля 2016 года № 293
title:
  rus: О повышении ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения на территории города Кентау
  kaz: Кентау қаласының аумағында пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлерге жер салығының мөлшерлемесін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-09-30
approved_by:
- '166014000002'
version_date:
  kaz: 2015-09-30
  rus: 2015-09-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/94834/kaz/30.09.2015
  rus: https://zan.gov.kz/client/#!/doc/94834/rus/30.09.2015
