act_code: '34836'
requisite: Оңтүстік Қазақстан облысы Кентау қалалық мәслихатының 2007 жылғы 1 тамыздағы № 261 шешімі. Оңтүстік Қазақстан облысы Кентау қаласының Әділет басқармасында 2007 жылы 7 тамызда № 14-3-46 болып тіркелді
title:
  rus: Кентау қаласында бейбіт жиналыстар, митингілер, шерулер, пикеттер және демонстрациялар өткізетін орынды белгілеу туралы
  kaz: Кентау қаласында бейбіт жиналыстар, митингілер, шерулер, пикеттер және демонстрациялар өткізетін орынды белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-08-01
approved_by:
- '166014000002'
version_date:
  kaz: 2007-08-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/34836/kaz/01.08.2007
