act_code: '190000'
requisite: Решение Туркестанского городского маслихата Туркестанской области от 13 декабря 2023 года № 10/44-VIII. Зарегистрировано в Департаменте юстиции Туркестанской области 14 декабря 2023 года № 6419-13. Утратило силу решением Туркестанского городского маслихата Туркестанской области от 25 апреля 2025 года № 30/141-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан города Туркестан
  kaz: Түркістан қаласының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-13
approved_by:
- '166015000002'
version_date:
  kaz: 2023-12-13
  rus: 2023-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/190000/kaz/13.12.2023
  rus: https://zan.gov.kz/client/#!/doc/190000/rus/13.12.2023
