act_code: '76689'
requisite: Решение Тюлькубасского районного маслихата Южно-Казахстанской области от 20 декабря 2013 года № 21/1-05. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 10 января 2014 года № 2491
title:
  rus: О районном бюджете на 2014-2016 годы
  kaz: 2014-2016 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-20
approved_by:
- '166012000002'
version_date:
  kaz: 2014-12-05
  rus: 2014-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/76689/kaz/05.12.2014
  rus: https://zan.gov.kz/client/#!/doc/76689/rus/05.12.2014
caused_by:
  code: '84863'
  requisite: Решение Тюлькубасского районного маслихата Южно-Казахстанской области от 5 декабря 2014 года № 35/1-05. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 9 декабря 2014 года № 2910
  title:
    rus: О внесении изменений в решение Тюлькубасского районного маслихата от 20 декабря 2013 года № 21/1-05 "О районном бюджете на 2014-2016 годы"
    kaz: Түлкібас аудандық мәслихатының 2013 жылғы 20 желтоқсандағы № 21/1-05 "2014-2016 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/84863/rus
