act_code: '129788'
requisite: Решение акима сельского округа Келтьтемашат Тюлькубасского района Туркестанской области от 14 марта 2019 года № 8. Зарегистрировано Департаментом юстиции Туркестанской области 19 марта 2019 года № 4939
title:
  rus: О присвоении наименований безымянным улицам населенных пунктов в сельском округа Кельтемашат
  kaz: Келтемашат ауылдық округіндегі елді мекендердегі атаусыз көшелерге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-03-14
approved_by:
- '166012012002'
version_date:
  kaz: 2019-11-25
  rus: 2019-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/129788/kaz/25.11.2019
  rus: https://zan.gov.kz/client/#!/doc/129788/rus/25.11.2019
caused_by:
  code: '136950'
  requisite: Решение акима Келтьтемашатского сельского округа акимата Тюлькубасского района Туркестанской области от 25 ноября 2019 года № 49. Зарегистрировано Департаментом юстиции Туркестанской области 3 декабря 2019 года № 5277
  title:
    rus: О внесении изменений в решение акима сельского округа Кельтемашат от 14 марта 2019 года № 8 «О присвоении наименований безымянным улицам населенных пунктов в сельском округе Кельтемашат»
    kaz: Келтемашат ауылдық округі әкімінің 2019 жылғы 14 наурыздағы № 8 «Келтемашат ауылдық округіндегі елді мекендердегі атаусыз көшелерге атау беру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136950/rus
