act_code: '85512'
requisite: Решение Мактааральского районного маслихата Южно-Казахстанской области от 24 декабря 2014 года № 38-218-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 31 декабря 2014 года № 2944
title:
  rus: О районном бюджете на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '166005000002'
version_date:
  kaz: 2015-01-28
  rus: 2015-01-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/85512/kaz/28.01.2015
  rus: https://zan.gov.kz/client/#!/doc/85512/rus/28.01.2015
caused_by:
  code: '86430'
  requisite: Решение Мактааральского районного маслихата Южно-Казахстанской области от 28 января 2015 года № 39-236-V. Зарегистрировано Департаментом юстиции Южно-Казахстанской области 29 января 2015 года № 2988. Утратило силу в связи с истечением срока применения - (письмо аппарата Мактааральского районного маслихата Южно-Казахстанской области от 13 января 2016 года № 7)
  title:
    rus: О внесении изменений в решение Мактааральского районного маслихата от 24 декабря 2014 года № 38-218-V "О районном бюджете на 2015-2017 годы"
    kaz: Мақтаарал аудандық мәслихатының 2014 жылғы 24 желтоқсандағы № 38-218-V "2015-2017 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/86430/rus
